var IntroTutorialUtils=IntroTutorialUtils||function(){return{setIFramePosition:function(b,c){try{var a={};c?a=c.tutorialStatus||c.tutorialData:(b=document.getElementsByClassName("lpiframeoverlay")[0],a.domain=document.domain);if(document.URL.toLowerCase().includes(a.domain)){var d;a.domain.includes("google.com")?(d=document.getElementById("Email"),d.className.includes("hidden")&&(d=document.getElementById("Passwd"))):a.domain.includes("amazon.com")?d=document.getElementById("ap_email"):a.domain.includes("facebook.com")?
d=document.getElementById("email")?document.getElementById("email"):document.getElementById("pass"):a.domain.includes("netflix.com")&&(d=document.getElementsByName("email")[0],d.type.includes("hidden")&&(d=document.getElementsByName("password")[0]));b.style.top=d.getBoundingClientRect().top-45+"px";b.style.left=d.getBoundingClientRect().left-390+"px"}}catch(g){console.log("Error in setIFramePosition: "+g.message)}},introTutorialHelpDialogConfig:function(b,c){var a=c.URL.toLowerCase();a.includes(b.tutorialStatus.domain)&&
(a.includes("amazon.com/gp/yourstore/home")&&(document.location="https://www.amazon.com/ap/cnep?_encoding=UTF8&openid.assoc_handle=usflex"),a.includes("netflix.com/login")||a.includes("facebook.com/login.php")||a.includes("facebook.com/?stype=lo")||a.includes("accounts.google.com/servicelogin")||a.includes("accounts.google.com/addsession")||a.includes("amazon.com/ap/signin")?(bg.IntroTutorial.setState({firstLogin:!1}),b.do_tutorial=!0,b.iframe_size="dialog",lpshownotification("add",b)):(bg.IntroTutorial.setState({firstLogin:!1}),
b.tutorialStatus.firstLogin&&a.includes("facebook")&&(b.do_interstitial=!0,b.iframe_size="full",lpshownotification("add",b),document.getElementsByClassName("_5lxs")[0].click(),setTimeout(function(){document.getElementsByClassName("_w0d")[0].submit()},2E3)),b.tutorialStatus.firstLogin&&(a.includes("https://www.netflix.com/logout")||a.includes("https://www.netflix.com/SignOut"))&&(document.location="https://www.netflix.com/Login")))},showTryAgain:function(b,c){b.tutorialData&&document.URL.includes(b.tutorialData.domain)&&
b.notificationdata.includes(b.tutorialData.domain)&&(c+="&hideoverlay=1","showaddnotification"===b.cmd&&(docURL=document.URL.toLowerCase(),docURL.includes("facebook.com/login")||docURL.includes("netflix.com/login")||docURL.includes("amazon.com/ap/signin")||docURL.includes("accounts.google.com/signin/challenge/sl/password")||docURL.includes("accounts.google.com/serviceloginauth")||docURL.includes("accounts.google.com/addsession#password")?(c+="&showtryagain=1",b.iframe_size="dialog"):(b.iframe_size=
"full",c+="&showadddialog=1")));return c}}}(),IntroTutorialHelpDialog=IntroTutorialHelpDialog||function(){};
(function(){IntroTutorialHelpDialog.prototype._dialog=null;IntroTutorialHelpDialog.prototype._options={makeShade:!1,alignBottom:!1,addHide:!1,transparentBG:!1,textChoice:""};IntroTutorialHelpDialog.prototype.setBackgroundTransparent=function(b,c){b&&c&&(document.body.style.background="transparent")};IntroTutorialHelpDialog.prototype.getTranslateFn=function(){return"undefined"!=typeof bg&&"function"==typeof bg.gs?bg.gs:"function"==typeof gs?gs:null};IntroTutorialHelpDialog.prototype.setArrow=function(b,
c){var a=IntroTutorialHelpDialog.prototype._dialog;if(b&&a&&c){a.className+=" arrow_box";switch(c.orientation){case "top":a.className+=" a-top";break;case "bottom":a.className+=" a-bottom";break;case "left":a.className+=" a-left";break;case "right":a.className+=" a-right"}switch(c.position){case "left":a.className+=" a-h-left";break;case "center":a.className+=" a-h-center";break;case "right":a.className+=" a-h-right";break;case "high":a.className+=" a-v-high";break;case "middle":a.className+=" a-v-middle";
break;case "low":a.className+=" a-v-low"}}};IntroTutorialHelpDialog.prototype.createDialog=function(b,c){var a=IntroTutorialHelpDialog.prototype.getTranslateFn();if(b&&a){var d=b.createElement("div");d.className="tutorialDialog";var g=b.createElement("div");g.className="dialogTextDiv";var e=b.createElement("p");e.className="topText";var f=b.createElement("p");f.className="bottomText";switch(c){case "saveSite":e.innerHTML=a("Easy, right?");f.innerHTML=a("Now just save it to your vault.");break;case "siteLanding":e.innerHTML=
a("Good choice!");f.innerHTML=a("Next, sign in to your account.");break;case "tryAgain":e.innerHTML=a("Login failed");f.innerHTML=a("Please try again.");break;case "finishSaveSite":e.innerHTML=a("Customize and Save");f.innerHTML=a("You can set these details for each site");break;case "downloadImporter":e.innerHTML=a("The LastPass Importer is downloading");f.innerHTML=a("When it's done, just run it!");setTimeout(function(){d.remove(b)},15E3);break;case "interstitial":e.innerHTML=a("Just a second..."),
f.innerHTML=a("Logging you out"),d.style.margin="15px auto 0px auto"}g.appendChild(e);g.appendChild(f);d.appendChild(g);return d}return null};IntroTutorialHelpDialog.prototype.setAlignment=function(b){var c=IntroTutorialHelpDialog.prototype._dialog;c&&b&&(c.className+=" downloadDialog")};IntroTutorialHelpDialog.prototype.setFooter=function(b,c){var a=IntroTutorialHelpDialog.prototype.getTranslateFn(),d=IntroTutorialHelpDialog.prototype._dialog;if(b&&d){var g=b.createElement("div");g.className="footerDiv";
var e=b.createElement("img");e.className="dialogLPLogo";e.src="images/vault_4.0/LastPass_Color_Small.png";g.appendChild(e);if(c){e=b.createElement("div");e.className="hideDiv";var f=b.createElement("p");f.className="hideP";f.innerHTML=a("Hide");e.addEventListener("click",function(){IntroTutorialHelpDialog.prototype.remove(b)});e.appendChild(f);g.appendChild(e)}d.appendChild(g)}};IntroTutorialHelpDialog.prototype.setShade=function(b,c,a){b&&c&&(c=b.createElement("div"),c.className="interstitial"===
a?"interstitialShade":"shade",b.body.appendChild(c))};IntroTutorialHelpDialog.prototype.setPosition=function(b){try{var c=IntroTutorialHelpDialog.prototype._dialog;if(c&&b&&b.positionFn&&"function"==typeof b.positionFn){var a=b.positionFn();a&&a.top&&a.left&&(a.top+=b.offset&&b.offset.top?b.offset.top:0,a.left+=b.offset&&b.offset.left?b.offset.left:0,c.style.position="absolute",c.style.top=a.top+"px",c.style.left=a.left+"px")}}catch(d){console.log("Error in IntroTutorialHelpDialog.setPosition: "+
d.message)}};IntroTutorialHelpDialog.prototype.subscribeToWindowResize=function(){window&&(window.addEventListener("resize",IntroTutorialHelpDialog.prototype.windowResizeHandler),"undefined"!=typeof Topics&&Topics.get(Topics.DIALOG_RESIZE).subscribe(function(b){IntroTutorialHelpDialog.prototype.windowResizeHandler()}))};IntroTutorialHelpDialog.prototype.unSubscribeToWindowResize=function(){window&&IntroTutorialHelpDialog.prototype.windowResizeHandler&&(window.removeEventListener?window.removeEventListener("resize",
IntroTutorialHelpDialog.prototype.windowResizeHandler):window.detachEvent&&window.detachEvent("resize",IntroTutorialHelpDialog.prototype.windowResizeHandler),IntroTutorialHelpDialog.prototype.windowResizeHandler=null)};IntroTutorialHelpDialog.prototype.windowResizeHandler=function(b){IntroTutorialHelpDialog.prototype.setPosition(IntroTutorialHelpDialog.prototype._options.position)};IntroTutorialHelpDialog.prototype.initialize=function(b,c){try{IntroTutorialHelpDialog.prototype._options=c||IntroTutorialHelpDialog.prototype._options;
IntroTutorialHelpDialog.prototype.setBackgroundTransparent(b,c.transparentBG);IntroTutorialHelpDialog.prototype._dialog=IntroTutorialHelpDialog.prototype.createDialog(b,c.textChoice);IntroTutorialHelpDialog.prototype.setFooter(b,c.addHide);IntroTutorialHelpDialog.prototype.setArrow(b,c.arrow);IntroTutorialHelpDialog.prototype.setAlignment(c.alignBottom);c.position?(IntroTutorialHelpDialog.prototype.setPosition(c.position),IntroTutorialHelpDialog.prototype.subscribeToWindowResize()):IntroTutorialHelpDialog.prototype.unSubscribeToWindowResize();
var a=b.getElementById(c.appendElementId);a?a.appendChild(IntroTutorialHelpDialog.prototype._dialog):b.body.appendChild(IntroTutorialHelpDialog.prototype._dialog);IntroTutorialHelpDialog.prototype.setShade(b,c.makeShade,c.textChoice)}catch(d){console.log("Error in IntroTutorialHelpDialog.initialize: "+d.message)}};IntroTutorialHelpDialog.prototype.remove=function(b){IntroTutorialHelpDialog.prototype.unSubscribeToWindowResize();b.getElementsByClassName("tutorialDialog")[0].remove();b.getElementsByClassName("shade")[0]&&
(b.getElementsByClassName("shade")[0].remove(),window.top.postMessage("minimizeIframe","*"))}})();
