/*
 typeahead.js 0.11.1
 https://github.com/twitter/typeahead.js
 Copyright 2013-2015 Twitter, Inc. and other contributors; Licensed MIT
*/
(function(f,d){"function"===typeof define&&define.amd?define("bloodhound",["jquery"],function(n){return f.Bloodhound=d(n)}):"object"===typeof exports?module.exports=d(require("jquery")):f.Bloodhound=d(jQuery)})(this,function(f){var d=function(){return{isMsie:function(){return/(msie|trident)/i.test(navigator.userAgent)?navigator.userAgent.match(/(msie |rv:)(\d+(.\d+)?)/i)[2]:!1},isBlankString:function(a){return!a||/^\s*$/.test(a)},escapeRegExChars:function(a){return a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,
"\\$&")},isString:function(a){return"string"===typeof a},isNumber:function(a){return"number"===typeof a},isArray:f.isArray,isFunction:f.isFunction,isObject:f.isPlainObject,isUndefined:function(a){return"undefined"===typeof a},isElement:function(a){return!(!a||1!==a.nodeType)},isJQuery:function(a){return a instanceof f},toStr:function(a){return d.isUndefined(a)||null===a?"":a+""},bind:f.proxy,each:function(a,g){f.each(a,function(a,b){return g(b,a)})},map:f.map,filter:f.grep,every:function(a,g){var c=
!0;if(!a)return c;f.each(a,function(b,h){if(!(c=g.call(null,h,b,a)))return!1});return!!c},some:function(a,g){var c=!1;if(!a)return c;f.each(a,function(b,h){if(c=g.call(null,h,b,a))return!1});return!!c},mixin:f.extend,identity:function(a){return a},clone:function(a){return f.extend(!0,{},a)},getIdGenerator:function(){var a=0;return function(){return a++}},templatify:function(a){function g(){return String(a)}return f.isFunction(a)?a:g},defer:function(a){setTimeout(function(){a()},0)},debounce:function(a,
g,c){var b,h;return function(){var e=this,k=arguments,m,d;m=function(){b=null;c||(h=a.apply(e,k))};d=c&&!b;clearTimeout(b);b=setTimeout(function(){m()},g);d&&(h=a.apply(e,k));return h}},throttle:function(a,g){var c,b,h,e,k,m;k=0;m=function(){k=new Date;h=null;e=a.apply(c,b)};return function(){var d=new Date,f=g-(d-k);c=this;b=arguments;0>=f?(clearTimeout(h),h=null,k=d,e=a.apply(c,b)):h||(h=setTimeout(function(){m()},f));return e}},stringify:function(a){return d.isString(a)?a:JSON.stringify(a)},noop:function(){}}}(),
n=function(){function a(b){return(b=d.toStr(b))?b.split(/\s+/):[]}function g(b){return(b=d.toStr(b))?b.split(/\W+/):[]}function c(b){return function(a){a=d.isArray(a)?a:[].slice.call(arguments,0);return function(e){var c=[];d.each(a,function(a){c=c.concat(b(d.toStr(e[a])))});return c}}}return{nonword:g,whitespace:a,obj:{nonword:c(g),whitespace:c(a)}}}(),p=function(){function a(b){this.maxSize=d.isNumber(b)?b:100;this.reset();0>=this.maxSize&&(this.set=this.get=f.noop)}function g(){this.head=this.tail=
null}function c(b,a){this.key=b;this.val=a;this.prev=this.next=null}d.mixin(a.prototype,{set:function(b,a){var e=this.list.tail;this.size>=this.maxSize&&(this.list.remove(e),delete this.hash[e.key],this.size--);(e=this.hash[b])?(e.val=a,this.list.moveToFront(e)):(e=new c(b,a),this.list.add(e),this.hash[b]=e,this.size++)},get:function(b){if(b=this.hash[b])return this.list.moveToFront(b),b.val},reset:function(){this.size=0;this.hash={};this.list=new g}});d.mixin(g.prototype,{add:function(b){this.head&&
(b.next=this.head,this.head.prev=b);this.head=b;this.tail=this.tail||b},remove:function(b){b.prev?b.prev.next=b.next:this.head=b.next;b.next?b.next.prev=b.prev:this.tail=b.prev},moveToFront:function(b){this.remove(b);this.add(b)}});return a}(),t=function(){function a(b,a){this.prefix=["__",b,"__"].join("");this.ttlKey="__ttl__";this.keyMatcher=new RegExp("^"+d.escapeRegExChars(this.prefix));this.ls=a||c;!this.ls&&this._noop()}function g(b){return JSON.stringify(d.isUndefined(b)?null:b)}var c;try{c=
window.localStorage,c.setItem("~~~","!"),c.removeItem("~~~")}catch(b){c=null}d.mixin(a.prototype,{_prefix:function(b){return this.prefix+b},_ttlKey:function(b){return this._prefix(b)+this.ttlKey},_noop:function(){this.get=this.set=this.remove=this.clear=this.isExpired=d.noop},_safeSet:function(b,a){try{this.ls.setItem(b,a)}catch(e){"QuotaExceededError"===e.name&&(this.clear(),this._noop())}},get:function(b){this.isExpired(b)&&this.remove(b);return f.parseJSON(this.ls.getItem(this._prefix(b)))},set:function(b,
a,e){d.isNumber(e)?this._safeSet(this._ttlKey(b),g((new Date).getTime()+e)):this.ls.removeItem(this._ttlKey(b));return this._safeSet(this._prefix(b),g(a))},remove:function(b){this.ls.removeItem(this._ttlKey(b));this.ls.removeItem(this._prefix(b));return this},clear:function(){var b;b=this.keyMatcher;var a,e,k=[],g=c.length;for(a=0;a<g;a++)(e=c.key(a)).match(b)&&k.push(e.replace(b,""));for(b=k.length;b--;)this.remove(k[b]);return this},isExpired:function(b){b=f.parseJSON(this.ls.getItem(this._ttlKey(b)));
return d.isNumber(b)&&(new Date).getTime()>b?!0:!1}});return a}(),r=function(){function a(e){e=e||{};this.cancelled=!1;this.lastReq=null;this._send=e.transport;this._get=e.limiter?e.limiter(this._get):this._get;this._cache=!1===e.cache?new p(0):h}var g=0,c={},b=6,h=new p(10);a.setMaxPendingRequests=function(e){b=e};a.resetCache=function(){h.reset()};d.mixin(a.prototype,{_fingerprint:function(e){e=e||{};return e.url+e.type+f.param(e.data||{})},_get:function(e,a){function k(e){a(null,e);f._cache.set(l,
e)}function d(){a(!0)}function h(){g--;delete c[l];f.onDeckRequestArgs&&(f._get.apply(f,f.onDeckRequestArgs),f.onDeckRequestArgs=null)}var f=this,l,q;l=this._fingerprint(e);this.cancelled||l!==this.lastReq||((q=c[l])?q.done(k).fail(d):g<b?(g++,c[l]=this._send(e).done(k).fail(d).always(h)):this.onDeckRequestArgs=[].slice.call(arguments,0))},get:function(e,b){var a,c;b=b||f.noop;e=d.isString(e)?{url:e}:e||{};c=this._fingerprint(e);this.cancelled=!1;this.lastReq=c;(a=this._cache.get(c))?b(null,a):this._get(e,
b)},cancel:function(){this.cancelled=!0}});return a}(),u=window.SearchIndex=function(){function a(b){b=b||{};b.datumTokenizer&&b.queryTokenizer||f.error("datumTokenizer and queryTokenizer are both required");this.identify=b.identify||d.stringify;this.datumTokenizer=b.datumTokenizer;this.queryTokenizer=b.queryTokenizer;this.reset()}function g(b){b=d.filter(b,function(b){return!!b});return b=d.map(b,function(b){return b.toLowerCase()})}function c(b){for(var a={},e=[],c=0,d=b.length;c<d;c++)a[b[c]]||
(a[b[c]]=!0,e.push(b[c]));return e}d.mixin(a.prototype,{bootstrap:function(b){this.datums=b.datums;this.trie=b.trie},add:function(b){var a=this;b=d.isArray(b)?b:[b];d.each(b,function(e){var b;a.datums[b=a.identify(e)]=e;e=g(a.datumTokenizer(e));d.each(e,function(e){var c,d;c=a.trie;for(e=e.split("");d=e.shift();)c=c.c[d]||(c.c[d]={i:[],c:{}}),c.i.push(b)})})},get:function(b){var a=this;return d.map(b,function(e){return a.datums[e]})},search:function(b){var a=this,e;b=g(this.queryTokenizer(b));d.each(b,
function(b){var c,d;if(e&&0===e.length)return!1;c=a.trie;for(b=b.split("");c&&(d=b.shift());)c=c.c[d];if(c&&0===b.length){d=c.i.slice(0);if(e){c=e;var g=b=0,k=[];c=c.sort();d=d.sort();for(var h=c.length,f=d.length;b<h&&g<f;)c[b]<d[g]?b++:(c[b]>d[g]||(k.push(c[b]),b++),g++);c=k}else c=d;e=c}else return e=[],!1});return e?d.map(c(e),function(b){return a.datums[b]}):[]},all:function(){var b=[],a;for(a in this.datums)b.push(this.datums[a]);return b},reset:function(){this.datums={};this.trie={i:[],c:{}}},
serialize:function(){return{datums:this.datums,trie:this.trie}}});return a}(),v=function(){function a(a){this.url=a.url;this.ttl=a.ttl;this.cache=a.cache;this.prepare=a.prepare;this.transform=a.transform;this.transport=a.transport;this.thumbprint=a.thumbprint;this.storage=new t(a.cacheKey)}d.mixin(a.prototype,{_settings:function(){return{url:this.url,type:"GET",dataType:"json"}},store:function(a){this.cache&&(this.storage.set("data",a,this.ttl),this.storage.set("protocol",location.protocol,this.ttl),
this.storage.set("thumbprint",this.thumbprint,this.ttl))},fromCache:function(){var a,c;if(!this.cache)return null;a=this.storage.get("data");c=this.storage.get("protocol");c=this.storage.get("thumbprint")!==this.thumbprint||c!==location.protocol;return a&&!c?a:null},fromNetwork:function(a){var c=this,b;a&&(b=this.prepare(this._settings()),this.transport(b).fail(function(){a(!0)}).done(function(b){a(null,c.transform(b))}))},clear:function(){this.storage.clear();return this}});return a}(),w=function(){function a(a){this.url=
a.url;this.prepare=a.prepare;this.transform=a.transform;this.transport=new r({cache:a.cache,limiter:a.limiter,transport:a.transport})}d.mixin(a.prototype,{_settings:function(){return{url:this.url,type:"GET",dataType:"json"}},get:function(a,c){var b=this,d;if(c)return d=this.prepare(a||"",this._settings()),this.transport.get(d,function(e,a){e?c([]):c(b.transform(a))})},cancelLastRequest:function(){this.transport.cancel()}});return a}(),x=function(){function a(b){var a;if(!b)return null;a={url:null,
ttl:864E5,cache:!0,cacheKey:null,thumbprint:"",prepare:d.identity,transform:d.identity,transport:null};b=d.isString(b)?{url:b}:b;b=d.mixin(a,b);!b.url&&f.error("prefetch requires url to be set");b.transform=b.filter||b.transform;b.cacheKey=b.cacheKey||b.url;b.thumbprint="0.11.1"+b.thumbprint;b.transport=b.transport?h(b.transport):f.ajax;return b}function g(a){var e;if(a)return e={url:null,cache:!0,prepare:null,replace:null,wildcard:null,limiter:null,rateLimitBy:"debounce",rateLimitWait:300,transform:d.identity,
transport:null},a=d.isString(a)?{url:a}:a,a=d.mixin(e,a),!a.url&&f.error("remote requires url to be set"),a.transform=a.filter||a.transform,a.prepare=c(a),a.limiter=b(a),a.transport=a.transport?h(a.transport):f.ajax,delete a.replace,delete a.wildcard,delete a.rateLimitBy,delete a.rateLimitWait,a}function c(b){function a(b,a){a.url=f(a.url,b);return a}function c(b,a){a.url=a.url.replace(g,encodeURIComponent(b));return a}function e(b,a){return a}var d,f,g;d=b.prepare;f=b.replace;g=b.wildcard;return d?
d:d=f?a:b.wildcard?c:e}function b(b){function a(b){return function(a){return d.debounce(a,b)}}function c(b){return function(a){return d.throttle(a,b)}}var e,f;e=b.limiter;f=b.rateLimitBy;b=b.rateLimitWait;e||(e=/^throttle$/i.test(f)?c(b):a(b));return e}function h(b){return function(a){var c=f.Deferred();b(a,function(b){d.defer(function(){c.resolve(b)})},function(b){d.defer(function(){c.reject(b)})});return c}}return function(b){var c;b=d.mixin({initialize:!0,identify:d.stringify,datumTokenizer:null,
queryTokenizer:null,sufficient:5,sorter:null,local:[],prefetch:null,remote:null},b||{});!b.datumTokenizer&&f.error("datumTokenizer is required");!b.queryTokenizer&&f.error("queryTokenizer is required");c=b.sorter;b.sorter=c?function(b){return b.sort(c)}:d.identity;b.local=d.isFunction(b.local)?b.local():b.local;b.prefetch=a(b.prefetch);b.remote=g(b.remote);return b}}();return function(){function a(a){a=x(a);this.sorter=a.sorter;this.identify=a.identify;this.sufficient=a.sufficient;this.local=a.local;
this.remote=a.remote?new w(a.remote):null;this.prefetch=a.prefetch?new v(a.prefetch):null;this.index=new u({identify:this.identify,datumTokenizer:a.datumTokenizer,queryTokenizer:a.queryTokenizer});!1!==a.initialize&&this.initialize()}var g;g=window&&window.Bloodhound;a.noConflict=function(){window&&(window.Bloodhound=g);return a};a.tokenizers=n;d.mixin(a.prototype,{__ttAdapter:function(){function a(b,a,c){return d.search(b,a,c)}function b(b,a){return d.search(b,a)}var d=this;return this.remote?a:
b},_loadPrefetch:function(){function a(a,c){if(a)return d.reject();b.add(c);b.prefetch.store(b.index.serialize());d.resolve()}var b=this,d,e;d=f.Deferred();this.prefetch?(e=this.prefetch.fromCache())?(this.index.bootstrap(e),d.resolve()):this.prefetch.fromNetwork(a):d.resolve();return d.promise()},_initialize:function(){var a=this;this.clear();(this.initPromise=this._loadPrefetch()).done(function(){a.add(a.local)});return this.initPromise},initialize:function(a){return!this.initPromise||a?this._initialize():
this.initPromise},add:function(a){this.index.add(a);return this},get:function(a){a=d.isArray(a)?a:[].slice.call(arguments);return this.index.get(a)},search:function(a,b,f){function c(a){var b=[];d.each(a,function(a){!d.some(h,function(b){return g.identify(a)===g.identify(b)})&&b.push(a)});f&&f(b)}var g=this,h;h=this.sorter(this.index.search(a));b(this.remote?h.slice():h);this.remote&&h.length<this.sufficient?this.remote.get(a,c):this.remote&&this.remote.cancelLastRequest();return this},all:function(){return this.index.all()},
clear:function(){this.index.reset();return this},clearPrefetchCache:function(){this.prefetch&&this.prefetch.clear();return this},clearRemoteCache:function(){r.resetCache();return this},ttAdapter:function(){return this.__ttAdapter()}});return a}()});
