var SiteDialog=function(h){DialogWithGroupInput.call(this,h,{confirmOnClose:!1,hideButtons:!0,hideHeader:!0,type:Account,additionalClasses:"lmiDialog",additionalDropdownClasses:"lmiDropdown"});this.tiles=[];this.selectedTile=this.activeTile=null;this.submitted=this.isSelectable=!1};SiteDialog.prototype=Object.create(DialogWithGroupInput.prototype);SiteDialog.prototype.constructor=SiteDialog;
(function(){SiteDialog.prototype.initialize=function(a){DialogWithGroupInput.prototype.initialize.apply(this,arguments);(function(b){a.on("click",".neverSave",function(){bg.handleNeverURL({action:"never",cmd:"neverdomain",url:b.data.defaultData.url,fromsave:!0});bg.IntroTutorial.setState({enabled:!1});b.sendTrackingEvent("never");b.close()});a.on("input change",function(){b.data.generatedPasswordSaved&&b.nextButton.text(Strings.translateString("Update"))});b.backButton=a.find("#close").bind("click",
function(){b.data.generatedPassword?b.data.generatedPasswordSaved?(b.dialogContent.css({height:b.dialogContent.css("height")}),b.$element.addClass("removeGeneratedConfirmation"),b.sendTrackingEvent("undo")):(b.sendTrackingEvent("discard"),b.close()):(b.sendTrackingEvent("notnow"),b.close())});b.nextButton=a.find("#submit").bind("click",function(){b.isSelectable?b.selectedTile&&b.submit():b.submit()});a.find("#closeConfirmation").bind("click",function(){b.close()});a.find("#deleteGenerated").bind("click",
function(){b.vaultItem.deleteItem({confirm:!1});b.close()});a.find(".addNewSiteButton").bind("click",function(){var a=b.tiles.slice();b.defaultFields(b.data);b.originalData=b.getData();b.populateFields(b.data.dialogData);b.setupAdd();b.setSelectable(!1);$(this).LP_hide();for(var d=0;d<a.length;++d)a[d].remove()})})(this)};var h=function(a){var b={};a=a.find("[dialogFieldDisplay]");for(var c=0;c<a.length;++c)b[a[c].getAttribute("dialogFieldDisplay")]=!0;return b},B=function(a,b){for(var c=a.find("[dialogFieldDisplay]"),
d=0;d<c.length;++d){var f=c[d],g=b[f.getAttribute("dialogFieldDisplay")];g&&(f.textContent=g)}};SiteDialog.prototype.sendTrackingEvent=function(a){var b=this.clickedEdit?"savesiteedit":"savesiteseen";a={action:a};this.clickedEdit&&$.extend(a,{changedEmail:this.inputFields.unencryptedUsername.getValue()!==this.data.defaultData.unencryptedUsername,changedPassword:this.inputFields.password.getValue()!==this.data.dialogData.password,showedPassword:this.activeTile?this.activeTile.showedPassword():!1});
bg.sendLpImprove(b,a)};SiteDialog.prototype.setupAdd=function(a){a=a||this.data;this.$element.find(".question").text(Strings.translateString("Add to LastPass?"));this.nextButton.text(Strings.translateString("Add"));var b=new this.SiteTile;a.defaultData.unencryptedUsername||b.showDetails({animate:!1,clearErrors:!0,tileHeight:"auto"})};var x=function(a,b,c){var d=$.extend({},a.defaultData);b&&$.extend(d,b.getFormData($.extend(c,DialogInput.getProperties(a.dialogData),DialogInput.getProperties(a.defaultData))));
return d},p=function(a,b,c){return $.extend(x(a,b,c),a.dialogData)},C=function(a,b){bg.LPIcons.get({url:a.defaultData.url,square:!0,callback:function(c){if(c)b(c);else{var d=function(){bg.LPPlatform.getFavicon({url:a.defaultData.url,callback:b})};a.sameDomain?csTop.LPContentScriptTools.getFavicon(function(a){a?b(a):d()}):d()}}})};SiteDialog.prototype.hasDuplicates=function(){for(var a=0;a<this.tiles.length;++a)if(0<this.tiles[a].getDuplicates().length)return!0;return!1};SiteDialog.prototype.setup=
function(a,b){b.saveOptions={source:"saveSite"};a.find(".addSiteFavicon").append(LPTools.createElement("img",{"class":"favicon",src:b.favicon?b.favicon:"images/site/world.png"}));var c=this,d=a.find(".tileContainer"),f=a.find(".question"),g=a.find(".explanation"),z=a.find(".dialogForm"),m=a.find(".tile.template"),v=a.find(".deleteOverlayContainer.template"),w=h(m),y=DialogInput.getProperties(c.inputFields),k=this.SiteTile=function(a){a=a||{};var b=this,e=m.clone().removeClass("template"),f=null,g=
c.data,q=!1,h=!1,r=null,k=!1,l=x(g,a.site,y),t=p(g,a.site,y),u=null,n=function(a){a&&c.clearErrors();c.originalData=l;c.populateFields(t)};this.showedPassword=function(){return k};this.getDialogData=function(){return t};this.getOriginalData=function(){return l};this.getOriginalDialogData=function(){return p(g,a.site,y)};this.getDuplicates=function(){if(null===u&&(u=[],g.defaultData.unencryptedUsername)){var a=bg.hostof(t.url);c.tiles.forEach(function(c){var d=c.getDialogData();c!==b&&bg.hostof(d.url)===
a&&u.push(c)})}return u};this.handleHeightChange=function(){var a=function(a,b){var c=function(d){d.target===this&&(a.unbind("transitionend",c),b())};a.bind("transitionend",c)},b=function(b,c){b=b||{};var d=LPTools.getOption(b,"animate",!0),f="animating";d&&(b.animationClass&&(f+=" "+b.animationClass),e.addClass(f));var A=function(a){e.removeClass(f);a&&a.transitionEndHandler&&a.transitionEndHandler();c({callback:a&&a.onFrameResizeComplete})};b.change(function(c){var f=LPTools.getOption(c,"tileHeight",
LPTools.getOption(b,"tileHeight",e.children().first().outerHeight())),g=e.height();e.css("height",f);f!==g&&d?a(e,function(){A(c)}):A(c);return f})};return function(a){LPTools.getOption(a,"animate",!0)?c.requestAnimationFrame(function(c){b(a,c)}):b(a,function(a){c.setFrameSize();a&&a.callback&&a.callback()})}}();this.showDetails=function(a){this.handleHeightChange($.extend(a,{animationClass:"details-animatation",change:function(d){null===r&&(r=e.height());c.activeTile&&c.activeTile!==b&&c.activeTile.hideDetails(a);
c.activeTile=b;n(a&&a.clearErrors);e.find(".tileContent").append(z);e.addClass("details");d=d();c.clickedEdit||(c.clickedEdit=!0,c.sendTrackingEvent("edit"),c.adjustView(!0),c.adjustScrollHeight(d-r))}}))};this.preSubmit=function(){c.activeTile!==this&&(c.activeTile&&(c.activeTile.hideDetails(),c.activeTile=null),n());c.vaultItem=a.site;!c.vaultItem&&g.dialogData.fields&&(g.saveOptions.saveFromSubmit=!0)};this.hideDetails=function(a){t=c.getData();var b=z.clone();this.handleHeightChange($.extend(a,
{animationClass:"details-animatation",change:function(a){e.find(".tileContent").append(b);e.removeClass("details");a({transitionEndHandler:function(){b.remove()},tileHeight:r})}}))};this.unselect=function(){q&&(c.selectedTile=null,q=!1,e.removeClass("selected"),c.$element.removeClass("selected"),c.nextButton.prop("disabled",!0))};this.toggleSelect=function(){q?(this.unselect(),this.getDuplicates().forEach(function(a){a.hideDeleteOverlay()})):(this.getDuplicates().forEach(function(a){a.showDeleteOverlay()}),
c.tiles.forEach(function(a){a.unselect()}),c.selectedTile=this,q=!0,e.addClass("selected"),c.$element.addClass("selected"),c.nextButton.prop("disabled",!1))};this.remove=function(){e.remove();for(var a=0;a<c.tiles.length;++a)if(c.tiles[a]===this){c.tiles.splice(a,1);break}};this.showDeleteOverlay=function(){null===f&&(f=v.clone().removeClass("template"),f.find(".cancelDeleteButton").bind("click",this.hideDeleteOverlay),f.find(".deleteButton").bind("click",function(){a.site.deleteItem({confirm:!1,
success:function(){b.remove()}});b.hideDeleteOverlay()}));e.append(f);e.addClass("duplicate")};this.hideDeleteOverlay=function(){e.removeClass("duplicate");f.one("animationend",function(){e.hasClass("duplicate")||f.detach()})};this.setSelectable=function(a){h=a;var b=e.find(".favicon");h?(b.addClass("hoverFadeOut"),e.find(".checkmark").LP_show()):(b.removeClass("hoverFadeOut"),e.find(".checkmark").LP_hide());c.setSelectable(a)};e.find(".tileEdit").bind("click",function(){b.showDetails({clearErrors:!0})});
e.find(".checkmark").bind("click",function(){b.toggleSelect()});e.on("click",".showPassword",function(){k=!0});d.append(e);B(e,a.site?a.site.getFormData(w):g.defaultData);c.tiles.push(this)};if(b.matchingSites)if(0===b.matchingSites.length)b.generatedPasswordSaved?(f.text(Strings.translateString("Nice! We've now added this to LastPass")),this.nextButton.text(Strings.translateString("Got it")),this.backButton.text(Strings.translateString("Undo")),new k({site:b.vaultItem})):this.setupAdd(b);else if(1===
b.matchingSites.length)b.generatedPasswordSaved?(f.text(Strings.translateString("Nice! We've updated your password")),this.nextButton.text(Strings.translateString("Got it")),this.backButton.LP_hide()):(f.text(Strings.translateString("Update password?")),this.nextButton.text(Strings.translateString("Update")),b.defaultData.unencryptedUsername||a.find(".addNewSiteButton").LP_show()),b.vaultItem=LPProxy.getSiteModel(b.matchingSites[0]),new k({site:b.vaultItem});else{for(var l=0;l<b.matchingSites.length;++l)(new k({site:LPProxy.getSiteModel(b.matchingSites[l])})).setSelectable(!0);
f.text(Strings.translateString("Which account should we update?"));b.defaultData.unencryptedUsername?this.hasDuplicates()&&g.text(Strings.translateString("Choose one to update and delete the duplicate.")):a.find(".addNewSiteButton").LP_show();this.nextButton.text(Strings.translateString("Update"))}!b.generatedPassword||b.generatedPasswordSaved||b.sameDomain||(f.text(Strings.translateString("Oops! What would you like to do with your generated password?")),this.backButton.text(Strings.translateString("Discard")));
DialogWithGroupInput.prototype.setup.apply(this,arguments);this.inputFields.unencryptedUsername.setValues(LPProxy.getSiteUsernames());this.inputFields.unencryptedUsername.disableClickToggle()};SiteDialog.prototype.setSelectable=function(a){a?(this.$element.addClass("selectable"),this.nextButton.prop("disabled",!0)):(this.$element.removeClass("selectable"),this.nextButton.prop("disabled",!1))};SiteDialog.prototype.validate=function(a){var b=DialogWithGroupInput.prototype.validate.apply(this,arguments);
""===a.unencryptedUsername&&(this.addError("unencryptedUsername",Strings.translateString("Please enter a username.")),b=!1);return b};SiteDialog.prototype.getDialogActions=function(a){};SiteDialog.prototype.close=function(a){bg.LPTabState.clear({force:!0});DialogWithGroupInput.prototype.close.apply(this,arguments)};SiteDialog.prototype.saveGeneratedPassword=function(a,b){var c;if(a.generatedPassword&&a.formSubmitted&&a.defaultData.unencryptedUsername)if(0===a.matchingSites.length)c=p(a),(new Account).addFromDialog(c,
this.getGroup(c),{success:function(c){a.vaultItem=c;a.generatedPasswordSaved=!0;bg.LPTabState.clear({force:!0});b()}});else if(1===a.matchingSites.length){var d=LPProxy.getSiteModel(a.matchingSites[0]);c=p(a,d);v(c,x(a,d),c);d.saveFromDialog(c,this.getGroup(c),{success:function(c){a.vaultItem=c;a.generatedPasswordSaved=!0;bg.LPTabState.clear({force:!0});b()}})}else b();else b()};SiteDialog.prototype.open=function(a){var b=this;this.saveGeneratedPassword(a,function(){C(a,function(c){a.favicon=c;DialogWithGroupInput.prototype.open.call(b,
a)})})};SiteDialog.prototype.adjustScrollHeight=function(a){this.scrollHeight&&(this.scrollHeight+=a,this.tileContainer.css({"max-height":this.scrollHeight}))};SiteDialog.prototype.setInitialScrollHeight=function(){if(3<this.tiles.length){this.tileContainer=this.$element.find(".tileContainer");var a=this.tileContainer.height(),b=this.$element.find(".tile").first().height();this.scrollHeight=3.5*b+(a-b*this.tiles.length)/(this.tiles.length-1)*3;this.tileContainer.css({overflow:"auto","max-height":this.scrollHeight})}};
SiteDialog.prototype.showInitial=function(){(function(a){a.requestAnimationFrame(function(b){a.show();a.setInitialScrollHeight();a.$element.addClass("animate-enter").one("animationend",function(){a.$element.removeClass("animate-enter");b()})})})(this)};var m=null,w=!1;SiteDialog.prototype.showInProcessOverlay=function(){if(this.submitted){var a=this.$element;a.addClass("inProcess").one("animationend",function(){a.addClass("waiting");setTimeout(function(){w=!0;m&&m()},500)})}};SiteDialog.prototype.hideInProcessOverlay=
function(){this.$element.removeClass("inProcess waiting")};SiteDialog.prototype.closeOnSuccess=function(){if(this.submitted){var a=this;a.$element.addClass("inProcess waiting");var b=function(){a.$element.removeClass("waiting").addClass("success").one("animationend.success",function(){setTimeout(function(){a.close()},500)})};w?b():m=function(){setTimeout(function(){b()},0)}}};SiteDialog.prototype.performValidate=function(a){var b=this;if(b.selectedTile)if(b.selectedTile===b.activeTile)b.activeTile.handleHeightChange({change:function(c){var d=
a.callback;a.callback=function(){var a=arguments;c({onFrameResizeComplete:function(){d&&d.apply(b,a)}})};DialogWithGroupInput.prototype.performValidate.call(b,a)}});else{var c=a.callback;a.callback=function(a){a||b.selectedTile.showDetails();c&&c.apply(this,arguments)};DialogWithGroupInput.prototype.performValidate.call(b,a)}};SiteDialog.prototype.getErrorOptions=function(){return{"static":!0,alignTop:!0,showErrorLabel:!1}};SiteDialog.prototype.submit=function(){1===this.tiles.length&&(this.selectedTile=
this.tiles[0]);this.selectedTile.preSubmit();DialogWithGroupInput.prototype.submit.apply(this,arguments);this.vaultItem?this.sendTrackingEvent("update"):this.sendTrackingEvent("add")};var n=function(a,b){a.fields&&a.fields.forEach(function(c){a.unencryptedUsername&&a.unencryptedUsername===c.value&&"password"!==c.type?c.value=b.unencryptedUsername:"password"===c.type&&(c.value=b.password)})},v=function(a,b,c){if(c.fields){n(b,c);n(a,c);var d=b.fields?b.fields:[];a.fields&&(d=d.concat(a.fields.filter(function(a){for(var b=
0;b<d.length;++b){var c=d[b];if(a.type===c.type&&a.name===c.name&&a.formname===c.formname)return!1}return!0})));c.fields=d}};SiteDialog.prototype.handleSubmit=function(a){this.submitted=!0;v(this.selectedTile.getOriginalDialogData(),this.selectedTile.getOriginalData(),a);DialogWithGroupInput.prototype.handleSubmit.apply(this,arguments)}})();
