var ContainerSelectionDialog=function(e){VaultItemDialog.call(this,e,{additionalHeaderClasses:["icon"],closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.selectedCollapsed=this.availableCollapsed=!1;this.toggleCollapse=function(d){return function(c,b,a){a=$(a.target);d[c]?(b.expandAll(),d[c]=!1,a.attr("title","Collapse All")):(b.collapseAll(),d[c]=!0,a.attr("title","Expand All"));a.toggleClass("selected")}}(this)};ContainerSelectionDialog.prototype=Object.create(VaultItemDialog.prototype);
ContainerSelectionDialog.prototype.constructor=ContainerSelectionDialog;
(function(e){ContainerSelectionDialog.prototype.initialize=function(c){VaultItemDialog.prototype.initialize.apply(this,arguments);(function(b){c.find(".availableSearch").LP_addSearchHandlers("inputDialog",function(a){b.containers.available.applySearch(a)});c.find(".selectedSearch").LP_addSearchHandlers("inputDialog",function(a){b.containers.selected.applySearch(a)});c.find(".availableCollapseToggle").bind("click",function(a){b.toggleCollapse("availableCollapsed",b.containers.available,a)});c.find(".selectedCollapseToggle").bind("click",
function(a){b.toggleCollapse("selectedCollapsed",b.containers.selected,a)});b.availableContainerElement=c.find(".containerSelectionDialogAvailable");b.availableContainerElement.bind("dragover",function(a){0<b.selectedFromSelected.length&&(a.preventDefault(),a.stopPropagation())});b.availableContainerElement.bind("drop",function(){d(b.selectedFromSelected,b.containers.available)});b.selectedContainerElement=c.find(".containerSelectionDialogSelected");b.selectedContainerElement.bind("dragover",function(a){0<
b.selectedFromAvailable.length&&(a.preventDefault(),a.stopPropagation())});b.selectedContainerElement.bind("drop",function(){d(b.selectedFromAvailable,b.containers.selected)});b.availableVaultItemOverrides={getContextMenuItems:function(a){return[new LPTools.ContextMenuItem(Constants.ACTION_ADD,{text:b.getAddToSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_ADD},add:function(){d(this.getItemsForAction(),b.containers.selected)}};b.availableGroupOverrides={getContextMenuItems:function(a){return[new LPTools.ContextMenuItem(Constants.ACTION_ADD,
{text:b.getAddToSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_ADD},add:function(){d(this.getItemChildren(),b.containers.selected)}};b.selectedVaultItemOverrides={getContextMenuItems:function(a){return[new LPTools.ContextMenuItem(Constants.ACTION_REMOVE,{text:b.getRemoveFromSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_REMOVE},remove:function(){d(this.getItemsForAction(),b.containers.available)}};b.selectedGroupOverrides={getContextMenuItems:function(a){return[new LPTools.ContextMenuItem(Constants.ACTION_REMOVE,
{text:b.getRemoveFromSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_REMOVE},remove:function(){d(this.getItemChildren(),b.containers.available)}}})(this)};var d=function(c,b){c=c.slice();for(var a=0,d=c.length;a<d;++a){var f=c[a],e=f._parent._model,g=f._model;f.destruct();b.addChild(g.newDisplayObject(),e)}};ContainerSelectionDialog.prototype.getAddToSelectedText=function(){return Strings.translateString("Add to Selected")};ContainerSelectionDialog.prototype.getRemoveFromSelectedText=
function(){return Strings.translateString("Remove from Selected")};ContainerSelectionDialog.prototype.setup=function(c,b){this.selectedFromAvailable=[];this.selectedFromSelected=[];(function(a){a.containers.available=new Container(a.getAvailableItems(b),{display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,additionalItemClasses:"dialogItem noItemButtons",additionalGroupClasses:"dialogItemGroup",forceDrag:!0,allowDrop:!1,publishSelect:!1,dragstart:function(){a.selectedFromAvailable=LPTools.getDragItems()},
override:function(){return this instanceof GroupDisplay?a.availableGroupOverrides:a.availableVaultItemOverrides}});a.containers.available.initialize(a.availableContainerElement.get(0));a.containers.selected=new Container(a.getSelectedItems(b),{display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,additionalItemClasses:"dialogItem noItemButtons",additionalGroupClasses:"dialogItemGroup",forceDrag:!0,allowDrop:!1,publishSelect:!1,dragstart:function(){a.selectedFromSelected=LPTools.getDragItems()},override:function(){return this instanceof
GroupDisplay?a.selectedGroupOverrides:a.selectedVaultItemOverrides}});a.containers.selected.initialize(a.selectedContainerElement.get(0))})(this);VaultItemDialog.prototype.setup.apply(this,arguments)}})(document);
