var CreateAccountDialog=function(a){Dialog.call(this,a,{views:[{selector:"#dataEntry"},{selector:"#confirmation",title:Strings.translateString("Confirm Password")}],dynamicHeight:!0,additionalHeaderClasses:["icon"],nextButtonText:Strings.translateString("Create Account"),largeButtons:!0,title:Strings.translateString("Create Account")})};CreateAccountDialog.prototype=Object.create(Dialog.prototype);CreateAccountDialog.prototype.constructor=CreateAccountDialog;
(function(){CreateAccountDialog.prototype.initialize=function(a){Dialog.prototype.initialize.apply(this,arguments);this.inputFields.password.getElement().LP_addPasswordMeter();(function(b){b.inputFields.email.onChange(function(a){a&&getBG().LPServer.textRequest({type:"GET",url:"create_account.php",CSRFToken:!1,data:{username:a,check:"avail",mistype:1},success:function(a){0===a.indexOf("mistype:")?b.addError("email",a.substring(8)):"no"===a&&b.addError("email",Strings.translateString("Email already in use."))}})})})(this)};
CreateAccountDialog.prototype.close=function(a){a?Dialog.prototype.close.apply(this,arguments):function(a){LPTools.getOption(a.data,"showcloseconfirm",!0)?dialogs.confirmation.open({title:"LastPass",text:Strings.translateString("Do you really want to quit?  You cannot use LastPass without creating an account."),handler:function(){dialogs.alert.open({title:"LastPass",text:Strings.translateString("Please visit https://lastpass.com to create an account at a later time."),handler:function(){a.close(!0)}})}}):
a.close(!0)}(this)};CreateAccountDialog.prototype.validate=function(a){var b=Dialog.prototype.validate.apply(this,arguments);5>a.email.length&&(this.addError("email",Strings.translateString("It looks like you've entered an invalid or incomplete email address. Please try again.")),b=!1);a.agreeTerms||(this.addError("agreeTerms",Strings.translateString("You must agree to the Terms and Conditions in order to continue")),b=!1);8>a.password.length&&(this.addError("password",Strings.translateString("Sorry, your password is too short. It must be a minimum of 8 characters long for security reasons.")),
b=!1);a.password&&a.password===a.email&&(this.addError("password",Strings.translateString("Sorry, your password can not be the same as your email address.")),b=!1);if(a.password.match(/^password\d{0,3}$/i)||"12345678"===a.password||"123456789"===a.password||"1234567890"===a.password||a.password.match(/^lastpass\d{0,3}$/i)||"lastpass.com"===a.password||"qwertyuiop"===a.password||"abcd1234"===a.password)this.addError("password",Strings.translateString("Your password is easily guessable, avoid simple runs of characters, or variations of 'password' or 'lastpass'.")),
b=!1;a.password&&-1!==a.reminder.toLowerCase().indexOf(a.password.toLowerCase())&&(this.addError("reminder",Strings.translateString("Your Password Reminder can not be the same as your chosen Master Password for security reasons. Please edit your Reminder so that it does not contain your Master Password.")),b=!1);this.currentViewIndex===this.views.length-1&&a.password!==a.reconfirm&&(this.addError("reconfirm",Strings.translateString("Your Master Password and Confirm Master Password entries do not match, please enter them again.")),
b=!1);return b};CreateAccountDialog.prototype.handleSubmit=function(){var a=function(a,f,e){Topics.get(Topics.ERROR).publish(a);Topics.get(Topics.REQUEST_ERROR).publish({requestID:e})};return function(b){b.email=bg.fix_username(b.email);var f=LPRequest.getNewRequestID();(function(e,h){e.make_lp_key_hash(b.email,b.password,function(g,k,l){g={username:b.email,email:b.email,hash:k,password_hint:b.reminder,improve:1,loglogins:1,iterations:l,xml:1};BuildVariables.createSource&&(g[BuildVariables.createSource]=
1);Topics.get(Topics.REQUEST_START).publish({requestID:f});e.create_account_safe($.param(g),function(c){var d="";c?0<=c.indexOf("ok")?(e.set("g_manual_login",!0),e.LP_do_login(b.email,b.password,!0,!1,null,!0),h.close(!0)):0<=c.indexOf("usernametaken")?d=Strings.translateString("Email already in use, have you forgotten your password?"):0<=c.indexOf("usernameinvalid")||0<=c.indexOf("emailfailed")?d=Strings.translateString("Invalid email address, try again"):((c=jQuery.parseXML(c))&&c.documentElement&&
(c=c.getElementsByTagName("error"))&&0<c.length&&c[0].getAttribute("msg")&&(d=c[0].getAttribute("msg")),""===d&&(d=Strings.translateString("A server error occurred while processing your request."))):d=Strings.translateString("Received empty response from server.");d&&a(d,b,f)},a)})})(bg,this)}}()})();
