DialogInput=function(){var v=function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]instanceof h?v(a[c]):!0);return b},h=function(){};h.prototype.validate=function(){var a=!0,b;for(b in this)this.hasOwnProperty(b)&&(a=this[b].validate()&&a);return a};h.prototype.clear=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clear()};h.prototype.clearErrors=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clearErrors()};h.prototype.adjustView=function(){for(var a in this)if(this.hasOwnProperty(a)){var b=
this[a];"function"===typeof b.adjustView&&b.adjustView()}};h.prototype.getValue=function(a){var b={},c;for(c in this)this.hasOwnProperty(c)&&(b[c]=this[c].getValue(a));return b};h.prototype.setValue=function(a){for(var b in this)this.hasOwnProperty(b)&&this[b].setValue(void 0===a[b]?"":a[b])};h.prototype.hasError=function(){for(var a in this)if(this.hasOwnProperty(a)&&this[a].hasError())return!0;return!1};var t=function(a){this.items={};this.groupName=a};t.prototype.getValue=function(){for(var a in this.items)if(this.items[a].prop("checked"))return a};
t.prototype.setValue=function(a){if(a=this.items[a])a.prop("checked",!0);else for(var b in this.items)this.items[b].prop("checked",!1)};t.prototype.addRadioInput=function(a){var b=a.attr("value");if(b){if(a.attr("name")!==this.groupName)throw"RadioGroup member must have the same name attribute as the other radio inputs in the group (based on dialogField)!";this.items[b]=a}else throw"RadioGroup member must have a value!";};var f=function(){this._errors=[];this._errorOptions=this._errorContainer=null;
this._hasError=!1};f.prototype.postValidate=function(){(this._hasError=0<this._errors.length)&&this._errorContainerWrapper.find("input,select,textarea").bind("focus",this.focusHandler).bind("blur",this.blurHandler).bind("change",this.changeHandler)};f.prototype.hasError=function(){return this._hasError};f.prototype.buildError=function(){var a=this.getElement(),b={element:a,alignTop:"SELECT"===this.input.prop("nodeName").toUpperCase()};"checkbox"===a.attr("type")&&(b.element=b.element.add(a.next()),
b["static"]=!0);return this.buildErrorElement(b)};f.prototype.buildErrorElement=function(a){this._errorOptions=a=$.extend(this.getDialog().getErrorOptions(),a);var b=this._errorContainerWrapper=$(LPTools.createElement("div","relative"));this._errorContainer=$(LPTools.createElement("div","dialogErrorContainer"));a.element.before(b);a["static"]&&b.addClass("staticError");a.alignTop&&this._errorContainer.addClass("alignTop");a["static"]&&!a.alignTop?(b.append(a.element),b.append(this._errorContainer)):
(b.append(this._errorContainer),b.append(a.element));var c=this.getDialog();this.focusHandler=function(){b.addClass("focus")};this.blurHandler=function(){b.removeClass("focus")};this.changeHandler=function(){c.performValidate({data:c.getData(),errorsOnly:!0})}};f.prototype.addError=function(a,b){b=this.dialog=this.getDialog()||b;if(!this.disabled&&!LPTools.getOption(b.validateOptions,"errorsOnly",!1)||this.hasError())this._hasError=!0,this._errors.push(a),this.buildErrorMessage()};f.prototype.clearErrors=
function(){this._errors=[];this._errorContainer&&(this._errorContainer.empty(),this._errorContainerWrapper.removeClass("error"),this._errorContainerWrapper.find("input,select,textarea").unbind("focus",this.focusHandler).unbind("blur",this.blurHandler).unbind("change",this.changeHandler))};f.prototype.clear=function(){this._hasError=!1};f.prototype.adjustView=function(){};f.prototype.buildErrorMessage=function(){this._errorContainer||this.buildError();this._errorContainerWrapper.addClass("error");
this._errors.forEach(function(a){var b=LPTools.createElement("div","dialogError");b.appendChild(LPTools.createElement("div","validation-img warning"));LPTools.getOption(this._errorOptions,"showErrorLabel",!0)&&b.appendChild(LPTools.createElement("span","errorLabel",Strings.translateString("ERROR")+": "));b.appendChild(LPTools.createElement("span","",a));this._errorContainer.append(b)},this)};f.prototype.getDialog=function(){return this.dialog};f.prototype.getElement=function(){return this.input};
var d=function(a,b){f.call(this);this.setElement(a);this.disabled=!1;this.dialog=b;this.radioGroup=null};d.prototype=Object.create(f.prototype);d.prototype.constructor=d;d.prototype.getNativeElement=function(){return this.getElement().get(0)};d.prototype.setElement=function(a){this.input=a instanceof $?a:$(a)};d.prototype["default"]=function(){this.setValue("")};d.prototype.validate=function(){return!0};d.prototype.focus=function(){this.input.focus()};d.prototype.disable=function(){this.disabled||
(this.disabled=!0,this.input.prop("disabled",!0))};d.prototype.enable=function(){this.disabled&&(this.disabled=!1,this.input.prop("disabled",!1))};d.prototype.clear=function(){f.prototype.clear.apply(this,arguments);if(this.input){switch(this.input.attr("type")){case "checkbox":case "radio":this.setValue(!1);break;default:this.setValue("")}this.input.passwordShown&&this.input.hidePassword()}};d.prototype.getValue=function(){switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.getValue();
case "checkbox":return this.input.prop("checked");default:return this.input.val()||""}};d.prototype.setValue=function(a){var b=this.getValue();switch(this.input.attr("type")){case "radio":if(this.radioGroup)return this.radioGroup.setValue(a);case "checkbox":this.input.prop("checked",a);break;default:this.input.val(a)}b!==a&&this.fireOnChange()};d.prototype.addRadioInput=function(a,b){null===this.radioGroup&&(this.radioGroup=new t(a),this.radioGroup.addRadioInput(this.input));this.radioGroup.addRadioInput(b instanceof
$?b:$(b))};d.prototype.fireOnChange=function(){if(this.onChangeCallback)this.onChangeCallback(this.getValue())};d.prototype.onChange=function(a){this.onChangeCallback=a;(function(a){a.getElement().bind("change",function(){a.fireOnChange()})})(this)};var p=function(a,b){d.apply(this,arguments)};p.prototype=Object.create(d.prototype);p.prototype.constructor=p;p.prototype.setOptions=function(a){this.input.empty();for(var b=0,c=a.length;b<c;++b){var d=a[b],e=d.value,f=d.label;"string"===typeof d&&(e=
f=d);this.input.append(LPTools.createElement("option",{value:e},f))}};var e=function(a,b){d.call(this);this.field=a;this.label=void 0===b?a:b?Strings.translateString(b):null};e.prototype=Object.create(d.prototype);e.prototype.constructor=e;e.prototype.build=function(){var a="settingLabel";this.isTopAlign()&&(a+=" topAlign");var b=LPTools.createElement("tr"),c=LPTools.createElement("td");this.label&&b.appendChild(LPTools.createElement("td",a,this.label));b.appendChild(c);c.appendChild(this.buildInput());
return b};e.prototype.buildInput=function(){var a=this.buildInputElement();this.setElement(a);return a};e.prototype.isTopAlign=function(){return!1};var l=function(a,b,c){e.call(this,a,b);this.options=c};l.prototype=Object.create(e.prototype);l.prototype.constructor=l;l.prototype.buildInputElement=function(){return LPTools.createElement("input",{"class":"dialogInput",type:"text"})};l.prototype.buildInput=function(){var a=e.prototype.buildInput.apply(this,arguments),b=LPTools.getOption(this.options,
"inputButton",null);if(b){var c=LPTools.createElement("div","relative");c.appendChild(a);this.inputButtonElement=LPTools.createElement("button","dialogInputButton",b);var d=LPTools.getOption(this.options,"inputButtonHandler",null);d&&function(a){LPPlatform.addEventListener(a.inputButtonElement,"click",function(){d.apply(a)})}(this);c.appendChild(this.inputButtonElement);return c}return a};l.prototype.adjustView=function(){if(this.inputButtonElement){var a=parseInt(this.input.css("padding-right"));
this.input.css("padding-right",a+$(this.inputButtonElement).outerWidth())}};var q=function(a,b){e.call(this,a,b)};q.prototype=Object.create(e.prototype);q.prototype.constructor=q;q.prototype.buildInput=function(){this.setElement(LPTools.createElement("input",{"class":"dialogInput",type:"password"}));this.input.LP_addPasswordEye({includeGenerateButton:!0});var a=this.input.parents();return a[a.length-1]};var k=function(a,b,c,d){this.classToUse=c||"";this.options=d||"";e.call(this,a,b)};k.prototype=
Object.create(e.prototype);k.prototype.constructor=k;k.prototype.buildInputElement=function(){return LPTools.createElement("textarea",["dialogInput",this.classToUse])};k.prototype.buildInput=function(){var a=e.prototype.buildInput.apply(this,arguments),b=LPTools.getOption(this.options,"inputButton",null);if(b){var c=LPTools.createElement("div","relative");c.appendChild(a);this.inputButtonElement=LPTools.createElement("button","dialogInputButton copy",b);var d=LPTools.getOption(this.options,"inputButtonHandler",
null);d&&function(a){LPPlatform.addEventListener(a.inputButtonElement,"click",function(){d.apply(a)})}(this);c.appendChild(this.inputButtonElement);return c}return a};k.prototype.adjustView=function(){if(this.inputButtonElement){var a=parseInt(this.input.css("padding-right"));this.input.css("padding-right",a+$(this.inputButtonElement).outerWidth())}};k.prototype.isTopAlign=function(){return!0};var r="January February March April May June July August September October November December".split(" "),
y="01 02 03 04 05 06 07 08 09 10 11 12".split(" "),u=[];(function(){for(var a=0,b=r.length;a<b;++a){var c=a+1;u.push((10>c?"0"+c:c)+" - "+Strings.translateString(r[a]))}})();var w=[{value:"",label:""}];(function(){for(var a=0,b=r.length;a<b;++a)w.push({value:r[a],label:u[a]})})();var x=[{value:"",label:""}];(function(){for(var a=0,b=r.length;a<b;++a)x.push({value:y[a],label:u[a]})})();var g=function(a,b){e.call(this,a,LPTools.getOption(b,"label",void 0));this.includeDay=LPTools.getOption(b,"includeDay",
!0)};g.prototype=Object.create(e.prototype);g.prototype.constructor=g;g.prototype.buildInputElement=function(){var a="";this.includeDay||(a="monthYearDate");var a=LPTools.createElement("div",a),b=LPTools.createElement("div","dateInputMonth");this.monthInput=LPTools.createSelectElement(this.getMonthOptions());this.dayInput=null;this.includeDay&&(this.dayInput=LPTools.createElement("input",{"class":"dialogInput dateInputDay",type:"text"}));this.yearInput=LPTools.createElement("input",{"class":"dialogInput dateInputYear",
type:"text"});b.appendChild(this.monthInput);a.appendChild(b);null!==this.dayInput&&a.appendChild(this.dayInput);a.appendChild(this.yearInput);return a};g.prototype.clear=function(){this.monthInput&&(this.monthInput.value="");this.dayInput&&(this.dayInput.value="");this.yearInput&&(this.yearInput.value="")};g.prototype.getValue=function(){return this.toString()};g.prototype.setValue=function(a){a=this.parse(a);var b="",c="",d="";a&&(b=a.shift(),2===a.length&&(c=a.shift()),d=a.shift());this.monthInput.value=
b;this.includeDay&&(this.dayInput.value=c);this.yearInput.value=d};var m=function(a,b){g.call(this,a,b)};m.prototype=Object.create(g.prototype);m.prototype.constructor=m;m.prototype.toString=function(){var a=this.monthInput.value;this.dayInput&&(a+=","+this.dayInput.value);return a+=","+this.yearInput.value};m.prototype.parse=function(a){return a?a.split(","):null};m.prototype.getMonthOptions=function(){return w};var n=function(a,b){g.call(this,a,b)};n.prototype=Object.create(g.prototype);n.prototype.constructor=
n;n.prototype.toString=function(){var a=this.yearInput.value+"-"+this.monthInput.value;this.includeDay&&(a+="-"+this.dayInput.value);if("-"===a||"--"===a)a="";return a};n.prototype.parse=function(a){return a?(a=a.split("-"),a.push(a.shift()),a):null};n.prototype.getMonthOptions=function(){return x};return{ErrorDisplayInput:f,Input:d,TextInput:l,PasswordInput:q,TextArea:k,NumericDateInput:n,AlphaDateInput:m,NestedFields:h,NativeSelect:p,getProperties:v}}();
