Dialog=function(f,m){this.dialogConfig=f;this.options=$.extend(f.dialogOptions,m);this.adjustedView=!1;this.previousFocus=this.previousDialog=this.dialogContent=this.$element=this.element=this.headerElement=this.titleElement=this.title=null;this.maximized=this.pendingRefresh=!1;this.currentMenuElement=this.currentViewElement=null;this.keyboardShown=!1;this.inputFields={};this.hiddenFields={};this.originalData={};this.containers={};this.passwordInputs=[];this.leftMenu=null;this.dynamicHeight=LPTools.getOption(this.options,
"dynamicHeight",!1);this.responsive=LPTools.getOption(this.options,"responsive",!0);this.title=LPTools.getOption(this.options,"title",null);this.overlayDialog=LPTools.getOption(this.options,"overlayDialog",!1);this.backButton=this.nextButton=this.actionButtonContainer=this.buttonContainer=this.blurOverlay=this.inProcessOverlay=null;this.buttonHeight=this.headerHeight=0;this.excludedActions={};for(var e=LPTools.getOption(this.options,"excludedActions",[Constants.ACTION_EDIT]),k=0,p=e.length;k<p;++k)this.excludedActions[e[k]]=
!0;this.setupComplete=!1;(function(e){e.checkViewPasswordHandler=function(f){e.checkViewPassword(f)}})(this)};
(function(f){var m=!1,e=[],k=[],p=!1,t=function(a,b){for(var c=0,d=b.length;c<d;++c)if(a===b[c]){b.splice(c,1);break}},h={},q=f.body,r=!1,l=$(f.body);Dialog.prototype.DIALOG_FIELD="dialogField";Dialog.prototype.RIGHT_ALIGN=0;Dialog.prototype.CENTER_ALIGN=1;Dialog.prototype.LEFT_ALIGN=2;f.body.appendChild(LPTools.createElement("div",{id:"dialogLoadingOverlay","class":"overlay"}));f.body.appendChild(function(){var a=LPTools.createElement("div",{id:"dialogOverlay","class":"overlay"});$(a).bind("click",
function(){Dialog.prototype.closeAllDialogs()});return a}());Topics.get(Topics.ENTER).subscribe(function(a){0<k.length&&"TEXTAREA"!==a.target.nodeName&&"BUTTON"!==a.target.nodeName&&k[k.length-1].submit()});Topics.get(Topics.REQUEST_START).subscribe(function(a){if(0<k.length&&LPTools.getOption(a,"dialogRequest",!0)){var b=k[k.length-1],c;if(!(c=!a.hasOwnProperty("items"))){a:{c=b.$element;for(var d=a.items,g=0;g<d.length;++g)for(var n=d[g]._views,e=0;e<n.length;++e)if(jQuery.contains(c,n[e].getElement())){c=
!0;break a}c=!1}c=!c}c&&(b.showInProcessOverlay(),h[a.requestID]=b)}});Topics.get(Topics.REQUEST_SUCCESS).subscribe(function(a){if(LPTools.getOption(a,"dialogRequest",!0)){var b=h[a.requestID];if(b){delete h[a.requestID];var c=!1,d;for(d in h)if(h[d]===b){c=!0;break}c||(b.hideInProcessOverlay(),LPTools.getOption(a.requestSuccessOptions,"closeDialog",!0)&&b.closeOnSuccess())}}});Topics.get(Topics.REQUEST_ERROR).subscribe(function(a){if(LPTools.getOption(a,"dialogRequest",!0)){var b=h[a.requestID];
b&&(b.hideInProcessOverlay(),delete h[a.requestID])}});(function(){var a=null;Topics.get(Topics.DIALOG_LOADING).subscribe(function(){r=!0;clearTimeout(a);a=setTimeout(function(){l.addClass("dialogLoading")},250)});Topics.get(Topics.DIALOG_LOADED).subscribe(function(){r=!1;l.removeClass("dialogLoading");clearTimeout(a)})})();Dialog.prototype.closeAllDialogs=function(a){a="object"===typeof a&&a?a.forceClose:a;for(var b=e.slice(),c=0;c<b.length;c++)b[c].close(a)};Dialog.prototype.getCurrentDialog=function(){return 0<
e.length?e[e.length-1]:null};Dialog.prototype.closeInProcessDialogs=function(){for(var a in h)h[a].close(!0)};Dialog.prototype.refreshOpenDialogs=function(){for(var a=[],b=0,c=e.length;b<c;++b){var d=e[b],g=!1,n;for(n in h)if(h[n]===d){g=!0;break}g||(d=d.refresh())&&a.push(d)}LPTools.openAlerts(a)};Dialog.prototype.getDialogCount=function(){return e.length};Dialog.prototype.setIsDialogWindow=function(a){m=a};Dialog.prototype.isDialogWindow=function(){return m};Dialog.prototype.closeOnSuccess=function(){this.close(!0)};
Dialog.prototype.refresh=function(){for(var a in this.inputFields){var b=this.inputFields[a];"function"===typeof b.refresh&&b.refresh()}};Dialog.prototype.inProcess=function(){for(var a in h)if(this===h[a])return!0;return!1};Dialog.prototype.showInProcessOverlay=function(){null===this.inProcessOverlay&&(this.inProcessOverlay=LPTools.createElement("div","dialogInProcessOverlay"),this.element.appendChild(this.inProcessOverlay));this.$element.addClass("inProcess")};Dialog.prototype.hideInProcessOverlay=
function(){this.$element.removeClass("inProcess")};Dialog.prototype.showBlurOverlay=function(){null===this.blurOverlay&&(this.blurOverlay=LPTools.createElement("div","dialogBlurOverlay"),this.element.appendChild(this.blurOverlay));this.$element.addClass("blurred")};Dialog.prototype.hideBlurOverlay=function(){this.$element.removeClass("blurred")};Dialog.prototype.addHeaderButton=function(a,b,c){void 0===this.headerButtons&&(this.headerButtons=LPTools.createElement("div","dialogHeaderButtons"),a.append(this.headerButtons),
a.addClass("dialogHeaderButtonsEnabled"));$(b).addClass("dialogHeaderButton");LPPlatform.addEventListener(b,"click",c);this.headerButtons.appendChild(b)};Dialog.prototype.maximize=function(){this.$element.addClass("maximized");this.maximizeButton.setAttribute("title",Strings.Vault.MINIMIZE);this.maximized=!0};Dialog.prototype.minimize=function(){this.$element.removeClass("maximized");this.maximizeButton.setAttribute("title",Strings.Vault.MAXIMIZE);this.maximized=!1;this.setDynamicHeight()};Dialog.prototype.loadDialog=
function(a){var b=this.dialogConfig.getID()+"Title";this.element=LPTools.createElement("div",{"class":function(a){var b=["dialog"];m&&!a.isOverlay()&&b.push("dialogWindow");a.responsive&&b.push("responsive");return b.concat(LPTools.getOption(a.options,"additionalClasses",[]))}(this),role:"dialog","aria-labelledby":b});this.$element=$(this.element);var c=["dialogHeader"],c=c.concat(LPTools.getOption(this.options,"additionalHeaderClasses",[]));this.headerElement=LPTools.createElement("div",c);c=LPTools.createElement("div",
"dialogHeaderInner");this.titleElement=LPTools.createElement("span",{"class":"dialogHeaderTitle",id:b});c.appendChild(this.titleElement);this.headerElement.appendChild(c);this.element.appendChild(this.headerElement);this.titleElement=$(this.titleElement);this.headerElement=$(this.headerElement);!this.isOverlay()&&m||!LPTools.getOption(this.options,"maximizeButtonEnabled",!1)||(this.maximizeButton=LPTools.createElement("button",{title:Strings.Vault.MAXIMIZE,"class":"dialogMaximizeButton"}),this.addHeaderButton(this.headerElement,
this.maximizeButton,this.createHandler(function(){this.maximized?this.minimize():this.maximize();Topics.get(Topics.DIALOG_RESIZE).publish(this)})));!this.isOverlay()&&m||!LPTools.getOption(this.options,"closeButtonEnabled",!1)||this.addHeaderButton(this.headerElement,LPTools.createElement("button",{title:Strings.Vault.CLOSE,"class":"dialogCloseButton"}),this.createHandler(this.close));this.dialogContent=LPTools.createElement("div",LPTools.getOption(this.options,"buttonsInsideContent",!1)?"dialogContent":
"dialogContent dialogContentFixed");this.element.appendChild(this.dialogContent);this.dialogContent=$(this.dialogContent);this.dialogConfig.parentElementID?f.getElementById(this.dialogConfig.parentElementID).appendChild(this.element):q.appendChild(this.element);this.element.setAttribute("id",this.dialogConfig.getID());this.dialogConfig.load(this.dialogContent,a)};Dialog.prototype.getNextViewButton=function(){return this.nextButton};Dialog.prototype.setupButtons=function(a){if(LPTools.getOption(this.options,
"hideButtons",!1)||0!==a.find(".buttons").length)this.buttonContainer=$();else{a=["buttons"];LPTools.getOption(this.options,"buttonsInsideContent",!1)||(a=a.concat(["buttonsFixed"]));this.buttonContainer=LPTools.createElement("div",a);this.buttonContainer=$(this.buttonContainer);a=["nbtn"];LPTools.getOption(this.options,"largeButtons",!1)||a.push("btn_midi");this.nextButton=LPTools.createElement("button",a.concat("rbtn"),LPTools.getOption(this.options,"nextButtonText",Strings.Vault.SAVE));this.nextButton=
$(this.nextButton);var b=LPTools.getOption(this.options,"views",null);b&&(this.views=b,this.currentViewIndex=0,b=this.getNextViewButton(),b!==this.nextButton&&b.bind("click",this.createHandler(this.showNextView)));this.nextButton.bind("click",this.createHandler(this.submit));LPTools.getOption(this.options,"hideBackButton",!1)||(this.backButton=LPTools.createElement("button",a.concat("wbtn"),LPTools.getOption(this.options,"backButtonText",Strings.Vault.CANCEL)),this.backButton=$(this.backButton),this.backButton.bind("click",
this.createHandler(this.close)),this.buttonContainer.append(this.backButton));this.buttonContainer.append(this.nextButton);a=LPTools.getOption(this.options,"buttonAlign",this.CENTER_ALIGN);a===this.RIGHT_ALIGN?this.buttonContainer.addClass("rightButtons"):a===this.CENTER_ALIGN&&this.buttonContainer.addClass("centerButtons");LPTools.getOption(this.options,"buttonsInsideContent",!1)?this.dialogContent.append(this.buttonContainer):this.$element.append(this.buttonContainer)}};Dialog.prototype.applyToContainers=
function(a){for(var b in this.containers){var c=this.containers[b];if(c)switch(typeof a){case "string":c[a].apply(c);break;case "function":a.call(this,c)}}};Dialog.prototype.destroyContainers=function(){this.applyToContainers("destruct");for(var a in this.containers)this.containers[a]=null};Dialog.prototype.createHandler=function(a){for(var b=[],c=1,d=arguments.length;c<d;++c)b.push(arguments[c]);return function(c){return function(){a.apply(c,b)}}(this)};Dialog.prototype.createDynamicHandler=function(a){return function(b){return function(){a.apply(b,
arguments)}}(this)};Dialog.prototype.resetScroll=function(){this.$element.find(".dialogRightPane").scrollTop(0)};Dialog.prototype.leftMenuChange=function(a){};Dialog.prototype.setupLeftMenu=function(a){this.leftMenu=a.find(".dialogLeftMenu");if(0<this.leftMenu.length){var b=function(a,b,c){return function(d){a.currentViewElement&&a.currentViewElement.removeClass("selected");a.currentMenuElement&&a.currentMenuElement.removeClass("selected");a.currentViewElement=c;a.currentMenuElement=b;a.currentViewElement.addClass("selected");
a.currentMenuElement.addClass("selected");a.resetScroll();a.leftMenuChange(b)}};a=a.find(".dialogLeftMenuView");for(var c=this.leftMenu.get(0).children,d=0,g=c.length;d<g;++d){var n=$(c[d]),e=b(this,n,$(a[d]));n.bind("click",e)}}};Dialog.prototype.selectFirstLeftMenuItem=function(){this.leftMenu&&this.leftMenu.find(":visible").first().trigger("click")};Dialog.prototype.addZebraStriping=function(a){a=a.find(".settings");for(var b=0,c=a.length;b<c;++b)LPTools.addZebraStriping(a[b])};Dialog.prototype.show=
function(){this.$element.show()};Dialog.prototype.hide=function(){this.$element.hide()};Dialog.prototype.initialize=function(a){a.find("input,textarea").prop("spellcheck",!1);this.setupButtons(a);this.addZebraStriping(a);this.setupLeftMenu(a);(function(b){var c=a.find(".advancedOptionsLabel");c.length&&(c.attr("aria-expanded","false"),b.advancedOptionsLabel=c,b.advancedOptionsShown=!1);c.bind("click",b.createHandler(b.toggleAdvancedOptions));a.bind("click",function(){b.applyToContainers("clearSelected")})})(this);
a.find(".help").bind("click",function(a){bg.openhelp(a.target.getAttribute("help-section"))});this.initializeInputObjects(a);this.intializeFocusHandlers(a);this.show();LPTools.getOption(this.options,"buttonsInsideContent",!1)||(this.buttonHeight=this.buttonContainer.outerHeight(),this.dialogContent.css("bottom",this.buttonHeight));this.headerHeight=this.headerElement?this.headerElement.outerHeight():0;this.responsiveTextAreas=[];this.responsiveTextAreasSelector=this.$element.find(".responsiveTextArea");
for(var b=u(this.responsiveTextAreasSelector),c=0,d=this.responsiveTextAreasSelector.length;c<d;++c){var g=$(this.responsiveTextAreasSelector[c]);this.responsiveTextAreas.push({element:g,ratio:g.outerHeight()/b*100})}this.hide()};Dialog.prototype.toggleKeyboard=function(){this.keyboardShown?this.disableVirtualKeyboard():this.enableVirtualKeyboard()};Dialog.prototype.enableVirtualKeyboard=function(){var a=function(){this.focus();this.$element.addClass("keyboard");VirtualKeyboard.show(f.activeElement,
q);this.keyboardShown=VirtualKeyboard.isOpen()};return function(){if("undefined"===typeof VirtualKeyboard){var b=LPTools.createElement("script",{type:"text/javascript",src:LPPlatform.getBaseURL()+"/js/virtualkeyboard/vk_loader.js?vk_layout=US%20US&vk_skin=air_small"});f.head.appendChild(b);var c=setInterval(this.createHandler(function(){"undefined"!==typeof VirtualKeyboard&&(a.call(this),this.keyboardShown&&(this.$element.find(".dialogInput").bind("focus",function(a){VirtualKeyboard.attachInput(a.target)}),
clearInterval(c)))}),100)}else a.call(this)}}();Dialog.prototype.disableVirtualKeyboard=function(){"undefined"!==typeof VirtualKeyboard&&(VirtualKeyboard.hide(),this.$element.removeClass("keyboard"),this.keyboardShown=!1)};Dialog.prototype.intializeFocusHandlers=function(){var a=function(a){a=a.find(".dialogInput:visible,button:visible");return 2<a.length?a:null};return function(b){var c=LPTools.createElement("button","focusCycler");LPPlatform.addEventListener(c,"focus",function(){var c=a(b);c&&c[1].focus()});
b.append(c);c=LPTools.createElement("button","focusCycler");LPPlatform.addEventListener(c,"focus",function(){var c=a(b);c&&c[c.length-2].focus()});b.prepend(c)}}();Dialog.prototype.toggleAdvancedOptions=function(){this.advancedOptionsShown?this.hideAdvancedOptions():this.showAdvancedOptions()};Dialog.prototype.showAdvancedOptions=function(){this.advancedOptionsLabel.attr("aria-expanded","true");this.advancedOptionsLabel.addClass("open");this.advancedOptionsLabel.next().show();this.setDynamicHeight();
this.advancedOptionsShown=!0};Dialog.prototype.hideAdvancedOptions=function(){this.advancedOptionsLabel.attr("aria-expanded","false");this.advancedOptionsLabel.removeClass("open");this.advancedOptionsLabel.next().hide();this.setDynamicHeight();this.advancedOptionsShown=!1};Dialog.prototype.showNextView=function(){this.performValidate({data:this.getData(),callback:function(a){a&&this.setNextView(this.currentViewIndex+1)}})};Dialog.prototype.setNextView=function(a){if(0<=a&&a<this.views.length&&a!==
this.currentViewIndex){var b=this.views[a],c=this.views[this.currentViewIndex];void 0===c.title&&(c.title=this.getTitle());LPTools.getOption(this.options,"hideBackButton",!1)||(void 0===c.cancelButtonText&&(c.cancelButtonText=this.backButton.text()),this.backButton.text(void 0===b.cancelButtonText?Strings.translateString("Back"):b.cancelButtonText));$(c.selector).hide();this.setTitle(b.title);b.nextButtonText&&this.nextButton.text(b.nextButtonText);$(b.selector).show();LPTools.getOption(this.options,
"hideBackButton",!1)||(0===a?(this.backButton.unbind("click"),this.backButton.bind("click",this.createHandler(this.close))):(this.backButton.unbind("click"),this.backButton.bind("click",this.createHandler(this.showPreviousView))));this.currentViewIndex=a;LPTools.getOption(b,"dynamicHeight",!0)&&this.setDynamicHeight();this.focus()}};Dialog.prototype.showPreviousView=function(){this.setNextView(this.currentViewIndex-1)};Dialog.prototype.initializeInputFields=function(a,b){for(var c=0,d=a.length;c<
d;++c){var g=a[c],e=g.getAttribute(this.DIALOG_FIELD),f=this.inputFields[e];void 0===f?this.inputFields[e]=b.call(this,g,e):"radio"===g.getAttribute("type")&&(e=g.getAttribute("name"))&&f.addRadioInput(e,g)}};var v=function(a){var b=LPTools.createTimezoneSelect();a.parentElement.insertBefore(b,a);a.parentElement.removeChild(a);return new DialogInput.Input(b)},w=function(a,b){var c={};$(a).hasClass("monthYearDate")&&(c.includeDay=!1);c=new DialogInput.NumericDateInput(b,c);a.parentElement.insertBefore(c.buildInput(),
a);a.parentElement.removeChild(a);return c};Dialog.prototype.initializeInputObjects=function(a){this.initializeInputFields(a.find("input.selectDropdown"),function(a){return new DropdownInput(a,null,{dialog:this,additionalDropdownClasses:this.options.additionalDropdownClasses})});this.initializeInputFields(a.find(".typeaheadDropdown"),function(a){return new TypeaheadDropdown(a,null,{dialog:this,additionalDropdownClasses:this.options.additionalDropdownClasses})});this.initializeInputFields(a.find(".timezoneDropdown"),
v);this.initializeInputFields(a.find(".dateInput"),w);this.initializeInputFields(a.find("select["+this.DIALOG_FIELD+"]"),function(a){return new DialogInput.NativeSelect(a,this)});this.initializeInputFields(a.find("input["+this.DIALOG_FIELD+"],textarea["+this.DIALOG_FIELD+"]"),function(a){a=new DialogInput.Input(a,this);var b=a.getElement();b.hasClass("passwordToggle")&&this.addPasswordEye(b);return a})};Dialog.prototype.addPasswordEye=function(a){a.LP_addPasswordEye({checkPermissionHandler:this.checkViewPasswordHandler,
includeGenerateButton:a.hasClass("generate")})};Dialog.prototype.checkViewPassword=function(a){a()};Dialog.prototype.close=function(a){if(LPTools.getOption(this.options,"confirmOnClose",!0)&&(void 0===a||!a)&&this.isModified())return dialogs.confirmation.open({title:Strings.translateString("Discard Unsaved Changes?"),text:Strings.translateString("Changes will be lost if you close before saving."),nextButtonText:Strings.translateString("Discard"),backButtonText:Strings.Vault.CANCEL,handler:this.createHandler(this.close,
!0)}),!1;f.activeElement&&"INPUT"===f.activeElement.nodeName.toUpperCase()&&"password"===f.activeElement.type&&f.activeElement.blur();this.clearFields();this.destroyContainers();this.hide();t(this,e);t(this,k);this.disableVirtualKeyboard();0<e.length?this.focusPreviousDialog():(l.removeClass("dialogState"),l.css("min-width",""));this.previousFocus&&this.previousFocus.focus();this.hideBlurOverlay();this.hideInProcessOverlay();this.setupComplete=!1;"function"===typeof this.data.onClose&&this.data.onClose.apply(this);
Topics.get(Topics.DIALOG_CLOSE).publish(this);return!0};Dialog.prototype.differs=function(){var a=function(a){return null===a||"undefined"===typeof a};return function(b,c){if(b&&c){for(var d in b){var g=b[d];if("object"===typeof g){if(this.differs(g,c[d]))return!0}else{var e=c[d],g=a(g)&&a(e)?!1:g!==e;if(g)return!0}}for(var f in c)if(!a(c[f])&&!b.hasOwnProperty(f))return!0;return!1}return!0}}();Dialog.prototype.getChanges=function(a){var b={},c;for(c in a){var d=this.originalData[c],e=a[c];"object"===
typeof d?(d=this.getChanges(d,e),LPTools.hasProperties(d)&&(b[c]=d)):d!==e&&(b[c]=e)}return b};Dialog.prototype.isModified=function(){var a=this.getData(),b=this.getOriginalData();return this.differs(b,a)};Dialog.prototype.getOriginalData=function(){return this.originalData};Dialog.prototype.clearFields=function(){for(var a in this.inputFields)this.inputFields[a].clear();this.clearErrors();this.originalData={};this.originalFormData={};this.hiddenFields={}};Dialog.prototype.addError=function(a,b){this.inputFields[a].addError(b,
this)};Dialog.prototype.populateFields=function(a){for(var b in a){var c=this.inputFields[b],d=a[b];c?c.setValue(d):this.hiddenFields[b]=d}};Dialog.prototype.getData=function(){var a={},b;for(b in this.inputFields)a[b]=this.inputFields[b].getValue();for(var c in this.hiddenFields)a[c]=this.hiddenFields[c];return $.extend(!0,{},a)};Dialog.prototype.initFunction=function(a){return function(b){return function(){Strings.translate(b.dialogContent.get(0));b.initialize(b.$element);b.preSetup(a);b.setup(b.$element,
a);b.postSetup(a)}}(this)};Dialog.prototype.open=function(a){e.push(this);LPTools.getOption(this.options,"submitDialog",!0)&&k.push(this);this.data=a=a||{};null===this.element?this.loadDialog(this.initFunction(a)):(this.preSetup(a),this.setup(this.$element,a),this.postSetup(a))};Dialog.prototype.preSetup=function(a){a=LPTools.getOption(a,"preSetup",null);"function"===typeof a&&a(this)};Dialog.prototype.postSetup=function(a){this.setupComplete=!0;this.originalData=this.getData();a.virtualKeyboard&&
this.enableVirtualKeyboard();a=LPTools.getOption(a,"postSetup",null);"function"===typeof a&&a(this);this.adjustView()};Dialog.prototype.adjustView=function(a){if(!this.adjustedView||a){for(var b in this.inputFields)a=this.inputFields[b],"function"===typeof a.adjustView&&a.adjustView();this.adjustedView=!0}};Dialog.prototype.getZIndex=function(){var a=this.$element.css("z-index");return"auto"===a?0:parseInt(a)};Dialog.prototype.useDynamicHeignt=function(a){this.dynamicHeight&&!a&&this.element.removeAttribute("style");
this.dynamicHeight=a};var u=function(a){for(var b=0,c=0,d=a.length;c<d;++c)b+=$(a[c]).outerHeight();return b};Dialog.prototype.setDynamicHeight=function(){var a=window.outerHeight-window.innerHeight,b=window.outerWidth-window.innerWidth;return function(){if(this.dynamicHeight){this.show();this.dialogContent.css("position","static");var c=this.dialogContent.outerHeight();!LPTools.getOption(this.options,"hideHeader",!1)&&this.headerHeight&&(c+=this.headerHeight);!LPTools.getOption(this.options,"hideButtons",
!1)&&this.buttonHeight&&(c+=this.buttonHeight);this.$element.css(this.responsive?"max-height":"height",c);for(var c=this.dialogContent.height()-u(this.responsiveTextAreasSelector),d=0,e=this.responsiveTextAreas.length;d<e;++d){var f=this.responsiveTextAreas[d];f.element.css("height","calc("+f.ratio+"% - "+c+"px)")}this.dialogContent.css("position","")}this.responsive||!m||this.isOverlay()||(l.css("overflow","hidden"),LPPlatform.resizeTo(this.$element.outerWidth()+b,this.$element.outerHeight()+a),
l.css("overflow",""));"function"===typeof this.data.onResize&&this.data.onResize.call(this,this.$element.outerHeight(),this.$element.outerWidth())}}();Dialog.prototype.isOverlay=function(){return this.overlayDialog&&(0<e.length&&e[0]!==this||p)};Dialog.prototype.blurPreviousDialog=function(){this.previousDialog&&(this.isOverlay()?this.previousDialog.showBlurOverlay():this.previousDialog.hide())};Dialog.prototype.focusPreviousDialog=function(){this.previousDialog&&(this.isOverlay()?this.previousDialog.hideBlurOverlay():
(this.previousDialog.show(),this.previousDialog.setMinWidth()),this.previousDialog.setDynamicHeight(),this.previousDialog=null)};Dialog.prototype.focus=function(){var a=this.$element.find(".dialogInput:visible").first();0<a.length?a.focus():this.nextButton&&this.nextButton.focus()};Dialog.prototype.setup=function(a,b){LPTools.getOption(this.options,"hideHeader",!1)?(this.headerElement.LP_hide(),this.dialogContent.css("top","")):(this.dialogContent.css("top",this.headerHeight),this.headerElement.LP_show());
var c=q;this.dialogConfig.parentElementID&&(c=f.getElementById(this.dialogConfig.parentElementID));this.element.parentElement!==c&&c.appendChild(this.element);this.defaultFields(b);"undefined"!==typeof LPProxy&&LPTools.parseUserSpecificMenu(a.get(0),LPProxy.getAccountClass());this.setTitle(b.title||this.title);this.views&&(this.views[0].title=b.title,this.setNextView(0));this.setDynamicHeight();this.previousFocus=f.activeElement;1<e.length&&(this.previousDialog=e[e.length-2],c=this.previousDialog.getZIndex(),
a.css("z-index",c+1),this.blurPreviousDialog());1===e.length&&l.addClass("dialogState");LPTools.getOption(b,"show",!0)&&a.show();this.focus();this.setMinWidth();this.resetScroll();this.selectFirstLeftMenuItem();r&&Topics.get(Topics.DIALOG_LOADED).publish();Topics.get(Topics.DIALOG_OPEN).publish(this)};Dialog.prototype.setMinWidth=function(){var a=parseInt(this.$element.css("min-width"));0<a?l.css("min-width",a+40):l.css("min-width","")};Dialog.prototype.clearErrors=function(){for(var a in this.inputFields)this.inputFields[a].clearErrors();
this.leftMenu&&this.leftMenu.children().removeClass("error")};Dialog.prototype.performValidate=function(a){this.validateOptions=a;this.clearErrors();var b=this.validate(a.data);this.postValidate(b);a.callback&&a.callback.call(this,b)};Dialog.prototype.postValidate=function(a){this.validateOptions=null;for(var b in this.inputFields){var c=this.inputFields[b];"function"===typeof c.postValidate&&c.postValidate()}if(!a&&(this.setDynamicHeight(),0<this.leftMenu.length))for(b in this.inputFields)if(a=this.inputFields[b],
a.hasError()&&(a=a.getElement().closest(".dialogLeftMenuView"),0<a.length)){a=a.get(0);for(var c=a.parentElement,d=0,e=c.children.length;d<e;++d)c.children[d]===a&&this.leftMenu.children().eq(d).addClass("error")}};Dialog.prototype.validate=function(a){var b=!0,c;for(c in this.inputFields){var d=this.inputFields[c];if(!LPTools.getOption(this.validateOptions,"errorsOnly",!1)||d.hasError())b=d.validate(this,c,a[c])&&b}return b};Dialog.prototype.submit=function(){try{if(this.getNextViewButton()===this.nextButton&&
this.views&&this.currentViewIndex<this.views.length-1)this.showNextView();else{var a=this.getData();this.performValidate({data:a,callback:function(b){b&&(b=LPTools.getOption(this.data,"handleSubmit",null),"function"===typeof b?b(a,this.data):this.handleSubmit(a,this.data))}})}}catch(b){LPPlatform.logException(b)}};Dialog.prototype.getTitle=function(){return this.title};Dialog.prototype.setTitle=function(a){a&&(this.title=a,this.titleElement&&!LPTools.getOption(this.options,"hideHeaderTitle",!1)&&
this.titleElement.text(a),this.titleElement.text().trim()?this.headerElement.addClass("titleEnabled"):this.headerElement.removeClass("titleEnabled"))};Dialog.prototype.defaultFields=function(a){for(var b in this.inputFields){var c=this.inputFields[b];"function"===typeof c["default"]?c["default"]():c.setValue("")}this.populateFields(LPTools.getOption(a,"defaultData",{}))};Dialog.prototype.getErrorOptions=function(){return{}};VaultItemDialog=function(a,b){Dialog.call(this,a,b);(function(a){a.itemButtonHandler=
function(b){b=LPTools.getAttribute(a.actionButtonContainer.get(0),b.target,"vaultaction");a.vaultItem.handleClickEvent(b,{itemsForAction:[a.vaultItem],source:a.data.saveOptions&&a.data.saveOptions.source?a.data.saveOptions.source:"vault"})}})(this)};VaultItemDialog.prototype=Object.create(Dialog.prototype);VaultItemDialog.prototype.constructor=VaultItemDialog;(function(){VaultItemDialog.prototype.refresh=function(){Dialog.prototype.refresh.apply(this,arguments);if(this.data.vaultItem&&!this.pendingRefresh){if(this.data.vaultItem.removed)return this.pendingRefresh=
!0,function(a){return{type:"alert",title:Strings.translateString("Deleted"),text:Strings.translateString("%1 has been deleted. This dialog will be closed.",a.data.vaultItem.toString()),handler:function(){a.close(!0);a.pendingRefresh=!1}}}(this);var a=this.getFormData();if(this.differs(this.originalFormData,a))return this.pendingRefresh=!0,function(b){return{type:"confirmation",title:Strings.translateString("Updated"),text:Strings.translateString("%1 has been updated. Would you like to update this dialog with the latest data?",
b.data.vaultItem.toString()),handler:function(){b.populateFields(a);b.originalData=b.getData();b.pendingRefresh=!1}}}(this)}};VaultItemDialog.prototype.getDialogActions=function(a){var b=a.vaultItem.newDisplayObject();a.dialogActions=b.getDialogActions()};VaultItemDialog.prototype.open=function(a){a=a||{};a.saveOptions=$.extend({source:"vault"},a.saveOptions);"string"===typeof a.vaultItem&&"function"===typeof a.sourceFunction&&(a.vaultItem=a.sourceFunction(a.vaultItem),void 0===a.dialogActions&&this.getDialogActions(a));
a.vaultItem&&(a.actions=this.getItemButtonActions(a));a.vaultItem?(p=!0,a.vaultItem.passwordProtect(this.createHandler(function(){p=!1;Dialog.prototype.open.call(this,a)}))):Dialog.prototype.open.call(this,a)};VaultItemDialog.prototype.getItemButtonActions=function(a){if(a.dialogActions){for(var b=[],c=0,d=a.dialogActions.length;c<d;++c){var e=a.dialogActions[c];void 0===this.excludedActions[e]&&b.push(e)}return b}};VaultItemDialog.prototype.handleSubmit=function(a){this.vaultItem?this.isModified()?
this.save(this.vaultItem,a):this.close(!0):this.add(a)};VaultItemDialog.prototype.save=function(a,b){a.saveFromDialog(b,null,this.data.saveOptions)};VaultItemDialog.prototype.getFormData=function(){if(this.vaultItem){var a=$.extend(!0,DialogInput.getProperties(this.inputFields),DialogInput.getProperties(this.hiddenFields));return this.vaultItem.getFormData(a)}return{}};VaultItemDialog.prototype.setup=function(a,b){Dialog.prototype.setup.apply(this,arguments);if(this.vaultItem=LPTools.getOption(b,
"vaultItem",void 0))this.originalFormData=this.getFormData(),this.populateFields(this.originalFormData);this.buildActionButtons(LPTools.getOption(b,"actions",null))};VaultItemDialog.prototype.postSetup=function(a){Dialog.prototype.postSetup.apply(this,arguments);a.dialogData&&this.populateFields(a.dialogData)};VaultItemDialog.prototype.buildActionButtons=function(a){this.actionButtonContainer&&(this.actionButtonContainer.unbind("click"),this.actionButtonContainer.empty());if(a){null===this.actionButtonContainer&&
(this.actionButtonContainer=LPTools.createElement("div","dialogItemButtons"),this.actionButtonContainer=$(this.actionButtonContainer),this.buttonContainer.prepend(this.actionButtonContainer));this.actionButtonContainer.bind("click",this.itemButtonHandler);for(var b=0,c=a.length;b<c;++b)this.actionButtonContainer.append(LPTools.buildItemButton(a[b]))}};VaultItemDialog.prototype.add=function(a){if(this.options.type)(new this.options.type).addFromDialog(a,null,this.data.saveOptions);else throw"Dialog must provide a type for new item or override this function.";
}})()})(document);
