EditableFieldsDialog=function(b,d){d=d||{};d.views=[{selector:".mainView"},{selector:".formFieldsView",title:Strings.translateString("Edit Form Fields"),dynamicHeight:!1}];DialogWithGroupInput.call(this,b,d);this.postSetupData=this.fieldsTable=this.addFieldsButton=this.fieldsElement=null;this.editFormFieldsButton=$(LPTools.buildItemButton(Constants.ACTION_EDIT));this.editFormFieldsButton.attr("title",Strings.translateString("Edit Form Fields"))};EditableFieldsDialog.prototype=Object.create(DialogWithGroupInput.prototype);
EditableFieldsDialog.prototype.constructor=EditableFieldsDialog;
(function(){var b=function(a,c){DialogInput.Input.call(this,void 0);this.fieldElements=[];this.container=a;this.parentDialog=c};b.prototype=Object.create(DialogInput.Input.prototype);b.prototype.constructor=b;b.prototype.clear=function(){LPTools.removeDOMChildren(this.container)};b.prototype.getValue=function(){for(var a=[],c=0,e=this.fieldElements.length;c<e;++c){var d=this.fieldElements[c];d.data.value=d.input.getValue();a.push($.extend({},d.data))}return a};b.prototype.setValue=function(a){LPTools.removeDOMChildren(this.container);
this.fieldElements=[];for(var c=0,e=a.length;c<e;++c)this.addField(a[c]);LPTools.addZebraStriping(this.container)};b.prototype.addField=function(a){if("hidden"!==a.type){var c=LPTools.createElement("tr","settingsRow");c.appendChild(LPTools.createElement("td","settingLabel",a.name));var e="Form Field "+a.name;switch(a.type){case "radio":case "select":case "select-one":e=LPTools.createElement("input",{"class":"dialogInput",type:"text","aria-label":e});break;case "checkbox":e=LPTools.buildCheckbox(void 0,
{checkboxAttributes:{"aria-label":e}});break;default:e=LPTools.createElement("input",{"class":"dialogInput",type:a.type,"aria-label":e})}var b;b=$(e);b=b.is("input")?e:b.find("input").get(0);b=new DialogInput.Input(b);this.fieldElements.push({data:a,input:b});b.setValue(a.value);var f=LPTools.createElement("td","formFieldValue"),g=LPTools.createElement("div");f.appendChild(g);g.appendChild(e);c.appendChild(f);e=LPTools.createElement("div","rightItemButtons");f=LPTools.buildItemButton(Constants.ACTION_REMOVE);
$(f).bind("click",d(this.parentDialog,this.container,c,this.fieldElements,a));e.appendChild(f);g.appendChild(e);this.container.appendChild(c);"password"===a.type&&b.getElement().LP_addPasswordEye({checkPermissionHandler:this.parentDialog.checkViewPasswordHandler})}};var d=function(a,c,e,b,d){return function(){for(var g=null,f=0,h=b.length;f<h;++f)if(b[f].data===d){g=f;break}if(null!==g){var k=function(){c.removeChild(e);LPTools.addZebraStriping(c);b.splice(g,1)};a.vaultItem?LPRequest.makeUpdateRequest(LPProxy.deleteField,
{parameters:[a.vaultItem,a.vaultItem._data.fields[g]],requestSuccessOptions:{closeDialog:!1},success:function(){k();a.vaultItem.removeField(g);a.originalData=a.getData(!1)},confirm:{title:Strings.Vault.DELETE,text:Strings.translateString("Are you sure you want to delete field %1?",d.name)}}):k()}}};EditableFieldsDialog.prototype.initialize=function(a){DialogWithGroupInput.prototype.initialize.apply(this,arguments);this.formFieldsView=a.find(".formFieldsView");this.fieldsTable=a.find(".fieldsTable");
this.fieldsElement=a.find(".fieldsElement");this.addFieldsButton=a.find(".addFormFieldButton");this.inputFields.fields=new b(this.fieldsElement.get(0),this);this.addFieldsButton.bind("click",function(a){return function(){dialogs.addFormField.open({sourceDialog:a})}}(this))};EditableFieldsDialog.prototype.getNextViewButton=function(){return this.editFormFieldsButton};EditableFieldsDialog.prototype.setNextView=function(a){DialogWithGroupInput.prototype.setNextView.apply(this,arguments);0<a?this.editFormFieldsButton.hide():
this.editFormFieldsButton.show()};EditableFieldsDialog.prototype.postSetup=function(){DialogWithGroupInput.prototype.postSetup.apply(this,arguments);this.postSetupData=this.getData()};EditableFieldsDialog.prototype.clearFields=function(){DialogWithGroupInput.prototype.clearFields.apply(this,arguments);this.postSetupData=null};EditableFieldsDialog.prototype.getData=function(){var a=DialogWithGroupInput.prototype.getData.apply(this,arguments),c=this.postSetupData;if(c&&c.fields&&a.fields)for(var b=
a.unencryptedUsername!==c.unencryptedUsername,d=a.password!==c.password,f=null,g=null,l=0;l<a.fields.length;++l){var h=a.fields[l],k=c.fields[l];if(k){var m=h.value!==k.value;c.unencryptedUsername&&c.unencryptedUsername===k.value?b?h.value=a.unencryptedUsername:m&&null===f?a.unencryptedUsername=f=h.value:null!==f&&(h.value=f):c.password&&c.password===k.value&&(d?h.value=a.password:m&&null===g?a.password=g=h.value:null!==g&&(h.value=g))}}return a};EditableFieldsDialog.prototype.setup=function(a,c){c.vaultItem?
this.addFieldsButton.LP_show():this.addFieldsButton.LP_hide();this.editFormFieldsButton.LP_hide();this.$element.removeClass("saveAll");this.fieldsTable.append(this.fieldsElement);this.formFieldsView.append(this.addFieldsButton);if(c.defaultData&&c.defaultData.save_all||c.vaultItem&&c.vaultItem._data.save_all){this.$element.addClass("saveAll");var b=a.find(".saveAllFields");b.append(this.fieldsElement);b.after(this.addFieldsButton)}else c.vaultItem&&this.editFormFieldsButton.LP_show();DialogWithGroupInput.prototype.setup.apply(this,
arguments)};EditableFieldsDialog.prototype.checkViewPassword=function(a){this.vaultItem?this.vaultItem.canViewPassword()?LPProxy.reprompt(function(c){return function(){a();bg.loglogin(c.vaultItem.getID())}}(this),{types:AccountBaseWithFields.prototype.REPROMPT_TYPE_VIEW_PW}):Topics.get(Topics.ERROR).publish(Strings.translateString("This is a shared site. You are not permitted to view the password.")):a()}})();
var AddFormFieldDialog=function(b){Dialog.call(this,b,{closeButtonEnabled:!0,nextButtonText:Strings.translateString("Add"),title:Strings.translateString("Add Form Field"),dynamicHeight:!0,overlayDialog:!0});this.fieldsInput=null};AddFormFieldDialog.prototype=Object.create(Dialog.prototype);AddFormFieldDialog.prototype.constructor=AddFormFieldDialog;
AddFormFieldDialog.prototype.initialize=function(b){Dialog.prototype.initialize.apply(this,arguments);(function(b){b.inputFields.type.onChange(function(){var a=!1;return function(c){var d="checkbox"===c;d!==a&&(c=document.getElementById("addFormFieldDialogValue"),LPTools.removeDOMChildren(c),(a=d)?(d=LPTools.buildCheckbox(),c.appendChild(d),b.inputFields.value.setElement($(d).find("input"))):(d=LPTools.createElement("input",{"class":"dialogInput",type:"text"}),c.appendChild(d),b.inputFields.value.setElement(d)))}}())})(this)};
AddFormFieldDialog.prototype.setup=function(b,d){d.sourceDialog&&d.sourceDialog.vaultItem&&d.sourceDialog.vaultItem._data.save_all?$("#addFormFieldDialogFormName").LP_show():$("#addFormFieldDialogFormName").LP_hide();Dialog.prototype.setup.apply(this,arguments)};
AddFormFieldDialog.prototype.validate=function(b){var d=Dialog.prototype.validate.apply(this,arguments);if(b.name)for(var a=this.data.sourceDialog.inputFields.fields.getValue(),c=0,e=a.length;c<e;++c)a[c].name===b.name&&(this.addError("name","A field with this name already exists."),d=!1);else this.addError("name","Field Name is required."),d=!1;b.type||(this.addError("type","Field Type is required."),d=!1);return d};
AddFormFieldDialog.prototype.handleSubmit=function(b){(function(d){var a=$.extend({},b);d.vaultItem.processEnteredFieldData(b);LPRequest.makeUpdateRequest(LPProxy.addField,{parameters:[d.vaultItem,b],success:function(){d.vaultItem.addField(b);d.inputFields.fields.addField(a);d.originalData=d.getData(!1)}})})(this.data.sourceDialog)};
