var ExtensionCreateAccount=function(g){Dialog.call(this,g,{views:[{selector:"#emailEntry",nextButtonText:Strings.translateString("Create Account")},{selector:"#mpEntry",nextButtonText:Strings.translateString("Unlock my Vault")}],dynamicHeight:!1,responsive:!1,additionalHeaderClasses:["icon"],nextButtonText:Strings.translateString("Create Account"),buttonAlign:this.CENTER_ALIGN,hideBackButton:!0,largeButtons:!0,buttonsInsideContent:!0,title:Strings.translateString("Create Account"),hideHeaderTitle:!0})};
ExtensionCreateAccount.prototype=Object.create(CreateAccountDialog.prototype);ExtensionCreateAccount.prototype.constructor=ExtensionCreateAccount;
(function(){function g(){b.inputFields.email.onChange(function(c){c&&h(c,function(a){b.inputFields.email.validate({response:a})})})}function l(){b.inputFields.password.onChange(function(c){c&&b.inputFields.password.validate({password:b.inputFields.password.getValue(),email:b.inputFields.email.getValue()})});b.inputFields.password.getElement().keyup(function(c){b.inputFields.password.validate({password:b.inputFields.password.getValue(),email:b.inputFields.email.getValue()},!0)})}function m(){b.inputFields.reconfirm.onChange(function(c){c&&
b.inputFields.reconfirm.validate({reconfirm:b.inputFields.reconfirm.getValue(),password:b.inputFields.password.getValue()})})}function n(){b.inputFields.reminder.onChange(function(c){c&&b.inputFields.reminder.validate({reminder:b.inputFields.reminder.getValue(),password:b.inputFields.password.getValue()})})}function h(c,a){bg.LPServer.textRequest({type:"GET",url:"create_account.php",CSRFToken:!1,data:{username:c,check:"avail",mistype:1},success:a,error:a})}function p(){var c=LPTools.createElement("a",
{"class":"pull-right",href:"https://lastpass.com/forgot.php",target:"_blank"},Strings.translateString("Recovery Help")),a=LPTools.createElement("p",null,Strings.translateString("Email address already in use "));a.appendChild(c);c=new FieldValidator({summary:{id:"validatorSummaryEmail",parentEl:$("label[for='createAccountEmail'].error-summary")},validators:[{id:"404",errorMsg:LPTools.createElement("p",null,Strings.translateString("You have made too many attempts.")+"<br>"+Strings.translateString("Please wait 5 minutes then try again.")),
isValid:function(a){return!(a.response.status&&404===a.response.status)}},{id:"emailUsed",errorMsg:a,isValid:function(a){return"no"!==a.response}},{id:"emailInvalid",errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure to use a real email address")),isValid:function(a){return"ok"===a.response&&0!==a.response.indexOf("mistype:")&&"emailinvalid"!==a.response}}]});b.inputFields.email.validate=e("email",c);b.inputFields.email.fieldValidator=c}function e(c,a){return function(d,q){var e=
!1;a&&(b.clearError(c),e=a.validate(d,function(a){b.addError(c,a)},q));return e}}function r(){var c=new FieldValidator({summary:{id:"validatorSummaryTermsAndConditions",parentEl:$("label[for='termsAndConditions'].error-summary")},validators:[{id:"termsNotChecked",errorMsg:LPTools.createElement("p",null,Strings.translateString("Please agree to the Terms and Conditions")),isValid:function(a){return!0===a.termsAndConditions}}]});b.inputFields.termsAndConditions.validate=e("termsAndConditions",c);b.inputFields.termsAndConditions.fieldValidator=
c}function t(){var c=new FieldValidator({summary:{id:"validatorSummaryPassword",parentEl:$("label[for='createAccountDialogPassword'].error-summary"),labelEl:$("label[for='createAccountDialogPassword'].label"),errorMsg:LPTools.createElement("p",null,Strings.translateString("Sorry, your password is invalid"))},listParentEl:$("#mpValidators"),validators:[{id:"passwordLength",name:LPTools.createElement("p",null,Strings.translateString("At least 8 characters long")),errorMsg:LPTools.createElement("p",
null,Strings.translateString("Master Password must be at least 8 characters")),isValid:function(a){return!0===(a.password&&8<=a.password.length)}},{id:"passwordSameAsEmail",name:LPTools.createElement("p",null,Strings.translateString("Not your email")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Master Password shouldn't contain your email")),isValid:function(a){return!0===(a.password&&a.email&&-1===a.password.toLowerCase().indexOf(a.email.toLowerCase())&&-1===a.email.toLowerCase().indexOf(a.password.toLowerCase()))}},
{id:"easyPassword",name:LPTools.createElement("p",null,Strings.translateString("Not easily guessable")),errorMsg:LPTools.createElement("p",null,Strings.translateString("That's in the top 100 most-used passwords")),isValid:function(a){return!0===(a.password&&!a.password.match(/^password\d{0,3}$/i)&&!a.password.match(/^lastpass\d{0,3}$/i)&&!a.password.match(/^.{0,7}$/)&&"12345678"!==a.password&&"123456789"!==a.password&&"1234567890"!==a.password&&"lastpass.com"!==a.password&&"qwertyuiop"!==a.password&&
"abcd1234"!==a.password)}}]});b.inputFields.password.validate=e("password",c);b.inputFields.password.fieldValidator=c}function u(){$("#twinsies").hide();var c=new FieldValidator({summary:{id:"validatorSummaryReconfirm",parentEl:$("label[for='createAccountDialogConfirmPassword'].error-summary"),labelEl:$("label[for='createAccountDialogConfirmPassword'].label, #twinsies")},validators:[{id:"reconfirmSameAsPassword",name:LPTools.createElement("p",null,Strings.translateString("Reconfirm same as password")),
errorMsg:LPTools.createElement("p",null,Strings.translateString("Make sure this matches your Master Password")),isValid:function(a){return!0===(a.reconfirm&&a.password===a.reconfirm)}}]});b.inputFields.reconfirm.validate=e("reconfirm",c);b.inputFields.reconfirm.fieldValidator=c}function v(){var c=new FieldValidator({summary:{id:"validatorSummaryReminder",parentEl:$("label[for='createAccountReminder'].error-summary"),labelEl:$("label[for='createAccountReminder'].label")},validators:[{id:"reminderNotPassword",
name:LPTools.createElement("p",null,Strings.translateString("Reminder doesn't contain password")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Reminder shouldn't contain your Master Password")),isValid:function(a){return!(a.password&&-1!==a.reminder.toLowerCase().indexOf(a.password.toLowerCase()))}}]});b.inputFields.reminder.validate=e("reminder",c);b.inputFields.reminder.fieldValidator=c}var b,f,k;ExtensionCreateAccount.prototype.initialize=function(c){CreateAccountDialog.prototype.initialize.apply(this,
arguments);$(".meterContainer").remove();this.inputFields.password.getElement().LP_addPasswordMeter(this.inputFields.email.getElement(),!0);b=this;(function(a){var d=c.find(".buttonContent"),e=c.find(".buttons").detach();d.append(e);new FieldToolTip({parentEl:c});k=new EmailToolTip({toolTipEl:c.find("#mpCurrentEmail"),parentEl:$("body"),emailField:b.inputFields.email,backActionFn:function(){b.showPreviousView()}});c.find("#signInBtn").bind("click",function(c){c.preventDefault();$("[for^=createAccountEmail]")[0].style.display=
"none";dialogs.loginSimple.open({isPopup:!1});bg.sendLpImprove("viewloginform");a.close(!0)});p();r();g();l();m();n();f=new BackgroundOverlay({parentEl:$("body")});a.data.isPopup||$("body").addClass("login-background")})(this)};ExtensionCreateAccount.prototype.setNextView=function(c){Dialog.prototype.setNextView.apply(this,arguments);k.toggle(0<c);bg.sendLpImprove("viewregform",{currentPage:0===this.currentViewIndex?"email":"mpw"})};ExtensionCreateAccount.prototype.close=function(c){c?Dialog.prototype.close.apply(this,
arguments):function(a){LPTools.getOption(a.data,"showcloseconfirm",!0)?(f.show(),dialogs.confirmation.open({title:"LastPass",text:Strings.translateString("Do you really want to quit?  You cannot use LastPass without creating an account."),closeHandler:function(){f.hide()},handler:function(){a.close(!0)}})):a.close(!0)}(this)};ExtensionCreateAccount.prototype.clearError=function(c){(c=this.inputFields[c])&&c.clearErrors()};ExtensionCreateAccount.prototype.addError=function(c,a){var b=this.inputFields[c];
b&&(b._errors.push(a),b.clearErrors=function(){this._errors=[];b._errorElement&&b._errorElement.remove();this._errorElement=null})};ExtensionCreateAccount.prototype.validate=function(c,a){if(0===this.currentViewIndex)h(c.email,function(d){(d=b.inputFields.email.validate({response:d}))&&(d&=b.inputFields.termsAndConditions.validate(c));a&&a(d)});else if(this.currentViewIndex===this.views.length-1){var d=b.inputFields.password.validate(c),d=d&b.inputFields.reconfirm.validate(c),d=d&b.inputFields.reminder.validate(c);
a&&a(d)}};ExtensionCreateAccount.prototype.submit=function(){try{var c=this.getData();this.validate(c,function(a){if(a)b.getNextViewButton()===b.nextButton&&b.views&&b.currentViewIndex<b.views.length-1?(t(),u(),v(),b.setNextView(b.currentViewIndex+1)):(bg.sendLpImprove("completedregform"),b.handleSubmit(c,this.data));else{a=[];for(var d in b.inputFields)b.inputFields.hasOwnProperty(d)&&b.inputFields[d].fieldValidator&&(a=a.concat(b.inputFields[d].fieldValidator.getValidationList()));d=a.join(",");
a={errorlist:d};b.inputFields.reminder&&""!==b.inputFields.reminder.getValue()&&(a.isReminder=!0);0<d.length&&(a.currentPage=0===b.currentViewIndex?"email":"mpw",bg.sendLpImprove("validationregform",a))}})}catch(a){LPPlatform.logException(a)}};ExtensionCreateAccount.prototype.showInProcessOverlay=function(){f.show(!0)}})();
