(function(){var g=!1;VaultItemBase.prototype.reprompt=function(a){var b=function(a){return function(){a.apply(this,arguments);LPPlatform.closePopup()}};return function(c,d){g=a.call(this,b(c),d)}}(VaultItemBase.prototype.reprompt);VaultItemBaseDisplay.prototype.build=function(a){var b=["extensionMenuItem"],b=b.concat(this.getMenuItemClass()),b=LPTools.createElement("li",b);a&&a.additionalItemClasses&&LPTools.addClass(b,a.additionalItemClasses);var c=this.buildItemIconElement();null!==c&&b.appendChild(c);
a=this.buildItemInfoTextElements(a);0<a.length&&b.appendChild(a[0]);if(a=this.buildMoreOptionsButtons())if(a instanceof Array)for(var c=0,d=a.length;c<d;++c)b.appendChild(a[c]);else b.appendChild(a);return b};VaultItemBaseDisplay.prototype.getMenuItemClass=function(){return"item"};VaultItemBaseDisplay.prototype.buildMoreOptionsButtons=function(){return LPTools.createElement("div",{"class":"moreItem moreActions",vaultaction:Constants.ACTION_OPEN_MORE_OPTIONS,title:Strings.Vault.MORE_OPTIONS})};VaultItemBaseDisplay.prototype.buildItemIconElement=
function(){var a=LPTools.createElement("div","itemIcon");a.appendChild(this.getIconElement());a.appendChild(LPTools.createElement("div","itemIconOverlay"));return a};VaultItemBaseDisplay.prototype.buildItemMenuOption=function(a){var b=LPTools.createElement("li",{"class":"extensionMenuItem",vaultaction:a});b.textContent=Strings.Vault[Constants.CONTEXT_MENU_ITEMS[a]];LPPlatform.addEventListener(b,"click",this._eventHandler);return b};VaultItemBaseDisplay.prototype.buildMoreOptions=function(a){var b=
this.getContainer()._buildOptions;void 0===a&&(a=LPTools.getOption(b,"moreOptionsElement",this._element?this._element.parentElement:null));LPTools.removeDOMChildren(a);var c=this.build(b);this.postBuild(c,b);a.appendChild(c);this._$_element.unbind("contextmenu");for(var b=this.getMoreOptions(),c=[],d=0,f=b.length;d<f;++d){var e=b[d];this.isExcludedAction(e)||(e=this.buildItemMenuOption(e),c.push(e),a.appendChild(e))}LPTools.addKeyBoardNavigation(c,{useRightArrow:!1,selectFirst:!0});ExtensionDropdown.setGroupLabel(LPProxy.getGroupByName(this._model.getGroupName()))};
VaultItemBaseDisplay.prototype.openMoreOptions=function(){this.pushState(LPTools.getOption(this.getContainer()._buildOptions,"moreOptionsState",void 0));this.buildMoreOptions()};VaultItemBaseDisplay.prototype.pushState=function(a){a=a||ExtensionDropdown.State.GroupState;Topics.get(Topics.PUSH_STATE).publish(new a(this._parent))};VaultItemBaseDisplay.prototype.handleEvent=function(a,b){var c={source:"icon"};switch(a.type){case "click":var d=this.getVaultAction(a.target);this.handleClickEvent(d,c);
switch(d){case Constants.ACTION_OPEN_MORE_OPTIONS:case Constants.ACTION_TOGGLE_OPEN:g=!0}g&&(a.stopPropagation(),a.preventDefault(),g=!1);break;case "contextmenu":this.handleClickEvent(Constants.ACTION_OPEN_MORE_OPTIONS,c),a.stopPropagation(),a.preventDefault()}};GroupDisplay.prototype.getDisplayName=function(){return this._model.getGroupName()};GroupDisplay.prototype.build=function(a){var b=VaultItemBaseDisplay.prototype.build.apply(this,arguments);b.setAttribute("vaultaction",Constants.ACTION_TOGGLE_OPEN);
return b};GroupDisplay.prototype.buildItemIconElement=function(){return null};GroupDisplay.prototype.getMenuItemClass=function(){return"group"};GroupDisplay.prototype.buildMoreOptionsButtons=function(){return LPTools.createElement("div","more")};GroupDisplay.prototype.setupListeners=function(a,b){$(a).bind("click",this._eventHandler)};GroupDisplay.prototype.toggleOpen=function(){this.pushState();this.rebuildItems(this._element.parentElement);ExtensionDropdown.setGroupLabel(this._model)};var k=function(a,
b){for(var c=0,d=a.length;c<d;++c)b.push(a[c]._element)};GroupDisplay.prototype.rebuildItems=function(a){var b=this.getContainer();a=a||b._element;if(0===this._subGroups.length&&1===this._items.length&&LPTools.getOption(b._buildOptions,"autoExpandSingleItem",!0))this._items[0].buildMoreOptions(a);else{LPTools.removeDOMChildren(a);var c=this.favoritesGroup&&!this.favoritesGroup.isEmpty();c&&this.buildItems([this.favoritesGroup],a,b._buildOptions);var d=0,f=[],e=null;if(bg.get("g_nofolder_feature_enabled"))for(var h=
0,g=this._subGroups.length;h<g;h++)this._subGroups[h]instanceof DefaultGroupDisplay?(e=this._subGroups[h],d=e._items?e._items.length:0):f.push(this._subGroups[h]);f=e?f:this._subGroups;this.buildItems(f,a,b._buildOptions);this.buildItems(this._items,a,b._buildOptions);e&&0<d&&this.buildItems(e._items,a,b._buildOptions);0<f.length&&(0<this._items.length||0<d)&&f[f.length-1]._$_element.removeClass("last");a=[];c&&a.push(this.favoritesGroup._element);k(f,a);k(this._items,a);e&&0<d&&k(e._items,a);LPTools.addKeyBoardNavigation(a,
{rightArrowSelector:".moreItem",selectFirst:!0});LPTools.getOption(b._buildOptions,"addLastClass",!0)||$(a[a.length-1]).removeClass("last")}};GroupDisplay.prototype.getItemContainer=function(){return this.getContainer()._element};GroupDisplay.prototype.getSubFolderContainer=GroupDisplay.prototype.getItemContainer;AccountDisplay.prototype.build=function(a){var b=VaultItemBaseDisplay.prototype.build.apply(this,arguments);ExtensionDropdown.isMatchingSite(this._model.getID())?(b.setAttribute("vaultaction",
Constants.ACTION_FILL_SITE),b.setAttribute("title",Strings.Vault.FILL+" "+this.getDisplayName())):(b.setAttribute("vaultaction",Constants.ACTION_LAUNCH),b.setAttribute("title",Strings.Vault.LAUNCH+" "+this.getDisplayName()));return b};AccountDisplay.prototype.setupListeners=function(a,b){VaultItemBaseDisplay.prototype.setupListeners.apply(this,arguments)};AccountDisplay.prototype.getMoreOptions=function(){var a=[Constants.ACTION_COPY_USERNAME,Constants.ACTION_COPY_PASSWORD,Constants.ACTION_COPY_URL,
Constants.ACTION_GO_TO_URL,Constants.ACTION_EDIT,Constants.ACTION_DELETE];ExtensionDropdown.isMatchingSite(this._model.getID())&&a.unshift(Constants.ACTION_FILL_SITE);return a};NoteDisplay.prototype.build=function(a){var b=VaultItemBaseDisplay.prototype.build.apply(this,arguments);LPTools.addClass(b,"note");b.setAttribute("vaultaction",Constants.ACTION_EDIT);b.setAttribute("title",Strings.Vault.EDIT+" "+this.getDisplayName());return b};NoteDisplay.prototype.getMoreOptions=function(){var a=[];this._model.hasUsername()&&
a.push(Constants.ACTION_COPY_USERNAME);this._model.hasPassword()&&a.push(Constants.ACTION_COPY_PASSWORD);a.push(Constants.ACTION_COPY_NOTE);this._model.hasPrivateKey()&&a.push(Constants.ACTION_COPY_KEY);a.push(Constants.ACTION_EDIT);a.push(Constants.ACTION_DELETE);return a};NoteDisplay.prototype.setupListeners=function(a,b){VaultItemBaseDisplay.prototype.setupListeners.apply(this,arguments)};FormFillDisplay.prototype.getMoreOptions=function(){return[Constants.ACTION_EDIT,Constants.ACTION_FILL]};FormFillDisplay.prototype.setupListeners=
function(a,b){VaultItemBaseDisplay.prototype.setupListeners.apply(this,arguments)};FormFillDisplay.prototype.build=function(a){var b=VaultItemBaseDisplay.prototype.build.apply(this,arguments);LPTools.addClass(b,"formFill");b.setAttribute("vaultaction",Constants.ACTION_FILL);b.setAttribute("title",Strings.Vault.FILL+" "+this.getDisplayName());return b};FormFillDisplay.prototype.includeCreditInfo=function(){return!1};IdentityDisplay.prototype.build=function(a){var b=VaultItemBaseDisplay.prototype.build.apply(this,
arguments);b.setAttribute("vaultaction",Constants.ACTION_ENABLE);b.setAttribute("title",Strings.Vault.ENABLE+" "+this.getDisplayName());return b};AllIdentityDisplay.prototype.build=IdentityDisplay.prototype.build;IdentityDisplay.prototype.buildMoreOptionsButtons=function(){return null};IdentityDisplay.prototype.openMoreOptions=function(){};MatchingAccountDisplay=function(a){AccountDisplay.call(this,a)};MatchingAccountDisplay.prototype=Object.create(AccountDisplay.prototype);MatchingAccountDisplay.prototype.constructor=
MatchingAccountDisplay;MatchingAccountDisplay.prototype.build=function(a){var b=VaultItemBaseDisplay.prototype.build.apply(this,arguments);b.setAttribute("vaultaction",Constants.ACTION_FILL_SITE);b.setAttribute("title",Strings.Vault.FILL+" "+this.getDisplayName());LPTools.addClass(b,"matchingSite");return b};MatchingAccountDisplay.prototype.buildMoreOptionsButtons=function(){var a=[];this.isExcludedAction(Constants.ACTION_COPY_USERNAME)||a.push(LPTools.createElement("div",{"class":"moreItem copyUsername",
title:Strings.Vault.COPY_USERNAME,vaultaction:Constants.ACTION_COPY_USERNAME}));this.isExcludedAction(Constants.ACTION_COPY_PASSWORD)||a.push(LPTools.createElement("div",{"class":"moreItem copyPassword",title:Strings.Vault.COPY_PASSWORD,vaultaction:Constants.ACTION_COPY_PASSWORD}));a.push(LPTools.createElement("div",{"class":"moreItem",title:Strings.Vault.MORE_OPTIONS,vaultaction:Constants.ACTION_OPEN_MORE_OPTIONS}));return a};ApplicationDisplay.prototype.getMoreOptions=function(){return[Constants.ACTION_EDIT,
Constants.ACTION_COPY_USERNAME,Constants.ACTION_COPY_PASSWORD,Constants.ACTION_DELETE]};ApplicationDisplay.prototype.build=function(a){var b=VaultItemBaseDisplay.prototype.build.apply(this,arguments);LPFeatures.allowLaunchApplication()&&(b.setAttribute("vaultaction",Constants.ACTION_LAUNCH),b.setAttribute("title",Strings.Vault.LAUNCH+" "+this.getDisplayName()));return b}})();
