var ExtensionLoginDialogSimple=function(f){ExtensionLoginDialog.call(this,f,{confirmOnClose:!0,responsive:!1})};ExtensionLoginDialogSimple.prototype=Object.create(ExtensionLoginDialog.prototype);ExtensionLoginDialogSimple.prototype.constructor=ExtensionLoginDialogSimple;
(function(){function f(c,b,a){return function(e,g){var d=!1;a&&(c.clearError(b),d=a.validate(e,function(a){c.addError(b,a)},g));return d}}function h(c){var b=new FieldValidator({summary:{id:"validatorSummaryEmail",parentEl:$("label[for='loginDialogEmail'].error-summary"),labelEl:$("label[for='loginDialogEmail'].label")},validators:[{id:"emailRequired",name:LPTools.createElement("p",null,Strings.translateString("Email required")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Please enter your email.")),
isValid:function(a){return""!==a.email}}]});c.inputFields.email.validate=f(c,"email",b)}function k(c){var b=new FieldValidator({summary:{id:"validatorSummaryPassword",parentEl:$("label[for='loginDialogPassword'].error-summary"),labelEl:$("label[for='loginDialogPassword'].label")},validators:[{id:"passwordRequired",name:LPTools.createElement("p",null,Strings.translateString("Password required")),errorMsg:LPTools.createElement("p",null,Strings.translateString("Please enter your password.")),isValid:function(a){return""!==
a.password}}]});c.inputFields.password.validate=f(c,"password",b)}var d;ExtensionLoginDialogSimple.prototype.initialize=function(c){ExtensionLoginDialog.prototype.initialize.apply(this,arguments);h(this);k(this);this.inputFields.rememberPassword.getElement().bind("click",function(b){var a=!1,c=function(){a=!0;b.inputFields.rememberPassword.setValue(!0);d.hide()};return function(){var e=b.inputFields.rememberPassword.getValue();!a&&e?(d.show(),dialogs.confirmation.open({title:Strings.translateString("Are you sure?"),
text:Strings.translateString("Saving your Master Password on this device is like leaving the keys in the door to your Vault.")+"<br/><br/>"+Strings.translateString("You should make sure this device is in a secure location and unlikely to be lost or stolen before enabling this option."),handler:c,closeHandler:function(){d.hide()},onResize:b.data.onResize}),b.inputFields.rememberPassword.setValue(!1)):a=!1}}(this));(function(b){b.inputFields.email.getElement().change(function(a){b.inputFields.password.validate({email:b.inputFields.email.getValue()})});
b.inputFields.password.onChange(function(a){a&&b.inputFields.password.validate({password:a})});$("#forgotPassword").off("click");$("#forgotPassword").bind("click",function(){LPPlatform.openURL(LPPlatform.getBaseURL()+"forgot.php");b.close(!0)});$("#newToLastPass").off("click");$("#newToLastPass").bind("click",function(){b.data.isPopup?bg.LPPlatform.openTabDialog("createAccountSimple"):dialogs.createAccountSimple.open();b.close(!0)});c.find(".showKeyboard").off("click");c.find(".showKeyboard").bind("click",
function(){b.data.isPopup?(bg.LPPlatform.openTabDialog("loginSimple",{virtualKeyboard:!0}),b.close(!0)):b.toggleKeyboard()});var a={parentEl:$("body")};b.data.isPopup&&(a.shadeStyle="light");d=new BackgroundOverlay(a);b.data.isPopup||$("body").addClass("login-background")})(this)};ExtensionLoginDialogSimple.prototype.close=function(c){c?Dialog.prototype.close.apply(this,arguments):function(b){LPTools.getOption(b.data,"showcloseconfirm",!0)?(d.show(),dialogs.confirmation.open({title:"LastPass",text:Strings.translateString("Do you really want to quit? You cannot use LastPass without logging in to an account."),
closeHandler:function(){d.hide()},handler:function(){b.close(!0)}})):b.close(!0)}(this)};ExtensionLoginDialogSimple.prototype.handleSubmit=function(){var c=null,b=function(a,b){null===c&&(c=setInterval(function(){"undefined"===typeof VaultState&&bg.getData&&bg.getData({context:"login"});bg.get("lploggedin")?(clearInterval(c),c=null,a.title===b&&a.close(!0)):"error"===bg.get("g_notification_type")&&(clearInterval(c),c=null,dialogs.alert.open({title:Strings.translateString("Login Error"),text:Strings.translateString(bg.get("g_notification_data").msg),
onResize:a.data.onResize,handler:function(){d.hide()}}))},1E3))};return function(a){a.email=bg.fix_username(a.email);bg.Preferences.set({rememberemail:a.rememberEmail,rememberpassword:a.rememberPassword});a.disablePasswordManager&&bg.disablepasswordmanager(!0);bg.make_lp_key_hash(a.email,a.password,function(b,c){return function(d,e){b.set("g_manual_login",!0);b.LP_do_login(a.email,a.password,a.rememberEmail,a.rememberPassword,null,a.rememberShowVault,d,e);c.data.isPopup&&c.close(!0)}}(bg,this));this.data.isPopup||
(d.show(!0),b(this,this.title))}}();ExtensionLoginDialogSimple.prototype.addError=function(c,b){var a=this.inputFields[c];a&&(a._errors.push(b),a.clearErrors=function(){this._errors=[];a._errorElement&&a._errorElement.remove();this._errorElement=null;a.input[0].className=a.input[0].className.replace(" errorInput","")},a.input[0].className.includes("errorInput")||(a.input[0].className+=" errorInput"))};ExtensionLoginDialogSimple.prototype.clearError=function(c){(c=this.inputFields[c])&&c.clearErrors()};
ExtensionLoginDialogSimple.prototype.validateField=function(c,b,a,d){var e=!1;b&&(this.clearError(a),e=b.validate(c,function(b){this.addError(a,b)},!0),d&&(!1===e?d.hide():d.show()));return e};ExtensionLoginDialogSimple.prototype.validate=function(c){var b;Dialog.prototype.validate.apply(this,arguments);b=this.inputFields.email.validate(c);return b&=this.inputFields.password.validate(c)}})();
