ExtensionDropdown=function(d){var A=$(d.body),l=d.getElementById("items"),r=d.getElementById("searchResults"),t=d.getElementById("recentSites"),B=d.getElementById("identitiesMenuItem"),ja=d.getElementById("matchingSitesTopLevel"),ka=d.getElementById("matchingSites"),p=$("#groupLabel"),C=$("#backButton"),M=$("#debugconsole"),N=$("#encryptedExportMenuItem"),O=$("#wifiExportMenuItem"),P=$("#matchingSitesMenuItem"),Q=$("#recentSitesMenuItem"),g=$("#container"),u=$("#searchInput"),Y=$("#applicationsMenuItem"),
Z=null,v=null,w=null,x=null,D=null,E=null,F=null,aa=null,G=!1,H=!1,R=!1,S=!1,T={},h=null,I={},k=[],f={},U=function(a){p.empty();if(a){var b=a.getName(),b=b.replace(/\\/g," \\ "),c=b.indexOf("\\",b.length/2);-1===c&&(c=b.lastIndexOf("\\"));if(0<c){var e=LPTools.createElement("div","textOverflowContainer groupLabel");e.appendChild(LPTools.createElement("span",null,b.substring(0,c)));p.append(LPTools.createElement("span","textTail","\u00a0"+b.substring(c)));p.append(e);LPTools.setupMiddleEllipsis(p)}else p.append(LPTools.createElement("span",
"groupLabel",b));p.find(".groupLabel").attr("title",a.toString())}};f.GroupState=function(a){var b=LPTools.getNavIndex();this.pop=function(){a.rebuildItems();LPTools.setNavIndex(b);U(a._model)}};f.SearchState=function(){var a=new f.CSSState("searchItem",{restoreKeyboardNav:!1});this.pop=function(){ba();a.pop()}};f.TopLevelMatchingSitesState=function(a){var b=new f.CSSState("matchingSites"),c=new f.GroupState(a);this.pop=function(){c.pop();b.pop()}};f.CSSState=function(){var a=A.attr("class"),b=function(b){A.removeClass(a);
A.addClass(b);a=b};return function(c,e){var d=a;b(c);LPTools.getOption(e,"applyKeyboardNav",!0)&&LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"),{selectFirst:!0});this.pop=function(){U(null);b(d);LPTools.getOption(e,"restoreKeyboardNav",!0)&&LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"));if(e&&"function"===typeof e.onPop)e.onPop()}}}();var ea=function(){g.addClass("loading");M.LP_removeAttr("style");N.LP_removeAttr("style");O.LP_removeAttr("style");Y.LP_removeAttr("style");
bg.is_user_debug_enabled()&&M.show();bg.have_binary()&&(N.show(),bg.LPPlatform.isWin()&&O.show());LPTools.hasProperties(bg.get("g_applications"))&&Y.show();la();LPTools.parseUserSpecificMenu(d.getElementById("mainMenu"),LPProxy.getAccountClass());$("#username").text(bg.get("g_username"));V();g.addClass("initialized");u.focus();setTimeout(function(){LPProxy.initializeModel();v=LPProxy.getIdentities();LPProxy.enableCurrentIdentity(v);if(0<v.length){var a=Z,a=Strings.translateString("Identities")+" ("+
a.getName()+")",b=B.firstChild;3!==b.nodeType?(b=d.createTextNode(a),B.insertBefore(b,B.firstChild)):b.textContent=a;for(var a=[],b=0,c=v.length;b<c;++b)a.push(v[b].newDisplayObject());(new IdentityContainer(a)).initialize(d.getElementById("identities"))}else $(B).hide();w=ca(LPProxy.getSites());w.setElement(l);x=ca(LPProxy.getNotes());x.setElement(l);D=new Container(LPProxy.getFormFills());D.setElement(l);E=new Container(LPProxy.getApplications());E.setElement(l);aa=new Container(LPProxy.getAllItems(),
{moreOptionsState:f.SearchState});H=!0;g.removeClass("loading");for(var e in I)I[e]();(e=u.val())&&da(e);V()},0)},V=function(){var a=function(){g.LP_removeAttr("style");var a=g.outerHeight();LPPlatform.setDropdownPopoverSize(a,g.outerWidth());g.css("height",a);LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"))};return function(){0===k.length?a():k[0].pop=function(b){return function(){b();a()}}(k[0].pop)}}(),ca=function(a){var b;LPProxy.getPreference("showAcctsInGroups",!0)&&(a=LPProxy.assignItemsToGroups(a,
!1),b={separateFavorites:!0});return new Container(a,b)},fa=function(a,b,c){for(var e=[],d=0,f=h.length;d<f;++d)e.push(new MatchingAccountDisplay(LPProxy.getSiteModel(h[d].aid)));b=new Container(e,b);b.setElement(a);b.rebuildItems();c&&V()},la=function(){h=bg.getmatchingsites(!1,!0,!1);for(var a=0,b=h.length;a<b;++a)T[h[a].aid]=!0;(a=LPProxy.getPreference("toplevelmatchingsites",!1))||0===h.length?(P.LP_removeAttr("style"),Q.addClass("divider")):(P.show(),Q.removeClass("divider"));a?m("topLevelMatchingSites",
function(){fa(ja,{autoExpandSingleItem:!1,moreOptionsElement:d.getElementById("matchingSites"),moreOptionsState:f.TopLevelMatchingSitesState,addLastClass:!1},!0)})():0<h.length&&$("#matchingSiteCounter").text(h.length)},ba=function(){LPTools.removeDOMChildren(r);for(var a=0,b=F.length;a<b;++a){var c=F[a],e=c.build();c.postBuild(e);r.appendChild(e)}0===F.length&&(a=LPTools.buildEmptyPlaceholder(Strings.translateString("No Matching Results"),"extensionSearchPlaceholder",r),r.appendChild(a));LPTools.addKeyBoardNavigation(r.children,
{rightArrowSelector:".moreItem",selectFirst:!0})},da=function(){var a=null;return function(b){0<b.length?(H&&(F=aa.getSearchResultItems(b),ba()),G||(ga("search",{applyKeyboardNav:!1,onPop:function(){u.val("")}}),G=!0)):a&&0<a.length&&(y(),G=!1);a=b}}(),m=function(a,b){return function(){H?b():I[a]=b}},z=function(a){a||(a={});a.saveOptions={source:"icon"};return a},W=function(a){bg.LPPlatform.openTabDialog("formFill",z(a))},ha=function(a){a.appendChild(LPTools.createElement("li","extensionMenuItem none",
"None Available"))},ga=function(a,b){k.push(new f.CSSState(a,b))},y=function(){var a=k.pop();a&&a.pop()},X=function(){dialogs.generatePassword.getDialog().close();C.unbind("click",X)},J=null,K=function(a,b,c){a.isEmpty()&&(a=LPTools.createElement("div","emptyView"),a.appendChild(LPTools.createElement("img",{src:"images/vault_4.0/"+b,"class":"emptyViewIcon"})),a.appendChild(LPTools.createElement("h1","emptyViewText",c)),document.getElementById("items").appendChild(a))};u.LP_addSearchHandlers("inputDialog",
function(a){da(a)});C.bind("click",y);$("[childview]").bind("click",function(a){for(var b=a.target,c=null;null!==b&&(c=b.getAttribute("childview"),null===c);)b=b.parentElement;ga(c);a&&(a.stopPropagation(),a.preventDefault())});$("#addSite").bind("click",function(a){bg.get_selected_tab_data_no_extension(null,function(a){bg.lpevent("m_add");bg.LPPlatform.openTabDialog("site",z({defaultData:{url:a?a.url:""}}));LPPlatform.closePopup()});a.stopPropagation()});$("#saveAllEnteredData").bind("click",function(){bg.lpevent("m_saed");
bg.saveall()});$("#addNote").bind("click",function(){bg.lpevent("m_addn");bg.LPPlatform.openTabDialog("note",z(void 0))});$("#addFormFill").bind("click",function(){bg.lpevent("m_af");W()});$("#addCreditCard").bind("click",function(){bg.lpevent("m_af");W({defaultData:{profiletype:FormFill.prototype.FORM_FILL_TYPE_CREDIT_CARD}})});$("#clearForms").bind("click",function(){bg.lpevent("m_clrf");bg.clearforms("icon")});var L=null;$("#chooseProfile").bind("click",function(){dialogs.chooseProfile.open({preSetup:function(a){if(null===
L){var b=dialogs.chooseProfile.parentElementID,c=a.options.hideHeader;L=function(){dialogs.chooseProfile.parentElementID=b;a.options.hideHeader=c;a.$element.css("min-height","")}}a.$element.css("min-height",0);dialogs.chooseProfile.parentElementID="chooseProfileCreditCard";a.options.hideHeader=!0},onClose:function(){y()},saveOptions:{source:"icon"}})});$("#vaultMenuItem").bind("click",function(){bg.lpevent("m_ov");bg.openvault()});$("#sitesMenuItem").bind("click",function(){return m("sites",function(){w.rebuildItems(l);
K(w,"Empty_Site.png",Strings.translateString("Remember every password"))})}());$("#formFillsMenuItem").bind("click",function(){return m("formFills",function(){D.rebuildItems(l);K(D,"Empty_Form.png",Strings.translateString("Fill Every Form"))})}());$("#applicationsMenuItem").bind("click",function(){return m("applications",function(){E.rebuildItems(l);K(E,"Empty_Site.png",Strings.translateString("Remember every password"))})}());$("#generateMenuItem").bind("click",function(){dialogs.generatePassword.open({preSetup:function(a){if(null===
J){var b=dialogs.generatePassword.parentElementID,c=a.options.hideHeader,e=a.dynamicHeight;J=function(){dialogs.generatePassword.parentElementID=b;a.options.hideHeader=c;a.useDynamicHeignt(e)}}dialogs.generatePassword.parentElementID="extensionDropdownGeneratePassword";a.options.hideHeader=!0;a.useDynamicHeignt(!1)},onClose:function(){y()},onCopy:function(){LPPlatform.closePopup(!0)},saveOptions:{source:"icon"}});C.unbind("click",X);C.bind("click",X)});$("#notesMenuItem").bind("click",function(){return m("notes",
function(){x.rebuildItems(l);K(x,"Empty_Note.png",Strings.translateString("Store Every Note"))})}());$("#clearMostRecent").bind("click",function(){bg.clearrecent();LPTools.removeDOMChildren(t);ha(t)});var q=m("mostRecent",function(a){if(!R){a=bg.getClearRecentTime();var b=bg.Preferences.get("recentUsedCount"),c=w.getItemChildren().concat(x.getItemChildren());c.sort(VaultItemBaseDisplay.prototype.sortByMostRecent);for(var e=[],d=0,f=c.length;d<f&&d<b;++d){var g=c[d];g.getLastTouchValue()>=a&&e.push(g._model.newDisplayObject())}0<
e.length?(new Container(e,{sortFunction:VaultItemBaseDisplay.prototype.sortByMostRecent})).initialize(t):ha(t);R=!0}LPTools.addKeyBoardNavigation(t.children,{rightArrowSelector:".moreItem",selectFirst:!0})});Q.bind("click",q);q=m("matchingSites",function(a){S||(fa(ka),S=!0);LPTools.addKeyBoardNavigation(d.getElementById("matchingSites").children,{rightArrowSelector:".moreItem",selectFirst:!0})});P.bind("click",q);$("#prefMenuItem").bind("click",function(){bg.lpevent("m_op");bg.openprefs()});$("#helpMenuItem").bind("click",
function(){bg.lpevent("m_oh");bg.openhelp()});$("#adminConsoleMenuItem").bind("click",function(){bg.lpevent("m_oec");bg.openentconsole()});$("#logoutMenuItem").bind("click",function(){bg.lpevent("m_lo");bg.loggedOut(!1,"menu")});$("#challengeMenuItem").bind("click",function(){bg.lpevent("m_sec");bg.openseccheck()});$("#favoritesMenuItem").bind("click",function(){bg.lpevent("m_of");bg.openfavorites()});$("#aboutMenuItem").bind("click",function(){bg.lpevent("m_abt");bg.openabout()});M.bind("click",
function(){bg.lpevent("m_dbgcon");bg.opendebugtab()});$("#csvExportMenuItem").bind("click",function(){bg.lpevent("m_e");bg.openexport()});$("#formFillExportMenuItem").bind("click",function(){bg.lpevent("m_eff");bg.formfillexport()});N.bind("click",function(){bg.lpevent("m_elp");bg.openlastpassexport()});O.bind("click",function(){bg.lpevent("m_ewlan");bg.wlanexport()});$("#printSitesMenuItem").bind("click",function(){bg.lpevent("m_p");bg.openprint(!1)});$("#printNotesMenuItem").bind("click",function(){bg.lpevent("m_pn");
bg.openprint(!0)});$("#refreshMenuItem").bind("click",function(){bg.lpevent("m_ref");LPProxy.refreshSites()});$("#clearCachMenuItem").bind("click",function(){bg.lpevent("m_cl");bg.clearCache(!1,!0,!1)});$("#myAccountMenuItem").bind("click",function(){bg.lpevent("m_mya");bg.openmyaccount()});$("#sessionsMenuItem").bind("click",function(){bg.lpevent("m_ses");bg.opensessions()});LPPlatform.addEventListener(window,"unload",function(){ia()});A.on("click",".extensionMenuItem, .footer",function(){LPPlatform.closePopup()});
LPFeatures.allowGift()&&(q=$("#specialOfferMenuItem"),q.show(),q.bind("click",function(){bg.openURL(LPProxy.getBaseURL()+"gift.php")}));Topics.get(Topics.PUSH_STATE).subscribe(function(a){k.push(a)});Topics.get(Topics.EDIT_SITE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();bg.LPPlatform.openTabDialog("site",z(a))});Topics.get(Topics.EDIT_NOTE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();bg.LPPlatform.openTabDialog("note",z(a))});Topics.get(Topics.EDIT_FORM_FILL).subscribe(function(a){a.vaultItem=
a.vaultItem.getID();W(a)});Topics.get(Topics.EDIT_APPLICATION).subscribe(function(a){a.vaultItem=a.vaultItem.getID();bg.LPPlatform.openTabDialog("application",a)});Topics.get(Topics.IDENTITY_ENABLE).subscribe(function(a){LPProxy.enableIdentity(a);Z=a});Topics.get(Topics.CONFIRM).subscribe(function(a){n("confirmation",a)});Topics.get(Topics.ERROR).subscribe(function(a){n("alert",{title:Strings.Vault.ERROR,text:a})});Topics.get(Topics.REPROMPT).subscribe(function(a){n("reprompt",{successCallback:a})});
Topics.get(Topics.LEFT_ARROW).subscribe(function(){LPTools.disableMouse();y()});Topics.get(Topics.CLEAR_DATA).subscribe(function(){for(var a=k.length-1;-1<a;--a)k[a].pop();k=[];LPTools.setNavIndex(0);u.val("");S=R=H=G=!1;T={};I={};h=null;J&&J();L&&L();g.removeClass("initialized");Dialog.prototype.closeAllDialogs(!0)});Topics.get(Topics.INITIALIZED).subscribe(function(){Strings.translate(d.body);LPFeatures.updateFeatures({"import":!0,noexport:!1,show_notes:!0,hideidentities:!1,show_formfills:!0});
LPPlatform.setupDropdownImportMenu(g)});var n=function(a,b){$("#container").LP_hide();LPTools.removeKeyBoardNavigation();b=$.extend(b,{onResize:function(a,b){LPPlatform.setDropdownPopoverSize(a,b)},onClose:function(){LPPlatform.closePopup()}});LPDialog.openDialog(a,b)},ia=function(){Topics.get(Topics.CLEAR_DATA).publish()};return{setup:ea,State:f,isMatchingSite:function(a){return!0===T[a]},setGroupLabel:U,open:function(){var a=bg.get("g_badgedata");if(a&&"notification"===a.cmd){switch(a.alerttype){case "duplicate":n("duplicatePassword",
{notification:a});break;case "weak":n("weakPassword",{notification:a})}switch(a.type){case "error":n("notification",{notification:bg.get("g_notification_data")})}bg.clear_badge()}else $("#container").LP_show(),ea()},openDialog:n,reset:ia,setBigIcons:function(a){bg.set("g_bigicons",a)}}}(document);
