var ExtensionLoginDialog=function(a){LoginDialog.call(this,a,{closeButtonEnabled:!1});this.populatedSavedLogin=!1;(function(b){b.savedLoginCallback=function(c){for(var a=[],k=function(c){return function(a){bg.delete_saved_login(c);a.stopPropagation();a.preventDefault();for(a=0;a<b.data.savedLogins.length;a++)if(b.data.savedLogins[a].username===c){b.data.savedLogins.splice(a,1);break}b.inputFields.email.removeValue(c);b.inputFields.email.inputObject.input.val("");b.inputFields.password.setValue("");
b.inputFields.email.updateDropdown("");b.inputFields.email.clearHint()}},d=0,e=c.length;d<e;++d){var f=c[d].username,g=LPTools.createElement("li",{dropdownValue:f},"");g.appendChild(LPTools.createElement("span",{"class":"dropdownText"},f));var h=LPTools.createElement("img",{src:"images/vault_4.0/Close_x.png","class":"ddl-remove"});LPPlatform.addEventListener(h,"mousedown",k(f));g.appendChild(h);a.push({value:f,label:f,element:g})}b.inputFields.email.setOptions(a);0<c.length?(a=c[0],b.data.savedLogins=
c,b.inputFields.email.setValue(a.username),b.inputFields.password.focus()):b.inputFields.email.focus()};b.browserPasswordManagerCallback=function(){$("#loginDialogDisablePasswordManagerContainer").show();b.inputFields.disablePasswordManager.setValue(bg.Preferences.get("disableffpwasked"))}})(this)};ExtensionLoginDialog.prototype=Object.create(LoginDialog.prototype);ExtensionLoginDialog.prototype.constructor=ExtensionLoginDialog;
(function(){ExtensionLoginDialog.prototype.populateSavedLogin=function(a){this.inputFields.password.setValue(a);this.inputFields.rememberPassword.setValue(""!==a);this.populatedSavedLogin=!0};ExtensionLoginDialog.prototype.parseSavedLogin=function(a){switch(a["protected"]){case 0:this.populateSavedLogin(a.password);break;case 1:bg.unprotect_data(a.password,!1,this.createDynamicHandler(function(a){this.populateSavedLogin(a)}));break;case 2:this.populateSavedLogin(bg.lpdec(a.password,bg.AES.hex2bin(bg.SHA256(a.username))))}};
ExtensionLoginDialog.prototype.initialize=function(a){LoginDialog.prototype.initialize.apply(this,arguments);this.inputFields.rememberPassword.getElement().bind("click",function(c){var a=!1,b=function(){a=!0;c.inputFields.rememberPassword.setValue(!0)};return function(){var d=c.inputFields.rememberPassword.getValue();!a&&d?(dialogs.confirmation.open({title:Strings.translateString("Are you sure?"),text:Strings.translateString("Using 'remember password' makes it easier to forget your password and decreases your security if your device is infected or stolen."),
handler:b,onResize:c.data.onResize}),c.inputFields.rememberPassword.setValue(!1)):a=!1}}(this));var b=function(c){var a;return function(b){var d=c.populatedSavedLogin;c.populatedSavedLogin=!1;if(c.data.savedLogins)for(var e=0,f=c.data.savedLogins.length;e<f;++e){var g=c.data.savedLogins[e];if(g.username===b){c.parseSavedLogin(g);break}}d&&!c.populatedSavedLogin&&(c.inputFields.password.clear(),c.inputFields.rememberPassword.clear());d=a;b&&bg.localStorage_getItem(bg.SHA256(b)+".noremember")?($("#ExtensionLoginDialogRememberPasswordContainer").hide(),
a=!1):($("#ExtensionLoginDialogRememberPasswordContainer").show(),a=!0);a!==d&&c.setDynamicHeight()}}(this);this.inputFields.email.onChange(b);this.inputFields.email.inputObject.onChange(b)};ExtensionLoginDialog.prototype.setup=function(){LoginDialog.prototype.setup.apply(this,arguments);bg.get_saved_logins(this.savedLoginCallback);LPPlatform.checkBrowserPasswordManager(this.browserPasswordManagerCallback)};ExtensionLoginDialog.prototype.open=function(a){LoginDialog.prototype.open.call(this,$.extend(a,
{defaultData:{rememberEmail:bg.Preferences.get("rememberemail"),rememberPassword:bg.Preferences.get("rememberpassword"),rememberShowVault:bg.Preferences.get("showvault")}}))};ExtensionLoginDialog.prototype.handleSubmit=function(){var a=null,b=function(c){null===a&&(a=setInterval(function(){"undefined"===typeof VaultState&&bg.getData&&bg.getData({context:"login"});bg.get("lploggedin")&&(clearInterval(a),a=null,c.close())},1E3))};return function(a){a.email=bg.fix_username(a.email);bg.Preferences.set({rememberemail:a.rememberEmail,
rememberpassword:a.rememberPassword,showvault:a.rememberShowVault});a.disablePasswordManager&&bg.disablepasswordmanager(!0);bg.make_lp_key_hash(a.email,a.password,function(b,c){return function(d,e){b.set("g_manual_login",!0);b.LP_do_login(a.email,a.password,a.rememberEmail,a.rememberPassword,null,a.rememberShowVault,d,e);c.data.isPopup&&c.close()}}(bg,this));this.data.isPopup||b(this)}}()})();
