function LP_field_set_backgroundPosition(b,a){b||(b=LP_derive_doc());if(!b||!a)return!1;var c=!1;if(!0===LP_get_text_dir(a)){var d="98% 50%";-1<document.location.href.indexOf("https://mint.intuit.com/login.event?task=S")&&0<document.getElementById(a.id).nextElementSibling.offsetWidth&&(d="92% 50%");a.style.backgroundPosition!=d&&(c=!0)}else d="center left",lp_in_array(a.style.backgroundPosition,["center left","left center","0% 50%","left"])||(c=!0);c&&(a.style.backgroundPosition=d);return!0}
function LP_get_text_dir(b){var a=!0;if(b){var c=LP_get_live_style(b);c&&"rtl"==c.direction?a=!1:"rtl"==b.getAttribute("dir")&&(a=!1)}return a}
function LP_input_has_bg_style_override(b){if(!b||!g_stylesheet_grubbing)return!1;var a=!1;try{var c=formcacheget(b,"fakedoc","input-bg-style");if(null!=c)return c;var d=c=0,g=/(background|background-color):[^:].*!important/,e=b.styleSheets;if(e&&g)for(c=0;c<e.length&&32>c;c++){var f=null;"undefined"!=typeof e[c].rules?f=e[c].rules:"undefined"!=typeof e[c].cssRules&&(f=e[c].cssRules);if(f){for(d=0;d<f.length;d++)if(f[d]&&f[d].selectorText&&f[d].cssText&&-1!=f[d].selectorText.indexOf("input:focus")){var k=
f[d].cssText;if(k&&g.exec(k)){verbose_log("focus hack:"+k);a=!0;break}}if(a)break}}}catch(h){}formcacheset(b,"fakedoc","input-bg-style",a);return a}
function ForceFillOrphanFieldClicked(b,a,c){if(!b&&(b=elt.ownerDocument,!b))return!1;var d;if(d=ForceFillFieldClicked(b,a,!1,c)){var g=b.getElementsByTagName("INPUT"),e;for(e=0;e<g.length&&e<MAX_INPUTS_HARD;e++)if(g[e]==a&&g[e+1]&&e+1<g.length&&e+1<MAX_INPUTS_HARD){isInputFieldPassword(b,g[e+1])&&!lpIsFieldCurrentPWField(g[e+1])&&(d=ForceFillFieldClicked(b,g[e+1],!1,c));break}}return d}
function revert_clickable_icon(b,a){verbose_log("entered revert_clickable_icon");if(null!=b){var c=LP_getElementByIdOrName(b,a),d=getIconState(b,a),g=!1,e="sites";d&&"undefined"!=typeof d.dofloater&&(g=d.dofloater);d&&"undefined"!=typeof d.fillhint&&(e=d.fillhint);verbose_log("entered BG image revert");c?g?reset_floating_icon(b,c,e):set_input_icon_image(b,c,e):verbose_log("could not find field named "+field_id)}}function conditional_create_popup(b,a,c){return!1}
function closeclickableicons(b){if(do_experimental_popupfill&&(b||(b=document),null!=b)){verbose_log("closeclickableicons called on "+b.location.href);var a=getAllIconStates(),c,d;for(c=0;c<a.length;c++){var g=a[c];(d=g.IHTMLElement)||(d=LP_getElementByIdOrName(b,g.idorname));if(g.dofloat||!g.inframe||d)!g.dofloater&&d&&inputHasLPBackground(d)?removeLPBackground(d):pass;else if(g_isfirefox)try{var e,f,k=b.getElementsByTagName("IFRAME");for(e=0;e<k.length;e++)f=k[e].contentDocument,(d=LP_getElementByIdOrName(f,
g.idorname))&&"INPUT"==d.tagName&&removeLPBackground(d)}catch(h){verbose_log("Error frame traverse "+h.message),f=null}else!g_isie&&g_create_iframe_in_top&&pass;resetAllIconStates()}a=LP_get_icon_divs(b);for(e in a)a.hasOwnProperty(e)&&null!=b.getElementById(a[e])&&(g_do_icon_number_hint&&LP_delete_floating_icon_hint(b,a[e]),LP_delete_floating_icon(b,a[e]));LP_reset_icon_divs(b)}}
function setup_input_icon(b,a,c,d,g){var e=!1;if(null==a)return verbose_log("setup_input_icon: ERROR passed null field"),e;if(a.form&&"sites"==c&&is_shopping_form(b,a.form)&&g_aspx_hack&&(isASPpage()&&2<b.getElementsByTagName("form").length||!isASPpage()))return e;g_isfirefox&&LP&&"undefined"!=typeof g_icon_number_in_toolbar&&g_icon_number_in_toolbar&&LP.lp_handle_buttons_all("refresh");var f=null,f="undefined"!=typeof LP&&"function"==typeof LP.lpGetCurrentWindow?"undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?
LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument:g_isfirefox?top.document:document;if(!do_experimental_popupfill)return e;b||(b=f);var k=LP_pickFieldName(b,a);if(null==a||!f||!b||LP_explicit_ignored(b,a))return e;if((e=getIconState(b,k))&&e.IHTMLElement==a&&(inputHasLPBackground(a)||LP_floating_icon_exists(b,k)))return!1;e=null;if("generate"==c||!g&&shouldOfferGenerate(b,a))c="generate";var h=gettldcached(b.location.href),e=shouldCreateFloatingIcon(b,a,h),m=LP_get_text_dir(a);
!1===m&&pass;if(LP_fieldIsReadOnly(a)||LP_fieldIsDisabled(a))return!1;f=b!=f;g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&LP_inIframe(window)&&(f=!0);g={fillhint:c,fillhintnumber:d[c],inframe:f,idorname:k,doctld:h,dofloater:e?1:0,no_check_generate:g?1:0,IHTMLElement:a,text_direction:m};"function"==typeof is_edge&&is_edge()&&("undefined"==typeof g_created_edge_stylesheet&&(g_created_edge_stylesheet=!0,f=b.createElement("style"),f.type="text/css",f.appendChild(b.createTextNode(".lastpassClearHidden::-ms-clear { display:none; }")),
document.head?document.head.appendChild(f):document.body&&document.body.appendChild(f)),-1==a.className.indexOf("lastpassClearHidden")&&(a.className+=" lastpassClearHidden"));if(e)if(g_isfirefox&&verbose_log("setup_input_icon step3b"),lpIsVisible(a)&&(null==a.form||a.form&&lpIsVisible(a.form)))saveIconState(k,g,a),e=LP_create_floating_icon(b,a,c,d);else return!1;else saveIconState(k,g,a),e=set_input_icon_image(b,a,c,!1);set_bg_highlight_effect_handlers(b,a,c);LP_didDocumentEscapeEvent(b)||(LP_setDocumentEscapeEvent(b),
LP_addEventHandler(b,"keydown",function(a){LP_keypress_handler(a)},!1));LP_didFieldKeyEvent(b,a)?verbose_log("skip KEYDOWN HANDLER ON "+LP_pickFieldName(b,a)):(verbose_log("SETTING KEYDOWN HANDLER ON "+LP_pickFieldName(b,a)),LP_setFieldKeyEvent(b,a),LP_addEventHandler(a,"keydown",function(d){LP_field_keypress_handler(d,a,c,b)},!1),g_isfirefox&&LP_addEventHandler(a,"keyup",function(c){handle_form_text_change(b,a,a.form,c)},!1));return e}
function refresh_input_icon_bg(b,a,c){if(!b&&(b=LP_derive_doc(),!b))return null;a&&set_input_icon_image(b,a,c,!1)}
function refresh_input_all_icon_bg(b){null==b&&(b=document);if(null!=b){try{if(0<b.location.href.indexOf(".xul"))return;verbose_log("refreshing input icons on "+b.location.href)}catch(k){return}var a=getAllIconStates(),c;for(c=0;c<a.length;c++){var d=a[c].idorname,g=a[c].fillhint,e=a[c].dofloater,f=a[c].IHTMLElement;element_is_detached(b,f,0)&&(f=null);f||(f=LP_getElementByIdOrName(b,d));f&&!e&&refresh_input_icon_bg(b,f,g)}}}
function set_input_icon_image(b,a,c,d){b||(b=LP_derive_doc());if(!b)return!1;var g=b.defaultView;g||(g=window);var e,f=[];f[0]=g_sites_light_ico;f[1]=g_pw_light_ico;f[3]=g_close_light_ico;f[-1]="";f[2]=g_ff_light_ico;f[16]=g_sites_ico;f[17]=g_pw_ico;f[19]=g_close_ico;f[-17]="";f[18]=g_ff_ico;LP_has_highdef_display(g)&&(f[0]=g_40_icons["16x16_lite@2x"],f[16]=g_40_icons["16x16_dark@2x"],f[3]=g_40_icons["IF_Close@2x"],f[19]=g_40_icons["IF_Close@2x"],f[2]=g_40_icons["FormFill@2x"],f[18]=g_40_icons["FormFill_dark@2x"],
f[1]=g_40_icons["Generate@2x"],f[17]=g_40_icons["Generate_dark@2x"]);if(null==a||a.tagName&&"undefined"!=typeof a.tagName.toUpperCase&&"INPUT"!=a.tagName.toUpperCase())return!1;"undefined"==typeof c||null==c?e=0:"formfills"==c?e=2:"sites"==c?e=0:"generate"==c?e=1:"cancel"==c&&(e=3);d&&(e|=16);var k=LP_fieldGetWidth(a),h=!1;if("sites"==c||g_is_specialsite)h=!0;if(!LP_iconFieldWidthOK(a,k,h))return!0;c=a.style.border;k=a.style.backgroundImage;""==k&&(g=LP_getComputedStyle(g,a))&&(k=g.backgroundImage,
c=g.border);"none"==k&&(k="");0<=e&&("undefined"==typeof f[e]&&verbose_log("no icon defined for iconval="+e),d=LP_getloggedin()?0==e||16==e?getnumbericon(b,a,d):f[e]:f[e],k!="url("+d+")"&&(a.style.backgroundImage="url("+d+")",g_issafari&&""!==c&&0<c.indexOf("inset")&&c.replace("inset",""),"no-repeat"!=a.style.backgroundRepeat&&(a.style.backgroundRepeat="no-repeat"),"scroll"!=a.style.backgroundAttachment&&(a.style.backgroundAttachment="scroll"),(d=LP_getAbsolutePos(b,a))&&18>d.height&&0<d.height?"contain"!=
a.style.backgroundSize&&(a.style.backgroundSize="contain"):"16px 18px"!=a.style.backgroundSize&&(a.style.backgroundSize="16px 18px"),LP_field_set_backgroundPosition(b,a)));return!0}
function set_bg_highlight_effect_handlers(b,a,c){a&&(LP_didFieldMouseEvent(b,a)||(LP_setFieldMouseEvent(b,a),LP_addEventHandler(a,"mouseover",function(d){bg_highlight_effect_mouseover(d,b,a,c)}),LP_addEventHandler(a,"focus",function(d){bg_highlight_effect_mouseover(d,b,a,c)}),LP_addEventHandler(a,"mouseout",function(d){bg_highlight_effect_mouseout(d,b,a,c)}),LP_addEventHandler(a,"blur",function(d){bg_highlight_effect_mouseout(d,b,a,c)}),LP_addEventHandler(a,"mousemove",function(d){bg_highlight_effect_mousemove(d,
b,a,c)})),"sites"==c&&(!LP_getloggedin()||g_isfirefox||g_isie||a.setAttribute("autocomplete","off")))}function bg_highlight_effect_mousemove(b,a,c,d){null==b&&(b=window.event);b=LP_getMousePos(b);0>=b.x&&0>=b.y||(a=LP_getAbsolutePos(a,c),0>=a.width&&0>=a.height||(d=a.left+a.width-20,d<a.left&&(d=a.left),c.style.cursor=d<b.x&&a.left+a.width>b.x&&a.top<b.y&&a.top+a.height>b.y?"pointer":"auto"))}
function bg_highlight_effect_mouseover(b,a,c,d){null==b&&(b=window.event);if((!is_your_popup_showing(a)||a.g_popupfill_parent!=c)&&LP_getEventTarget(b)==c){b=d;d=!1;var g=getIconState(a,LP_pickFieldName(a,c));!b&&g&&g.hint&&(b=g.hint);g&&g.dofloater&&(d=g.dofloater);b&&!d&&set_input_icon_image(a,c,b,!0)}}
function bg_highlight_effect_mouseout(b,a,c,d){if(!is_your_popup_showing(a)||a.g_popupfill_parent!=c){b=d;d=!1;var g=getIconState(a,LP_pickFieldName(a,c));!b&&g&&g.hint&&(b=g.hint);g&&g.dofloater&&(d=g.dofloater);b&&!d&&set_input_icon_image(a,c,b,!1)}}
function popuptoggle(b,a,c,d,g,e,f,k,h,m){if(m)h=m;else if(a){if(0<a.location.href.indexOf(".xul"))return!0;h=LP_getElementByIdOrName(a,c)}else{if(0<b.location.href.indexOf(".xul"))return!0;h=LP_getElementByIdOrName(b,c)}"undefined"!=typeof reset_forcefill_without_fillbest&&reset_forcefill_without_fillbest();m="sites";d?m="generate":e?m="save":f&&(m="formfills");if(is_your_popup_showing(b))closepopupfills(b,"away"),g_isfirefox?a?(a.g_popupfill_parent_last=a.g_popupfill_parent,a.g_popupfill_parent=
null):(b.g_popupfill_parent_last=b.g_popupfill_parent,b.g_popupfill_parent=null):(g_popupfill_parent_last=g_popupfill_parent,g_popupfill_parent=null);else{var l=LP_getloggedin();if(!l){if("undefined"!=typeof LP&&"undefined"!=typeof LP.lpOpenLogin){LP.lpOpenLogin();return}if(!g_isie){sendBG({cmd:"dologinaction"});return}}g_isfirefox?a?a.g_popupfill_parent=h:b.g_popupfill_parent=h:g_popupfill_parent=h;e=e?!0:!1;g_isie?"undefined"!=typeof init_LPfn&&init_LPfn()&&LPfn.ie_set_lpifmsg(b,h,d,e,m,k):g_isfirefox||
(f=LP_pickFormName(h.ownerDocument,h.form),d=d?1:0,sendBG({cmd:"setpopupfilllastactive",active:f,activefieldid:LP_pickFieldName(document,h),ask_generate:d,opentosave:e,activefieldtype:h.type,start_type:m}));g_isfirefox||g_isie||(l=document.location.href,"undefined"!=typeof punycode&&(l=punycode.URLToASCII(document.location.href)),sendBG({cmd:"popupregister",docnum:g_docnum,url:l}));l=("function"==typeof ff_calculate_iframe_pos?ff_calculate_iframe_pos:calculate_iframe_pos)(b,h,"300px",should_ignore_body_relative(b));
e=d=0;l&&(d=l.posx,e=l.posy);if(g_isfirefox)ff_popupfill_create_iframe(b,d,e,c,null,null,h,m);else{f=chk_form_is_nonlogin_form(document,h.form);m=checkDocumentForLoginOrphans(document)||checkDocumentForLoginOrphansFirstStage(document);l=checkDocumentForLoginFirstStageForm(document);l=m||l||chk_form_has_password(document,h.form);m=g_popupfill_rows;f&&!l&&(m=g_popupfill_rows_FF);f=g_popupfill_widest+40;120>f&&(f=120);f<g_popupfill_parent.offsetWidth&&(f=g_popupfill_parent.offsetWidth,f+=2*Math.abs(POPUP_FIELD_OFFSET));
f=Math.min(f,MAX_DIALOG_WIDTH);if(1==m&&!create_onerow_iframe){l=null;g_fillaid&&(l=g_fillaid);isEmptyObject(g_autofillsites)||(l=g_autofillsites[0].aid);if(null!=l){sendBG({cmd:"autofillaid",aid:l});verbose_log("filling only, not creating 1 row iframe");return}verbose_log("tried to fill form with invalid acct")}if(0==m&&g==NO_FORCE_NOHITS)verbose_log("not creating empty iframe");else if(l=LP_getloggedin(),g_dologin_clickable&&!l&&(!g_isie||g_isie&&g==FORCE_SHOW_NOHITS_NOLOGIN)){verbose_log("login state: checking whether to issue Chrome login prompt");
if(g==FORCE_SHOW_NOHITS_NOLOGIN)return;if(!g_isie){sendBG({cmd:"dologinaction"});return}}if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&LP_inIframe(window)&&LP_do_toplevel_iframe_hack(window)){(l=calculate_iframe_pos(b,h,"300px",!0))?(d=parseInt(l.posx),e=parseInt(l.posy)):e=d=0;var p=g="";try{g=window.name,p=document.location.href}catch(q){}l=b.location.href;"undefined"!=typeof punycode&&(l=punycode.URLToASCII(b.location.href));var n=null;h&&h.getBoundingClientRect&&(n=h.getBoundingClientRect());
sendBG({cmd:"createpopuptoplevelfromframe",posx:d,posy:e,id:c,rows:m,width:f,minheight:g_minheight_override,framename:g,framesrc:p,url:l,fillhint:k,fieldBox:{top:n.top,right:n.right,bottom:n.bottom,left:n.left,width:n.width}})}else popupfill_create_iframe(b,d,e,c,m,f,g_minheight_override,null,null,{posx:d,posy:e,id:c,width:f,fieldEl:h,fillhint:k});g_popupfill_iframe_width_save=f}g_isfirefox?a?relocate_popupfill_iframes(a):relocate_popupfill_iframes(b):g_create_iframe_in_top&&LP_inIframe(window)&&
!g_isie&&!g_isfirefox||relocate_popupfill_iframes(b);if(!bg.get("LPContentScriptFeatures").is_infield_enabled){b=a?a:b;a=!1;if(k=getIconState(b,c))a=k.dofloater;a?change_clickable_icon_to_cancel(b,LPMAGIC+c,c):set_input_icon_image(b,h,"cancel",!0)}}}
function inputHasLPBackground(b){if(null==b)return!1;var a=null;if(g_isie&&"undefined"!=typeof b.currentStyle)"undefined"!=typeof b.currentStyle&&(a=b.currentStyle);else try{a=b.ownerDocument.defaultView.getComputedStyle(b,"")}catch(d){"undefined"!=typeof b.currentStyle&&(a=b.currentStyle)}if(a&&("INPUT"==b.tagName||"input"==b.tagName)&&""!=a.backgroundImage){if(-1!=a.backgroundImage.indexOf(g_sites_light_ico)||-1!=a.backgroundImage.indexOf(g_40_icons["16x16_lite@2x"])||-1!=a.backgroundImage.indexOf(g_pw_light_ico)||
-1!=a.backgroundImage.indexOf(g_close_light_ico)||-1!=a.backgroundImage.indexOf(g_ff_light_ico)||-1!=a.backgroundImage.indexOf(g_sites_ico)||-1!=a.backgroundImage.indexOf(g_pw_ico)||-1!=a.backgroundImage.indexOf(g_close_ico)||-1!=a.backgroundImage.indexOf(g_ff_ico)||-1!=a.backgroundImage.indexOf(g_40_icons.IF_Close)||-1!=a.backgroundImage.indexOf(g_40_icons["IF_Close@2x"])||-1!=a.backgroundImage.indexOf(g_40_icons.FormFill)||-1!=a.backgroundImage.indexOf(g_40_icons["FormFill@2x"])||-1!=a.backgroundImage.indexOf(g_40_icons.FormFill_dark)||
-1!=a.backgroundImage.indexOf(g_40_icons["FormFill_dark@2x"])||-1!=a.backgroundImage.indexOf(g_40_icons.Generate)||-1!=a.backgroundImage.indexOf(g_40_icons["Generate@2x"])||-1!=a.backgroundImage.indexOf(g_40_icons.Generate_dark)||-1!=a.backgroundImage.indexOf(g_40_icons["Generate_dark@2x"]))return verbose_log("icon "+LP_getname(b)+" has icon w/o number"),!0;if(-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,b,!0))||-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,b,!1)))return!0;
var c;for(c=0;9>=c;c++)if(-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,b,!0,c))||-1!=a.backgroundImage.indexOf(getnumbericon(b.ownerDocument,b,!1,c)))return verbose_log("icon "+LP_getname(b)+" has icon with number "+c),!0}return!1}
function removeLPBackground(b){if(!b)return!1;try{b.style.backgroundImage="none",b.style.backgroundRepeat="initial",b.style.backgroundAttachment="initial",b.style.backgroundPosition="initial",b.style.backgroundSize="initial"}catch(a){return verbose_log("removeLPBackground error: "+a.message),!1}return!0};
