function LPNG_humanize_fill(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=101;if(function(a,b){a||(a=LP_derive_doc());if(!a||!b)return!0;var c=b.field;if(!c)return!0;var d=b.type,e=b.value,l=b.allowforce,m=b.reqinfo,h=b.realurl,k=gettldcached(get_doc_location_href(a));if(skip_filling_field(c,k)||!b.is_launch&&should_ignore_autocompleteoff_bypref(a,c)||c.form&&!lpCheckWarnInsecure(c.form,c.form.ownerDocument,!1,l))return!0;c=LP_iscrossdomainok(a,k,c,d,e,m,h);return"calldelayed"==c?(console_warn("you lose"),
!0):c?chkoriginok(a,h)?!1:!0:!0}(b,c))return!1;"undefined"!=typeof c.beforeJS&&c.beforeJS&&LPNG_javascript_beforefield(b,c);"number"==typeof c.quant&&50<c.quant&&(a=c.quant);"undefined"==typeof c.send_keyevents&&(c.send_keyevents=!0);setTimeout(function(){LPNG_moveto_field(b,c);setTimeout(function(){LPNG_setval(b,c);setTimeout(function(){LPNG_moveout_field(b,c);"undefined"!=typeof c.afterJS&&c.afterJS&&LPNG_javascript_afterfield(b,c)},a)},a)},a);return!0}
function LPNG_moveto_field(b,c){b||(b=LP_derive_doc());if(!b||!c||!c.field)return!1;var a=c.field,d={},e=LP_getAbsolutePos(b,a);if(!e)return!1;d.target=a;d.posx=e.left;d.posy=e.top;LPNG_mouse_moveto(b,d);d.bubble=!1;LP_fireEvent(a,"mouseenter","MouseEvent",d);d.bubble=!0;LP_fireEvent(a,"mouseenter","MouseEvent",d);LPNG_do_focus(b,d);if(lp_in_array(a.type,["select","select-one"])){var e=a.selectedIndex,f=a.options;f.length>=e&&((e=f[e])&&e.value===c.value?pass:LP_humanizeClick(b,a,d))}else lp_in_array(a.type,
["radio","checkbox"])||LP_humanizeClick(b,a,d)}function LPNG_javascript_beforefield(b,c){b||(b=LP_derive_doc());return b&&c&&c.beforeJS?!0:!1}
function LPNG_setval(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.field,d=c.type,e=c.checked,f=c.sharedsite,g=c.keyevents;if(!a||!d)return!1;(d=b)||(d=LP_derive_doc());d&&c?(d=c.field,d=LP_fieldIsDisabled(d)||LP_fieldIsReadOnly(d)?!0:!1):d=!0;if(d)return!1;d=!1;switch(c.type){case "tel":case "number":case "url":case "text":a.value!=c.value&&("function"==typeof sendkey&&g&&(sendKey(KeyEvent.DOM_VK_SHIFT,a),sendKey(KeyEvent.DOM_VK_SPACE,a),sendKey(KeyEvent.DOM_VK_BACKSPACE,a)),a.value=c.value,
d=!0);lphighlightField(a);LP_getform_for_input(b,a);break;case "password":a.value!=c.value&&(a.value=c.value,d=!0);lphighlightField(a);LP_getform_for_input(b,a);f&&("undefined"!=typeof g_isie&&g_isie||(lpsharedpasswordfills[lpsharedpasswordfills.length]=a));break;case "checkbox":if(a.checked&&!e||!a.checked&&e){e={};e.target=a;if(f=LP_getAbsolutePos(b,a))e.posx=f.left,e.posy=f.top;LP_humanizeClick(b,a,e);d=!0}break;case "radio":if(a.checked&&!e||!a.checked&&e){e={};e.target=a;if(f=LP_getAbsolutePos(b,
a))e.posx=f.left,e.posy=f.top;LP_humanizeClick(b,a,e);d=!0}break;case "select":case "select-one":if(a.value!=c.value){if(g=a.options)for(d=0;d<g.length;d++)if(g[d].value===c.value){e={};e.target=g[d];if(f=LP_getAbsolutePos(b,g[d]))e.posx=f.left,e.posy=f.top;LP_humanizeClick(b,g[d],e);break}d=!0;a.value=c.value}break;case "textarea":a.value!=c.value&&(a.value=c.value,d=!0);lphighlightField(a);LP_getform_for_input(b,a);break;default:console_warn("unsupported type "+c.type)}d&&LPNG_do_input(b,c);return!0}
function LPNG_do_input(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.field,d=LP_getAbsolutePos(b,a);d&&LP_fireEvent(a,"input","Event",{evt_class:"Event",posx:d.posx,posy:d.posy});return!0}
function LPNG_moveout_field(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.field;if(!a)return!1;var d={},e=LP_getAbsolutePos(b,a);if(!e)return!1;d.target=a;d.posx=e.left;d.posy=e.top;LPNG_mouse_moveto(b,d);LPNG_do_unfocus(b,d);d.target=null;d.posx=e.left+2;d.posy=e.top+2;LPNG_mouse_moveto(b,d);d.bubble=!1;LP_fireEvent(a,"mouseleave","MouseEvent",d);d.bubble=!0;LP_fireEvent(a,"mouseout","MouseEvent",d)}
function LPNG_javascript_afterfield(b,c){b||(b=LP_derive_doc());return b&&c&&c.afterJS?!0:!1}function LPNG_customjs(b,c){}function LPNG_mouse_moveto(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.target;a||(a=b.documentElement);LP_fireEvent(a,"mousemove","MouseEvent",{evt_class:"MouseEvent",posx:c.posx,posy:c.posy});return!0}
function LPNG_do_focus(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.target;a||(a=b.documentElement);try{var d={evt_class:g_isie?"FocusEvent":"UIEvent",posx:c.posx,posy:c.posy};LP_fireEvent(a,"focus",g_isie?"FocusEvent":"UIEvent",d);d.bubble=!1;LP_fireEvent(a,"focusin",g_isie?"FocusEvent":"UIEvent",d)}catch(e){a.focus()}return!0}
function LPNG_do_unfocus(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.target;a||(a=b.documentElement);try{var d={evt_class:g_isie?"FocusEvent":"UIEvent",posx:c.posx,posy:c.posy};LP_fireEvent(a,"blur",g_isie?"FocusEvent":"UIEvent",d);d.bubble=!1;LP_fireEvent(a,"focusout",g_isie?"FocusEvent":"UIEvent",d)}catch(e){a.blur()}return!0}function fillfield_handler(b){}
function LPNG_pick_field(b,c){b||(b=LP_derive_doc());if(!b||!c)return null;var a=null,d=c.name,e=c.type,f=c.formname,g=c.otherfield;f&&(a="INPUT",e&&("select-one"==e.toLowerCase()?a="SELECT":"textarea"==e.toLowerCase()&&(a="TEXTAREA")),a=LP_getElementByIdOrName(b,d,a,f));if(a||(a=LP_getElementByIdOrName(b,d)))return a;g&&(e=b.getElementsByTagName("select-one"==e?"select":"textarea"==e?"textarea":"input"),d=d.match(/^(input|select|textarea)(\d+)$/))&&(a=parseInt(d[2]),a>e.length&&(a=e.length-1),a=
e[a]);return a};
