function LP_floating_icon_exists(a,b){return a||(a=LP_derive_doc(),a)?null!=LP_getElementByIdOrName(a,LP_compute_floating_iconcontainer_id(a,b)):!1}
function do_icon_mouseover(a,b,c){if(null==a||null==b||!c)return!1;c=LP_pickFieldName(a,c);var d=LP_compute_floating_icon_id(a,c),d=a.getElementById(d);if(is_your_popup_showing(a))return null!=d&&(d.style.opacity="1",d.style.filter="alpha(opacity=100)"),!1;if(null!=d){var e=!0;if(null!=a.getElementById(b)){b=!1;var k=getIconState(a,c);k&&(b=k.fillhint);"formfills"==b?(LP_has_highdef_display(f)?LP_set_image_src(d,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(d,g_40_icons.FormFill_dark),e=!1):"offersave"==
b?e=!1:"generate"==b&&(LP_has_highdef_display(f)?LP_set_image_src(d,g_40_icons["Generate_dark@2x"]):LP_set_image_src(d,g_40_icons.Generate_dark),e=!1)}if(e){var f=a.defaultView;f||(f=window);LP_has_highdef_display(f)?LP_set_image_src(d,g_40_icons["16x16_dark@2x"]):LP_set_image_src(d,g_40_icons["16x16"])}d.style.opacity="1";d.style.filter="alpha(opacity=100)"}g_do_icon_number_hint&&(f=LP_compute_floating_number_id(a,c),a=a.getElementById(f),null!=a&&g_icon_shading&&(a.style.backgroundColor="#CCFF99"))}
function do_icon_mouseout(a,b,c){if(null==a||null==b||!c)return!1;c=LP_pickFieldName(a,c);var d=LP_compute_floating_icon_id(a,c),d=a.getElementById(d);if(is_your_popup_showing(a))return null!=d&&(d.style.opacity="0.6"),!1;if(null!=d){if(null==a.getElementById(b))return!1;(b=a.defaultView)||(b=window);var e=!1,k=getIconState(a,c);k&&(e=k.fillhint);if(!e||"sites"!==e&&"formfills"!==e&&"generate"!==e&&"offersave"!==e)e="default";"default"==e||"sites"==e?(LP_has_highdef_display(b)?LP_set_image_src(d,
g_40_icons["16x16_dark@2x"]):LP_set_image_src(d,g_40_icons["16x16"]),d.style.opacity="0.6",d.style.filter="alpha(opacity=60)"):"formfills"==e?(LP_has_highdef_display(b)?LP_set_image_src(d,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(d,g_40_icons.FormFill_dark),d.style.opacity="0.6",d.style.filter="alpha(opacity=60)"):"generate"==e&&(LP_has_highdef_display(b)?LP_set_image_src(d,g_40_icons["Generate_dark@2x"]):LP_set_image_src(d,g_40_icons.Generate_dark),d.style.opacity="0.6",d.style.filter="alpha(opacity=60)")}g_do_icon_number_hint&&
(c=LP_compute_floating_number_id(a,c),a=a.getElementById(c),null!=a&&(g_icon_shading?a.style.backgroundColor="#FFFFFF":a.style.display=e&&g_icon_numbers&&1<g_icon_numbers[e]?"block":"none"))}
function change_clickable_icon_to_cancel(a,b,c){if(!a&&(a=LP_derive_doc(),!a))return!1;var d=a.defaultView;d||(d=window);c=LP_compute_floating_icon_id(a,c);c=a.getElementById(c);if(null!=c){if(null==a.getElementById(b))return!1;LP_has_highdef_display(d)?LP_set_image_src(c,g_40_icons["IF_Close@2x"]):LP_set_image_src(c,g_40_icons.IF_Close);c.style.opacity="0.6";c.style.filter="alpha(opacity=60)"}return!0}
function shouldCreateFloatingIcon(a,b,c){if(!a&&(a=LP_derive_doc(),!a)||!a||!b)return!1;if("stripe.com"==c)return!0;if("dominos.com"==c)return!1;if("metlife.com"==c&&-1!=a.location.href.indexOf("mybenefits.metlife.com"))return!0;if((a=LP_get_live_style(b))&&a.backgroundImage&&"none"!=a.backgroundImage&&!inputHasLPBackground(b))b=0<=a.backgroundImage.indexOf("blank")?!1:!0;else{if(a=g_trial_bg_expt)b?(b.style.backgroundImage="url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGP6zwAAAgcBApocMXEAAAAASUVORK5CYII=)",
a=LP_get_live_style(b),b=!a||"none"==a.backgroundImage||!a.backgroundImage||g_stylesheet_grubbing&&LP_input_has_bg_style_override(b.ownerDocument)?!1:!0):b=!1,a=!b;b=a?!0:!1}return b}
function LP_create_floating_icon(a,b,c,d){if(!a&&(a=LP_derive_doc(),!a)||!b)return!1;var e=a.defaultView;e||(e=window);var k=a.getElementsByTagName("body")[0],f,h;f=LP_pickFieldName(a,b);getIconState(a,f);var m=LP_compute_floating_iconcontainer_id(a,f);if(LP_floating_icon_exists(a,f))return!1;h=a.createElement("div");h.id=m;"undefined"!=typeof g_isfirefox&&g_isfirefox?(null==a.g_popup_divs&&(a.g_popup_divs={}),a.g_popup_divs[h.id]=h.id):g_popup_divs[h.id]=h.id;f=a.createElement("img");b.offsetHeight<
LPICON_WIDTH&&(f.height=b.offsetHeight,f.width=f.height);f.id=h.id+"_icon";m=!0;null!=c&&("formfills"==c?(LP_has_highdef_display(e)?LP_set_image_src(f,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(f,g_40_icons.FormFill_dark),f.style.opacity="0.6",f.style.filter="alpha(opacity=60)",m=!1):"generate"==c&&(LP_has_highdef_display(e)?LP_set_image_src(f,g_40_icons["Generate_dark@2x"]):LP_set_image_src(f,g_40_icons.Generate_dark),f.style.opacity="0.6",f.style.filter="alpha(opacity=60)",m=!1));m&&(LP_has_highdef_display(e)?
LP_set_image_src(f,g_40_icons["16x16_dark@2x"]):LP_set_image_src(f,g_40_icons["16x16"]),f.style.opacity="0.6",f.style.filter="alpha(opacity=60)");h.appendChild(f);"sites"==c&&(!LP_getloggedin()||g_isfirefox||g_isie||b.setAttribute("autocomplete","off"));g_do_icon_number_hint&&LP_create_floating_icon_hint(a,h.id,c,d)&&LP_set_floating_icon_hint(a,h.id,c,d);k.appendChild(h);h.style.maxHeight=LPICON_WIDTH+"px";h.style.verticalAlign="top";f.style.verticalAlign="top";"undefined"!=typeof g_docnum&&verbose_log("["+
g_docnum+"] setting up click listener on icon for "+LP_pickFieldName(a,b));g_icon_hover&&(LP_addEventHandler(h,"mouseover",function(c){do_icon_mouseover(a,h.id,b);LP_stopEventPropagation(c);return!1}),LP_addEventHandler(h,"mouseout",function(c){do_icon_mouseout(a,h.id,b);LP_stopEventPropagation(c);return!1}));g_icon_parent_hover&&(LP_addEventHandler(b,"mouseover",function(c){do_icon_mouseover(a,h.id,b);LP_stopEventPropagation(c);return!1}),LP_addEventHandler(b,"mouseout",function(c){do_icon_mouseout(a,
h.id,b);LP_stopEventPropagation(c);return!1}));LP_addEventHandler(k,"DOMsubtreemodified",function(){popupfill_resize(a);return!1},!1);LP_addEventHandler(k,"resize",function(){popupfill_resize(a);return!1},!1);k.onresize=onresize_handler;setprops_floating_icon(a,b,h,c,d);return!0}
function move_floating_icon(a,b,c,d){a||(a=LP_derive_doc());if(!a||!b)return!1;a.getElementsByTagName("body");var e;e=LP_pickFieldName(a,b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(!c){var k=getIconState(a,e);k&&(c=k.fillhint)}if(e=LP_getElementByIdOrName(a,LP_compute_floating_iconcontainer_id(a,e)))g_do_icon_number_hint&&(LP_getloggedin()?LP_set_floating_icon_hint(a,e.id,c,d):LP_delete_floating_icon_hint(a,e.id)),setprops_floating_icon(a,b,e,c,d);return!0}
function setprops_floating_icon(a,b,c,d,e){function k(a,b){if(!a||!b)return!1;var c=!1,d=a.getElementsByTagName("body")[0],e=b.parentNode;e&&e!=d&&d&&(e.removeChild(b),d.appendChild(b),c=!0);return c}if(a&&b&&c){var f=LP_pickFieldName(a,b);if(f=getIconState(a,f)){k(a,c);"absolute"!=c.style.position&&(c.style.position="absolute");var h=LP_getAbsolutePos(a,b);if(null!=h){if(b.offsetHeight>LPICON_WIDTH){var m=h.top+(b.offsetHeight-LPICON_WIDTH)/2+"px";c.style.top!=m&&(c.style.top=m)}else c.style.top!=
h.top+"px"&&(c.style.top=h.top+"px");f=0==f.text_direction?h.left+2+"px":h.left+b.offsetWidth-LPICON_WIDTH-2+"px";c.style.left!=f&&(c.style.left=f);if(g_do_icon_number_hint){var g;null==g&&(g=a.getElementById(c.id+"_icon"));var f=parseInt(c.style.left),h=parseInt(c.style.top),n=a.getElementById(c.id+"_numspan");if(null!=n)if(k(a,n),null!=d&&null!=e&&null!=e[d]&&1<e[d]){var l=e[d];0<e[d]&&9>e[d]&&(l=" "+e[d]);l=LP_measureText(a,l,null,"font-size: 9px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;line-height:11px;");
if(null!=l){var p=h+("undefined"==typeof g.height||0==g.height?LPICON_HEIGHT:g.height)-l.height+6+"px",q=f+("undefined"==typeof g.width||0==g.width?LPICON_WIDTH:g.width)-l.width+2+"px",l="position:absolute !important; visibility:visible !important; border:0px !important; font-size:9px !important; font-family: Helvetica Neue,Helvetica,Arial,sans-serif; top:"+p+" !important; left:"+q+" !important; background-color: #808080; padding: 1px 2px !important; font-weight: bold !important; color:#ffffff !important; cursor: default; line-height:11px !important; max-width: 10px !important; ";
g="undefined"!=typeof window&&window?window:a.defaultView;g=LP_getComputedStyle(g,n);d=g.zIndex;""!==d&&"auto"!=d&&(l=l+"z-index:"+d+" !important;");if("absolute"!=g.position||"visible"!=g.visibility||"9px"!=g.fontSize||"1px 2px"!=g.padding||"11px"!=g.lineHeight||g.top!=p||g.left!=q)n.style.cssText=l}else l="display:none;",n.style.cssText=l}else l="display:none;",n.style.cssText=l}}else verbose_log("ERROR: unable to relocate clickable icon");d=getZIndex(a,b,0,0);null!=d?d++:d=CLICKABLE_ICON_ZINDEX;
c.style.zIndex!=d&&(c.style.zIndex=d);g_do_icon_number_hint&&null!=n&&(l=l+"z-index:"+(d+1)+" !important;",g="undefined"!=typeof window&&window?window:a.defaultView,g=LP_getComputedStyle(g,n),g&&"absolute"==g.position&&"visible"==g.visibility&&"9px"==g.fontSize&&"1px 2px"==g.padding&&"11px"==g.lineHeight&&g.top==p&&g.left==q&&g.zIndex==d+1||(n.style.cssText=l));checkIsDisplayed(a,b,0)?c.style.display="":c.style.display="none";g=c.childNodes[0];parseInt(b.offsetHeight)<LPICON_WIDTH?(b.offsetHeight!=
g.height&&(g.height=parseInt(b.offsetHeight)),b.offsetHeight!=g.height&&(g.width=g.height)):(g.height!=LPICON_WIDTH&&(g.height=LPICON_WIDTH),g.width!=LPICON_WIDTH&&(g.width=LPICON_WIDTH))}}}function refresh_floating_icon_number_hints(a){null==a&&(a=document);if(null!=a)if(LP_get_icon_divs(a),LP_getloggedin())for(i in iconidhash);else for(i in iconidhash){var b=a.getElementById(iconidhash[i]+"_numspan");b&&(b.parentNode.removeChild(b),verbose_log("deleting icon number for "+iconidhash[i]))}}
function LP_reset_icon_divs(a){if(!a&&(a=LP_derive_doc(),!a))return!1;"undefined"!=typeof g_isfirefox&&g_isfirefox?a.g_popup_divs={}:g_popup_divs={};return!0}function LP_store_icon_div(a,b){if(!a&&(a=LP_derive_doc(),!a))return!1;"undefined"!=typeof g_isfirefox&&g_isfirefox?(null==a.g_popup_divs&&(a.g_popup_divs={}),a.g_popup_divs[b]=b):g_popup_divs[b]=b;return!0}
function LP_delete_icon_div(a,b){"undefined"!=typeof g_isfirefox&&g_isfirefox?a&&delete a.g_popup_divs[b]:delete g_popup_divs[b];return!0}function LP_get_icon_divs(a){if(!a&&(a=LP_derive_doc(),!a))return{};if("undefined"!=typeof g_isfirefox&&g_isfirefox){if(null!=a.g_popup_divs)return a.g_popup_divs}else if(null!=g_popup_divs)return g_popup_divs;return{}}
function LP_set_floating_icon_hint(a,b,c,d){if(!a&&(a=LP_derive_doc(),!a))return!1;if(LP_getloggedin()){var e=a.getElementById(b+"_numspan");null!=e?(a=LP_elt_get_text(e),null!=c&&null!=d&&null!=d[c]&&0<d[c]?"formfills"!=c&&"generate"!=c||!1!==g_show_icon_number_for_formfills?(c=9>d[c]?" "+d[c]:9<d[c]?"9+":" "+d[c],a!=c&&LP_elt_set_text(e,c)):""!=a&&LP_elt_set_text(e,""):LP_elt_set_text(e,"")):LP_create_floating_icon_hint(a,b,c,d);return!0}}
function LP_create_floating_icon_hint(a,b,c,d){if(!a&&(a=LP_derive_doc(),!a)||!b)return!1;d=a.getElementsByTagName("body")[0];if(a.getElementById(b+"_numspan")||("formfills"==c||"generate"==c)&&!1===g_show_icon_number_for_formfills)return!1;a=a.createElement("div");a.id=b+"_numspan";a.style.position="absolute";a.style.top="-1000px";a.style.left="-1000px";d.appendChild(a);g_defensive&&LP_addEventHandler(a,"mousedown",function(a){LP_stopEventPropagation(a);return!1});return!0}
function LP_delete_floating_icon_hint(a,b){if(!a&&(a=LP_derive_doc(),!a))return!1;var c=a.getElementById(b+"_numspan");return null!=c?(c.parentNode.removeChild(c),!0):!1}function LP_delete_floating_icon(a,b){if(!a&&(a=LP_derive_doc(),!a))return!1;var c=a.getElementById(b);return null!=c?(c.parentNode.removeChild(c),!0):!1}
function relocate_popupfill_clickables(a){if(!a&&(a=LP_derive_doc(),!a))return null;if("function"==typeof a.getElementsByName){g_isfirefox&&verbose_log("relocate_popupfill_clickables doc is "+get_doc_location_href(a));var b=LP_get_icon_divs(a);if(isEmptyObject(b))return null;try{var c,d=0;for(c in b)if(b.hasOwnProperty(c)){var e=b[c].substr(LPMAGIC.length);if(null!=e&&0<e.length){var k=e,f=LP_getElementByIdOrName(a,k);if(null!=f||g_double_password_hack||g_double_secret_password_hack)if(g_do_icon_number_hint){if(null!=
a.getElementById(b[c])){var h="",m=getIconState(a,k);m&&(h=m.fillhint);null!=h&&"sites"!=h&&(h=null);k={};g_isfirefox?k[h]=m.fillhintnumber:(k.sites=0<g_icon_number_overrides.sites?g_icon_number_overrides.sites:g_icon_numbers.sites,k.formfills=0<g_icon_number_overrides.formfills?g_icon_number_overrides.formfills:g_icon_numbers.formfills);move_floating_icon(a,f,h,k)}}else move_floating_icon(a,f);else LP_delete_floating_icon(a,b[c])&&(verbose_log("relocate: deleting orphaned icon container for "+e),
d++),g_do_icon_number_hint&&LP_delete_floating_icon_hint(a,b[c])&&(verbose_log("relocate: deleting orphaned icon number for "+e),d++),delete b[c]}}}catch(n){verbose_log("relocate_popupfill_clickables caught error:"+n.message),g_isfirefox&&end_weasel(a)}if(0<d)if(g_isfirefox){var g=lpGetBrowserForDocument(a);setTimeout(function(){LP.checkShouldRecheck(g)},500)}else setTimeout(function(){if(g_pending_recheck)verbose_log("skipped 1 recheck, 1 is already queued up, #7");else{var b=LP_get_last_url_history(a);
checkShouldRecheck({href:b.href,href_hash:b.href_hash})}},500)}}
function reset_floating_icon(a,b,c){if(!a&&(a=LP_derive_doc(),!a))return!1;var d=a.defaultView;d||(d=window);b=LP_pickFieldName(a,b);var e=getIconState(a,b);!c&&e&&(c=e.fillhint);e=LP_getElementByIdOrName(a,LP_compute_floating_iconcontainer_id(a,b));a=LP_getElementByIdOrName(a,LPMAGIC+b+"_icon");return e&&a?("formfills"==c?LP_has_highdef_display(d)?LP_set_image_src(a,g_40_icons["FormFill_dark@2x"]):LP_set_image_src(a,g_40_icons.FormFill_dark):"generate"==c?LP_has_highdef_display(d)?LP_set_image_src(a,
g_40_icons["Generate_dark@2x"]):LP_set_image_src(a,g_40_icons.Generate_dark):LP_has_highdef_display(d)?LP_set_image_src(a,g_40_icons["16x16_dark@2x"]):LP_set_image_src(a,g_40_icons["16x16"]),a.style.opacity="0.6",a.style.filter="alpha(opacity=60)",!0):!1}
function getZIndex(a,b,c,d){LPCTR("getzindex");if(null==a||b==a.body||null==b||50<c)return null;var e=LP_getComputedStyle("undefined"!=typeof window&&window?window:a.defaultView,b);if(null==e)return null;if("absolute"==e.position||"relative"==e.position||"fixed"==e.position){if("auto"==e.zIndex||""===e.zIndex)return a=getZIndex(a,b.parentNode,c+1,d+1),null==a?0:parse_zindex(a);a=getZIndex(a,b.parentNode,c+1,parse_zindex(e.zIndex));return null==a?parse_zindex(e.zIndex)+1:parse_zindex(a)+1}if("auto"==
e.zIndex||""==e.zIndex)return a=getZIndex(a,b.parentNode,c+1,d+1),null==a?d+1:parse_zindex(a)+1;a=getZIndex(a,b.parentNode,c+1,parse_zindex(e.zIndex));return null==a?parse_zindex(e.zIndex):parse_zindex(a)+1}function end_weasel(a){if(do_experimental_popupfill&&(a||(a=document?document:LP.getBrowser().contentDocument),a)){var b;b=a&&null!=a.g_weasel_id?a.g_weasel_id:g_weasel_id;null!=b&&clearTimeout(b);g_isfirefox?a&&(a.g_weasel_id=null,a.g_weaseled=!1):(g_weasel_id=null,g_weaseled=!1)}}
function LP_compute_floating_iconcontainer_id(a,b){a||(a=LP_derive_doc());return a&&b?LPMAGIC+b:""}function LP_compute_floating_icon_id(a,b){a||(a=LP_derive_doc());return a&&b?LP_compute_floating_iconcontainer_id(a,b)+"_icon":""}function LP_compute_floating_number_id(a,b){a||(a=LP_derive_doc());return a&&b?LP_compute_floating_iconcontainer_id(a,b)+"_numspan":""};
