var MAX_DIALOG_WIDTH=400;
function LP_getLPIframe(a,b){a||(a=LP_derive_doc());if(!a)return null;var d=null,c,e;if(b&&(c=a.getElementById(b))&&"IFRAME"==c.tagName.toUpperCase()&&c.name==c.id)return c;(c=g_popupfill_parent)||(c=g_popupfill_parent_last);if((b=LP_getLPIframeID(a,c))&&(c=a.getElementById(b))&&"IFRAME"==c.tagName.toUpperCase()&&c.name==c.id)return c;var f=a.getElementsByTagName("IFRAME");for(e=0;e<f.length;e++)if((c=f[e])&&"undefined"!=typeof c.id&&null!=c.id&&0==c.id.indexOf(LPMAGICIFRAME)){d=c;break}return d}
function relocate_LPIframe(a,b){a||(a=LP_derive_doc());if(!a)return!1;var d=!0,c=LP_getLPIframeID(a);(c=LP_getLPIframe(a,c))?(LP_getComputedStyle(a,c),g_iframe_docked&&LP_getAbsolutePos(a,g_popupfill_parent)):d=!1;return d}
function resize_LPIframe(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d;g_drag_type=LP_DRAG_NODRAG;if("undefined"==typeof b.height||"undefined"==typeof b.width)if("undefined"!=typeof b.delx&&"undefined"!=typeof b.dely)g_drag_type=LP_DRAG_RESIZE;else return!1;d=!1;var c=LP_getLPIframeID(a);if(c=LP_getLPIframe(a,c))g_draggable&&g_drag_type===LP_DRAG_RESIZE?(d=LP_getAbsolutePos(a,c),d={width:d.width+b.delx,height:d.height+b.dely},g_minwidth_override=d.width,g_minheight_override=d.height):d={width:b.width,
height:b.height},d=place_LPIframe(a,d);return d}
function place_LPIframe(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=sprintf;"undefined"!=typeof g_isie&&g_isie&&(init_LPfn(),"undefined"!=typeof LPfn&&(d=LPfn.sprintf));var c=!0,e=LP_getLPIframeID(a);if(e=LP_getLPIframe(a,e)){var f=LP_getAbsolutePos(a,e);if(null===f||0>parseInt(b.width)||0>parseInt(b.height))verbose_log("invalid iframe pos"),c=!1;else{var k=parseInt(f.top)+"px",q=parseInt(f.left)+"px",m=parseInt(f.height)+"px",f=parseInt(f.width)+"px",g;"undefined"!=typeof b.height&&(g=parseInt(b.height),
""===g||isNaN(g)||(m=g+"px"));"undefined"!=typeof b.width&&(g=parseInt(b.width),""===g||isNaN(g)||(f=g+"px"));"undefined"!=typeof b.left&&(g=parseInt(b.left),""===g||isNaN(g)||(q=g+"px"));"undefined"!=typeof b.top&&(g=parseInt(b.top),""===g||isNaN(g)||(k=g+"px"));d=d("width: %s !important; height: %s !important; top: %s !important; left:%s !important;",f,m,k,q);if(""==g_frame_css_str)try{var h=document.body.getAttribute("data-lp-gcss");h&&(g_frame_css_str=LPJSON.parse(h),document.body.removeAttribute("data-lp-gcss"))}catch(n){write_error_to_history(a,
"resize_LPIframe",n)}h=g_frame_css_str+d;h.match(/position: *absolute/)||(h+=" position: absolute;");normalize_css(e.style.cssText)!=normalize_css(h)&&(e.style.cssText=h,e.setAttribute("width",parseInt(f)),e.setAttribute("height",parseInt(m)))}}else c=!1;return c}function LP_getLPIframeID(a,b){!a&&b&&(a=b.ownerDocument);a||(a=LP_derive_doc());if(!a)return null;var d;b?(d=LP_pickFieldName(a,b),d=LPMAGICIFRAME+d):d=void 0;return d}
function LP_computeLPIframeID(a){if("undefined"==typeof SHA256)return LPMAGICIFRAME+a;var b=sprintf;"undefined"!=typeof g_isie&&g_isie&&(init_LPfn(),"undefined"!=typeof LPfn&&(b=LPfn.sprintf));return SHA256(b("%d-%s",Date.now(),a))}function rot13(a){if(!a)return"$str =~ tr/a-zA-Z/n-za-mN-ZA-M/";for(var b="",d=0;d<a.length;d++){var c=a.charCodeAt(d);if(65<=c&&77>=c||97<=c&&109>=c)c+=13;else if(78<=c&&90>=c||110<=c&&122>=c)c-=13;b+=String.fromCharCode(c)}return b}
function LP_inIframe(a){a||(a=window);if(null==g_inframe)try{var b=get_win_self(a);return b!==a.top?is_edge()?b.location.href!=a.top.location.href||a.frameElement:!0:!1}catch(d){return!0}else return g_inframe}
function is_your_popup_showing(a){if(null==a)return!1;var b=a.defaultView;b||"undefined"==typeof window||(b=window);var d=!1;try{if(null==a.location){verbose_log("is_your_popup_showing given a firefox zombie document?");var c="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument;closepopupfills(c);d=!0}}catch(e){d=!0}if(d)return!1;g_isfirefox&&verbose_log("entered is_your_popup_showing for doc="+a.location.href);
if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&LP_inIframe(b))return toplevel_iframe_state_get();if(0<a.location.href.indexOf("popupfilltab.xul"))return!0;a=a.getElementsByTagName("iframe");for(b=0;b<a.length;b++)if(("function"!=typeof a.hasOwnProperty||a.hasOwnProperty(b))&&0==a[b].id.indexOf(LPMAGICIFRAME))return!0;return!1}
function enableScrollOnIframe(a,b){null==b&&(b=document?document:LP.getBrowser().contentDocument);if(null==b)return null;verbose_log("enabling Scroll on Iframe for "+b.location.href);var d=b.getElementsByTagName("IFRAME"),c,e;if(null!=d&&0<d.length)for(c=0;c<d.length;c++){e=d[c];var f=a.replace(/^(https:|http:)/,"");verbose_log("checking iframe src="+lp_ofa(e.src)+" passed href="+lp_ofa(a));if(e.src==a||0<e.src.indexOf(a)||0<e.src.indexOf(f))"undefined"!=typeof g_isie&&g_isie?(e.setAttribute("scrolling",
"auto"),e.style.overflow="visible",e.style.maxHeight="none"):(e.setAttribute("scrolling","auto"),e.style.overflow="auto"),verbose_log("enabling scroll on iframe to "+lp_ofa(a))}}
function enableScrollWithinIframe(a,b){a||(a=LP_derive_doc());if(!a)return!1;null==b&&(b=window);if(is_your_popup_showing(a)&&get_win_self(b)!=b.top)if(verbose_log("enabling scroll on body of iframe"),g_isfirefox)a.body.style.overflow="auto";else if(g_isie){var d=0;"undefined"!=typeof init_LPfn&&init_LPfn()&&LPfn&&(d=LPfn.getDocumentMode(document));7<d?(a.body.style.overflow="visible",a.body.setAttribute("scroll","auto")):a.body.setAttribute("overflow","auto")}else a.body.style.overflow="auto"}
function LP_getIframeBySrc(a,b){null==a&&(a=document);var d=a.getElementsByTagName("IFRAME"),c;for(c=0;c<d.length;c++)if(d[c].src==b)return d[c];return null}function toplevelpopupsetstate_handler(a){g_create_iframe_in_top&&toplevel_iframe_state_set(a?!0:!1)}function toplevel_iframe_state_get(){return g_toplevel_iframe_exists}function toplevel_iframe_state_set(a){g_toplevel_iframe_exists=a}function LP_do_toplevel_iframe_hack(a){return!a||g_isie||g_isfirefox?!1:!0}
function relocate_popupfill_iframes(a,b){if(do_experimental_popupfill)try{var d=a;g_isfirefox&&(d="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument);if(!a||!d)return null;if(g_isfirefox&&null==a.location){verbose_log("relocate_popupfill_iframes given zombie document?");var c="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument;
closepopupfills(c)}else{var e=c=!1;if(!f){var f=a.defaultView;f||(f=a.parentWindow)}"undefined"!=typeof g_iscasper&&g_iscasper&&(f=a.defaultView);var k,q=d.getElementsByTagName("iframe");for(k=0;k<q.length;k++){var m=q[k];if("undefined"!=typeof m.id&&null!=m.id){var g=LPMAGICIFRAME;if(0==m.id.indexOf(g)){var h=m.id.substr(g.length),g=h,c=!0,n=LP_getElementByIdOrName(a,h),p=!b;if(g_isfirefox||null!=n&&lpIsVisible(n,p)){var l=null;if(g_isfirefox)l=ff_get_iframe_pos(a,f,n,g,d),null!=l&&(e=!0);else if(l=
calculate_iframe_pos(a,n,0<g_minwidth_override?g_minwidth_override:0),g_draggable&&!g_iframe_docked){var v=!1,t=v,r=LP_getAbsolutePos(a,m,t);l.posx=r.left;l.posy=r.top}null!=l&&place_iframe_absolute(a,f,m,l,d)}else!g_create_iframe_in_top||g_isie||g_isfirefox||LP_inIframe(f)||!toplevel_iframe_state_get()?g_isfirefox||g_double_password_hack||g_double_secret_password_hack||LP_element_is_MaskedField(n)||LP_element_is_UnmaskedField(n)||closepopupfills(a):(t=v=!1,l=LP_getAbsolutePos(a,m,t),l.posx=l.left,
l.posy=l.top,place_iframe_absolute(a,f,m,l,d))}}}g_isfirefox&&!e&&c&&(verbose_log("found orphan iframe, remove it"),closepopupfills(a))}}catch(u){lplog("relocate_popupfill_iframe failed, "+u.message),do_bgiconinput||end_weasel(a),g_isfirefox&&closepopupfills(a)}}
function place_iframe_absolute(a,b,d,c,e){if(!(d&&a&&b&&c))return!1;var f=null,k;if("undefined"!=typeof Math){var q=null;g_draggable&&!g_iframe_docked&&(q=LP_getComputedStyle(b,d));try{var m=c.posx,g=c.posy,h=parseInt(m)+"px",n=parseInt(g)+"px",p=0;0<parseInt(g_minwidth_override)?(p=Math.max(parseInt(g_popupfill_iframe_width_save),parseInt(g_minwidth_override))+"px",(k=LP_getWindowWidth(b,!0))&&parseInt(p)+parseInt(h)>k&&(h=k-parseInt(p)-20+"px")):0<parseInt(g_popupfill_iframe_width_save)?p=parseInt(g_popupfill_iframe_width_save)+
"px":(null==f&&(f=LP_getComputedStyle(b,d)),p=f.width);0>parseInt(h)&&(h="0px");0>parseInt(n)&&(n="0px");k=0;0<parseInt(g_minheight_override)?k=Math.max(parseInt(g_popupfill_iframe_height_save),parseInt(g_minheight_override))+"px":""!=g_popupfill_iframe_height_save&&0<parseInt(g_popupfill_iframe_height_save)?k=parseInt(g_popupfill_iframe_height_save)+"px":(null==f&&(f=LP_getComputedStyle(b,d)),f&&(k=f.height));p=Math.min(parseInt(p),MAX_DIALOG_WIDTH)+"px";if(g_iframe_scroll_hack&&!g_frame_scrollable_set){var l=
parseInt(k),v=parseInt(p),t;t=b&&"undefined"!=typeof b.getComputedStyle?g_isfirefox?LP_getComputedStyle(b,a.documentElement):LP_getComputedStyle(b,a.body):"undefined"!=typeof a.documentElement?LP_getComputedStyle(b,a.documentElement):LP_getComputedStyle(b,a.body);parseInt(t.height);parseInt(t.width);var r=b.innerHeight,u=b.innerWidth;"undefined"==typeof r&&(r=LP_getWindowHeight(b,a));"undefined"==typeof u&&(u=LP_getWindowWidth(b));if((null!=l&&0<l&&null!=r&&0<r||null!=v&&0<v&&null!=u&&0<u)&&(parseInt(g)+
l>r||parseInt(m)+v>u)&&LP_inIframe(b)){if(g_isfirefox){enableScrollWithinIframe(a,b);var w=LP.getBrowser(),x=w?w.contentDocument:null;x&&x!=a&&enableScrollOnIframe(a.location.href,e)}else g_isie||(verbose_log("ensuring this frame/iframe has scrolling enabled"),sendBG({cmd:"iframescrollenable",href:a.location.href}));g_frame_scrollable_set=!0}}g_draggable&&!g_iframe_docked&&q&&(c&&"undefined"!=typeof c.posx&&"undefined"!=typeof c.posy?(n=parseInt(c.posy)+"px",h=parseInt(c.posx)+"px",0>parseInt(c.posy)&&
(n="0px"),0>parseInt(c.posx)&&(h="0px")):(n=q.top,h=q.left));place_LPIframe(a,{width:p,height:k,top:n,left:h})||(verbose_log("invalid iframe pos"),debug_checkpoint("failed to place iframe"),closepopupfills(a))}catch(y){verbose&&alert("place_abs "+y.message)}return True}}
function normalize_css(a){a=a.replace(/ /g,"");a=a.replace(/1\.0/g,"1");a=a.replace(/2147483647/g,"2147483648");a=a.replace("border-top-style:none!important;border-right-style:none!important;border-bottom-style:none!important;border-left-style:none!important;","border-style:none!important;");g_isie&&(a=a.replace("filter:alpha(opacity=100)!important;",""),a=a.replace("border-style:none!important;",""),a=a.split(";").sort().join(";"));return a}
function moveIframe_handler(a,b){a||(a=LP_derive_doc());if(a){var d=a.defaultView;d||(d=window);if(g_draggable&&"undefined"!=typeof b.delx&&"undefined"!=typeof b.dely){g_iframe_docked=!1;var c=LP_getLPIframe(a);if(c){var e=LP_getAbsolutePos(a,c);e&&place_iframe_absolute(a,d,c,{posx:e.left+b.delx,posy:e.top+b.dely})}}}}function resizeIframe_handler(a,b){a||(a=LP_derive_doc());a&&b&&resize_LPIframe(a,b)};
