LPTabState=function(){var h={},q=null;LPPlatform.onTabClosed(function(a){delete h[a]});Topics.get(Topics.CLEAR_DATA).subscribe(function(){h={}});var n=function(a,c){c=[].concat(c);var b=c.indexOf(lpmdec_acct(a.password,!0,a,g_shares));if(-1===b&&a.fields&&0<a.fields.length)for(var d=0;d<a.fields.length;++d){var g=a.fields[d];if("password"===g.type&&(b=c.indexOf(lpmdec_acct(g.value,!0,a,g_shares)),-1<b))break}return-1<b?c[b]:null},p=function(){var a=/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*/g,
c=function(a){if(a=get_ff_translation(a))return new RegExp(a)},b=function(a,b){if(a&&b)return a.test(b.toLowerCase())},d=[function(){var a=function(a,c,k){if(b(c,a.id)||b(a.attributes.name)||b(k,a.label))return!0};return function(b,k,d){k=c("ff_ssn_regexp");d=c("ff_text_ssn_regexp");for(var f=c("ff_cccsc_regexp"),v=c("ff_text_cccsc_regexp"),g=c("ff_securityanswer_regexp"),w=c("ff_captcha_regexp"),m=0;m<b.fields.length;++m){var e=b.fields[m];if(a(e,k,d)||a(e,f,v)||a(e,g)||a(e,w))return!1}}}(),function(a,
b,c){if(1===b.uniquePasswords.length)return c=b.uniquePasswords[0],2===b.passwordsByValue[c].count&&(2===a.fields.length?a.passwordChangeForm=!0:a.createAccountForm=!0),c},function(a,b,c){for(var f in b.passwordsByValue)if(1<b.passwordsByValue[f].count)return 2===b.uniquePasswords.length?(a.passwordChangeForm=!0,a.originalPassword=b.uniquePasswords[0]===f?b.uniquePasswords[1]:b.uniquePasswords[0]):a.createAccountForm=!0,f},function(a,b,c){if(2===b.uniquePasswords.length){a:{c=c.getSites();for(var f=
b.uniquePasswords,d=0;d<c.length;++d){var k=n(c[d],f);if(k){c=k;break a}}c=null}if(c)return a.passwordChangeForm=!0,a.originalPassword=c,b.uniquePasswords[0]===c?b.uniquePasswords[1]:b.uniquePasswords[0]}},function(a,b,c){for(var f in b.passwordsByValue)if(a=b.passwordsByValue[f].field,c=["pw","pass"],e(a.attributes.name,c)||e(a.id,c))return f}],g=[function(a,f,d){if(f=c("ff_username_regexp"))for(d=0;d<a.fields.length;++d){var k=a.fields[d];if(b(f,k.label))return k.value}},function(a,b,c){if(1===
b.uniqueTextValues.length)return c=b.uniqueTextValues[0],2===b.textFieldsByValue[c].count&&(a.createAccountForm=!0),c},function(a,b,c){for(var d in b.textFieldsByValue)if(1<b.textFieldsByValue[d].count)return a.createAccountForm=!0,d},function(a,b,c){a=a.fields;for(b=1;b<a.length;++b)if("password"===a[b].type&&(c=a[b-1],"password"!==c.type))return c.value},function(a,b,c){for(var d in g_sites)if(-1<b.uniqueTextValues.indexOf(g_sites[d].unencryptedUsername))return g_sites[d].unencryptedUsername},function(b,
c,d){b=[];for(var f in c.textFieldsByValue)(c=f.match(a))&&1===c.length&&b.push(f);if(1===b.length)return b[0]},function(a,b,c){for(var d in b.textFieldsByValue)if(a=b.textFieldsByValue[d].field,e(a.attributes.name,"user")||e(a.id,"user"))return d}],m=function(){var a=function(a,b,c){var d=c[b];"undefined"===typeof d?c[b]={field:a,count:1}:++d.count};return function(b){var c={},d={},f={};b.fields.forEach(function(b){"password"===b.type?a(b,b.value,c):(a(b,b.value,d),a(b,b.type,f))});return{passwordsByValue:c,
textFieldsByValue:d,textFieldsByType:f,uniqueTextValues:Object.keys(d),uniquePasswords:Object.keys(c)}}}(),e=function(b,a){if(b){a=[].concat(a);for(var c=0;c<a.length;++c)if(-1<b.indexOf(a[c]))return!0}return!1},r=function(b,a,c,d){for(var f=null,g=0;g<d.length&&!(f=d[g](b,a,c))&&!1!==f;++g);return f};return function(b,a){a.fields=a.fields||[];var c=m(a),e=!1,f=!a.generatedPassword;a.username||(a.username=r(a,c,b,g));a.password||(a.password=a.generatedPassword?a.generatedPassword:r(a,c,b,d));var k=
function(){if(a.username&&!a.createAccountForm)for(var b=0;b<a.fields.length;++b){var c=a.fields[b];if(c.value===a.username)return c}return null}();this.submitted=function(a){"boolean"===typeof a&&(f=a);return f};this.succeeded=function(a){"boolean"===typeof a&&(e=a);return e};this.getUsernameField=function(){return k};this.getUsername=function(){return a.username};this.getPassword=function(){return a.password};this.getFormData=function(){return a};this.getFields=function(){return a.fields.slice()};
this.getOriginalPassword=function(){return a.originalPassword};this.isChangePasswordForm=function(){return!0===a.passwordChangeForm};this.isCreateAccountForm=function(){return!0===a.createAccountForm};this.isBasicAuthentication=function(){return!0===a.basicAuthentication};this.shouldSaveFields=function(){return!this.isChangePasswordForm()&&!this.isCreateAccountForm()}}}(),e=function(a){this.tabID=a.tabID;this.domain=lp_gettld_url(a.tabURL);this.sites=[];this.username=this.usernameField=this.acccountsVersion=
null};e.prototype.getSites=function(){if(this.acccountsVersion!==g_local_accts_version){this.sites=[];var a=getsites(this.domain),c;for(c in a)this.sites.push(g_sites[c]);this.acccountsVersion=g_local_accts_version}return this.sites};e.prototype.getFields=function(){var a=[];this.passwordForm&&(a=this.passwordForm.getFields());var c=this.getUsernameField();c&&c.value===this.getUsername()&&0===a.filter(function(a){return a.name===c.name&&a.value===c.value}).length&&a.unshift(c);return a};e.prototype.getUsernameField=
function(){if(!this.usernameField)for(var a in h){var c=h[a];if(c.usernameField&&compare_tlds(c.domain,this.domain)){this.usernameField=c.usernameField;break}}return this.usernameField};e.prototype.setUsernameField=function(a){a&&(this.usernameField=a)};e.prototype.setUsername=function(a){a&&(this.username=a)};e.prototype.getUsername=function(){!this.username&&this.passwordForm&&(this.username=this.passwordForm.getUsername());if(!this.username)for(var a in h){var c=h[a];if(c.username&&compare_tlds(c.domain,
this.domain)){this.username=c.username;break}}return this.username};e.prototype.processPasswordSubmit=function(a,c){this.passwordForm=new p(this,a);this.setUsernameField(this.passwordForm.getUsernameField());this.setUsername(this.passwordForm.getUsername());if(a.generatedPassword)this.generatedPassword=a.generatedPassword;else LPPlatform.once(LPPlatform.onTransition,function(a){a:{switch(a.transitionType){case "auto_subframe":case "manual_subframe":a=!1;break a}a=-1<a.transitionQualifiers.indexOf("from_address_bar")||
-1<a.transitionQualifiers.indexOf("forward_back")}a&&this.clear()},this)};e.prototype.processTextSubmit=function(a,c){this.getUsernameField()&&a.fields.unshift(this.getUsernameField());var b=new p(this,a);this.setUsernameField(b.getUsernameField());this.setUsername(b.getUsername())};e.prototype.getMatchingSites=function(){var a=function(a,c){if(c&&-1<c.indexOf("@")){var b=c.split("@");return 2===b.length&&a===b[0]}return!1},c=function(b,c){var d;(d=b===c||a(b,c)||a(c,b))||(d=-1<c.indexOf("*")||-1<
c.indexOf(String.fromCharCode(8226))?b.length===c.length&&(b[0]===c[0]||b[b.length-1]===c[c.length-1]):!1);return d};return function(){var a=this,d=a.getSites();if(a.getUsername())d=d.filter(function(b){a:{var d=a.getUsername();if(c(b.unencryptedUsername,d))b=!0;else{if(b.fields&&0<b.fields.length)for(var g=0;g<b.fields.length;++g){var e=b.fields[g];switch(e.type){case "text":case "email":case "tel":if(c(lpmdec_acct(e.value,!0,b,g_shares),d)){b=!0;break a}}}b=!1}}return b});else{var g=a.passwordForm&&
a.passwordForm.getOriginalPassword();g&&(d=d.filter(function(a){return null!==n(a,g)}));0===d.length&&(d=a.getSites())}return d}}();e.prototype.shouldShowSiteNotification=function(){if(this.passwordForm&&this.passwordForm.succeeded())return this.passwordForm.isChangePasswordForm()?Preferences.get("showChangeNotificationBar"):Preferences.get("showSaveNotificationBar")};var x=function(){var a=function(a){var b="";a.forEach(function(a){b+=a.formname+"\t"+encodeURIComponent(a.name)+"\t"+encodeURIComponent(crypto_btoa(a.value))+
"\t"+encodeURIComponent(a.type)+"\n"});return bin2hex(b)};return function(c,b){if(0<b.length){c.fields=c.fields.concat(b);g_local_accts_version++;rewritelocalfile();var d={data:a(b),ref:url2hex(c.url),updatefields:1,aid:c.aid};c.sharedfolderid&&(d.sharedfolderid=c.sharedfolderid);c.postdata=(new PostParams(d)).toString();c.posturl=base_url+"gm_deliver.php";c.newvalues=b;updateFieldsFromSubmit(c.postdata,c)}}}(),t=function(a){return{name:a.attributes.name||a.id,type:a.type,value:a.value,formname:""}},
y=function(a,c){return c===a.unencryptedUsername?a.username:c===lpmdec_acct(a.password,!0,a,g_shares)?a.password:lpmenc_acct(c,!0,a,g_shares)};e.prototype.addFields=function(a){if(this.getUsername()){var c=this.getFields();a.forEach(function(a){if(a.fields){var b=[];c.forEach(function(c){var d=t(c);0===a.fields.filter(function(b){return b.name===d.name&&(!a.save_all||b.formname===c.formname)}).length&&b.push({otherfield:a.save_all,name:d.name,type:d.type,value:y(a,c.value),checked:!1,formname:a.save_all?
c.formname:"",urid:"0",otherlogin:"0",url:""})});x(a,b)}})}};e.prototype.getSiteNotificationData=function(a){if(this.passwordForm){var c={formSubmitted:this.passwordForm.submitted(),formSucceeded:this.passwordForm.succeeded()};if(this.shouldShowSiteNotification()){var b=this.passwordForm.getFormData(),d=this.getMatchingSites(),g=d.filter(function(a){return null!==n(a,this.passwordForm.getPassword())},this);if(0<g.length)return this.addFields(g),this.clear({force:!0}),{};c.matchingSites=d.map(function(a){return a.aid});
c.defaultData={url:this.passwordForm.shouldSaveFields()?b.url:hostof(b.url),name:this.domain,unencryptedUsername:this.getUsername(),group:g_nofolder_feature_enabled?"":siteCats[this.domain],basic_auth:this.passwordForm.isBasicAuthentication()?"1":"0",realm:b.realm};c.dialogData={password:this.passwordForm.getPassword()};c.sameDomain=compare_tlds(lp_gettld_url(this.passwordForm.getFormData().url),lp_gettld_url(a.tabURL));c.generatedPassword=this.generatedPassword===this.passwordForm.getPassword();
this.passwordForm.shouldSaveFields()&&0<this.getFields().length&&(c.dialogData.fields=this.getFields().map(t))}else this.clear();return c}return{}};e.prototype.getFormSubmissionTabState=function(){for(var a=this;a;){if(a.passwordForm)return a;a=a.previousTabState}return this};e.prototype.getUsernames=function(){return this.getSites().map(function(a){return a.unencryptedUsername})};e.prototype.getSiteNotification=function(){var a=function(a,c,g){var b=a.getUsernames();c.forEachWindow({each:function(c,
d){return c.LPContentScriptTools.findText({searches:b,callback:function(b){a.setUsername(b);d()}})},done:g})},c=function(b,c,g){var d=!1,e=LPTabs.get({tabID:b.tabID}),h=function(){if(b.passwordForm&&(b.passwordForm.succeeded()||b.passwordForm.succeeded(!d),b.passwordForm.succeeded()&&!b.passwordForm.getUsername()&&0<b.getSites().length)){a(b,e,g);return}g()};if(c)(c=e.getFrame(c.frameID))&&c.LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){d=a;h()});else if(b.passwordForm.getFormData().top)e.getTop().LPSiteNotification.formExists(b.passwordForm.getFormData(),
function(a){d=a;h()});else e.onFramesLoaded(function(){e.forEachFrame({each:function(a,c){return a.LPSiteNotification.formExists(b.passwordForm.getFormData(),function(a){d=d||a;c()})},done:h})})};return function(a,d){if(a.callback){var b=this.getFormSubmissionTabState(),e=function(){a.callback(b.getSiteNotificationData(d))};if(b.passwordForm&&b.passwordForm.getPassword())if(b.domain!==this.domain||b.passwordForm.isBasicAuthentication())b.passwordForm.succeeded(!0);else{c(b,a.source,e);return}e()}}}();
e.prototype.clear=function(a){var c=a&&a.force,b=!0;this.previousTabState&&(b=this.previousTabState.clear(a))&&delete this.previousTabState;this.passwordForm&&(this.passwordForm.getPassword()===this.generatedPassword&&(this.passwordForm.submitted(!1),b=!1),b||c)&&(delete this.passwordForm,delete this.generatedPassword);return b};e.prototype.processBasicAuthentication=function(a){this.passwordForm=new p(this,{basicAuthentication:!0,url:a.url,realm:a.realm,username:a.username,password:a.password})};
var u=function(a){if(!lploggedin)return!1;var c=lp_gettld_url(a.tabURL);if(LPContentScriptFeatures.new_save_site)return!hasNeverSave(a.tabURL,c)&&!lp_url_is_lastpass(a.tabURL)&&!lp_url_is_lastpassext(a.tabURL);a=IntroTutorial.getState();return a.enabled&&a.domain===c},l=function(a,c){if(a){if(u(a)){var b=h[a.tabID];if(!b||!compare_tlds(b.domain,lp_gettld_url(a.tabURL))){var d=h[a.tabID]=new e(a);d.previousTabState=b;b=d}c(b)}}else LPPlatform.getCurrentTab(function(a){l(a.tabDetails,c)})};return{getSiteNotification:function(a,
c){l(c,function(b){b.getSiteNotification(a,c)})},clear:function(a,c){l(c,function(b){b.clear(a)})},processPasswordSubmit:function(a,c){l(c,function(b){b.processPasswordSubmit(a.formData,c);b.getSiteNotification({callback:a.callback,source:c},c)})},processTextSubmit:function(a,c){l(c,function(b){b.processTextSubmit(a,c)})},processBasicAuthentication:function(a,c){l(c,function(b){b.processBasicAuthentication(a)})},getState:function(a,c){var b={enabled:u(c)};b.enabled?l(c,function(c){b.usernames=c.getUsernames();
b.formSubmittedFrame=c.passwordForm&&!c.passwordForm.getFormData().top;a(b)}):a(b)},setCopiedGeneratedPassword:function(a){q=a},getCopiedGeneratedPassword:function(a){a(q)}}}();
