function sendRequest(a){if(null!=a)if(a.cmd&&"popupfillinputget"!=a.cmd&&"popupfilliconnumber"!=a.cmd&&L("IF -> BG : cmd="+a.cmd),g_ischrome)try{chrome_runtime_sendMessage(a,function(){})}catch(c){}else g_issafari?safari.self.tab?safari.self.tab.dispatchMessage(a.cmd,a):safari.extension&&safari.extension.globalPage&&safari.extension.globalPage.contentWindow&&safari.extension.globalPage.contentWindow.message_handler({name:a.cmd,message:a,target:window}):g_isfirefoxsdk?(a.messagetype=a.cmd,send_message(a)):
g_iscasper&&"function"==typeof t_sendmsg&&t_sendmsg(a)}
var g_reference_url="",InfieldIcons={globe:"/images/Globe.png",profile:"/images/Profile.png",other:"/images/Other.png",mastercard:"/images/Mastercard.png",visa:"/images/Visa.png",amex:"/images/Amex.png",discover:"/images/Discover.png"},InfieldCommands=function(){function a(a){csTop.LPInfieldFrame.close(a)}return{closePopup:a,copyToClipboard:function(a,b){sendRequest({cmd:"copytoclipboard",g_data:a,action:b,source:"formv2"})},editSite:function(a){sendRequest({cmd:"editaid",aid:a,fromiframe:1})},fillUsernamePass:function(c){sendRequest({cmd:"autofillaid",
aid:c,from_iframe:!0,no_manualfill_on_saveall:!0,fromiframe:1});a("action")},copyUrl:function(a){sendRequest({cmd:"copyurl",aid:a,fromiframe:1})},copyUserName:function(a){sendRequest({cmd:"copyusername",aid:a,fromiframe:1})},copyPassword:function(a){sendRequest({cmd:"copypassword",aid:a,fromiframe:1,source:"formv2"})},editFormFill:function(c){sendRequest({cmd:"editprofile",ffid:c,fromiframe:1,source:"formv2"});a("action")},fillForm:function(c){sendRequest({cmd:"fillformffid",ffid:c,fromiframe:1,source:"formv2"});
a("action")},getGeneratePrefs:function(a){chrome_runtime_sendMessage({cmd:"popupfillgetgenerateprefs"},a)},writeAllPrefs:function(a,b){chrome_runtime_sendMessage({cmd:"popupfillsetgenerateprefs",prefstr:a,genpwstr:b})},fillGeneratedPassword:function(c,b){sendRequest({cmd:"fillgenpassword",password:c,saveOptions:b,nofill:1});a("action")},searchVault:function(a,b,e){chrome_runtime_sendMessage({cmd:"searchvault",searchQuery:a,searchType:b},e)},getInitialData:function(a){chrome_runtime_sendMessage({cmd:"getpopupfilldata"},
a)},sendLPImprove:function(a,b){sendRequest({cmd:"lpimprove",event:a,properties:b})}}}();
(function(a){var c=function(b,e,g){var c=this;c._onResizeCallback=g;b&&(c._triggerElement=b instanceof jQuery?b:a("#"+b),e?(c._triggerElement.click(function(a){c.show();c._setPosition(a)}),c._triggerElement.keypress(function(b){c.show();a(c._menuElement[0]).children().children()[0].focus();c._setPosition(b)})):(c._triggerElement.children().click(function(a){c.show()}),c._triggerElement.children().keypress(function(b){c.show();a(c._menuElement[0]).children().children()[0].focus()})))};c.prototype._setPosition=
function(b){b=a(b.currentTarget).offset();b.top+=20;b.left+=20;this._menuElement.offset(b)};c.prototype.show=function(){a(".dropdown").hide();a(".menuTriggered").removeClass("menuTriggered");var b=this;b._triggerElement.closest(".tile").addClass("menuTriggered");b._triggerElement.addClass("menuTriggered");this._menuElement&&this._menuElement.show(0,function(){b._onResizeCallback&&b._onResizeCallback(b._menuElement.height(),90)})};c.prototype.hide=function(a){this._triggerElement.closest(".tile").removeClass("menuTriggered");
this._triggerElement.removeClass("menuTriggered");this._triggerElement.blur();this._menuElement&&(this._menuElement.hide(a),this._onResizeCallback())};c.prototype.resetTimer=function(a){var c=this;c._menuElement&&(c._menuTimer=setTimeout(function(){c.hide()},a||1E3))};c.prototype.createMenu=function(c,e,g){var b=this;b._menuElement=a("<div></div>").attr("id",c+"Menu").addClass("dropdown").addClass(e).hide().hover(function(){b._triggerElement.closest(".tile");clearTimeout(b._menuTimer)},function(){b.resetTimer(300)}).append(b._createMenuItems(g));
return b._menuElement};c.prototype._createMenuItems=function(c){var b=this;b._menuItems=c;c=a("<ul></ul>").addClass("menuList");for(var g=0;g<b._menuItems.length;g++){var h=a("<li></li>").attr("data-viewId",b._menuItems[g].id).attr("tabindex","1").click(function(a){b.hide();b.select(a.currentTarget.getAttribute("data-viewId"),!0)}).focus(function(){clearTimeout(b._menuTimer)}).keypress(function(a){b.hide();b.select(a.currentTarget.getAttribute("data-viewId"),!0)}).append(a("<p></p>").text(b._menuItems[g].text));
c.append(h)}return c};c.prototype._findMenu=function(c){var b=a.grep(this._menuItems,function(a){return a.id===c});return b&&0<b.length?b[0]:null};c.prototype.select=function(a,c){var b=this._findMenu(a);b&&this._triggerElement&&this._triggerElement.find("p").text(b.selectedText);!0===c&&b&&b.action&&b.action()};return window.InfieldMenu=c})(jQuery);
var InfieldView=function(a){function c(){a.each(b,function(c,b){a("#"+b).hide()})}var b=[];return{init:function(a){Array.isArray(a)&&0<a.length&&(b=a,c())},show:function(e){-1!=b.indexOf(e)&&(c(),a("#"+e).show())}}}(jQuery),InfieldGeneratePassword=function(a){function c(){var c=lpCreatePass(a("#length").val(),a("#upper").prop("checked"),a("#lower").prop("checked"),a("#digits").prop("checked"),a("#special").prop("checked"),2,a("#ambig").prop("checked"),!0,a("#pronounceable").prop("checked"));a("#password").val(c).change()}
function b(){a("#generatedPasswordLength").text(a("#length").val());a("#sliderFill").width(a("#length").val()+"%")}var e={};return{init:function(g,h,k){a("#moreOptions, #hideOptions").click(function(){a("#advancedView").toggle();a("#generateAndFillView").toggle();a("#generateBtnContainer").toggle();a("#moreOptions").toggle();k&&k()});a("#length").on("input",function(){InfieldSearch.debounce(b(),500)});a(".pwgen").change(c);a("#generateBtn").click(c);a("#pronounceable").click(function(){a("#pronounceable").prop("checked")?
(a("#digits").prop("checked",!1),a("#digits").prop("disabled",!0),a("#special").prop("checked",!1),a("#special").prop("disabled",!0),a("#ambig").prop("checked",!1),a("#upper").prop("checked",!0),a("#lower").prop("checked",!0)):(a("#digits").prop("checked",!0),a("#digits").prop("disabled",!1),a("#special").prop("checked",!0),a("#special").prop("disabled",!1))});a("#ambig").click(function(){a("#ambig").prop("checked")&&(a("#pronounceable").prop("checked",!1),a("#digits").prop("disabled",!1),a("#special").prop("disabled",
!1))});a("#password").on("copy",function(){bg.LPTabState.setCopiedGeneratedPassword(this.value)}).LP_addGeneratePasswordMeter();a("#btnCopy").click(function(){var c=a("#password").val();g.copyToClipboard(c,"generatepassword");a("#btnCopy").hide();a("#copied").show();setTimeout(function(){a("#copied").hide();a("#btnCopy").show()},1E3);bg.LPTabState.setCopiedGeneratedPassword(c)});h=function(){g.fillGeneratedPassword(a("#password").val(),{pronounceable:a("#pronounceable").prop("checked"),length:a("#password").val().length,
expand:a("#moreOptions").is(":hidden"),uppercase:a("#upper").prop("checked"),lowercase:a("#lower").prop("checked"),numeric:a("#digits").prop("checked"),special:a("#special").prop("checked"),avoidAmbiguous:a("#ambig").prop("checked"),source:"formv2"});e[Object.keys(e).length]=a("#password").val();g.writeAllPrefs(JSON.stringify({generate_pronounceable:a("#pronounceable").prop("checked")?1:0,generate_length:a("#length").val(),generate_upper:a("#upper").prop("checked")?1:0,generate_lower:a("#lower").prop("checked")?
1:0,generate_digits:a("#digits").prop("checked")?1:0,generate_special:a("#special").prop("checked")?1:0,generate_ambig:a("#ambig").prop("checked")?1:0,generate_mindigits:2,generate_reqevery:0}),LPJSON.stringify(e))};a("#fillPasswordBtn").click(h);a("#generateAndFillBtn").click(h);a("#generateAndFillBtn").keypress(h);a("#advancedView").hide();a("#generateBtnContainer").hide()},setup:function(c){e=LPJSON.parse(c.genpwstr);c=JSON.parse(c.prefstr);a("#length").val(parseInt(c.generate_length));b();a("#upper").prop("checked",
parseInt(c.generate_upper)?!0:!1);a("#lower").prop("checked",parseInt(c.generate_lower)?!0:!1);a("#digits").prop("checked",parseInt(c.generate_digits)?!0:!1);a("#special").prop("checked",parseInt(c.generate_special)?!0:!1);a("#ambig").prop("checked",parseInt(c.generate_ambig)?!0:!1);a("#advancedView").hide();a("#generateAndFillView").show();parseInt(c.generate_pronounceable)?a("#pronounceable").click():a("#pronounceable").prop("pronounceable",!1);a("#password").val(lpCreatePass(a("#length").val(),
a("#upper").prop("checked"),a("#lower").prop("checked"),a("#digits").prop("checked"),a("#special").prop("checked"),2,a("#ambig").prop("checked"),!0,a("#pronounceable").prop("checked"))).change()},show:function(){a("#moreOptions").show();a("#generateBtnContainer").hide()},hide:function(){a("#moreOptions").hide();a("#generateBtnContainer").hide()}}}(jQuery),InfieldTiles=function(a,c,b,e){function g(b,d,e){var f="";if("formfills"===d)if(0==e.profiletype)b=InfieldIcons.profile;else switch(e.ccType){case "VISA":b=
InfieldIcons.visa;break;case "AMEX":b=InfieldIcons.amex;break;case "MC":b=InfieldIcons.mastercard;break;case "DISC":b=InfieldIcons.discover;break;default:b=InfieldIcons.other}else f="siteIcon",b&&e.aid&&b[e.aid]?b=b[e.aid]:(b=InfieldIcons.globe,c.sendLPImprove("iconnotfound",{domain:e.tld}));return{normalEl:a("<img/>").attr("src",b).addClass("defaultIcon "+f)}}function h(c){return a("<div></div>").addClass("col-2 no-left-gutter no-right-gutter").append(a("<div></div>").addClass("icon").append(c))}
function k(e,d){if(!d)return null;var g=null,f=a("<div></div>").addClass("col-8 text full-height"),k=a("<button></button>").attr("id",d.id+"btn").attr("tabindex","1").text(d.moreText);switch(e){case "formfills":f.append(a("<span></span>").text(d.name));d.description&&f.removeClass("full-height").append(a("<br/>")).append(a("<span></span>").addClass("small").text(d.description));break;case "sites":f.append(a("<span></span>").addClass("small").text(d.name)),d.description&&f.removeClass("full-height").append(a("<br/>")).append(a("<span></span>").text(d.description)),
g=new b(k,!0,m),a("#menuContainer").append(g.createMenu(d.id+"btn","tileDropdown",[{id:"copyPassword",text:"Copy password",action:function(){c.copyPassword(d.id)}},{id:"copyUsername",text:"Copy username",action:function(){c.copyUserName(d.id)}},{id:"copyURL",text:"Copy URL",action:function(){c.copyUrl(d.id)}},{id:"editSite",text:"Edit",action:function(){c.editSite(d.id)}}]))}d.moreHandler&&k.click(d.moreHandler);var g=a("<div></div>").addClass("col-2 no-right-gutter no-left-gutter pull-right more").append(k),
t=h([d.icons.normalEl]);t.click(d.clickHandler);f.click(d.clickHandler);var n=a("<div></div>").addClass("tile col-12").attr("id",d.id).attr("tabindex","1").append(a("<div></div>").addClass("row").append(t,f,g)).hover(function(){},function(){n.removeClass("triggered")});d.lastTile&&n.addClass("lastTile");k.focus(function(){n.addClass("triggered")}).blur(function(){n.removeClass("triggered")}).click(function(){n.addClass("menuTriggered");n.removeClass("triggered")});return n}var m;return{setup:function(b,
d,h,q,w,t){m=w;var f=[];a("#menuContainer").empty();a("#"+b).empty().append(a('<p class="italic"></p>').text(t));if(h){var l=a.map(h,function(a,c){return a});l.sort(function(a,c){return a});a.each(l,function(a,b){var h=!1;a+1===l.length&&(h=!0);(h=k(d,{id:"sites"===d?b.aid:b.ffid,name:"sites"===d?b.name:b.decprofilename,description:"sites"===d?b.unencryptedUsername:1==b.profiletype?b.formattedCCNum:null,icons:g(q,d,b),moreText:"sites"===d?e.translateString("More"):e.translateString("Edit"),moreHandler:"sites"===
d?null:function(){c.editFormFill(b.ffid)},clickHandler:"sites"===d?function(){c.fillUsernamePass(b.aid)}:function(){c.fillForm(b.ffid)},lastTile:h}))&&f.push(h)});0<f.length&&a("#"+b).empty().append(f)}return f.length}}}(jQuery,InfieldCommands,InfieldMenu,Strings),InfieldSearch=function(a){function c(a,b){var c;return function(){var d=this,e=arguments;clearTimeout(c);c=setTimeout(function(){c=null;a.apply(d,e)},b)}}function b(){m.fadeOut();k.show();k.animate({width:"360px"},250,function(){r.show();
d.fadeIn().focus()});q.addClass("searchBtnActive")}function e(){d.val("");d.hide();r.fadeOut();k.show();k.animate({width:"16px"},250,function(){f.fadeOut();m.fadeIn()});q.removeClass("searchBtnActive")}function g(){k.show()}function h(){d.hide();f.hide();r.hide();k.hide()}var k,m,f,d,r,q;return{init:function(g){k=a("#searchContainer");m=a("#currentTab");f=a("#searchBtnContainer");d=a("#inlineSearch");r=a("#searchCloseBtn");q=a("#searchBtn");d.hide();r.hide();k.show().css({width:"16px"});f.hide();
m.show();q.removeClass("searchBtnActive");a("#searchBtn").click(function(){b()}).keypress(function(){b()});a("#searchCloseBtn").click(function(){e();g("")}).keypress(function(){e();g("")});if(g){var h=c(function(b){g(a(b.currentTarget).val())},500);d.keyup(h)}},debounce:c,showIcon:g,hideIcon:h,display:function(a){a&&!0===a?g():h()}}}(jQuery),lpInfield=function(a,c,b,e,g,h,k,m,f){function d(b){x&&b&&b.position&&a.isNumeric(b.position)&&10<b.position&&370>b.position&&x.show("top",b.position)}function r(){u=
new b("currentTab",null,l);var c=u.createMenu("navigation",null,[{id:"sitesView",text:f.translateString("Log inlower"),selectedText:f.translateString("Log in as"),action:function(){p.start_type="sites";v(p)}},{id:"formFillView",text:f.translateString("Fill form"),selectedText:f.translateString("Fill form with"),action:function(){p.start_type="formfills";v(p)}},{id:"generatePassView",text:f.translateString("Generate password"),selectedText:f.translateString("Generate password"),action:function(){p.start_type=
"generate";v(p)}}]);a("#navigationPlaceholder").append(c)}function q(){a("#btnClose").click(function(){c.closePopup("close")});a("#btnClose").keypress(function(){c.closePopup("close")})}function w(a){var b=document.createElement("iframe");b.setAttribute("class","backgroundFrame");b.src="backgroundFrame.html";b.style.display="none";b.addEventListener("load",function(){b.contentWindow.LPPlatform.getBackgroundInterface({mainRequestFramework:!1,interfaceDefinition:Interfaces.InfieldPopupInterface,context:"infieldPopup",
callback:function(b){window.bg=b;a&&a()}});b.contentWindow.Topics.get(b.contentWindow.Topics.REQUEST_FRAMEWORK_INITIALIZED).subscribe(function(a,b){var c=parseInt(a.topFrameID);window.csTop=Interfaces.createInstance(Interfaces.ContentScriptInterface,{direct:!1,context:"infieldPopup",requestFunction:function(a){b.sendRequest({type:"contentScriptRequest",data:a,frameID:c})}});window.csTop.LPFrame.initializeRequestFramework(LPTools.getURLParams().dialogID)})});document.body.appendChild(b)}function t(a){c.searchVault(a,
p.start_type,n)}function n(a){var b=p.start_type;if(a&&(a=JSON.parse(a)))switch(b){case "sites":g.setup("sitesView",b,a.sites,a.bigicons,l,y);break;case "formfills":g.setup("formFillView",b,a.formfills,null,l,z)}}function l(b,c){var d=a(".infield-dialog").outerHeight()+20,e=a(".infield-dialog").outerWidth()+10;b&&a.isNumeric(b)&&(d+=b);c&&a.isNumeric(c)&&(e+=c);csTop.LPInfieldFrame.resizeFrame(d,e)}function v(b){if(b){p=b;if(b.start_type)switch(b.start_type){case "sites":if(b.sites){var d=JSON.parse(b.sites),
f=b.bigicons?JSON.parse(b.bigicons):null;b=g.setup("sitesView",b.start_type,d,f,l,A);u.select("sitesView");e.show("sitesView");h.display(2<b);k.hide()}break;case "formfills":b.formfills&&(d=JSON.parse(b.formfills),b=g.setup("formFillView",b.start_type,d,null,l,B),u.select("formFillView"),e.show("formFillView"),h.display(2<b),k.hide());break;case "generate":c.getGeneratePrefs(k.setup),u.select("generatePassView"),e.show("generatePassView"),h.display(!1),k.show()}csTop.LPInfieldFrame.positionFrame();
csTop.LPInfieldFrame.show();a(".infield-dialog").show()}else c.closePopup("close")}var u,p,x,A=f.translateString("No sites found for this web address. You can log in to this website to save your credentials"),y=f.translateString("No sites found matching your search."),B=f.translateString("No Form Fills saved. You can add one in your Vault."),z=f.translateString("No Form Fills found matching your search.");return{init:function(){document.addEventListener("DOMContentLoaded",function(){w(function(){f.translate(document.body);
x=new m({$parentEl:a(".infield-dialog")});d({position:360});q();e.init(["sitesView","formFillView","generatePassView"]);r();h.init(t);k.init(c,u,l);(new MutationObserver(function(){l()})).observe(a(".infield-dialog")[0],{subtree:!0,childList:!0});c.getInitialData(v);a("#currentTabText").focus()})})},setArrowPosition:d}}(jQuery,InfieldCommands,InfieldMenu,InfieldView,InfieldTiles,InfieldSearch,InfieldGeneratePassword,lpArrow,Strings);lpInfield&&lpInfield.init();
