LPServer=function(){var l=null,e=null,C=function(){var a=function(b,c){var d=b,f={},e;for(e in d){var k=d[e];if(null===k||void 0===k)k="";if("object"===typeof k)for(var h in k)k.hasOwnProperty(h)&&(f[e+"["+h+"]"]=k[h]);else f[e]=k}b=f;c=c||"";var d=[],g;for(g in b)f=b[g],"object"===typeof f?d=d.concat(a(f,g)):(c&&(g=c+"["+g+"]"),d.push(g+"="+encodeURIComponent(f)));return d};return function(b){return a(b).join("&")}}(),x=function(a){var b=new XMLHttpRequest,c=a.contentType||"application/x-www-form-urlencoded";
a.success&&(b.onload=function(){if(4===b.readyState)if(200===b.status)switch(a.dataType){case "xml":a.success(b.responseXML,b.responseText);break;case "json":var c=null;try{c=JSON.parse(b.responseText)}catch(k){}a.success(c,b.responseText);break;default:a.success(b.responseText)}else a.error&&a.error(b,b.statusText)});a.error&&(b.onerror=function(){a.error(b,b.statusText)});var d=function(){return"application/json"===c?JSON.stringify(a.data):C(a.data)},f=a.url;"GET"===a.type&&(f=d(),f=a.url+(0<f.length?
"?"+f:""));b.open(a.type||"GET",f,!0);"POST"===a.type?(b.setRequestHeader("Content-Type",c),a.beforeSend&&a.beforeSend(b,a),b.send(d())):(a.beforeSend&&a.beforeSend(b,a),b.send())},D=function(a,b){g.ajax({type:"POST",url:g.getBaseURL()+"getCSRFToken.php",success:function(b){l=b;a(l)},error:y(b)})},y=function(a){return function(b,c,d){a()}},m=function(a,b,c,d){h(a,b,c,d)||b.error&&b.error(c)},h=function(){var a=function(a,c,d,f){return a&&(a=a[d],"function"===typeof a)?(a(f,c),!0):!1};return function(b,
c,d,f){b=a(b,c,d,f);return b=a(c.callbacks,c,d,f)||b}}(),z=function(a,b){try{g.logException(a)}catch(c){}a instanceof n?b.error(a.message):b.error();if(LPServer.throwExceptions)throw a;},F=function(a,b){return function(c,d){try{if(!h(a,b,d)){if(null===c&&d&&"undefined"!==typeof DOMParser)try{c=(new DOMParser).parseFromString(d,"application/xml")}catch(f){}null===c?b.error("invalidxml"):E(c,a,b)}}catch(f){z(f,b)}}},p=function(a,b){var c=a.getElementsByTagName(b);return 0<c.length?c[0]:null},t=function(a,
b){var c=p(a,b);return c?c.textContent:""},E=function(a,b,c){var d=p(a,"result"),f=p(a,"ok"),e=p(a,"error"),g=p(a,"failed");if(d){var f=d.getAttribute("rc"),e=d.getAttribute("msg"),g=d.getAttribute("success"),l=d.getAttribute("ok");if(f){m(b,c,f,d);return}if(e){m(b,c,e,d);return}if(g){m(b,c,g,d);return}if(l){m(b,c,"ok");return}d=d.textContent.trim();if("ok"===d){h(b,c,"ok")||m(b,c,t(a,"status"));return}if("bad"===d){c.error(t(a,"message"));return}}else{if(f){m(b,c,"ok",f);return}if(e){h(b,c,e.getAttribute("cause"),
e)||m(b,c,e.getAttribute("message"),e);return}if(g){m(b,c,g.getAttribute("reason"),g);return}}"function"===typeof c.error&&c.error()},G=function(a,b){return function(c,d){try{if(null===c&&d)b.error("invalidjson");else{if(c.error){h(a,b,c.error,c)||b.error&&b.error(c.errortxt||c.error);return}if(c.hasOwnProperty("success")){if(c.success&&h(a,b,"success",c))return;if(!c.success){b.error&&b.error();return}}else if(c.res)if("success"===c.res){if(h(a,b,c.res,c))return}else{h(a,b,c.res,c)||b.error&&b.error(c.errortxt);
return}else if(h(a,b,c.reason,c)||h(a,b,c.status,c)||h(a,b,c.cmd,c))return}if(a&&"function"===typeof a["default"])a["default"](c,b);else"function"===typeof b.success&&b.success(c)}catch(f){z(f,b)}}},H=function(a,b){return function(c,d){var f;try{f=JSON.parse(c.responseText)}catch(L){b.error("invalidjson");return}h(a,b,f.code,f)||b.error(f.message)}},r=function(a){a.userSupplied=a.userSupplied||{};a.type=void 0===a.type?"POST":a.type;a.url=g.getBaseURL()+a.url;a.data=A(a.data,a.userSupplied.requestArgs);
"undefined"===typeof a.error&&a.userSupplied.error&&(a.error=y(a.userSupplied.error));a.data&&void 0===a.data.token&&(void 0===a.CSRFToken||a.CSRFToken)&&null===l?D(function(){g.ajax(a)},a.userSupplied.error):g.ajax(a)},u=function(a,b){var c={},d=b.userSupplied;"object"!==typeof d&&(d=b.userSupplied={});switch(typeof b.success){case "string":return c[b.success]=d.success,a(c,d);case "function":return c["default"]=b.success,a(c,d);default:if(b.callbacks||d.success||d.callbacks)return a(b.callbacks,
d)}return null},v=function(a,b){b.data&&void 0===b.data.token&&(void 0===b.CSRFToken||b.CSRFToken)&&(b.data.token=l)},B=function(a,b,c){c=c||[];for(var d in b){var f=a[d],e=b[d];if("object"===typeof e)B(f,e,c.concat(d));else if(typeof f!==e)throw c.push(d),"Extension is missing the following property: "+c.join(".")+" ("+e+")";}},w=function(a,b,c){a=a.getAttribute(b);return void 0===a?c:a},A=function(a){a=a||{};for(var b=1,c=arguments.length;b<c;++b){var d=arguments[b],e;for(e in d)a[e]=d[e]}return a},
q=function(a,b){return a?function(){var c=b.apply(window,arguments);a.apply(window,c||arguments)}:b},I={StringUtils:{translate:"function"},AES:{Encrypt:"function",Decrypt:"function",hex2bin:"function",bin2hex:"function"},enc:"function",dec:"function",RSAKey:"function",createRandomHexString:"function",parse_public_key:"function",parse_private_key:"function",enccbc:"function",make_lp_key_iterations:"function",make_lp_hash_iterations:"function",get_random_password:"function"},J={RSAKey:!0},g={ajax:x,
translate:function(){return e.StringUtils.translate.apply(e.StringUtils,arguments)},logException:function(){},hex2bin:function(){return e.AES.hex2bin.apply(e.AES,arguments)},bin2hex:function(){return e.AES.bin2hex.apply(e.AES,arguments)},encryptAES:function(a,b){return 0<a.length?e.AES.Encrypt({pass:b,data:a,b64:!0,bits:256}):a},decryptAES:function(a,b){return e.AES.Decrypt({pass:b,data:a,b64:!0,bits:256})},encrypt:function(a,b){return e.enc(a,b)},decrypt:function(a,b){try{return e.dec(a,b)}catch(c){return""}},
createRandomHexString:function(){return e.createRandomHexString.apply(e,arguments)},parsePublicKey:function(){return e.parse_public_key.apply(e,arguments)},parsePrivateKey:function(a,b){b=b||e.rsaprivatekeyhex;if(!b)throw"rsaprivatekeyhex required for this action.";return e.parse_private_key(a,b)},extractPrivateKey:function(a,b){return e.rsa_extract_privatekey(a,b)},encryptCBC:function(){return e.enccbc.apply(e,arguments)},makeKey:function(){return e.make_lp_key_iterations.apply(e,arguments)},makeHash:function(){return e.make_lp_hash_iterations.apply(e,
arguments)},makeRandomPassword:function(){return e.get_random_password.apply(e,arguments)},getBaseURL:function(){return e.base_url||""},getLocalKey:function(){return e.g_local_key},setLocalKey:function(a){e.g_local_key=a}},n=function(a){this.message=a;this.stack=Error().stack};n.prototype=Object.create(Error.prototype);n.prototype.name="ClientException";n.prototype.constructor=n;var K=function(){var a=function(a){a.setRequestHeader("X-CSRF-TOKEN",l)};return{jsonRequest:function(b){b.dataType="json";
b.contentType="application/json";b.beforeSend=q(b.beforeSend,a);b.error=u(H,b);r(b)}}}();return{ajax:x,getRecordsFromResponse:function(a,b,c){for(var d=[],e=0;e<c;++e)d.push(w(a,b+e));return d},jsonRequest:function(a){a.dataType="json";a.beforeSend=q(a.beforeSend,v);a.success=u(G,a);r(a)},xmlRequest:function(a){a.dataType="xml";a.beforeSend=q(a.beforeSend,v);a.success=u(F,a);r(a)},textRequest:function(a){a.dataType="text";a.beforeSend=q(a.beforeSend,v);r(a)},initialize:function(a,b){B(a,I);for(var c in b)g[c]=
b[c];for(var d in J)g[d]=a[d];e=a},ext:g,getNodes:function(a,b){return a.getElementsByTagName(b)},getNode:p,getNodeText:t,getAttr:w,getAttrInt:function(a,b,c){a=parseInt(w(a,b,c));return isNaN(a)?c:a},extend:A,extendCallback:q,ClientException:n,clearCSRFToken:function(){l=null},callback:function(a,b){a.callbacks&&"function"===typeof a.callbacks[b]&&a.callbacks[b].apply(window,Array.prototype.slice.call(arguments,2))},lmiapi:K}}();
