var gLastLoginState=0,gAccts_version=-1,gCurr_username="",gTimerId=null,gIconsLength=0,gLastSearch="",gIdentity="",gSearchWhileType=!0,gTreeHeightOffset=147,gPollInterval=500,gHidePreferences=!1,gLocalBaseUrl="",g_hideprofilecopy=1,g_hideidentcopy=1,g_localvault=1,g_showrows=1,g_autoselectcredmontab=0,g_partnername="",g_hideenterprisetab=!1,g_CNTsearch_it=0,g_CNTsearch_string_tokenize=0,g_CNTinit_vault=0,g_CNTpopulate=0,g_CNTsearch_tree=0,g_CNTclear_tree=0,event_handlers={},event_handlers_onmouseover=
{},event_handlers_onmouseout={},event_handlers_onclick={},styles={},VIEWS={TREE:0,GRID:1},g_view=VIEWS.TREE,g_groupidmap=[],g_idgroupmap=[],g_dolegacy=null;function getpartnerurl(a){""!=g_partnername&&(a+=(0<=a.indexOf("?")?"&":"?")+"partnername="+encodeURIComponent(g_partnername));return a}function fix_group(a){a==g_xlat_none&&(a="");return a}
function onLoad(a,b){try{if("undefined"!=typeof g_is_safari&&"undefined"==typeof LPFromWebsite)50>a?(a++,setTimeout(function(){onLoad(a)},25)):document.location.href=document.location.href;else if("undefined"!=typeof g_is_safari||b)if("function"!=typeof getBG||"undefined"==typeof getBG()||null==getBG())setTimeout(function(){onLoad()},50);else{var c=getBG();g_urlprefix=c.base_url;var f=document.createElement("base");f.href=g_urlprefix;document.head.appendChild(f);0<document.location.href.lastIndexOf("/")&&
(gLocalBaseUrl=document.location.href.substr(0,document.location.href.lastIndexOf("/")+1));c.LPISLOC&&(document.getElementById("accountsettingscontainer").style.display="none");c.g_hideidentities&&(document.getElementById("identitycontainer").style.display="none");c.g_hideseccheck&&(document.getElementById("seccheckcontainer").style.display="none");refresh_legacy_link(document);sr(document,"submit","value","Searchproper");document.getElementById("q").setAttribute("placeholder",gs("Search Vault"));
LP_decimate_children(document.getElementById("lpusername"));var g=document.createElement("b"),l=document.createElement("a");l.setAttribute("href","");l.id="lpusernamelink";set_innertext(l,gs("Login"));g.appendChild(l);document.getElementById("lpusername").appendChild(g);onResize();inittabs();setusernametext(c.g_username);g_view==VIEWS.GRID&&grid_init_vault_search();$("#gridview").click(function(a){g_view=VIEWS.GRID;populate(gLastSearch);showView()});$("#listview").click(function(a){g_view=VIEWS.TREE;
populate(gLastSearch);showView()});gTimerId=setInterval(function(){checkLoggedInHome()},gPollInterval);var k=getcolvisibility("usernamecol"),h=getcolvisibility("ltnamecol");document.getElementById("usercol").className=k?"usercolvisible":"usercolhidden";document.getElementById("ltcol").className=h?"ltcolvisible":"ltcolhidden";document.getElementById("ltcol").style.paddingRight=k?"calc(5% + 20px)":"5%";create_combo("grpsel",[]);document.getElementById("grpsel_combo").style.height="150px";document.getElementById("grpsel_combo").style.overflow=
"auto";document.getElementById("q").focus();c&&convert_object_to_array(c.g_identities).length?showhide_ident_actions(I_SHOW):showhide_ident_actions(I_HIDE);document.getElementById("addsecurenote").style.display=c.g_hidenotes?"none":"block";document.getElementById("lpimport").style.display=c.g_hideimport?"none":"block";document.getElementById("lpexport").style.display=c.g_hideexport?"none":"block";g_xlat_runame=gs("recently usedlower");g_xlat_pendingname=gs("(New Pending Share Offers)");g_xlat_favorites=
gs("favorites");g_xlat_edit=gs("Edit");g_xlat_delete=gs("Delete");g_xlat_share=gs("Share");g_xlat_none=gs("(none)");g_xlat_chpw=gs("Change Password");getBG().VaultToggle.supportsVault4_0()||(document.getElementById("vaultToggle").style.display="none")}else get_data("vault",function(){onLoad(a,!0)})}catch(q){alert("homelocal2 onLoad:"+q)}}function onUnLoad(){gTimerId&&(clearInterval(gTimerId),gTimerId=null);saveGroupState()}
function onResize(){for(var a=0;a<tabnames.length;a++)document.getElementById(tabnames[a])&&(document.getElementById(tabnames[a]).style.height=document.body.clientHeight-gTreeHeightOffset+20+"px");document.getElementById("thetree")&&(document.getElementById("thetree").style.height=document.body.clientHeight-gTreeHeightOffset-14+"px");document.getElementById("thegrid")&&(document.getElementById("thegrid").style.height=document.body.clientHeight-gTreeHeightOffset+20+"px")}
function checkLoggedInHome(a){try{var b=getBG(),c=b.lploggedin;if(("undefined"!=typeof g_issafari&&g_issafari||"undefined"!=typeof g_isopera&&g_isopera||"undefined"!=typeof g_ismaxthon&&g_ismaxthon||"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk)&&!a)b.update_state("vault");else{a="";c&&(a=b.g_username,refresh_ident_actions());if(c!=gLastLoginState||a!=gCurr_username)if(g_cachedOpenGroups=null,c)window_load_loggedin(a);else{try{var f={"static":"{}"};g_view==VIEWS.TREE?$(function(){$("#thetree").tree({data:{type:"json",
opts:f}})}):($("#thegrid").scrollTop(),$("#thegrid").empty())}catch(l){}finish_vault_search();g_lastnodeid=g_rootnodeid=null;window_load_loggedoff();update_identity_popup()}gLastLoginState=c;g_username=lpusername=gCurr_username=a;if(gLastLoginState){var g=b.g_local_accts_version;if(g>gAccts_version||b.IsIconsUpdated(gIconsLength)||b.g_identity!=gIdentity)window_load_loggedin(a),finish_vault_search(),gAccts_version=g,massoperation=!0,populateNewData(gLastSearch),massoperation=!1,saveGroupState(),populateff(gLastSearch),
populateident(gLastSearch),update_identity_popup(),setusernametext(a),showads()}}}catch(l){alert("checkLoggedInHome:"+l)}}
function setusernametext(a){var b=getBG(),c=document.getElementById("lplogoff");if(b.lploggedin){c.style.display="block";var c="",f;for(f in b.g_identities)if(b.g_identities.hasOwnProperty(f)&&b.g_identity==b.g_identities[f].iid){c=b.g_identities[f].deciname;break}""==c?set_innertext(document.getElementById("lpusername"),of(a)):set_innertext(document.getElementById("lpusername"),of(a+" ("+c+")"))}else LP_decimate_children(document.getElementById("lpusername")),a=document.createElement("b"),b=document.createElement("a"),
b.setAttribute("href",""),b.id="lpusernamelink",set_innertext(b,gs("Login")),a.appendChild(b),document.getElementById("lpusername").appendChild(a),c&&(c.style.display="none")}
function window_load_loggedin(a){var b=getBG();document.getElementById("identity").disabled=0;document.getElementById("enterpriseaction").style.display=!g_hideenterprisetab&&getBG().g_iscompanyadmin?"list-item":"none";document.getElementById("enterprise").style.display=g_hideenterprisetab||"1"==getBG().g_enterpriseuser?"none":"table-cell";"1"==b.g_enterpriseuser&&(document.getElementById("lpfriendemail").style.display=document.getElementById("lpgift").style.display="none");document.getElementById("addsharedfolder").style.display=
b.g_folder_sharing_enabled?"list-item":"none";document.getElementById("shares").style.display=b.g_hidesharing||!b.g_folder_sharing_enabled?"none":"table-cell";document.getElementById("credmon").style.display="1"==getBG().g_showcredmon?"table-cell":"none";document.getElementById("linkpersonal").style.display="1"!=getBG().g_enterpriseuser||g_hideenterprisetab||""!=get_personal_linked()?"none":"list-item";document.getElementById("removepersonal").style.display="1"!=getBG().g_enterpriseuser||g_hideenterprisetab||
""==get_personal_linked()?"none":"list-item";setusernametext(a);"undefined"!=typeof getBG().get_securityChallengeScore&&getBG().get_securityChallengeScore(function(a){var b=!1,c;for(c in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(c)){b=!0;break}a&&b&&(document.getElementById("securitycheckscore").style.display="block",document.getElementById("securitycheckscore").style.color="#fff",document.getElementById("securitycheckscore").style.backgroundColor=getscorecolor(a),set_innertext(document.getElementById("securitycheckscore"),
parseInt(a)+"%"),document.getElementById("securitycheckscore").style.display="inline")});refresh_legacy_link(document);g_local_key=getBG().g_local_key;g_key_iterations=getBG().get_key_iterations(a)}
function showads(){getBG().lploggedin&&getBG().g_premium_exp<lp_get_local_timestamp()&&"1"!=getBG().g_enterpriseuser&&-1==document.location.href.indexOf("cmd=video")?("none"==getComputedStyle(document.getElementById("adframe")).display&&(document.getElementById("adframe").style.display="block",document.getElementById("rightside").style.display="block",document.getElementById("adframe").setAttribute("src",getpartnerurl(g_urlprefix+"ads.php?nobr=1&noga=1&rand="+Math.floor(1E3*Math.random())))),document.getElementById("friend").style.display=
"block"):(document.getElementById("adframe").style.display="none",document.getElementById("rightside").style.display="none",document.getElementById("friend").style.display="none")}
function window_load_loggedoff(){gAccts_version=-1;gIconsLength=0;g_local_key=null;LP_decimate_children(document.getElementById("lpusername"));var a=document.createElement("b"),b=document.createElement("a");b.setAttribute("href","");b.id="lpusernamelink";set_innertext(b,gs("Login"));a.appendChild(b);document.getElementById("lpusername").appendChild(a);document.getElementById("q").value="";document.getElementById("credmon").style.display="none";document.getElementById("adframe").style.display="none";
document.getElementById("rightside").style.display="none";document.getElementById("friend").style.display="none";document.getElementById("enterpriseaction").style.display="none";document.getElementById("enterprise").style.display=g_hideenterprisetab?"none":"table-cell";document.getElementById("addsharedfolder").style.display="none";document.getElementById("linkpersonal").style.display="none";document.getElementById("removepersonal").style.display="none";for(a=0;a<tabnames.length;a++)"treepane"!=tabnames[a]&&
cleartab(tabnames[a]);setusernametext(getBG().g_username);document.getElementById("securitycheckscore").style.display="none";refresh_legacy_link(document)}
function populateNewData(a){var b=!1,c;for(c in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(c)){b=!0;break}if(!b)for(c in getBG().g_securenotes)if(getBG().g_securenotes.hasOwnProperty(c)){b=!0;break}var f=!1;for(c in getBG().g_pendings)if(getBG().g_pendings.hasOwnProperty(c)){f=!0;break}b||f?(document.getElementById("sitesiframe")&&(b=document.getElementById("treepane"),b.removeChild(document.getElementById("sitesiframe")),g_view==VIEWS.TREE?document.getElementById("thetree").style.display=
"block":document.getElementById("thegrid").style.display="block"),showView(),g_view==VIEWS.GRID&&grid_init_vault_search(),g_view!=VIEWS.GRID&&populate(a,!0),SearchTree(0,!0,!0)):document.getElementById("sitesiframe")||(b=document.getElementById("treepane"),a=document.createElement("iframe"),a.id="sitesiframe",a.className="overviewiframe",a.src=getpartnerurl("sites_overview.php?version="+encodeURIComponent(lpversion)),b.appendChild(a),document.getElementById("thetree").style.display="none",document.getElementById("thegrid").style.display=
"none")}function showView(){g_view==VIEWS.TREE?($("#thetree").show(),$("#headerli").show(),$("#thegrid").hide()):($("#thetree").hide(),$("#headerli").hide(),$("#thegrid").show())}function isSafariNative(){return"undefined"!=typeof LPFromWebsite&&("undefined"==typeof g_issafari||!g_issafari)}
function update_identity_popup(){for(var a=getBG(),b=document.getElementById("identity");b.length;)b.remove(0);var c=document.createElement("option");c.text=gs("All");c.value="";""==a.g_identity&&(c.selected=1);b.appendChild(c);var f=0,g;for(g in a.g_identities)a.g_identities.hasOwnProperty(g)&&(c=document.createElement("option"),c.text=a.g_identities[g].deciname,c.value=a.g_identities[g].iid,a.g_identity==a.g_identities[g].iid&&(c.selected=1),b.appendChild(c),f++);0<f&&!getBG().g_hideidentities?
document.getElementById("identitycontainer").style.display="block":document.getElementById("identitycontainer").style.display="none"}
function search_matches(a,b){var c=getBG(),c=c.g_prompts.edit_sn_prompt?!1:c.get_searchNotesPref(),f=getBG().g_sites[a];if("undefined"==typeof f&&(f=getBG().g_securenotes[a],"undefined"==typeof f&&(0==a.indexOf("app")&&(a=a.substring(3)),f=getBG().g_applications[a],"undefined"==typeof f&&(f=getBG().g_pendings[a],"undefined"==typeof f)))){var g=getgroupnamefromid(a);if(g)for(var l in getBG().g_sites)if(getBG().g_sites.hasOwnProperty(l)&&"undefined"!=typeof getBG().g_sites[l]&&"http://group"==getBG().g_sites[l].url&&
getBG().g_sites[l].group==g){f=getBG().g_sites[l];break}if("undefined"==typeof f)return!1}return matches(f,b,c)}var g_all_li=[],g_search_array={};function init_vault_search(){g_all_li=$("#thetree").find("li");g_CNTinit_vault++;var a=getBG(),a=a.g_prompts.edit_sn_prompt?!1:a.get_searchNotesPref();g_search_array=sites_tokenize(g_all_li,a)}function finish_vault_search(){lastqstr=g_search_array=g_all_li=null}
function sites_tokenize(a,b){for(var c={},f=0;f<a.length;f++){var g=a[f].id,l="id"+g,k="",h=getBG().g_sites[g];if("undefined"==typeof h&&(h=getBG().g_securenotes[g],"undefined"==typeof h&&(0==g.indexOf("app")&&(g=g.substring(3)),h=getBG().g_applications[g],"undefined"==typeof h&&(h=getBG().g_pendings[g],"undefined"==typeof h))))if(g=getgroupnamefromid(g))k=g;else if("undefined"==typeof h)continue;k?(h=k.toLowerCase(),c[l]=h):"undefined"!=typeof h&&(k=[],k.push(h.name),k.push(h.group),"http://group"!=
h.url&&"http://sn"!=h.url&&k.push(h.url),h.unencryptedUsername&&k.push(h.unencryptedUsername),is_application(h)&&(k.push(h.appname),k.push(getusernamefromacct(h))),b&&"undefined"!=typeof h.extra&&0<h.extra.length&&("undefined"==typeof h.url||"http://group"!=h.url)&&!h.pwprotect&&((g=getBG().lpmdec_acct(h.extra,!0,h,getBG().g_shares))&&0!=g.length||console.log("searchinnotes: site aid="+h.aid+" FAILED TO DECRYPT"),k.push(g)),h=k.join(" "),h=h.toLowerCase(),c[l]=h)}return c}
function search_string_tokenize(a){var b=[];g_CNTsearch_string_tokenize++;if(!a)return b;if(-1==a.indexOf('"'))b=a.split(/\s+/);else{a=a.split('"');for(var c=0;c<a.length;c++)if(c%2)b.push(a[c]);else{var f;f=a[c].split(/\s+/);for(var g=0;g<f.length;g++)f[g]=f[g].replace(/^\s+/,""),f[g]=f[g].replace(/\s+$/,""),0<f[g].length&&b.push(f[g])}}return b}
function search_it(a,b){g_CNTsearch_it++;var c="id"+a;"string"==typeof b&&(b=[b]);for(var f=1,g=0;g<b.length;g++)if(!g_search_array[c]||-1==g_search_array[c].indexOf(b[g])){f=0;break}return f}var populate_done=!1;
function populate(a,b){try{var c=getBG();g_CNTpopulate++;c.g_prompts.edit_sn_prompt||c.get_searchNotesPref();var f=$("#q").val(),g=0;a!=f&&($("#q").val(a),f=a,g=0);gLastSearch=a;gIconsLength=c.g_icons_length;gIdentity=c.g_identity;var l=[],k=""!=a;g_view==VIEWS.GRID&&k&&(l=search_string_tokenize(a));var f=[],h=[],q=[],r=[],y=[],m=[c.g_sites,c.g_securenotes],A;for(A in m)if(m.hasOwnProperty(A)){var u=m[A],p;for(p in u)if(u.hasOwnProperty(p)&&c.check_ident_aid(p)){var w=u[p];if(!(g_view==VIEWS.GRID&&
k&&0<l.length)||search_it(p,l)){for(var n=""!=w.group?w.group:"http://sn"==w.url?gs("Secure Notes"):g_xlat_none,n="_"+n;"\\"==n[0];)n=n.substr(1);"undefined"==typeof f[n]&&(f[n]=[],h[h.length]=n,q[n]="undefined"==typeof w.aid?null:w.aid);f[n][f[n].length]=w;y[y.length]=w;"1"==w.fav&&(r[r.length]=w)}}}for(p in c.g_applications)c.g_applications.hasOwnProperty(p)&&c.check_ident_appaid(p)&&(w=c.g_applications[p],g_view==VIEWS.GRID&&k&&0<l.length&&!search_it(p,l)||(n=""!=w.group?w.group:g_xlat_none,n=
"_"+n,"undefined"==typeof f[n]&&(f[n]=[],h[h.length]=n,q[n]="undefined"==typeof w.aid?null:w.aid),f[n][f[n].length]=w,y[y.length]=w,"1"==w.fav&&(r[r.length]=w)));var m=0,v;for(v in c.g_pendings)c.g_pendings.hasOwnProperty(v)&&(++m,w=c.g_pendings[v],""==a&&("undefined"==typeof f[g_xlat_pendingname]&&(f[g_xlat_pendingname]=[],h[h.length]=g_xlat_pendingname,q[g_xlat_pendingname]=null),f[g_xlat_pendingname][f[g_xlat_pendingname].length]=w));var I=h.length;h.sort(function(a,b){return"_Apps assigned to me"==
a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});y.sort(function(a,b){return a.last_touch>b.last_touch?1:-1});var w=[],B=c.getClearRecentTime(),C=c.getRecentCount();if(""==a)for(v=0;w.length<C&&v<y.length;v++)"http://group"!=y[y.length-v-1].url&&(y[y.length-v-1].last_touch<B||(w[w.length]=y[y.length-v-1]));w.length&&(h.unshift(g_xlat_runame),f[g_xlat_runame]=w);r.length&&(h.unshift(g_xlat_favorites),f[g_xlat_favorites]=r);B=[];""==a&&(B=getOpenedGroups());if(g_view==VIEWS.GRID)$("#thegrid").scrollTop(),
$("#thegrid").empty(),createTile(h,f,B,a),setupTileEvents();else{var D=[],C=[];resetgroupnames();event_handlers={};event_handlers_onmouseover={};event_handlers_onmouseout={};event_handlers_onclick={};styles={};for(v=0;v<h.length;v++){r=!1;if(""!=a||"undefined"!=typeof B[h[v]]||1==I&&v==h.length-1)r=!0;"undefined"!=typeof h[v]&&addGroup(c,f,D,C,h[v],r,!1,B,"undefined"==typeof q[h[v]]?null:q[h[v]])}g_tree&&"undefined"!=typeof g_tree?($.tree.focused().settings.data.opts["static"]=D,$.tree.focused().refresh()):
$(function(){var a={};a["static"]=D;var b={beforedelete:lpbeforedelete,beforemove:lpbeforemove,onmove:lponmove,check_move:lpcheck_move,onselect:lponselect};populate_done||(b.onrgtclk=lponrgtclk,populate_done=!0);$("#thetree").tree({callback:b,data:{type:"json",opts:a},rules:{multiple:"ctrl",drag_copy:!1,use_max_children:!1,use_max_depth:!1},plugins:{hotkeys:{functions:{"return":function(){var a=$.tree.focused().selected;a&&1==a.length&&(isNumber(a[0].id)||is_application(a[0].id))&&ls(a[0].id)}}}}})});
$(".shareimggroup").click(function(){var a=$(this).closest("li").get();a.length&&(a=getgroupnamefromid(a[0].id),0==a.indexOf("_")&&(a=a.substring(1)),0==a.indexOf("Shared-")?manageSharedFolder(a):shareFolder(a))});$(".toolsimg").click(function(){var a=$(this).closest("li").get();if(a.length){var a=a[0],b=getgroupnamefromid(a.id);0==b.indexOf("_")&&(b=b.substring(1));openGroupMenu(a,b,t,event)}});$(".folder").mouseover(function(){sv(null,this)});$(".folder").mouseout(function(){hv(null,this)})}}catch(x){if("undefined"==
typeof LPFromWebsite||"function"!=typeof LPFromWebsite.ipad){if(0<=x.message.indexOf("atob")&&-1==document.location.href.indexOf("retry")){document.location.href+="?retry=1";return}alert("populate_error:"+x)}}update_identity_popup();g_view!=VIEWS.GRID&&init_vault_search();a&&""!=a&&SearchTree(g,b);for(v in event_handlers)document.getElementById(v)&&(document.getElementById(v).onclick=event_handlers[v]);for(v in event_handlers_onmouseover)for(var c=document.getElementsByName(v),z=0;z<c.length;z++)c[z].onmouseover=
event_handlers_onmouseover[v];for(v in event_handlers_onmouseout)for(c=document.getElementsByName(v),z=0;z<c.length;z++)c[z].onmouseout=event_handlers_onmouseout[v];for(v in event_handlers_onclick)for(c=document.getElementsByName(v),z=0;z<c.length;z++)c[z].onclick=event_handlers_onclick[v];for(v in styles)if(c=document.getElementById(v))for(z in styles[v])c.style[z]=styles[v][z]}
function getSubfolders(a,b,c){var f="_"+gs("(none)"),g=""==a?a:a+"\\",l;for(l in b)0!=l.indexOf(g)||-1!=l.substring(g.length).indexOf("\\")||""==a&&l==f||(b=l.substring(g.length),-1!=b.indexOf("\\")&&(b=b.substring(0,b.indexOf("\\"))),0==b.indexOf("_")&&(b=b.substring(1)),-1==jQuery.inArray(b,c)&&c.push(b));return c}
function lpbeforedelete(a,b){var c=getBG();if(1<($.tree.focused().selected_arr&&$.tree.focused().selected_arr.length)){for(var f="",g=[],l=0;l<$.tree.focused().selected_arr.length;l++){var k=getmoveid($.tree.focused().selected_arr[l]);k&&""!=k&&(f+=(""!=f?",":"")+k,g[g.length]=$.tree.focused().selected_arr[l])}c.deleteAid(f,window,!1,!1,function(){for(var a=0;a<g.length;a++)$.tree.focused().cut(g[a])});return!1}f=!1;is_application(a.id)||isNumber(a.id)?f=c.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)}):
(f=getgroupnamefromid(a.id),f=c.deleteGroup(fix_group(f),window,function(){$.tree.focused().cut(a)}));return f}
function lpbeforemove(a,b,c,f){getBG().lpevent("v_dnd");c=b;for(b=0;c&&""==c.attr("id")&&100>b;)c=c.parent(),b++;if(99<b||!c)return!1;var g=c.attr("id");g.match(/launch_(nor|fav|rec)_\d+/)&&(g=g.substr(11));g.match(/accept2_(nor|fav|rec)_\d+/)&&(g=g.substr(12));b="";f=getBG();if(is_application(g)||isNumber(g)){is_application(g)?(f=[f.g_applications],g=get_appaid(g)):f=[f.g_sites,f.g_securenotes];for(var l in f)if(f.hasOwnProperty(l)){var k=f[l],h;for(h in k)if(k.hasOwnProperty(h)){var q=k[h];if(q.aid==
g){if("1"==q.fav){k=c.parent();for(b=0;k&&""==k.attr("id")&&100>b;)k=k.parent(),b++;if(99>b&&k&&k.attr("id")==g_xlat_favorites){b=g_xlat_favorites;break}}b=q.group;break}}}}else b=getgroupnamefromid(g);if(""!=b&&b!=g_xlat_runame&&b!=g_xlat_pendingname){l=$.tree.focused().selected_arr;h="";for(c=0;c<l.length;c++)if(is_application(getmoveid(l[c]))||isNumber(getmoveid(l[c])))h+=(""==h?"":",")+getmoveid(l[c]);0==h.length&&(h=a.attr("id"));0!=h.length&&getBG().moveSelectedToGroup(b,h);return!1}}
function lponmove(a,b,c,f,g){}function lpcheck_move(a,b,c,f){return 1<$.tree.focused().selected_arr.length?!0:!a||""==a.attr("id")||is_application(a.attr("id"))||isNumber(a.attr("id"))?!0:!1}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}var g_groups={},g_groupindex=2E5,g_groupid={},g_groupnames={};function getgroupnamefromid(a,b){var c=g_view==VIEWS.GRID?g_idgroupmap:g_groups;if("undefined"==typeof c[a])return a;c=c[a];b||0!=c.indexOf("_")||(c=c.substring(1));return c}
function getrawgroupid(a){return"undefined"==typeof g_groupid[a]||null==g_groupid[a]?null:g_groupid[a]}function resetgroupnames(){g_groups={};g_groupindex=2E5;g_groupid={};g_groupnames={}}function getgroupid(a,b){var c="LpGrOuP"+g_groupindex;g_groups[c]=a;g_groupnames[a]=c;g_groupid[c]=b;++g_groupindex;return"LpGrOuP"+(g_groupindex-1)}function getgroupidfromname(a){return"undefined"==typeof g_groupnames[a]||null==g_groupnames[a]?null:g_groupnames[a]}var div_ids={};
function get_div_id(){for(;;){var a="div"+Math.floor(1E9*Math.random()+1);if("undefined"==typeof div_ids[a])return div_ids[a]=!0,a}}var g_rootnodeid=null,g_lastnodeid=null;
function addGroup(a,b,c,f,g,l,k,h,q){var r="",y=g.indexOf("Shared-");if(g===g_xlat_favorites)r=" favorite";else if(g===g_xlat_runame)r=" recent";else if(0===y||1===y)r=" shared";for(;"\\"==g[0];)g=g.substr(1);for(var m=g.match(/^([^\\]*)\\(.*)$/),A=null!=m,u="",y=0;m&&!k;){var p=m[1],w=m[2],u=u+((""!=u?"\\":"")+p);"undefined"==typeof f[u]&&addGroup(a,b,c,f,u,l||"undefined"!=typeof h[u],!0,h,q);y++;m=w.match(/^([^\\]*)\\(.*)$/)}u=(""==u?"":"\\")+g;k=[];l=l?"open":"closed";h=b[g];"undefined"==typeof h&&
(h=[]);var n="nor_";g!=g_xlat_runame&&g!=g_xlat_pendingname?(h.sort(a.lp_sort_case_insensitive_name),g==g_xlat_favorites&&(n="fav_")):(h.sort(function(a,b){return a.last_touch>b.last_touch?-1:1}),g==g_xlat_runame&&(n="rec_"));for(var v=getcolvisibility("usernamecol"),I=getcolvisibility("ltnamecol"),B=navigator.userAgent.match("Gecko/"),C=1==g_showrows?"":"none",D=0;D<h.length;D++){var z=62+15*y;if(B||"undefined"!=typeof g_isopera&&g_isopera)z+=20;var x=h[D];if("http://group"!=x.url){m=p="";if("undefined"!=
typeof x.sharerusername)"undefined"!=typeof g_isopera&&g_isopera&&(p+="</a>"),b=get_div_id(),p+="<div class='actionmenu' id='"+b+"'><a href='#' id='accept_"+n+x.id+"' class='vaultlink'><img src='"+gLocalBaseUrl+"images/vaultaccept.png'/></a> | <a href='#' id='reject_"+n+x.id+"' class='vaultlink'><img src='"+gLocalBaseUrl+"images/vaultreject.png'/></a></div>",styles[b]={paddingRight:z+"px",display:C},event_handlers["accept_"+n+x.id]=function(){return accept(this.id.substring(11))},event_handlers["reject_"+
n+x.id]=function(){return reject(this.id.substring(11))},p+="<span class='clearboth'></span>",p+="<span><a href='#' id='accept2_"+n+x.id+"'>"+gs("Share offer from")+" "+of(a.hex2bin(x.sharerusername))+"</a></span>",event_handlers["accept2_"+n+x.id]=function(){return accept(this.id.substring(12))};else{var G=safclassdel=safclassshare="";if(g_issafari||g_isopera)G=" editsaf",safclassdel=" delsaf",safclassshare=" sharesaf";var m=get_record_id(x),F,E="<a href='#' id='share_"+n+m+"' class='vaultlink' title='"+
g_xlat_share+"'><span class='shareimg"+safclassshare+"'></span></a> ";event_handlers["share_"+n+m]=function(){return s(this.id.substring(10))};a.LPISLOC||x.genpw||"undefined"!=typeof x.sharedfromaid&&null!=x.sharedfromaid&&""!=x.sharedfromaid&&"0"!=x.sharedfromaid&&"null"!=x.sharedfromaid||"undefined"!=typeof x.sharefolderid||is_application(x)||0!=a.g_hidesharing||!a.g_sharing_enabled?(F='<font class="hiddenfont">'+E+"</font>",E=""):F="";var H="";b="undefined"!=typeof x.sharedfromaid&&"0"!=x.sharedfromaid?
x.sharedfromaid:"";"undefined"!=typeof x.hasbeenshared&&1==x.hasbeenshared?(H="<p class='sharesubtext'><subtext id='sharesub_"+n+m+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+n+m]=function(){return s(this.id.substring(13))}):x.individualshare&&(""==b?(H="<p class='sharesubtext'><subtext id='sharesub_"+n+m+"'>"+gs("shared")+"</subtext></p>",event_handlers["sharesub_"+n+m]=function(){return s(this.id.substring(13))}):H="<p class='sharesubtext'>"+gs("shared with you")+"</p>");"undefined"!=
typeof g_isopera&&g_isopera&&(p+="</a>");b=get_div_id();p+="<div class='actionmenu' id='"+b+"'>"+F;styles[b]={paddingRight:z+"px",display:C};p+="<a href='#' id='chpw_"+n+m+"' class='vaultlink colhidden' title='"+g_xlat_chpw+"'><span class='chpwimg'></span></a> ";g_cpwbot&&x.pwch&&(event_handlers["chpw_"+n+m]=function(){e(this.id.substring(9),!0)});p+="<a href='#' id='edit_"+n+m+"' class='vaultlink' title='"+g_xlat_edit+"'><span class='editimg"+G+"'></span></a> ";event_handlers["edit_"+n+m]=function(){return e(this.id.substring(9))};
p+=E;p+="<a href='#' id='delete_"+n+m+"' class='vaultlink' title='"+g_xlat_delete+"'><span class='delimg"+safclassdel+"'></span></a></div>";event_handlers["delete_"+n+m]=function(){return d(this.id.substring(11))};p+="<span class='clearboth'></span>";p+="<span><a href='#' id='launch_"+n+m+"'>"+of(x.name)+"</a>"+H+"</span>";event_handlers["launch_"+n+m]=function(){return ls(this.id.substring(11))}}z="calc(5% + 10px)";G=v?"usercolvisible":"usercolhidden";F=I?"ltcolvisible":"ltcolhidden";E=of(a.getusernamefromacct(x));
""==E&&(E="&nbsp;");b=get_div_id();p+="<div id='"+b+"' class='"+G+"' name='usercol'>"+E+"</div>";styles[b]={cssFloat:"right",paddingRight:z,display:C};b=get_div_id();p+="<div id='"+b+"' class='"+F+"' name='ltcol'>"+("undefined"!=typeof x.last_touch?of(elapsedTime(x.last_touch)):"")+"</div>";styles[b]={cssFloat:"right",paddingRight:z,display:C};k[k.length]={data:{title:p,icon:a.geticonurlfromrecord(x)},attributes:{id:m,name:m}};event_handlers_onmouseover[m]=function(a){sv(a,this);return!1};event_handlers_onmouseout[m]=
function(a){hv(a,this);return!1};event_handlers_onclick[m]=function(a){lc(a,this);return!1}}}h=g;0==h.indexOf("_")&&(h=h.substring(1));n=30+15*y;p=g===g_xlat_favorites||g==g_xlat_runame||g==g_xlat_pendingname;b=get_div_id();p=p?"":"<div class='actionmenu' id='"+b+"'>"+("1"==a.g_enterpriseuser&&!is_personal_linked(h)&&a.g_folder_sharing_enabled?"<a href='#' title='"+g_xlat_share+"'><span class='shareimggroup'></span></a> ":"")+"<a href='#' title='"+gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";
styles[b]={paddingRight:n+"px"};is_personal_linked(h)&&!A?(p+="<span class='boldspan' isgroup='1' >"+of(h)+" - "+of("Linked Personal Account")+"</span>",r=" linked"):p+="<span class='boldspan' isgroup='1' >"+of(h)+"</span>";f[g]=c.length;if(A){m=g.match(/^([^\\]*)\\(.*)$/);f=null;for(r=A=0;m;){p=m[1];w=m[2];if(0==A){for(u=c.length-1;0<=u;u--)if(c[u].group==p){f=c[u].children;break}r=0;A=1;if(!w.match(/^([^\\]*)\\(.*)$/))for(u=0;u<f.length;u++)if("undefined"==typeof f[u].group||f[u].group==p){r=u;
break}}else{for(u=m=0;u<f.length;u++)if("undefined"==typeof f[u].group){m=u-1;break}else if(f[u].group==p){m=u;break}f=f[m].children}m=w.match(/^([^\\]*)\\(.*)$/);if(!m)for(u=0;u<f.length;u++)if("undefined"==typeof f[u].group||f[u].group==p){r=u;break}else if(u==f.length-1){r=u+1;break}}m=getgroupid(g,q);n=30+15*y;b=get_div_id();p="<div class='actionmenu' id='"+b+"'>"+("1"==a.g_enterpriseuser&&!is_personal_linked(h)&&a.g_folder_sharing_enabled?"<a href='#' title='"+g_xlat_share+"'><span class='shareimggroup'></span></a> ":
"")+"<a href='#' title='"+gs("Group Actions")+"'><span class='toolsimg'></span></a></div>";styles[b]={paddingRight:n+"px"};p+="<span class='boldspan' isgroup='1'>"+of(w)+"</span>";f.splice(r,0,{data:p,children:k,state:l,group:w,attributes:{"class":"folder",id:m}})}else 0==c.length&&(g_rootnodeid=g),g_lastnodeid=g,m=getgroupid(u,q),c[c.length]={data:p,children:k,state:l,group:g,attributes:{"class":"folder"+r,id:m}}}function getcolvisibility(a){return 0==localStorage_getItem(a)?!1:!0}
function setcolvisibility(a,b){localStorage_setItem(a,b)}
function matches(a,b,c){var f=b.toLowerCase();return-1!=a.name.toLowerCase().indexOf(f)||a.url&&-1!=a.url.toLowerCase().indexOf(f)||-1!=a.group.toLowerCase().indexOf(f)||a.unencryptedUsername&&-1!=a.unencryptedUsername.toLowerCase().indexOf(f)||is_application(a)&&(a.appname&&-1!=a.appname.toLowerCase().indexOf(f)||-1!=getusernamefromacct(a).toLowerCase().indexOf(f))||c&&"undefined"!=typeof a.extra&&0<a.extra.length&&("undefined"==typeof a.url||"http://group"!=a.url)&&-1!=getBG().lpmdec_acct(a.extra,
!0,a,getBG().g_shares).toLowerCase().indexOf(f)||"has:attachment"==b&&"undefined"!=typeof a.attachid&&null!=a.attachid&&0!=a.attachid?!0:!1}var g_cachedOpenGroups=null;
function getOpenedGroups(){var a=getBG(),b=[];if("undefined"==typeof LPFromWebsite){if("undefined"==typeof localStorage)return b;if(g_cachedOpenGroups&&g_cachedOpenGroups.length)a=g_cachedOpenGroups;else{var c=localStorage_getItem(a.db_prepend(a.g_username_hash+".savedtree"));g_cachedOpenGroups=a=a.dec(c)}}else a=LPFromWebsite.readopengroups();if(!a||""==a)return b;a=a.split(",");for(c=0;c<a.length;c++)b[a[c].replace("%2C",",")]=1;return b}
function saveGroupState(){var a=getBG();if(!massoperation&&a.lploggedin){var b="";if(g_view==VIEWS.GRID)$(".cont:visible").each(function(a,c){var f=getgroupnamefromid(c.id.substr(2),!0);f.replace(",","%2C");b+=f+","});else{var c=$("#thetree").find(".open");$.each(c,function(a,c){var f=getgroupnamefromid(c.id,!0);f.replace(",","%2C");b+=f+","})}"undefined"==typeof LPFromWebsite?"undefined"!=typeof localStorage&&g_cachedOpenGroups!=b&&(g_cachedOpenGroups=b,c=a.enc(b),localStorage_setItem(a.db_prepend(a.g_username_hash+
".savedtree"),c)):LPFromWebsite.saveopengroups(b)}}function lc(a,b){$.tree.focused().select_branch(b,a.ctrlKey|a.metaKey,a.shiftKey)}function sv(a,b){$(b).children(".actionmenu").find("span").each(function(a){$(this).css("opacity","1.0")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="inline-block")}
function hv(a,b){$(b).children(".actionmenu").find("span").each(function(a){$(this).css("opacity","0.2")});if(1!=g_showrows)for(var c=0;c<b.children.length;c++)"DIV"==b.children[c].nodeName&&(b.children[c].style.display="none")}function lponopen(a,b){saveGroupState()}function lponclose(a,b){saveGroupState()}function lponselect(){document.getElementById("q").blur()}var g_lastpop=0;
function lponrgtclk(a,b,c){var f=$.tree.focused().selected_arr&&$.tree.focused().selected_arr.length;1==f&&a!==b.selected&&b.select_branch(a);getBG().lpevent("v_rgt");var g=(new Date).getTime();if(!(g_lastpop>g-500)){g_lastpop=g;if(1<f){for(var l="",k=[],h=!1,q=!1,f=0;f<$.tree.focused().selected_arr.length;f++)(g=getmoveid($.tree.focused().selected_arr[f]))&&""!=g&&(is_application(g)&&(h=!0),get_record(g)&&"undefined"!=typeof get_record(g).sharefolderid&&(q=!0),l+=(""!=l?",":"")+g,k[k.length]=$.tree.focused().selected_arr[f]);
setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};c[gs("Move Selected to Group")]=function(){b.lpevent("v_multmov");openMoveGroup(a)};h||q||(c[gs("Share Selected")]=function(){b.lpevent("v_mults");s(l)});c[gs("Delete Selected")]=function(){b.lpevent("v_multd");b.deleteAid(l,window,!1,!1,function(){for(var a=0;a<k.length;a++)$.tree.focused().cut(k[a])})};return[c]},{theme:"vista"}).show(b,c)},100)}else if("undefined"!=typeof a)if(""==a.id||is_application(a.id)||isNumber(a.id))""!=
a.id&&(is_application(a.id)||isNumber(a.id))&&setTimeout(function(){$.contextMenu.create(function(){var b=getBG(),c={};if("undefined"!=typeof getBG().g_sites[a.id]||is_application(a.id)){if("undefined"==typeof g_issafari&&"undefined"==typeof g_isopera&&"undefined"==typeof g_ismaxthon&&"undefined"==typeof g_isfirefoxsdk||"function"==typeof b.can_copy_to_clipboard&&b.can_copy_to_clipboard()||"undefined"!=typeof g_is_safari)c[gs("Copy Username")]=function(){b.copyusername(a.id)},c[gs("Copy Password")]=
function(){b.copypassword(a.id)},c[gs("Copy URL")]=function(){b.copyurl(a.id)}}else if("undefined"!=typeof getBG().g_securenotes[a.id]){var f=getBG().g_securenotes[a.id],g="undefined"!=typeof f.notetype?f.notetype:"";"undefined"!=typeof sntemplates[g]&&"undefined"!=typeof sntemplates[g].Username&&(c[gs("Copy Username")]=function(){b.copyusername(a.id)});var f=getBG().lpmdec_acct(f.extra,!0,f,getBG().g_shares),h;h=0|-1<f.indexOf("Wi-Fi Password");h|=-1<f.indexOf("Email Account");h=(h|=-1<f.indexOf("Server"))&&
-1<f.indexOf("Password");if("undefined"!=typeof sntemplates[g]&&"undefined"!=typeof sntemplates[g].Password||h)c[gs("Copy Password")]=function(){b.copypassword(a.id)}}c[gs("Move to Group")]=function(){b.lpevent("v_mov");openMoveGroup(a)};c[gs("Move to Sub-Group")]=function(){b.lpevent("v_msub");openMoveGroup(a,!0)};g=get_record(a.id);is_application(a.id)||!g||"undefined"!=typeof g.sharefolderid||"undefined"!=typeof g.sharedfromaid&&null!=g.sharedfromaid&&""!=g.sharedfromaid&&"0"!=g.sharedfromaid&&
"null"!=g.sharedfromaid||!b.g_sharing_enabled||(c[gs("Share")]=function(){s(a.id)});c[gs("Delete")]=function(){b.lpevent("v_rgtd");b.deleteAid(a.id,window,!1,!1,function(){$.tree.focused().cut(a)})};c[gs("Edit")]=function(){b.lpevent("v_rgte");b.editAid(a.id,window)};"undefined"!=typeof getBG().g_sites[a.id]&&(c[gs("Go to URL")]=function(){b.lpevent("v_g2");b.gotourl(a.id,null)});return[c]},{theme:"vista"}).show(b,c)},100);else{f=getgroupnamefromid(a.id);0==f.indexOf("_")&&(f=f.substring(1));for(var g=
!1,r=a;r.parentNode&&r.parentNode!=r;)if(r=r.parentNode,"thetree"==r.id){g=!0;break}if(!g)return;openGroupMenu(a,f,b,c);c.preventDefault()}c.preventDefault()}}var lastqstr="";
function SearchTree(a,b,c){g_CNTsearch_tree++;var f=!1;0<document.location.href.indexOf("cmd=viewcreditmon")&&1!=g_autoselectcredmontab?(ontabchange(document.getElementById("credmon")),g_autoselectcredmontab=1):"sites"!=g_activetab.id&&(f=!0);var g=$("#q").val(),l=!1;if(a||g!=lastqstr)f&&!b&&(ontabchange(document.getElementById("sites")),l=!0),gLastSearch=lastqstr=g,g_view==VIEWS.GRID?populate(g,!0):(massoperation=!0,""==g?c||clearTree():$.tree.focused().search(g),massoperation=!1);f&&!l&&setTimeout(function(){ontabchange(g_activetab)},
0);document.getElementById("searchx").src=""==g?gLocalBaseUrl+"images/search.png":gLocalBaseUrl+"images/cancel.png"}function ls(a){var b=getBG();b.lpevent("v_ls");b.launch(a);return!1}function cu(a){var b=getBG();b.lpevent("v_cu");b.copyusername(a);return!1}function cp(a){var b=getBG();b.lpevent("v_cp");b.copypassword(a);return!1}function curl(a){var b=getBG();b.lpevent("v_curl");b.copyurl(a);return!1}function e(a,b){var c=getBG();c.lpevent("v_e");c.editAid(a,window,null,b);return!1}
function d(a){var b=getBG();b.lpevent("v_d");b.deleteAid(a,window);return!1}function is_protected(a){"string"==typeof a&&(a=a.split(","));for(var b=0;b<a.length;b++){var c=get_record(a[b]);if(c&&1==c.pwprotect)return!0}return!1}function s(a){getBG().lpevent("v_s");callServerFunction("share",a);return!1}
function MoveFocus(a){if(40==a.keyCode||34==a.keyCode||38==a.keyCode||33==a.keyCode)a=38==a.keyCode||33==a.keyCode?getgroupidfromname(g_lastnodeid):getgroupidfromname(g_rootnodeid),$.tree.focused().select_branch("#"+a),document.getElementById("q").blur()}function clearTree(){g_CNTclear_tree++;populate("");document.getElementById("searchx").src=gLocalBaseUrl+"images/search.png";document.getElementById("q").value=""}var massoperation=!1;
function expandall(){if(!getBG().lploggedin)return!1;massoperation=!0;g_view==VIEWS.GRID?($(".cont").each(function(a,b){$(b).show()}),$(".grpclose").removeClass("grpclose").addClass("grpopen")):$.tree.focused().open_all();massoperation=!1;saveGroupState()}
function collapseall(){if(!getBG().lploggedin)return!1;massoperation=!0;g_view==VIEWS.GRID?($(".cont").each(function(a,b){$(b).hide()}),$(".grpopen").removeClass("grpopen").addClass("grpclose")):$.tree.focused().close_all();massoperation=!1;saveGroupState()}function creategroup(){var a=getBG();a.lploggedin&&(a.lpevent("v_cg"),openCreateGroup(null))}
function showformfill(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a=getBG(),b={},c;for(c in a.g_formfills)a.g_formfills.hasOwnProperty(c)&&a.check_ident_ffid(a.g_formfills[c].ffid)&&(b[of(a.g_formfills[c].decprofilename)]=function(a){editff(get_innerText(a))});a={};a[gs("Add Profile")]=function(){getBG().addprofile()};a[gs("Add Credit Card")]=function(){getBG().addcreditcard()};return[b,"context-menu-separator",a]},{theme:"vista"}).show(a,
b)},0);return!1}function editff(a){var b=getBG();a=$.trim(a);for(var c in b.g_formfills)if(b.g_formfills.hasOwnProperty(c)&&a==$.trim(b.g_formfills[c].decprofilename)){b.editprofile(b.g_formfills[c].ffid);break}}
function showmoremenu(a,b){var c=getBG();if(!c.lploggedin)return c.open_login(1),!1;setTimeout(function(){$.contextMenu.create(function(){var a={};gHidePreferences||(a[gs("Preferences")]=function(){getBG().openprefs()});getBG().LPISLOC||(a[gs("History")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&openhistory=1")},a[gs("Show Deleted Sites")]=function(){getBG().unlock_plug2web();getBG().openbaseurl("?ac=1&showdeleted=1")});getBG().LPISLOC&&getBG().LPISUPEK||(a[gs("Change Password")]=
function(){getBG().unlock_plug2web();getBG().changemasterpassword()});a[gs("Forums")]=function(){getBG().openURL("http://forums.lastpass.com")};a[gs("Blog")]=function(){getBG().openURL("http://blog.lastpass.com")};getBG().g_isadmin&&(a[gs("Admin Tools")]=function(){getBG().openURL("https://rodan-internal.lastpass.com/admintools/")});return[a]},{theme:"vista"}).show(a,b)},0);return!1}function addsecurenote(){getBG().lpevent("v_addn");getBG().openaddsecurenote();return!1}
function logoff(){if(!getBG().lploggedin)return!1;finish_vault_search();getBG().lpevent("v_off");saveGroupState();getBG().loggedOut(!1,"homelocal2");return!1}function accept(a){getBG().lpevent("v_apt");callServerFunction("acceptshare",a)}function reject(a){getBG().lpevent("v_rjt");callServerFunction("rejectshare",a)}function login(){getBG().lpevent("v_lgn");getBG().open_login(!0);return!1}
function changeidentity(a,b){"undefined"!=typeof b&&1!=b||closepopup();getBG();getBG().lpevent("v_cid");getBG().switch_identity(a);document.getElementById("identity").value=getBG().g_identity;setusernametext(getBG().g_username);closepopup()}var gMoveSelected=null;
function openMoveGroup(a,b,c){if(addedjqueryui){gMoveSelected=$.tree.focused().selected_arr;if("undefined"==typeof gMoveSelected||0==gMoveSelected.length)gMoveSelected=Array(a);var f=getBG(),g=[],l=[],k=[f.g_sites,f.g_securenotes,f.g_applications],h="",q;for(q in k)if(k.hasOwnProperty(q)){var r=k[q],y;for(y in r)if(r.hasOwnProperty(y)){var m=r[y];if(gMoveSelected&&1==gMoveSelected.length&&getmoveid(gMoveSelected[0])==get_record_id(m)&&(h=m.group,b)){""!=m.group&&(g[g.length]=m.group);break}m=""!=
m.group?m.group:gs("(none)");"undefined"!=typeof m&&"undefined"==typeof l[m]&&(l[m]="1",g[g.length]=m)}}g.sort(function(a,b){return"_Apps assigned to me"==a?-1:"_Apps assigned to me"==b?1:a.toLowerCase()<b.toLowerCase()?-1:1});l=!1;""!=h||1!=gMoveSelected.length||isNumber(getmoveid(gMoveSelected[0]))||(h=getmoveid(gMoveSelected[0]),l=!0);k=-1!=h.indexOf("\\")&&0<h.substring(h.indexOf("\\")+1).length;if(l&&0===h.indexOf("Shared-")&&!k){if(g=void 0,c){for(i in f.g_sites)if(f.g_sites[i].group==h){g=
f.g_sites[i].aid;break}callServerFunction("renamesharedfolder",g)}}else document.getElementById("grpsel").value="",repopulate_combo("grpsel",g),document.getElementById("dialog").title=gs("Change Group Name"),set_innertext(document.getElementById("dialogtext"),gs("Select or enter a new group name")),document.getElementById("dialoggrpinp").style.display="none",document.getElementById("dialoggrpsel").style.display="block",document.getElementById("dosubgroup").value="undefined"!=typeof b&&b?"1":"0",1==
gMoveSelected.length&&(b?(document.getElementById("dialogtext").appendChild(document.createElement("br")),document.getElementById("dialogtext").appendChild(document.createElement("br")),document.getElementById("dialogtext").appendChild(document.createTextNode(gs("Group will be created or currently exists under")+": ")),document.getElementById("dialogtext").appendChild(document.createElement("br")),document.getElementById("dialogtext").appendChild(document.createTextNode(h))):document.getElementById("grpsel").value=
h),$("#dialog").dialog("destroy"),$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,dragStop:function(a,b){var c=document.getElementById("grpsel_combo");c&&"block"==c.style.display&&realShowCombo()},close:function(a,b){var c=document.getElementById("grpsel_combo");c&&"block"==c.style.display&&close_combo("grpsel")},buttons:{Change:function(){var a=1==gMoveSelected.length?getmoveid(gMoveSelected[0]):"";if(1!=gMoveSelected.length||""==a||is_application(a)||isNumber(a)){for(var b=
"",c=0;c<gMoveSelected.length;c++)if(a=getmoveid(gMoveSelected[c]),is_application(a)||isNumber(a))b+=(""==b?"":",")+a;if(0==b.length)return;a=document.getElementById("grpsel").value;1==gMoveSelected.length&&"1"==document.getElementById("dosubgroup").value&&a!=h&&0!=a.indexOf(h+"\\")&&(a=h+"\\"+a);getBG().moveSelectedToGroup(a,b)}else b=fix_group(document.getElementById("grpsel").value),c=fix_group(a),0==b.indexOf("Shared-")?-1!=b.indexOf("\\")&&0==c.indexOf(b.substr(0,b.indexOf("\\")))?getBG().renameGroup(fix_group(a),
b):shareFolder(b.replace("Shared-","")):getBG().renameGroup(c,b);populate(gLastSearch);$(this).dialog("close")},Close:function(){$(this).dialog("close")}}}),$("#dialog").dialog("open"),$("#grpsel").click()}else addJqueryUI(),setTimeout(function(){openMoveGroup(a,b,c)},250)}var selected_global;
function openCreateGroup(a){addedjqueryui||(addJqueryUI(),setTimeout(function(){openCreateGroup(a)},250));selected_global=a;getBG().lpevent("v_cg");document.getElementById("dialog").title=gs("Group Name");set_innertext(document.getElementById("dialogtext"),gs("Group Name"));document.getElementById("dialoggrpinp").style.display="block";document.getElementById("grpinp").value="";document.getElementById("dialoggrpsel").style.display="none";"function"==typeof $("#dialog").dialog&&($("#dialog").dialog("destroy"),
$("#dialog").dialog({autoOpen:!1,bgiframe:!0,modal:!0,width:300,minWidth:300,minHeight:250,buttons:{OK:function(){var a=document.getElementById("grpinp").value;for(null!=selected_global&&(a=fix_group(getmoveid(selected_global))+"\\"+a);"\\"==a[0];)a=a.substr(1);if(a==gs("favorites")||a==g_xlat_runame||a==g_xlat_pendingname)alert(gs("That group already exists."));else if(null==selected_global&&0==a.indexOf("Shared-"))alert(gs("Sorry - group names starting with 'Shared-' are created by LastPass to indicate groups shared with other people. Please use a different name."));
else{var c=getBG(),f=[c.g_sites,c.g_securenotes,c.g_applications],g;for(g in f)if(f.hasOwnProperty(g)){var l=f[g],k;for(k in l)if(l.hasOwnProperty(k)&&l[k].group==a){alert(gs("That group already exists."));return}}c.addEmptyGroup(a);populate(gLastSearch);$(this).dialog("close")}},Close:function(){$(this).dialog("close")}}}),"function"==typeof $("#dialog").dialog&&$("#dialog").dialog("open"));$("#grpinp").click()}
function getmoveid(a){a="undefined"!=typeof a.id?getgroupnamefromid(a.id,!0):getgroupnamefromid(a.attr("id"),!0);0==a.indexOf("_")&&(a=a.substring(1));return a}function getacct(a){return get_record(a)}function getDragHTMLForNode(a){var b=a;for(a=0;b&&""==b.attr("id")&&100>a;)b=b.parent(),a++;a=getBG();b=b.attr("id");return(b=getacct(b))?"<div><img src='"+a.geticonurlfromrecord(b)+"' />&nbsp;<span>"+of(b.name)+"</span></div>":""}
function getDragHTML(a){var b="<div id='jstree-dragged' class='tree default'>";if(null==a){a=$.tree.focused().selected_arr;for(var c=0;c<a.length;c++)b+=getDragHTMLForNode(a[c])}else b+=getDragHTMLForNode(a);return b+"</div>"}var togglestate=0;
function toggleUserCol(){var a=getcolvisibility("usernamecol"),b=getcolvisibility("ltnamecol"),c="usercol",f="usernamecol",g="usercolhidden",l="usercolvisible",k=a;1==togglestate%2?(c="ltcol",f="ltnamecol",g="ltcolhidden",l="ltcolvisible",k=b):document.getElementById("ltcol").style.paddingRight=a?"calc(5% + 20px)":"5%";togglestate++;a=document.getElementsByName(c);for(b=0;b<a.length;b++)a[b].className=k?g:l,0==b&&setcolvisibility(f,k?"0":"1")}
function openinparent(a,b){0!=a.indexOf("http")&&(a=g_urlprefix+a);a+="?";for(var c in b)b.hasOwnProperty(c)&&(a+="&"+en(c)+"="+en(b[c]));window.open(a)}function showpopup(){getBG().lploggedin?document.getElementById("lppopup").style.display="block":login()}document.addEventListener("click",closepopup,!0);
function closepopup(a){"block"!=document.getElementById("lppopup").style.display||a&&a.target&&("person"==a.target.id||"identity"==a.target.id||"lpusername"==a.target.id)||(document.getElementById("lppopup").style.display="none");$("#tilepopup").hide()}var translations=[];translations.DeleteSiteConfirm=gs("Are you sure you want to delete this site?");translations.DeleteSite=gs("Delete Site?");translations.DeleteIdentityConfirm=gs("Are you sure you want to delete this identity?");
translations.DeleteIdentity=gs("Delete Identity?");translations["Invalid Password."]=gs("Invalid Password.");translations["Add Site"]=gs("Add Site");translations["Add Profile"]=gs("Add Profile");translations["Add Identity"]=gs("Add Identity");this.updated_enc=function(){return!0};var g_waitbox=null;
this.show_waitbox=function(a,b){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy());var c=gs("Submitting...");"undefined"!=typeof a&&null!=a&&1==a?c=gs("LastPass must reencrypt all of your data because of a key change.")+"<br/><br/>"+gs("This may take a while...")+"<br/><br/>"+gs("Please keep this page open until the operation completes.")+'<br/><br/><div id="changepw_progress" class="width300div"></div>':"undefined"!=typeof b&&b&&""!=b&&(c=b);b=gs("Please Wait...");g_waitbox=new Ext.Window({closable:!1,
width:Math.min(750,200+4*c.length),autoHeight:!0,layout:"fit",modal:!0,title:b,bodyStyle:"padding: 20px",id:"waitbox",html:"<br/><br/><b>"+c+"</b><br/><br/>"});g_waitbox.show()};this.hide_waitbox=function(){g_waitbox&&(g_waitbox.hide(),g_waitbox.destroy(),g_waitbox=null)};this.populateff=function(a,b){for(var c=getBG(),f=convert_object_to_array(c.g_formfills),g=[],l=0;l<f.length;l++){var k=f[l];c.check_ident_ffid(k.ffid)&&g.push(k)}populateffcommon(g,a,b)};
this.openff=function(a){getBG().lpevent("v_off");getBG().editprofile(a)};this.delff=function(a){confirm(gs("Are you sure you would like to delete this form fill profile?"))&&(getBG().lpevent("v_dff"),getBG().deleteformfill(a))};
this.populateident=function(a,b){var c=convert_object_to_array(getBG().g_identities);if(c.length){if(document.getElementById("identiframe")){var f=document.getElementById("identpane");f.removeChild(document.getElementById("identiframe"))}populateidentcommon(c,a)}else if(!document.getElementById("identiframe")){for(f=document.getElementById("identpane");f.children.length;)f.removeChild(f.children[0]);c=document.createElement("iframe");c.id="identiframe";c.className="overviewiframe";c.src=getpartnerurl("ident_overview.php");
f.appendChild(c)}};this.openident=function(a){getBG().lpevent("v_oid");callServerFunction("identity",a);return!1};this.delident=function(a){getBG().lpevent("v_did");confirm(gs("Are you sure you want to delete this identity?"))&&callServerFunction("deleteidentity",a,getBG().g_token);return!1};
this.populateshares_remote=function(a){cleartab("sharepane");a=document.getElementById("sharepane");if(!document.getElementById("shareiframe")){getBG().unlock_plug2web();var b=document.createElement("iframe");b.id="shareiframe";b.className="overviewiframe";b.src=getpartnerurl("share_overview.php?extension=1");a.appendChild(b)}};
this.populatealerts=function(a){cleartab("credmonpane");a=document.getElementById("credmonpane");if(!document.getElementById("credmoniframe")){var b=document.createElement("iframe");b.id="credmoniframe";b.className="overviewiframe";b.src=getpartnerurl("credmon_overview.php");a.appendChild(b)}};this.cleartab=function(a){for(a=document.getElementById(a);a&&a.children.length;)a.removeChild(a.children[0])};this.refreshsites=function(){getBG().refreshsites()};var g_loaded=g_haspluginrsa=!1,g_func=null;
this.doneloadingexternaljs=function(){g_loaded=!0;g_func&&g_func();g_func=null};this.openaddbytab=function(){if(getBG().lploggedin)return"ident"==g_activetab.id?callServerFunction("identity",""):"ff"==g_activetab.id||"credmon"==g_activetab.id?getBG().addprofile():getBG().openaddsite(),!1};this.opencreditmondash=function(a,b){if(getBG().lploggedin)return a?callServerFunction("opencreditmondash",b):callServerFunction("opencreditmondashnoalert",b),!1};function togglerows(){}
window.addEventListener("message",function(a){if("undefined"!=typeof getBG().base_url&&0==getBG().base_url.indexOf(a.origin)){var b=a.data+"";"addprofile"==b||"addidentity"==b?openaddbytab():0<=b.indexOf("showcredmondash_")?(a=b.substr(16),opencreditmondash(!0,a)):0<=b.indexOf("showcredmondashnoalert_")?(a=b.substr(23),opencreditmondash(!1,a)):"object"==typeof a.data&&("getdata"==a.data.msg?0==a.data.url.indexOf(getBG().base_url)&&(g_ipctarget=a,getBG().processCS(null,{cmd:"ipcgetdata",url:a.data.url,
callback:website_event_callback},null)):"refreshsites"==a.data.msg?getBG().refreshsites():"closeiframe"==a.data.msg?(a=document.body,b=document.getElementById("__serveriframe"),a&&b&&a.removeChild(b)):"websiteevent"==a.data.msg?(g_websiteeventtarget=a,document.getElementById("eventtype").value=a.data.eventtype,document.getElementById("eventdata1").value=a.data.eventdata1,document.getElementById("eventdata2").value=a.data.eventdata2,document.getElementById("eventdata3").value=a.data.eventdata3,document.getElementById("eventdata4").value=
a.data.eventdata4,document.getElementById("eventdata5").value=a.data.eventdata5,website_event()):0==a.data.msg.indexOf("sharefolder_")&&(b=a.data.msg.match(/^sharefolder_([^_]+)_(.*)$/))&&(a=b[1],b=b[2],"undefined"!=typeof share_folder_group&&share_folder_group==b&&(share_folder_id=a,getBG().set_share_folder_id(a))))}},!1);
function callServerFunction(a,b,c,f){var g=getBG();if(g.lploggedin){g.unlock_plug2web();var l=document,k=!1;if("share"==a||"acceptshare"==a||"rejectshare"==a){if(k=g.g_prompts.edit_site_prompt||g.g_prompts.edit_sn_prompt,!k&&"share"==a)for(var h=b.split(","),q=0;q<h.length;q++){var r=get_record(h[q]);if(r&&r.pwprotect){k=!0;break}}}else if("identity"==a||"deleteidentity"==a){if(k=g.g_prompts.switch_identity_prompt,!k&&""!=b)for(h=convert_object_to_array(g.g_identities),q=0;q<h.length;++q)if(h[q].iid==
b&&h[q].pw_prompt){k=!0;break}}else if("opencreditmondash"==a||"opencreditmondashnoalert"==a)k=!1;if(k&&!f)g.security_prompt(function(){callServerFunction(a,b,c,!0)});else{f=l.body;l=l.createElement("iframe");l.type="content";g=g_urlprefix+"acctsiframe.php?rand="+1E3*Math.random()+"&command="+encodeURIComponent(a);b&&(g+="&commandid="+encodeURIComponent(b));c&&(g+="&commandtoken="+encodeURIComponent(c));g+="&version="+encodeURIComponent(lpversion);l.setAttribute("src",getpartnerurl(g));l.id="__serveriframe";
l.style.position="absolute";l.style.top=l.style.left="0px";try{var y=f.ownerDocument.defaultView.getComputedStyle(f,"");l.style.width=y.width;l.style.height=y.height}catch(m){}f.appendChild(l)}}}function manageSharedFolder(a){var b=getBG(),c=a.indexOf("\\");-1!=c&&(a=a.substring(0,c));for(var f in b.g_shares)if(b.g_shares[f].decsharename==a){callServerFunction("sharedfolders",b.g_shares[f].id);break}}
function shareFolder(a){share_folder_id="";getBG().set_share_folder_id("");share_folder_group=a;getBG().set_share_folder_group(a);callServerFunction("sharefolder",a)}function sendToManageSharedFolders(a){alert("Please delete Shared Folders using the Manage Shared Folders link")}
function openGroupMenu(a,b,c,f){var g=getrawgroupid(a.id);setTimeout(function(){$.contextMenu.create(function(){var c=getBG(),f={};b!=g_xlat_favorites&&b!=g_xlat_runame&&b!=g_xlat_pendingname&&b!=g_xlat_none&&(0==b.indexOf("Shared-")&&c.g_folder_sharing_enabled?f[gs("Manage Shared Folder")]=function(){manageSharedFolder(b)}:"1"==c.g_enterpriseuser&&!is_personal_linked(b)&&c.g_folder_sharing_enabled&&(f[gs("Share Folder")]=function(){shareFolder(b)}),f[gs("Rename Group")]=function(){c.lpevent("v_ren");
openMoveGroup(a,void 0,!0)},f[gs("Delete Group")]=function(){0==b.indexOf("Shared-")&&-1==b.indexOf("\\")?(callServerFunction("sharedfolders"),sendToManageSharedFolders()):(c.lpevent("v_dg"),c.deleteGroup(fix_group(b),window,function(){$.tree.focused().cut(a)},"homelocal2.html B",0,g))},f[gs("Create Sub-Group")]=function(){c.lpevent("v_csub");openCreateGroup(a)});f[gs("Open All")]=function(){c.openall(b)};return[f]},{theme:"vista"}).show(c,f)},0)}
function contains(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return!0;return!1}var I_SHOW=!0,I_HIDE=!1;function refresh_ident_actions(){var a=getBG();a&&convert_object_to_array(a.g_identities).length&&showhide_ident_actions(I_SHOW)}
function showhide_ident_actions(a){getBG();a==I_SHOW?(document.getElementById("ident").style.display="table-cell",document.getElementById("lpidentities").style.display="block"):(document.getElementById("ident").style.display="none",document.getElementById("lpidentities").style.display="none")}
function grid_sites_tokenize(a){var b=getBG(),c,f={},b=[b.g_sites,b.g_securenotes,b.g_applications,b.g_pendings];for(c in b)if(b.hasOwnProperty(c)){var g=b[c],l;for(l in g)if(g.hasOwnProperty(l)){var k=g[l],h="id"+k.aid,q=[];k.name&&q.push(k.name);k.group&&q.push(k.group);"http://group"!=k.url&&"http://sn"!=k.url&&q.push(k.url);k.unencryptedUsername&&q.push(k.unencryptedUsername);is_application(k)&&(q.push(k.appname),q.push(getusernamefromacct(k)));if(a&&"undefined"!=typeof k.extra&&0<k.extra.length&&
("undefined"==typeof k.url||"http://group"!=k.url)&&!k.pwprotect){var r=getBG().lpmdec_acct(k.extra,!0,k,getBG().g_shares);r&&0!=r.length||console.log("searchinnotes: site aid="+k.aid+" FAILED TO DECRYPT");q.push(r)}k=q.join(" ");k=k.toLowerCase();f[h]=k}}return f}function grid_init_vault_search(){var a=getBG(),a=a.g_prompts.edit_sn_prompt?!1:a.get_searchNotesPref();g_search_array=grid_sites_tokenize(a);return!0}
function refresh_legacy_link(a){function b(a){return a?(a=a.getElementById("legacy_li"))?(a.style.display="block",!0):!1:!1}function c(a){return a?(a=a.getElementById("legacy_li"))?(a.style.display="none",!0):!1:!1}var f=getBG();if(!f)return!1;g_dolegacy=is_user_premium();return f.g_legacy_enabled&&f.lploggedin&&g_dolegacy?b(a):c(a)}$(document).bind("DOMContentLoaded",function(){$("#vaultToggle").bind("click",function(a){a.preventDefault();a.stopPropagation();getBG().VaultToggle.toggleVault4_0(window)})});
