var NoteDialog=function(g){DialogWithGroupInput.call(this,g,{closeButtonEnabled:!0,maximizeButtonEnabled:!0});this.addedAttachments=this.removedAttachments=null;this.showAttachmentContainer=function(g){g?$("#noteDialogExistingAttachments").hide():$("#noteDialogExistingAttachments").show()};this.noteForms={};this.noteTypeIconContainer=this.noteFormElement=null;this.noteTypeOptions=[];this.temporaryNoteTypeOptionValue=null};NoteDialog.prototype=Object.create(DialogWithGroupInput.prototype);
NoteDialog.prototype.constructor=NoteDialog;
(function(g){var k=function(){LPProxy.copyToClipboard(this.getValue())};NoteDialog.prototype.setNoteTypeImage=function(a){this.noteTypeIconContainer.children(".itemIcon").detach();this.noteTypeIconContainer.prepend(this.inputFields.notetype.options[a].icon)};var h=function(a){a=new NoteDisplay(new Note({notetype:a}));var c=a.buildItemIconElement();a.destruct();return c};NoteDialog.prototype.addCustomNote=function(a){var c="Custom_"+a.id;if(!this.noteForms.hasOwnProperty(c)){this.addNoteType({label:a.title,value:c});
for(var b=[],d=0;d<a.fields.length;++d){var f=a.fields[d].text;switch(a.fields[d].type){case "text":b.push(new DialogInput.TextInput(f));break;case "password":b.push(new DialogInput.PasswordInput(f));break;case "textarea":b.push(new DialogInput.TextArea(f));break;case "monthDayYear":b.push(new DialogInput.AlphaDateInput(f));break;case "monthYear":b.push(new DialogInput.AlphaDateInput(f,{includeDay:!1}));break;case "textWithCopy":b.push(new DialogInput.TextInput(f,void 0,{inputButton:Strings.translateString("Copy"),
inputButtonHandler:k}))}}b=new e(b);b.customTemplate=JSON.stringify(a);this.noteForms[c]=b}return c};NoteDialog.prototype.open=function(a){DialogWithGroupInput.prototype.open.call(this,$.extend(a,{title:a&&a.vaultItem?Strings.translateString("Edit Note"):Strings.translateString("Add Note"),sourceFunction:LPProxy.getNoteModel}))};NoteDialog.prototype.defaultFields=function(a){a.defaultData=$.extend({notetype:a.vaultItem?a.vaultItem.getNoteType():Note.prototype.NOTE_TYPES.GENERIC},a.defaultData);DialogWithGroupInput.prototype.defaultFields.apply(this,
arguments)};NoteDialog.prototype.clearFields=function(a){DialogWithGroupInput.prototype.clearFields.apply(this,arguments);for(var c in this.noteForms)this.noteForms[c].inputs.clear()};NoteDialog.prototype.clearErrors=function(){DialogWithGroupInput.prototype.clearErrors.apply(this,arguments);for(var a in this.noteForms)this.noteForms[a].inputs.clearErrors()};NoteDialog.prototype.validate=function(a){var c=DialogWithGroupInput.prototype.validate.apply(this,arguments);""===a.name&&(this.addError("name",
"Name is required."),c=!1);45E3<JSON.stringify(a.extra).length&&(function(b){dialogs.confirmation.open({title:Strings.translateString("Error"),text:Strings.translateString("The notes field contains too much data. You may store a maximum of 45,000 characters per note. Would you like us to truncate the note for you? You will lose some of your data."),handler:function(){b.inputFields.extra.Notes.setValue(a.extra.Notes.substring(0,45E3))}})}(this),c=!1);return c};NoteDialog.prototype.initializeAttachmentContainer=
function(a){this.containers.attachments=new Container(a,{stateChangeCallback:this.showAttachmentContainer});this.containers.attachments.initialize(document.getElementById("attachmentContainer"));this.showAttachmentContainer(this.containers.attachments.isEmpty())};NoteDialog.prototype.setup=function(a,c){var b=c.vaultItem;b?(this.inputFields.notetype.disable(),$("#deleteCustomNoteTemplate").hide()):this.inputFields.notetype.enable();b&&!this.inputFields.notetype.options.hasOwnProperty(b.getNoteType())&&
b.getTemplate()&&(this.temporaryNoteTypeOptionValue=b.getNoteType(),this.addCustomNote(JSON.parse(b.getTemplate())));if(b&&b.hasAttachments()){for(var b=b.getAttachments(),d=[],f=0,e=b.length;f<e;++f)d.push(b[f].newDisplayObject());this.initializeAttachmentContainer(d)}else this.showAttachmentContainer(!0);this.removedAttachments=[];this.addedAttachments=[];this.vaultItem?(a.find(".history").show(),bg.loglogin(this.vaultItem.getID())):a.find(".history").hide();DialogWithGroupInput.prototype.setup.apply(this,
arguments)};NoteDialog.prototype.addNoteType=function(){var a=function(a,d){return a.label<d.label?-1:a.label>d.label?1:0},c=LPTools.createElement("div",{id:"addCustomTemplate"},Strings.translateString("Add Custom Template"));$(c).bind("click",function(){dialogs.customNoteTemplate.open()});return function(b){var d=LPTools.createElement("li","noteDropdown",b.label);d.insertBefore(h(b.value),d.firstChild);b.element=d;b.icon=h(b.value);this.noteTypeOptions.push(b);this.noteTypeOptions=this.noteTypeOptions.sort(a);
this.inputFields.notetype.setOptions(this.noteTypeOptions);this.inputFields.notetype.dropdownElement.append(c)}}();NoteDialog.prototype.initialize=function(a){DialogWithGroupInput.prototype.initialize.apply(this,arguments);this.noteFormElement=g.getElementById("noteForm");this.noteTypeIconContainer=$("#noteDialogTypeContainer");this.inputFields.notetype=new DropdownInput(this.inputFields.notetype.getElement()[0]);for(var c in Note.prototype.NOTE_TYPES){var b=Note.prototype.NOTE_TYPES[c];this.addNoteType({label:b,
value:b})}(function(a){var b=function(){for(var b=LPProxy.getCustomNoteTemplates(),c=0,d=b.length;c<d;++c)a.addCustomNote(b[c])};b();Topics.get(Topics.REFRESH_DATA).subscribe(b);a.noteTypeIconContainer.bind("mousedown",function(b){a.inputFields.notetype.toggle(b);b.preventDefault();a.inputFields.notetype.focus()});a.inputFields.notetype.getElement().bind("focus",function(){a.noteTypeIconContainer.addClass("focus")});a.inputFields.notetype.getElement().bind("blur",function(){a.noteTypeIconContainer.removeClass("focus")});
var b=a.addFavButton(),c=LPTools.createElement("a",{"class":"itemButton history",title:Strings.translateString("Note History")});$(c).bind("click",function(){LPRequest.makeRequest(LPProxy.getNoteHistory,{parameters:[a.vaultItem.getID(),a.vaultItem.getShareID()],success:function(b){dialogs.fieldHistory.open({history:b,vaultItem:a.vaultItem,type:Constants.HISTORY_TYPES.NOTE})},requestSuccessOptions:{closeDialog:!1}})});b.appendChild(c);a.inputFields.notetype.onChange(function(b){a.setNoteFields(b);
b=a.noteForms[b];a.hiddenFields.template=b?b.customTemplate:"";b&&b.customTemplate&&!a.inputFields.notetype.disabled?$("#deleteCustomNoteTemplate").show():$("#deleteCustomNoteTemplate").hide()});Topics.get(Topics.ATTACHMENT_REMOVED).subscribe(function(b){for(var c=0,d=a.addedAttachments.length;c<d;++c)if(a.addedAttachments[c]===b){a.addedAttachments.splice(c,1);return}a.removedAttachments.push(b)});$("#addAttachmentButton").bind("click",function(){LPProxy.addAttachment(function(b){a.addAttachment(b)})});
$("#deleteCustomNoteTemplate").bind("click",function(){dialogs.confirmation.open({title:Strings.translateString("Confirm Deletion"),text:Strings.translateString("Are you sure you want do delete? <br/> Any notes you created using this template will not be deleted."),nextButtonText:Strings.translateString("Continue"),backButtonText:Strings.translateString(Strings.Vault.CANCEL),handler:function(){var b=a.inputFields.notetype.getValue(),c=JSON.parse(a.noteForms[b].customTemplate);LPRequest.makeRequest(LPProxy.deleteCustomNoteTemplate,
{params:{id:c.id},success:function(){a.inputFields.notetype.removeValue(b,Note.prototype.NOTE_TYPES.GENERIC);delete a.noteForms[b]},requestSuccessOptions:{closeDialog:!1}})}})});Topics.get(Topics.SECURENOTE_TEMPLATE_ADDED).subscribe(function(b){b=a.addCustomNote(b);a.inputFields.notetype.setValue(b)})})(this);this.noteForms[Note.prototype.NOTE_TYPES.BANK]=new e([new DialogInput.TextInput("Bank Name"),new DialogInput.TextInput("Account Type"),new DialogInput.TextInput("Routing Number"),new DialogInput.TextInput("Account Number"),
new DialogInput.TextInput("SWIFT Code"),new DialogInput.TextInput("IBAN Number"),new DialogInput.TextInput("Pin"),new DialogInput.TextInput("Branch Address"),new DialogInput.TextInput("Branch Phone"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.DATABASE]=new e([new DialogInput.TextInput("Type"),new DialogInput.TextInput("Hostname"),new DialogInput.TextInput("Port"),new DialogInput.TextInput("Database"),new DialogInput.TextInput("Username"),new DialogInput.PasswordInput("Password"),
new DialogInput.TextInput("SID"),new DialogInput.TextInput("Alias"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.DRIVERS_LICENSE]=new e([new DialogInput.TextInput("Number"),new DialogInput.AlphaDateInput("Expiration Date"),new DialogInput.TextInput("License Class"),new DialogInput.TextInput("Name"),new DialogInput.TextInput("Address"),new DialogInput.TextInput("City / Town"),new DialogInput.TextInput("State"),new DialogInput.TextInput("ZIP / Postal Code"),new DialogInput.TextInput("Country"),
new DialogInput.AlphaDateInput("Date of Birth"),new DialogInput.TextInput("Sex"),new DialogInput.TextInput("Height"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.EMAIL]=new e([new DialogInput.TextInput("Username"),new DialogInput.PasswordInput("Password"),new DialogInput.TextInput("Server"),new DialogInput.TextInput("Port"),new DialogInput.TextInput("Type"),new DialogInput.TextInput("SMTP Server"),new DialogInput.TextInput("SMTP Port"),new DialogInput.TextArea("Notes")]);
this.noteForms[Note.prototype.NOTE_TYPES.HEALTH_INSURANCE]=new e([new DialogInput.TextInput("Company"),new DialogInput.TextInput("Company Phone"),new DialogInput.TextInput("Policy Type"),new DialogInput.TextInput("Policy Number"),new DialogInput.TextInput("Group ID"),new DialogInput.TextInput("Member Name"),new DialogInput.TextInput("Member ID"),new DialogInput.TextInput("Physician Name"),new DialogInput.TextInput("Physician Phone"),new DialogInput.TextInput("Physician Address"),new DialogInput.TextInput("Co-pay"),
new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.IM]=new e([new DialogInput.TextInput("Type"),new DialogInput.TextInput("Username"),new DialogInput.PasswordInput("Password"),new DialogInput.TextInput("Server"),new DialogInput.TextInput("Port"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.INSURANCE]=new e([new DialogInput.TextInput("Company"),new DialogInput.TextInput("Policy Type"),new DialogInput.TextInput("Policy Number"),new DialogInput.AlphaDateInput("Expiration"),
new DialogInput.TextInput("Agent Name"),new DialogInput.TextInput("Agent Phone"),new DialogInput.TextInput("URL"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.MEMBERSHIP]=new e([new DialogInput.TextInput("Organization"),new DialogInput.TextInput("Membership Number"),new DialogInput.TextInput("Member Name"),new DialogInput.AlphaDateInput("Start Date"),new DialogInput.AlphaDateInput("Expiration Date"),new DialogInput.TextInput("Website"),new DialogInput.TextInput("Telephone"),
new DialogInput.PasswordInput("Password"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.CREDIT]=new e([new DialogInput.TextInput("Name on Card"),new DialogInput.TextInput("Type"),new DialogInput.TextInput("Number"),new DialogInput.TextInput("Security Code"),new DialogInput.AlphaDateInput("Start Date",{includeDay:!1}),new DialogInput.AlphaDateInput("Expiration Date",{includeDay:!1}),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SSN]=new e([new DialogInput.TextInput("Name"),
new DialogInput.TextInput("Number"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SOFTWARE_LICENSE]=new e([new DialogInput.TextInput("License Key"),new DialogInput.TextInput("Licensee"),new DialogInput.TextInput("Version"),new DialogInput.TextInput("Publisher"),new DialogInput.TextInput("Support Email"),new DialogInput.TextInput("Website"),new DialogInput.TextInput("Price"),new DialogInput.AlphaDateInput("Purchase Date"),new DialogInput.TextInput("Order Number"),new DialogInput.TextInput("Number of Licenses"),
new DialogInput.TextInput("Order Total"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SSH_KEY]=new e([new DialogInput.TextInput("Bit Strength"),new DialogInput.TextInput("Format"),new DialogInput.TextInput("Passphrase"),new DialogInput.TextArea("Private Key",void 0,"noResize",{inputButton:Strings.translateString("Copy"),inputButtonHandler:function(){this.dialog.vaultItem.copyPrivateKey()}}),new DialogInput.TextInput("Public Key"),new DialogInput.TextInput("Hostname"),
new DialogInput.AlphaDateInput("Date"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.WIFI]=new e([new DialogInput.TextInput("SSID"),new DialogInput.PasswordInput("Password"),new DialogInput.TextInput("Connection Type"),new DialogInput.TextInput("Connection Mode"),new DialogInput.TextInput("Authentication"),new DialogInput.TextInput("Encryption"),new DialogInput.TextInput("Use 802.1X"),new DialogInput.TextInput("FIPS Mode"),new DialogInput.TextInput("Key Type"),new DialogInput.TextInput("Protected"),
new DialogInput.TextInput("Key Index"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.SERVER]=new e([new DialogInput.TextInput("Hostname"),new DialogInput.TextInput("Username"),new DialogInput.PasswordInput("Password"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.PASSPORT]=new e([new DialogInput.TextInput("Type"),new DialogInput.TextInput("Name"),new DialogInput.TextInput("Country"),new DialogInput.TextInput("Number"),new DialogInput.TextInput("Sex"),
new DialogInput.TextInput("Nationality"),new DialogInput.TextInput("Issuing Authority"),new DialogInput.AlphaDateInput("Date of Birth"),new DialogInput.AlphaDateInput("Issued Date"),new DialogInput.AlphaDateInput("Expiration Date"),new DialogInput.TextArea("Notes")]);this.noteForms[Note.prototype.NOTE_TYPES.GENERIC]=new e([new DialogInput.TextArea("Notes",null)],["noteContent"])};NoteDialog.prototype.addAttachment=function(a){a&&(this.addedAttachments.push(a),a=a.newDisplayObject(),this.containers.attachments?
this.containers.attachments.addChild(a):this.initializeAttachmentContainer([a]))};NoteDialog.prototype.setNoteFields=function(a){a=a||Note.prototype.NOTE_TYPES.GENERIC;LPTools.removeDOMChildren(this.noteFormElement);var c=this.noteForms[a];if(c){var b=!1;null===c.element&&(c.initialize(this),b=!0);this.noteFormElement.appendChild(c.element);this.noteFormElement.scrollTop=0;this.inputFields.extra=c.inputs;b&&this.adjustedView&&c.inputs.adjustView();this.setNoteTypeImage(a)}};NoteDialog.prototype.add=
function(a){(new Note).addFromDialog(a,this.getGroup(a),this.data.saveOptions)};NoteDialog.prototype.getData=function(){var a=DialogWithGroupInput.prototype.getData.apply(this,arguments);if(this.removedAttachments&&0<this.removedAttachments.length||this.addedAttachments&&0<this.addedAttachments.length){a.attacharraychanges={};var c=this.addedAttachments,b=a.attacharraychanges;if(c){for(var d=[],f=0,e=c.length;f<e;++f)d.push(c[f]._data);0<d.length&&(b.add=d)}c=this.removedAttachments;b=a.attacharraychanges;
if(c){d=[];f=0;for(e=c.length;f<e;++f)d.push(c[f].getID());0<d.length&&(b.remove=d)}}return a};NoteDialog.prototype.close=function(a){if(Dialog.prototype.close.apply(this,arguments)&&this.temporaryNoteTypeOptionValue){var c=this.temporaryNoteTypeOptionValue;this.inputFields.notetype.removeValue(this.temporaryNoteTypeOptionValue,Note.prototype.NOTE_TYPES.GENERIC);this.noteTypeOptions=this.noteTypeOptions.filter(function(a){return a.value!==c});delete this.noteForms[c];this.temporaryNoteTypeOptionValue=
null}};var e=function(a,c){this.inputs=new DialogInput.NestedFields;this.inputsArray=[];if(a instanceof Array){this.inputsArray=a;for(var b=0,d=a.length;b<d;++b){var e=a[b];this.inputs[e.field]=e}}this.$_element=this.element=null;this.additionalClasses=c};e.prototype.initialize=function(a){var c=["settings"];this.additionalClasses&&(c=c.concat(this.additionalClasses));this.element=LPTools.createElement("table",c);this.$_element=$(this.element);for(var c=LPTools.createElement("tbody"),b=0,d=this.inputsArray.length;b<
d;++b){var e=this.inputsArray[b],g=e.build();g.setAttribute("class","settingsRow");c.appendChild(g);e.dialog=a}LPTools.addZebraStriping(c);this.element.appendChild(c);Strings.translate(this.element)}})(document);
