var g_notifytype=null,g_notifydata=null,g_matchingsites=null;function oninitnotify(){}
function onshownotify(){lpdbg("notify","showing notification");var e=getBG();if(e){lpdbg("notify","got background page");g_notifytype=e.g_notification_type;g_notifydata=e.g_notification_data;$("#body").css("background","#e6e6e6");$("#body").css("minHeight","auto");if("error"==g_notifytype){"undefined"!=typeof g_notifydata.yellow&&g_notifydata.yellow||($("#body").css("background","#d32d27"),$("#notifytable").css("color","#fff"),$("#notifymsg").css("color","#fff"));LP_decimate_children(document.getElementById("notifymsg"));
for(var a="string"==typeof g_notifydata.msg?g_notifydata.msg.split("<br/>"):[],b=0;b<a.length;b++)0<b&&document.getElementById("notifymsg").appendChild(document.createElement("br")),document.getElementById("notifymsg").appendChild(document.createTextNode(a[b]));document.getElementById("notifyfeedbackbtn").style.display=g_notifydata.showFeedback?"inline":"none";document.getElementById("notifytryagainbtn").style.display=g_notifydata.showLogin?"inline":"none";g_notifydata.custombutton&&g_notifydata.customaction?
(document.getElementById("notifytryagainbtn").style.display="none",document.getElementById("notifycustombtn").value=g_notifydata.custombutton,document.getElementById("notifycustombtn").style.display="inline",document.getElementById("notifycustombtn").addEventListener("click",function(){getBG().openURL(g_notifydata.customaction);closemole()})):document.getElementById("notifycustombtn").style.display="none";document.getElementById("notifycreateaccountbtn").style.display=g_notifydata.showCreateAccount&&
!e.LPISLOC?"inline-block":"none";document.getElementById("notifydisablebtn").style.display=g_notifydata.multifactor_disable_url?"inline-block":"none";document.getElementById("notifydisablesinglebtn").style.display="none";document.getElementById("notifystarttrialbtn").style.display=g_notifydata.showStartTrial?"inline-block":"none"}else if("save"==g_notifytype)$("#body").css("background","#87d087"),set_innertext(document.getElementById("notifymsg"),gs("Should LastPass remember this password?")+" ("+
g_notifydata.tld+")");else if("alert"==g_notifytype){lpdbg("notify","notify type is alert");$("#body").css("background","#ddd");document.getElementById("lefticon").src="images/warning.png";"weak"==g_notifydata.alerttype?(lpdbg("notify","alert type is weak"),set_innertext(document.getElementById("notifymsg"),gs("Weak Password")),set_innertext(document.getElementById("alertdescription"),gs("LastPass has detected that you are using a weak password for the site below. We recommend going to your account settings for this site, and creating a new password. Use LastPass to generate a unique, strong password for this account. You can then save the changes on the site, and to LastPass.")),
1==g_notifydata.pwch&&set_innertext(document.getElementById("notifyseccheck"),gs("Change Password Automatically"))):"duplicate"==g_notifydata.alerttype?(lpdbg("notify","alert type is duplicate"),set_innertext(document.getElementById("notifymsg"),gs("Duplicate password")),set_innertext(document.getElementById("alertdescription"),gs("LastPass has detected that you have used the password for this login on other sites, too. We recommend going to your account settings for this site, and creating a new password. Use LastPass to generate a unique, strong password for this account. You can then save the changes on the site, and to LastPass.")),
1==g_notifydata.pwch&&set_innertext(document.getElementById("notifyseccheck"),gs("Change Password Automatically"))):"mpw_reuse"==g_notifydata.alerttype?(set_innertext(document.getElementById("notifymsg"),gs("Security Alert: Master Password Reused")),set_innertext(document.getElementById("alertdescription"),gs("LastPass has detected that you have used your Master Password as the password for this site. It is highly recommended that you change your LastPass Master Password to protect all of your online accounts."))):
"hacked"==g_notifydata.alerttype&&(LP_decimate_children(document.getElementById("notifymsg")),document.getElementById("notifymsg").appendChild(document.createTextNode("Security Alert:")),document.getElementById("notifymsg").appendChild(document.createElement("br")),document.getElementById("notifymsg").appendChild(document.createTextNode("Site Hacked Detected")),set_innertext(document.getElementById("alertdescription"),"We detected that a site you use has announced it was hacked. Please change your password for that site now."),
document.getElementById("disables").style.display="none",set_innertext(document.getElementById("notifyseccheck"),"Change Password Automatically"));var c=document.createElement("span");c.className="alertheader";a=[];for(b=0;b<document.getElementById("notifymsg").childNodes.length;b++)a[b]=document.getElementById("notifymsg").childNodes[b];LP_decimate_children(document.getElementById("notifymsg"));for(b=0;b<a.length;b++)c.appendChild(a[b]);document.getElementById("notifymsg").appendChild(c);set_innertext(document.getElementById("alertsite"),
g_notifydata.name);set_innertext(document.getElementById("alertusername"),g_notifydata.username);lpdbg("notify","done creating alert");document.body.className+=" alertbody"}else if("change"==g_notifytype){g_matchingsites=e.getsites(g_notifydata.tld,!0);if(1==array_length(g_matchingsites))for(b in g_matchingsites){a=gs("LastPass detected a password change for user:")+" "+of(e.getusernamefromacct(e.g_sites[b]));break}else a=gs("LastPass detected a password change for domain:")+" "+of(g_notifydata.tld);
set_innertext(document.getElementById("notifymsg"),a)}else if("upgrade"==g_notifytype)g_notifydata.upgrade?(set_innertext(document.getElementById("notifymsg"),gs("An Update is Available. Would you like to install?")),document.getElementById("notifyyesbtn").style.display="inline-block",document.getElementById("notifynobtn").style.display="inline-block"):(g_notifydata.checking?set_innertext(document.getElementById("notifymsg"),gs("Checking For Updates...")):set_innertext(document.getElementById("notifymsg"),
gs("No Updates Are Available")),document.getElementById("notifyyesbtn").style.display="none",document.getElementById("notifynobtn").style.display="none");else if("lpalert"==g_notifytype){var f=g_notifydata.data,d=f.lpa_title,c=f.lpa_msg,b=f.lpa_onclicktext,g=f.lpa_onclickurl,g=g+("?lang="+en(lpGetPref("language",navigator.language))),a=f.lpa_iconurl?of(f.lpa_iconurl):"",f=f.lpa_secondary_msg;lpdbg("notify","alert type is lpalert");LP_decimate_children(document.getElementById("notifylpalert"));var k=
document.createElement("h2");k.id="lpalertheader";var h=document.createElement("img");h.id="lpalertheaderimg";h.setAttribute("src","images/lastpass_dialog_24x24.png");k.appendChild(h);k.appendChild(document.createTextNode(d));document.getElementById("notifylpalert").appendChild(k);d=document.createElement("p");h=document.createElement("img");h.id="lpalert_icon";h.setAttribute("src",a);d.appendChild(h);document.getElementById("notifylpalert").appendChild(d);d=document.createElement("p");set_innertext(d,
c);document.getElementById("notifylpalert").appendChild(d);d=document.createElement("p");c=document.createElement("span");c.id="lpalert_warning";set_innertext(c,f);d.appendChild(c);document.getElementById("notifylpalert").appendChild(d);d=document.createElement("p");d.id="btn_wrap";c=document.createElement("a");c.id="changepw";c.setAttribute("target","_blank");c.setAttribute("href","#");c.className="rbtn nbtn btn_exp_h btn_midi";set_innertext(c,b);d.appendChild(c);document.getElementById("notifylpalert").appendChild(d);
document.getElementById("changepw").onclick=function(){getBG().openURL(g);0===g.indexOf(base_url)&&e.unlock_plug2web();return!1};$("#lpnotify").css("display","block");$("#body").css("background","#ffffff");$("#notifytable").css("color","#fff");$("#body").css("width","450px");$("#notifytable").css("width","450px");$("#tablenotify").css("color","#00000");$("#lpalert_Warning").css("color","#d32d27");$("#notifytable").css("white-space","normal");set_innertext(document.getElementById("alertdescription"),
gs("LastPass has detected that you have used the password for this login on other sites, too. We recommend going to your account settings for this site, and creating a new password. Use LastPass to generate a unique, strong password for this account. You can then save the changes on the site, and to LastPass."));a||(document.getElementById("lpalert_icon").style.display="none")}a=document.getElementsByTagName("div");for(b=0;b<a.length;b++)lpdbg("notify","looking at div "+b),0==a[b].id.indexOf("notify")&&
"popup"!=a[b].id.substring(a[b].id.length-5)&&(lpdbg("notify","hiding div "+b),a[b].style.display="none");"undefined"==typeof document.getElementById("notify"+g_notifytype)&&onshownotify();document.getElementById("notify"+g_notifytype).style.display="block";lpdbg("notify","done showing notification");document.body.style.minHeight="inherit"}resize_panel()}
function resize_panel(){g_isfirefoxsdk?setTimeout(function(){getBG().resize_panel(Math.max(400,$(document).width()+10),$(document.body).height()+10)},0):g_issafari&&"error"==g_notifytype&&setTimeout(function(){safari.self.width=Math.max(400,$(document).width()+10);safari.self.height=$(document.body).height()+10},0)}function savethesite(){var e=getBG();g_notifydata.addsite=1;e.g_site_data=g_notifydata;e.openURL(getchromeurl("site.html"),null,e.g_site_data);closemole()}
function clicknever(e){var a={neversite:{title:gs("Never For This Site"),cmd:"neversite"},neverdomain:{title:gs("Never For This Domain"),cmd:"neverdomain"}},b=[],c,f={};for(c in a)if(null==a[c])b+='<div id="'+c+'" class="notifyspacer"><div></div></div>';else{var d=document.createElement("div");d.id=c;d.className="notifybutton";"undefined"!=typeof a[c].cmd&&d.setAttribute("data-lpcmd",a[c].cmd);var g=document.createElement("div");set_innertext(g,a[c].title);d.appendChild(g);b.push(d);f[c]=function(){notifyaction(this.getAttribute("data-lpcmd"))}}a=
document.getElementById("notifyneverpopup");LP_decimate_children(a);a.style.left=e.x;for(c=a.style.top=0;c<b.length;c++)a.appendChild(b[c]);for(c in f)document.getElementById(c).addEventListener("click",f[c])}function notifyaction(e){var a=g_notifydata.url,b=getBG();"neversite"==e?a=b.lpcanonizeUrl(a):"neverdomain"==e&&(a=b.lp_gettld_url(a));b.addNever(a);closemole()}
function changeconfirm(){if(1==array_length(g_matchingsites))for(var e in g_matchingsites){getBG().changePassword(g_notifydata.newpw,Array(e));break}else{if(g_browseraction){receiveBG({cmd:"changepw",newpw:g_notifydata.newpw,tld:g_notifydata.tld});return}getBG().openchangepw(g_notifydata.newpw,g_notifydata.tld)}closemole()};
