var do_bgiconinput=!0,g_CSPCHECKER=0;
function popupfill_create_iframe(a,f,c,d,b,e,h,k,m,l){if(do_experimental_popupfill&&a){var g=a.getElementsByTagName("input");for(k=0;k<g.length&&k<MAX_INPUTS_HARD;k++){var q=g[k];"undefined"!==typeof q.maxLength&&"password"==q.type&&(g_isie||sendBG({cmd:"set_possiblemax",max:q.maxLength}))}g_isie&&init_LPfn()&&LPfn&&LPfn.resetSafeCloseIframe();g_iframeclose_starttime=null;f=parseInt(f)+"px";c=parseInt(c)+"px";if((q=a.body)&&!a.getElementById(LPMAGICIFRAME+d)){g=a.createElement("iframe");g.id=LPMAGICIFRAME+
d;g.name=LPMAGICIFRAME+d;g_iframe_docked=!0;if(g_isie)g.src="https://lastpass.com/fake/fake.php#framesrc=LPMAGIC",init_LPfn()&&LPfn&&9>LPfn.getDocumentMode(a)&&(g.setAttribute("allowTransparency",!0),g.setAttribute("frameBorder",0),g.allowTransparency=!0,g.frameBorder=0);else if("undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk){g_popup_iframe=g;var p=a.location.href,p=lpParseUri(p);g.setAttribute("lpsrc",p.protocol+"://"+Math.floor(1E8*Math.random())+"."+p.host+"/lpblankiframe.local")}else{if(bg.get("LPContentScriptFeatures").is_infield_enabled){l.eventType=
"undefined"!=typeof event&&event&&event.type?event.type:"click";csTop.LPInfieldFrame.openFrame(l);return}p=urlprefix+"popupfilltab.html";"undefined"===typeof chrome&&"undefined"!=typeof lplanguage&&(p+="?lplanguage="+lplanguage);g.src=p}0>parseInt(f)&&(f="0px");0>parseInt(c)&&(c="0px");dotrans?(g_frame_css_str="display:block !important; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:none !important; opacity: 1.0 !important; margin:0 !important; padding:0 !important;",
"undefined"!=typeof g_isie&&g_isie&&(g_frame_css_str+="background-color:transparent !important;background-image:none !important;filter:alpha(opacity=100) !important ; ")):g_frame_css_str="display:block; position:absolute !important; visibility:visible !important; opacity: 1.0 !important ; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); filter:alpha(opacity=100) !important; ";
g.style.cssText=g_frame_css_str;try{if(framesetarr=document.getElementsByTagName("frameset"),0==framesetarr.length)q.appendChild(g);else if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&m&&1==framesetarr.length){var n=LPJSON.stringify(g_frame_css_str+" border: none;");m.body.setAttribute("data-lp-gcss",n);var r=m.getElementsByTagName("FRAMESET");if(r&&r[0]){var t=r[0].getElementsByTagName("FRAME");if(t){var u=t[0].contentWindow.document;u.body.setAttribute("data-lp-gcss",n);u.body.appendChild(g)}else m.body.appendChild(g)}}else for(m=
!1,k=0;k<framesetarr.length;k++){for(n=0;n<framesetarr[k].children.length;n++)if("FRAME"==framesetarr[k].children[n].tagName)if(cf=framesetarr[k].children[n].contentWindow.document,null!=cf.getElementById(d)){if(m=!0,toappendTo=cf.getElementById(d),l&&l.framesrc&&l.framesrc==get_doc_location_href(cf))break}else if(null!=cf.getElementsByName(d)&&0!=cf.getElementsByName(d).length&&(m=!0,toappendTo=cf.getElementsByName(d)[0],l&&l.framesrc&&l.framesrc==get_doc_location_href(cf)))break;if(m){try{toappendTo.ownerDocument.body.setAttribute("data-lp-gcss",
LPJSON.stringify(g_frame_css_str)),toappendTo.parentNode.appendChild(g)}catch(v){framesetarr[k].children[n].contentWindow.document.body.appendChild(g)}break}}}catch(v){verbose_log("append failed! "+v);return}g_isie&&!LP_getloggedin()&&g.parentNode.removeChild(g);g.width=parseInt(e)+"px";g_isie?(g.height="38px",g.height="173px"):g.height="26px";"undefined"!=typeof b&&0<b&&(g.height=24*b+23+"px");0<parseInt(h)?g.height=parseInt(h)+"px":g.height=parseInt(g.height)+"px";d=parseInt(g.width)+"px";b=parseInt(g.height)+
"px";g.style.cssText=g_frame_css_str+("width: "+d+" !important; height: "+b+" !important; top:"+c+" !important; left:"+f+" !important; ");setTimeout(function(){0==g_CSPCHECKER&&"undefined"===typeof chrome&&"object"===typeof safari&&do_iframe_sad_msg(a)},5E3)}}}
function weasel(a,f){LPCTR("weasel");if(do_experimental_popupfill){if("undefined"==typeof a||0==a||1==a||5>a)a=200;g_weaseled=!0;if(g_isdebug){var c=(new Date).getTime(),d=c-g_last_weasel;d>2*a&&verbose_log("last weasel cycle took too long"+d+" ms")}popupfill_resize();g_isdebug&&(c=(new Date).getTime()-c,c>a&&verbose_log("last resize took too long "+c+" ms"),g_last_weasel=(new Date).getTime());g_weasel_id=setTimeout(function(){weasel(a)},a)}}var g_last_weasel=0;
function issaveall(a){a=a.elements;for(var f=0,c=0,d=0,b=0;b<a.length;b++){var e=a[b].type;"password"==e?c++:"text"==e||"tel"==e||"email"==e?f++:"textarea"==e&&d++}return 1==f&&1==c&&0==d?!1:!0}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,f,c,d){if(!do_experimental_popupfill)return null;"undefined"==typeof d&&(d=!1);if(!a||null==f)return null;var b=f.style.left,e=f.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(b)||0>parseInt(e)){var h=a.getElementById(LPMAGICIFRAME+LP_pickFieldName(a,f));if(null!=h&&(h=LP_getAbsolutePos(a,h,null,d)))return e=parseInt(h.top),b=parseInt(h.left),isNaN(e)||isNaN(b)?null:{posx:b+"px",posy:e+"px"}}LP_pickFieldName(a,f);if(null!=f){h=LP_getAbsolutePos(a,
f,null,d);null!=h&&(b=parseInt(h.left)+POPUP_FIELD_OFFSET+"px",e=parseInt(h.top)+parseInt(h.height)+"px",g_do_icon_number_hint&&(e=parseInt(h.top)+parseInt(h.height)+4+"px"));if(null==c||0==c||""==c)h=LP_getElementByIdOrName(a,LPMAGICIFRAME+LP_pickFieldName(a,f)),c=null!=h?(c=LP_getAbsolutePos(a,h,null,!0))?c.width:0:0;if(!d){d=LP_getWindowWidth(window,!0);if(!d)return{posx:0,posy:0};parseInt(c)+parseInt(b)>d&&(b=d-parseInt(c)-20+"px")}}if(""==b||"auto"==b||""==e||"auto"==e)return null;b=parseInt(b);
e=parseInt(e);return"NaN"==b||"NaN"==e?null:{posx:b+"px",posy:e+"px"}}function verbose_log(a){verbose&&("undefined"!=typeof Date?console_log("["+g_docnum+"] "+((new Date).getTime()-g_tsstart)+" : "+a):console_log("["+g_docnum+"] "+a))}function is_watermark(a){return!1}function checkAskGenerate(){}function sendKey(a,f){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(f,0,KeyEvent[keyName],!1)}catch(c){lpdbg("error",c)}return null}
function send_simulated_key(a,f,c,d){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;var b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keydown",!0,!0,null,!1,!1,d,!1,c,f):b.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,d,!1,c,c);var e=a.dispatchEvent(b);e&&"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk&&(b=a.ownerDocument.createEvent("KeyboardEvent"),b.initKeyEvent("keypress",!0,
!0,null,!1,!1,d,!1,c,f),e=a.dispatchEvent(b));b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keyup",!0,!0,null,!1,!1,d,!1,c,f):b.initKeyboardEvent("keyup",!0,!0,null,!1,!1,d,!1,c,c);a.dispatchEvent(b);return e}var g_formmutations=0;
function checkShouldRecheck(a){function f(a){a||(a=LP_derive_doc());return a?LP_isSinglePageApp(a)||isASPpage()?!0:g_did_muto?(g_did_muto=!1,!0):!1:!1}var c=20,d=!1,b=document,e=window;a&&"object"==typeof a||(a={});var h=!1,k=!1,m=!1;"undefined"!=typeof a.fromclick&&(h=a.fromclick);"undefined"!=typeof a.frommuto&&(k=a.frommuto);"undefined"!=typeof a.skipfill&&(m=a.skipfill);g_pending_recheck=!1;debug_checkpoint("entered checkShouldRecheck, clear pending state");LP_isSinglePageApp(b)&&(c=100);if(g_formmutations>
c)return verbose_log("Abort"),!1;if(LP_should_ignore_this_doc(b,h))return!1;if(do_experimental_popupfill&&0<=g_input_cnt&&0<=g_form_cnt){var c=countInputs(document),h=countFormEquivalents(document),l=computeFingerprint(document);verbose_log("checkShouldRecheck() : # inputs was "+g_input_cnt+", now "+c+" #forms was "+g_form_cnt+" now "+h+", fingerprint was "+g_input_fingerprint+" now "+l);if(g_input_cnt!=c||g_form_cnt!=h||g_input_fingerprint!=l)g_formmutations++,formcachereset(document),fieldcachereset(document),
g_isie?setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3):(get_doc_location_href(b),setTimeout(function(){LPCTR("recheck");var c=LP_get_last_url_history(b);c||(LP_put_last_url_history(b),c=LP_get_last_url_history(b));var d=c.href,c=c.href_hash,h=get_doc_location_href(b);k||h===d&&a.href===h&&c===a.href_hash?g_pending_eval||evalScriptsInFrame(e,b,!0,{skipfill:m||!f(b),href:d,href_hash:c,frommuto:k}):(formcachereset(b),fieldcachereset(b),g_form_cnt=g_input_cnt=0,delete b.body._lpcrdone,
LP_put_last_url_history(b),c=LP_get_last_url_history(b),a.href=c.href,a.href_hash=c.href_hash,g_pending_recheck||checkShouldRecheck(a))},200)),g_input_cnt=c,g_form_cnt=h,g_input_fingerprint=l,d=!0}return d}function is_watermark_password(a){return!1}
function createpopuptoplevel_handler(a){if(!a)return!1;var f=LP_derive_doc();g_iscasper&&a.override_doc&&(f=a.override_doc);var c=parseInt(a.from_iframe.posx),d=parseInt(a.from_iframe.posy),b=a.from_iframe.id,e=a.from_iframe.rows,h=a.from_iframe.width,k=a.from_iframe.framename,m=a.from_iframe.framesrc,l=null;if(is_your_popup_showing(f))return!1;var g=find_iframe_pos(f,k,m,!1);g||(g=find_iframe_pos(f,k,m,!0),null!==g&&"undefined"!=typeof g.cframedoc?l=g.cframedoc:pass);g?(c=parseInt(g.left)+c+"px",
d=parseInt(g.top)+d+"px",g_toplevel_initial_abs_x=c,g_toplevel_initial_abs_y=d):d=c="10px";a.from_iframe.iframe=find_iframe(f,k,m,!1);popupfill_create_iframe(f,c,d,b,e,h,"90px",!1,l,a.from_iframe);g_popupfill_iframe_width_save=h;return!0}var g_toplevel_initial_abs_x=null,g_toplevel_initial_abs_y=null;
function popupfillresize_handler(a){0<a.width&&(g_minwidth_override=parseInt(a.width));0<a.height&&(g_minheight_override=parseInt(a.height));!g_create_iframe_in_top||g_isie||g_isfirefox||!LP_inIframe(window)&&toplevel_iframe_state_get()&&relocate_popupfill_iframes(document)}
function find_iframe_pos(a,f,c,d){if(!a)return null;var b,e;try{var h=a.getElementsByTagName("IFRAME");d&&(h=a.getElementsByTagName("FRAME"));if(!f&&1==h.length)return LP_getAbsolutePos(a,h[0],!0,!0);var k=[];for(b=0;b<h.length&&50>b;b++)k[b]=h[b];for(b=0;b<k.length;b++)if(k[b].name&&""!=f&&k[b].name==f||k[b].src&&""!=c&&compare_puny_urls(k[b].src,c))return LP_getAbsolutePos(a,k[b],!0,!0);if(d)for(b=0;b<k.length;b++){var m=k[b].contentWindow.document,l=m.getElementsByTagName("FRAME");for(e=0;e<l.length&&
50>e;e++)if(l[e].name&&""!=f&&l[e].name==f||l[e].src&&""!=c&&l[e].src==c){var g=LP_getAbsolutePos(m,l[e],!0,!0);g.cframedoc=m;return g}}}catch(q){}return null}
function find_iframe(a,f,c,d){if(!a)return null;var b,e;try{var h=a.getElementsByTagName("IFRAME");d&&(h=a.getElementsByTagName("FRAME"));if(!f&&1==h.length)return h[0];a=[];for(b=0;b<h.length&&50>b;b++)a[b]=h[b];for(b=0;b<a.length;b++)if(a[b].name&&""!=f&&a[b].name==f||a[b].src&&""!=c&&compare_puny_urls(a[b].src,c))return a[b];if(d)for(b=0;b<a.length;b++){var k=a[b].contentWindow.document.getElementsByTagName("FRAME");for(e=0;e<k.length&&50>e;e++)if(k[e].name&&""!=f&&k[e].name==f||k[e].src&&""!=
c&&k[e].src==c)return k[e]}}catch(m){}return null};
