var SHOULD_DO_LOGIN_ONLY=!0,SHOULD_DO_ALWAYS=!1;
function popupfill_shoulddofield(a,b,d){var c=["lpcurrpasselt","lpcurruserelt"];if(do_experimental_popupfill&&null!=b&&"undefined"!=typeof b.type&&"hidden"!=b.type&&("text"==b.type||"password"==b.type||"email"==b.type||!d&&"tel"==b.type||!d&&"url"==b.type||!d&&"textarea"==b.type)){var e=LP_pickFieldName(a,b);if(lp_in_array(e,c))return decision_log(a,"DE28",{param1:e}),!1;if(is_search_field(a,b,!d)||is_date_field(b)||LP_looksLikeOTPField(a,b)||LP_explicit_ignored(a,b)||LP_implicit_ignored(a,b)||LP_isCaptchaField(b))return!1;
if(d){if(!chk_form_has_password(a,b.form)&&!checkDocumentForLoginOrphans(a))return verbose&&(b=LP_pickFormName(a,b.form),decision_log(a,"DE29",{param1:b})),!1;if(b.form&&is_shopping_form(a,b.form)&&g_aspx_hack&&(isASPpage()&&2<a.getElementsByTagName("form").length||!isASPpage()))return!1}}else return!1;return!0}
function chk_form_ask_generate(a,b,d){var c=null;if(null==a||null==b||!b||!b.tagName||"FORM"!=b.tagName.toUpperCase())return!1;var e=LP_pickFormName(a,b),f;if(!d&&(f=formcacheget(a,e,"ask_generate"),null!=f))return f;var g="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(g.length<MAX_FORM_ELEMENTS_HARD,"form "+e+" has too many inputs");if(g.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,e,"is_login",!1),!1;try{var l=gettldcached(a.location.href)}catch(u){return!1}var m=
f=0,p=3;d&&(p=2);g_aspx_hack&&isASPpage()&&(p=7);if("tumblr.com"==l&&(tumblr_action_btn=a.getElementById("signup_forms_submit"),null!=tumblr_action_btn)){d=tumblr_action_btn.getElementsByTagName("SPAN");var h;for(h=0;h<d.length;h++)if(0<=d[h].className.indexOf("login_btn")&&checkIsDisplayed(a,d[h],0,l))return!1}if(!checkIsDisplayed(a,b,0,l))return decision_log(a,"DE30"),!1;d=LP_getname(b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=d&&(0<=d.toLowerCase().indexOf("signup")||0<=d.toLowerCase().indexOf("register"))&&
-1==d.toLowerCase().indexOf("login"))return decision_log(a,"DE31",{param1:e}),formcacheset(a,e,"ask_generate",!0),!0;var r;if("undefined"!=typeof Math){d=Math.floor(1E4*Math.random());r=g=h=0;var n=null,t=b.elements.length;Checkpoint.assert(t<MAX_FORM_ELEMENTS_SOFT,"form "+e+" too big 1");t>MAX_FORM_ELEMENTS_SOFT&&(t=MAX_FORM_ELEMENTS_SOFT);for(var q=0;q<t;q++){var k=b.elements[q];"INPUT"==k.tagName&&("password"==k.type?h++:"text"!=k.type&&"email"!=k.type||g++);if("INPUT"==k.tagName&&"submit"==k.type||
"BUTTON"==k.tagName)if(r++,n=k,10<r&&b.elements.length>MAX_FORM_ELEMENTS_SOFT)return!1}if(1==r&&2>=g&&0<h&&checkButtonHint(n))return decision_log(a,"DE32"),!1;g=b.elements;for(q=0;q<MAX_FORM_ELEMENTS_SOFT&&q<g.length;q++)if(k=g[q],r=!1,!("FIELDSET"==k.tagName||!valid_by_role(a,k)||LP_fieldIsDisabled(k)||LP_treat_as_hidden(k)||"expedia.com"!=l&&!checkIsDisplayed(a,k,0,l,d)||g_use_wacky_disp&&!is_wacky_disp(a,k))){if("text"==k.type&&is_watermark(k.className)&&is_watermark_password(k))try{k.type="password"}catch(u){r=
!0}n=LP_elt_get_text(k);if("BUTTON"==k.tagName&&"submit"==k.type&&null!=n&&0<=n.indexOf("Create")||"BUTTON"==k.tagName&&"submit"==k.type&&null!=n&&0<=n.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Create")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Sign me up")||"INPUT"==k.tagName&&"image"==k.type&&null!=k.value&&"create"==k.value)p=2,
decision_log(a,"DE33",{param1:e});if(1<h&&LP_passwordAlt(a,k))m++;else if(n=fieldIsDoublePassword(a,k),!(b&&"form1"==b.id&&b.action&&"string"==typeof b.action&&b.action.indexOf(".aspx"))||"text"!=k.type||n!==DOUBLE_PW_VISIBLE&&n!==DOUBLE_SECRET_PW_VISIBLE)if(!do_bgiconinput||"text"!=k.type||n!==DOUBLE_TEXT_VISIBLE&&n!==DOUBLE_SECRET_TEXT_VISIBLE){if("password"==k.type||r||"text"==k.type&&n===DOUBLE_TEXT_VISIBLE||"text"==k.type&&n===DOUBLE_SECRET_TEXT_VISIBLE){r=k.getAttribute("placeholder");null!=
r&&0<=r.indexOf("Create your")&&(p=2);if("facebook.com"==l&&"string"==typeof k.id&&k.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/))continue;else if("tdbank.com"==l&&"string"==typeof k.name&&"user"==k.name){m++;continue}if(0==f&&1<h&&passwordIsFake(k)){m++;continue}if(0<f&&1<h&&LP_looksLikeOTPField(a,k)){m++;continue}LP_get_input_pattern(a,k)&&!c&&(c=k);f++}else if("email"==k.type||"text"==k.type||"textarea"==k.type||"tel"==k.type||"url"==k.type)if(treat_text_as_password(k))f++;else{if(LP_isForgetField(k))continue;
lpIsVisible(k,!0)&&(r=LP_pickFieldName(a,k),LP_looksLikeOTPField(a,k)?decision_log(a,"DE35",{param1:r}):m++)}if(4<=f||100<=m)return 4<=f&&decision_log(a,"DE37",{param1:e,param2:f,param3:m}),100<=m&&decision_log(a,"DE38",{param1:e,param2:f,param3:m}),formcacheset(a,e,"ask_generate",!1),!1;if(2<=f||1<=f&&m>=p)return 2<=f&&decision_log(a,"DE39",{param1:e,param2:f,param3:m}),1<=f&&m>=p&&decision_log(a,"DE40",{param1:e,param2:f,param3:m}),formcacheset(a,e,"ask_generate",!0),c&&(g_isie||g_isfirefox||sendBG_generate_pattern(a,
c)),!0}}decision_log(a,"DE41",{param1:e,param2:f,param3:m});formcacheset(a,e,"ask_generate",!1);return!1}}function passwordIsFake(a){var b=/(?:Account)|(?:Member)|(?:IUO_NAME)/i,d=a.name;return b.exec(a.id)||b.exec(d)?!0:!1}function checkButtonHint(a){if(!a)return!1;var b="INPUT"==a.tagName?a.value:a.innerHTML,d=/(?:Login)|(?:Log.In)|(?:Logon)|(?:Log.on)/i;return d.exec(a.id)||d.exec(b)?!0:!1}
function LP_isForgetField(a){if(!a)return!1;var b=a.id;a=a.name;var d=new RegExp(lpgs("ff_forgot_regexp"),"i");return d.exec(b)||d.exec(a)?!0:!1}function LP_isCaptchaField(a){if(!a)return!1;var b=a.id;a=a.name;var d=new RegExp(lpgs("ff_captcha_regexp"),"i");return d.exec(b)||d.exec(a)?!0:!1}
function element_is_detached(a,b,d){if(!b||!a&&(a=b.ownerDocument,!a))return!1;"undefined"==typeof d&&(d=0);var c=null;try{if(15<d&&(c=!1),null==b.parentNode&&(c=!0),b.parentNode===a.documentElement||b.parentNode===b.ownerDocument.documentElement)c=!1}catch(e){c=!0}return null==c?element_is_detached(a,b.parentNode,d+1):c}
function get_javaservlet_fields(a,b){if(!a)return[];if("undefined"==typeof b||null===b)b=!1;var d=[],c=a.getElementsByName("j_username"),e=a.getElementsByName("j_password");if(1===c.length&&1===e.length)Checkpoint.assert(c[0].form===e[0].form,"javaservlet form mismatch"),d=[c[0],e[0]];else if(!b||1!==c.length&&1!==e.length){var c=a.getElementsByTagName("FORM"),f=LP_getFormsThreshold(a);Checkpoint.assert(c.length<f,"too many forms on page");for(e=0;e<f&&e<c.length;e++)if(c[e].action&&"undefined"!=
typeof c[e].action.indexOf&&0<=c[e].action.indexOf("j_security_check")){f=form_get_username(a,c[e]);g=form_get_password(a,c[e]);f&&g&&(d=[f,g]);break}}else{var g=f=null;1===c.length&&(f=c[0]);1===e.length&&(g=e[0]);d=[f,g]}return d}
function is_random_hashstr(a){return a?(16==a.length||32==a.length)&&a.match(/^[a-zA-Z0-9]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||32==a.length&&a.match(/^[a-f0-9]+$/)||a.match(/_\d{18}[A-Z]{4}_/)||17==a.length&&"a"==a.charAt(0)&&a.match(/^[a-zA-Z0-9_]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||20==a.length&&a.match(/^[A-Z]0[A-F]\d{16}[A-Z]$/)||21==a.length&&a.match(/^[A-Z]0[A-F]\d{17}[A-Z]$/)||18==a.length&&a.match(/^el[0-9a-f]{16}$/)||24<a.length&&a.match(/^yui_[0-9_a-z]+$/)||
14<=a.length&&a.match(/^[a-zA-Z_]{8}[a-zA-Z_]+\[[0-9]{2}[0-9]+\]$/)?!0:!1:!1}function chk_form_changepw_new(){return!0}
function shouldOfferGenerate(a,b){if(null==a||null==b)return null;var d=!1,c=b.form,e=!1;c||(e=checkDocumentForCPWOrphans(a));var f=!0,g=!0,l=check_nevers(a,g_nevers,a.location.href);null!=l&&(f=l.show_for_generate,g=l.show_for_clickable_icon);if(f&&chk_form_ask_generate(a,c)&&isInputFieldPassword(a,b)&&g){if(chk_form_has_password(a,c)&&(d=LP_pickFormName(a,c),(new RegExp(lpgs("ff_loginform_regexp"),"i")).exec(d)))return!1;(currentpw=lpCheckCurrentPWField(c))||(currentpw=lpCheckCurrentPWField(c,!0));
chk_form_changepw(a,c)&&b==lpCheckCurrentPWField(c)?(d=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE42",{param1:g_docnum,param2:LP_pickFormName(a,c),param3:LP_pickFieldName(a,b)})):chk_form_changepw_new(a,c)&&b==currentpw?(d=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE43",{param1:g_docnum,param2:LP_pickFormName(a,c),param3:LP_pickFieldName(a,b)})):(d=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE44",{param1:g_docnum,param2:LP_pickFormName(a,c),param3:LP_pickFieldName(a,b)}))}else!c&&
f&&e&&isInputFieldPassword(a,elt)&&!lpIsFieldCurrentPWField(b)&&(d=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE45",{param1:g_docnum,param2:LP_pickFieldName(a,b)}));return d}function popupfill_shoulddoform(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=b.name,c=b.id,e=["lpmanualform","lpwebsiteeventform"];return d&&lp_in_array(d,e)||c&&lp_in_array(c,e)?!1:!0}
function LP_isRememberCheckbox(a){if(!a||"checkbox"!=a.type)return!1;var b=a.id;a=a.name;var d=new RegExp(lpgs("ff_remember_regexp"),"i");return d.exec(b)||d.exec(a)?!0:!1}
function chk_form_is_nonlogin_form(a,b){if(null==a||null==b||!b||!b.tagName||"FORM"!=b.tagName.toUpperCase())return!1;try{var d=gettldcached(a.location.href)}catch(p){return!1}var c=LP_pickFormName(a,b),e=formcacheget(a,c,"is_nonlogin");if(null!=e)return e;e="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(e.length<MAX_FORM_ELEMENTS_HARD,"form "+c+" has too many inputs");if(e.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,c,"is_nonlogin",!0),!0;if(is_search_form(a,
b))return decision_log(a,"DE46",{param1:c}),formcacheset(a,c,"is_nonlogin",!1),!1;if(!checkIsDisplayed(a,b,0,d))return decision_log(a,"DE47",{param1:c}),!1;var f=d=0,e=b.elements,g=e.length;Checkpoint.assert(g<MAX_INPUTS_HARD,"form "+c+" too big 2");g>MAX_INPUTS_HARD&&(g=MAX_INPUTS_HARD);for(var l=0;l<g;l++){var m=e[l];if("FIELDSET"!=m.tagName&&("email"==m.type||"text"==m.type||"password"==m.type)&&!LP_fieldIsDisabled(m)){if(100<++f)return formcacheset(a,c,"is_nonlogin",!1),!1;if(1!=m.disabled&&valid_by_role(a,
m)&&lpIsVisible(m)&&!LP_treat_as_hidden(m)){if(is_search_field(a,m,!0)&&8>e.length)return decision_log(a,"DE48",{param1:c}),formcacheset(a,c,"is_nonlogin",!1),!1;d++;if(3<=d)return decision_log(a,"DE49",{param1:c}),formcacheset(a,c,"is_nonlogin",!0),!0}}}formcacheset(a,c,"is_nonlogin",!1);return!1}
function treat_text_as_password(a){return a&&"TEXTAREA"!=a.tagName?"text"==a.type&&(0==a.name.indexOf("pass")||0<=a.name.toLowerCase().indexOf(lpgs("Password").toLowerCase()))&&-1==a.name.toLowerCase().indexOf("hint")&&-1==a.name.toLowerCase().indexOf("placeholder")?(new RegExp(lpgs("ff_username_regexp"),"i")).exec(a.name)&&a.form&&a.form.action&&0<=a.form.action.indexOf("login")?!1:!0:!1:!1}function ASP_treat_text_as_password(a){return treat_text_as_password(a)}
function valid_by_role(a,b){if(!b)return!1;a||(a=b.ownerDocument);if(!a)return!1;var d=b.getAttribute("role");d||"INPUT"==b.tagName||(d=b.parentNode.getAttribute("role"));if(!d)return!0;switch(d){case "navigation":case "banner":case "contentinfo":case "note":case "search":case "seealso":return!1;case "columnheader":case "presentation":case "toolbar":case "directory":return!1;default:return!0}}
function should_do_lastpass_here(a){var b=null;if(!a)return!1;if(null!=a.g_content_check_result)return a.g_content_check_result;try{var d=a.location.href;if(0<d.indexOf(".xul")||0<d.indexOf("libsyn.com/embed")||0<d.indexOf("platform.twitter.com/tweet_button")||0<=d.indexOf("facebook.com/plugins/"))b=a.g_content_check_result=!1;null===b&&"complete"!=a.readyState&&"interactive"!=a.readyState&&(verbose_log("answer hazy, try again later"),b=!0);if(null===b){var c=a.body,e=LP_elt_get_text(c).length;null===
b&&2<e&&is_page_JSON(a)&&(b=a.g_content_check_result=!1)}if(null===b&&c){var f=c.getAttribute("contentEditable"),g=c.getAttribute("preview"),l=null!==c.getAttribute("data-silex-id")||null!==c.getAttribute("data-silex-type");if("edit"==g||f||l)b=!1}}catch(m){return a.g_content_check_result=!1}null===b&&(b=a.g_content_check_result=!0);return b}
function is_shopping_form(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=LP_createXPathFromElement(a,b);d||(d=LP_pickFormName(a,b));var c=formcacheget(a,d,"is-shopping");if(null!=c)return c;var c=!1,e=0,f=0,g=0,l=0,m=0,p,h=/qty|quantity/i,r=/[Ss]hipping/,n=/[Ss]hopping|[CcK]art/,t=/gift|Gift|GIFT/,q=/[Cc]heck[Oo]ut/,k=b.getElementsByTagName("input");Checkpoint.assert(k.length<MAX_INPUTS_SOFT,"form "+LP_getname(b)+" has too many inputs");var u=k.length;u>MAX_INPUTS_SOFT&&(u=MAX_INPUTS_SOFT);
for(p=0;p<u;p++){var v=k[p].id,w=k[p].name,y=k[p].className;if(h.exec(v)||h.exec(w)||h.exec(y))e++;else if(r.exec(v)||r.exec(w)||r.exec(y))g++;else if(n.exec(v)||n.exec(w)||n.exec(y))f++;else if(t.exec(v)||t.exec(w)||t.exec(y))l++;else if(q.exec(v)||q.exec(w)||q.exec(y))m++;else{w=0;y=[e,f,g,l,m];for(v=0;v<y.length;v++)0<y[v]&&w++;if(2<=w){c=!0;break}}}formcacheset(a,d,"is-shopping",c);return c}
function is_wacky_disp(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;if(b==a.body)return!0;var d=!0;try{var c=LP_get_live_style(b);if(c){if("none"==c.display||"hidden"==c.visibility)d=!1;1!=d||b.offsetHeight&&b.offsetHeight||(d=!1);1!=d||0!=c.height&&0!=c.width||(d=!1);1==d&&(2>parseInt(c.height)||2>parseInt(c.width))&&(d=!1);1==d&&(0>parseInt(c.left)&&"auto"!=c.left||0>parseInt(c.top)&&"auto"!=c.top)&&(d=!1);1==d&&"-1px"==c.marginTop&&1==b.offsetHeight&&(d=!1);1==d&&(3>b.offsetHeight||3>b.offsetWidth)&&
(d=!1);1==d&&("transparent"==c.backgroundColor&&"transparent"==c.color||g_isie&&"transparent"==c.backgroundColor&&""==c.color||"rgba(0, 0, 0, 0)"==c.backgroundColor&&"rgba(0, 0, 0, 0)"==c.color)&&(d=!1);1==d&&c.opacity&&.02>parseFloat(c.opacity)&&(d=!1);if(1==d&&g_isie&&c.filter){var e=/alpha\(opacity=(\d+)\)/.exec(c.filter);e&&e[1]&&2>parseInt(e[1])&&(d=!1)}}}catch(l){d=!0}if(d)try{var f=b.parentNode;f||(d=!1);var g=LP_get_live_style(f);g&&(1!=d||"none"!=g.display&&"hidden"!=g.visibility||(d=!1),
1==d&&(0>parseInt(g.left)&&"auto"!=g.left||0>parseInt(g.top)&&"auto"!=g.top)&&(d=!1),1!=d||!(3>parseInt(g.height)&&"auto"!=g.height||3>parseInt(g.width)&&"auto"!=g.width)||"hidden"!=g.overflowY&&"hidden"!=g.overflow||(d=!1))}catch(l){d=!0}return d}
function LP_treat_as_hidden(a){return a&&"hidden"!=a.type&&a.parentNode&&(0!=a.id.indexOf("hidden")||"none"!=a.style.display&&"none"!=a.parentNode.style.display)&&"true"!==a.getAttribute("aria-hidden")?(a=a.getAttribute("hidden"))&&"false"!==a?!0:!1:!0}
function LP_has_textlike_type(a){if(!a)return!1;var b=a.tagName.toUpperCase();if("INPUT"!=b&&"TEXTAREA"!=b)return!1;if("TEXTAREA"==b)return!0;var b="text number email tel url textarea".split(" "),d;for(d in b)if(b.hasOwnProperty(d)&&a.type==b[d])return True;return False}function computeFingerprint(a){if(!a)return"";var b="";a=a.getElementsByTagName("INPUT");var d;for(d=0;d<a.length&&20>d;d++)b+=a[d].id?a[d].id:a[d].name;try{"undefined"!=typeof crc32&&(b=crc32(b).toString())}catch(c){}return b}
function LP_firstVisibleOrphan(a){if(!a)return null;a=a.getElementsByTagName("INPUT");var b,d;for(b=0;b<a.length&&50>b;b++)if(d=a[b],!d.form&&("text"==d.type||"password"==d.type||"url"==d.type||"email"==d.type)&&lpIsVisible(d))return d;return null}
function checkFormForLoginFirstStage(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var d=LP_pickFormName(a,b);verbose_log("checking "+d+" for first stage of multi-stage login");var c=formcacheget(a,d,"multi-first");if(null!=c)return c;if("undefined"==typeof Math)return False;for(var c=0,e=!1,f,g=Math.floor(1E4*Math.random()),l=0,m=0;20>m&&m<b.elements.length;m++)if(f=b.elements[m],"INPUT"==f.tagName&&checkIsDisplayed(a,f,0,null,g)){looksLikeUsername(f)&&c++;if("text"==f.type||"tel"==f.type||
"url"==f.type||"email"==f.type||"textarea"==f.type){if("string"==typeof f.id&&"identifier-captcha-input"==f.id)try{if("google.com"==gettldcached(a.location.href))continue}catch(p){}l++}if(isInputFieldPassword(a,f)){e=!0;break}if(2<=c)break;if(2<=l)break}if(0<c&&3>=c&&0==e&&2>l)return verbose_log("isolated login field/initial stage of multi-stage found"),formcacheset(a,d,"multi-first",!0),!0;formcacheset(a,d,"multi-first",!1);return!1}
function checkDocumentForLoginFirstStageForm(a){if(!a)return!1;var b=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<b,"too many forms on page");for(var c,e=0;e<d.length&&e<b;e++)if(c=checkFormForLoginFirstStage(a,d[e]))return c;return!1}
function checkDocumentForNonLoginOrphans(a){if(null==a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup"),d=formcacheget(a,"fakedoc","orphan-registration"),c=formcacheget(a,"fakedoc","orphan-cc"),b=b||d||c;if(null!=b)return b;b=new RegExp(lpgs("ff_firstname_regexp"),"i");d=new RegExp(lpgs("ff_lastname_regexp"),"i");c=new RegExp(lpgs("ff_cctype_regexp"),"i");lpgs("ff_address1_regexp");lpgs("ff_forgot_regexp");lpgs("ff_remember_regexp");var e=!1,f=!1,g=!1,l=!1,m=!1;try{gettldcached(a.location.href)}catch(u){return!1}for(var p=
0,h=a.getElementsByTagName("INPUT"),r=0;r<h.length&&20>r;r++){var n=h[r];if("INPUT"==n.tagName){LP_isRememberCheckbox(n)&&lpIsVisible(n)&&!LP_fieldIsDisabled(n)&&p++;if("email"==n.type||"text"==n.type||"password"==n.type){if(LP_fieldIsDisabled(n))continue;if(LP_fieldIsDisabled(n))continue;if(!valid_by_role(a,n))continue;if(!lpIsVisible(n))continue;if(is_search_field(a,n,!0))continue;var t=n.name,q=n.id?n.id:"",k=lpGetTextBeforeFormField(n);looksLikeUsername(n)?e=!0:isInputFieldPassword(a,n)?f=!0:
b.exec(q)||b.exec(t)||b.exec(k)?g=!0:d.exec(q)||d.exec(t)||d.exec(k)?l=!0:c.exec(q)||c.exec(t)||c.exec(k)?m=!0:regexp_address1.exec(q)||regexp_address1.exec(t)||regexp_address1.exec(k);p++}if(3<=p){if(e&&f&&!m)return verbose_log("document appears to be have orphan signup fields"),formcacheset(a,"fakedoc","orphan-signup",!0),formcacheset(a,"fakedoc","orphan-cc",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if(m&&!e&&!f)return verbose_log("document appears to be have orphan credit card fields"),
formcacheset(a,"fakedoc","orphan-cc",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if((g||l)&&e)return verbose_log("document appears to be have orphan registration fields"),formcacheset(a,"fakedoc","orphan-registration",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-cc",!1),!0}}}formcacheset(a,"fakedoc","orphan-signup",!1);formcacheset(a,"fakedoc","orphan-cc",!1);formcacheset(a,"fakedoc","orphan-registration",
!1);return!1}function checkDocumentHasOrphanSignup(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-signup")}function checkDocumentHasOrphanCC(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-cc");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-cc")}
function checkDocumentHasOrphanRegistration(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-registration");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-registration")}function LP_should_ignore_this_doc(a,b){if(!a||!a.location)return!0;var d=a.location.href;return LP_is_browser_url(d)||0==d.indexOf("javascript:")||0<d.indexOf(".xul")||b&&"www.irccloud.com"==a.location.hostname?!0:!1}
function countInputs(a,b,d){var c=0,e=0,f=a.getElementsByTagName("INPUT");if("undefined"!=typeof Math){for(var g=0;g<f.length;g++){if(100<g){b||(c+=f.length-g);break}var l="password"==f[g].type;b&&!l||"checkbox"==f[g].type||"hidden"==f[g].type||(l&&e++,c++)}d&&(a.g_password_cnt=e);return c}}
function checkForLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(f){return!1}var b=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<b,"too many forms on page");for(var c,e=0;e<d.length&&e<b;e++){c=chk_form_has_password(a,d[e],!0);if(null==c)break;if(c)return c}return!1}
function checkForNonLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(f){return!1}var b=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<b,"too many forms on page");for(var c,e=0;e<d.length&&e<b;e++)if(c=chk_form_is_nonlogin_form(a,d[e]))return c;return!1}
function checkForSignupForm(a){a||(a=LP_derive_doc());if(!a)return!1;var b=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<b,"too many forms on page");for(var c,e=0;e<d.length&&e<b;e++)if(c=chk_form_ask_generate(a,d[e]))return c;return!1}
function usercacheset(a,b){if(null==a||null==b||0===b.length)return!1;var d=gettldcached(a.location.href);"function"==typeof sendBG&&sendBG({cmd:"usercacheset",tld:d,username:b});verbose_log("USERCACHE-SAVED  domain: "+d+" user: "+b);return!0}
function checkForTotpForm(a,b){if("undefined"==typeof g_do_totp||!g_do_totp||g_totp_elt)return!1;a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(g){return!1}verbose_log("checkForTotpForm called from "+b);var d=LP_getFormsThreshold(a),c=a.getElementsByTagName("form");Checkpoint.assert(c.length<d,"too many forms on page");for(var e,f=0;f<c.length&&f<d;f++){e=chk_form_has_totp(a,c[f],!0);if(null==e)break;if(e)return verbose_log("checkForTotpForm FOUND totp form - called from "+
b),e}return!1}
function chk_form_has_totp(a,b,d){if("undefined"==typeof g_do_totp||!g_do_totp||g_totp_elt||null==a||null==b||!b||!b.tagName||"FORM"!=b.tagName.toUpperCase())return!1;LP_pickFormName(a,b);d="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");if(d.length>=MAX_FORM_ELEMENTS_HARD)return!1;var c=0;verbose_log("checking form: id-> "+b.id+"  class-> "+b.className+" name-> "+b.name);c+=textFieldScore(b,"totp");c+=textFieldScore(b,"2fa");c+=textFieldScore(b,"twofactor");c+=textFieldScore(b,
"tfa");verbose_log("form score: ( id-> "+b.id+"  class-> "+b.className+" name-> "+b.name+" )   "+c);for(var e=0,f=0,g=0;g<MAX_FORM_ELEMENTS_SOFT&&g<b.elements.length;g++){var l=b.elements[g];"INPUT"==l.tagName&&("text"!=l.type&&"tel"!=l.type&&"number"!=l.type||e++);("INPUT"==l.tagName&&"submit"==l.type||"BUTTON"==l.tagName)&&f++}verbose_log("check for totp form: txtfieldcount="+e+" submitcnt="+f);if(0==f||0==e)return!1;for(g=0;g<MAX_FORM_ELEMENTS_SOFT&&g<d.length;g++)if(l=d[g],isInputFieldTotpCode(a,
l))if(c+=2,null===l.offsetParent){verbose_log("HIDDEN totp element found: id-> "+l.id+"  class-> "+l.className+"  name-> "+l.name);var m,p=l;m=setInterval(function(){var b=p;verbose_log("checking visibility for: id-> "+b.id+"  class-> "+b.className+"  name-> "+b.name);null===b.offsetParent?verbose_log("element is STILL HIDDEN: id-> "+b.id+"  class-> "+b.className+"  name-> "+b.name):(clearInterval(m),verbose_log("element become VISIBLE - totp code field revealed!!!!!: id-> "+b.id+"  class-> "+b.className+
"  name-> "+b.name),found_totp_elt(b,a))},5E3)}else found_totp_elt(l,a),verbose_log("VISIBLE totp element found!!!!!: id-> "+l.id+"  class-> "+l.className+"  name-> "+l.name);verbose_log("form totp score: "+c+"+id-> "+b.id+"  class-> "+b.className+" name-> "+b.name);return 2<=c}var g_totp_elt=null,g_totp_form=null;
function found_totp_elt(a,b){verbose_log("found totp elt");g_totp_elt?verbose_log("already found totp elt, returning"):(g_totp_elt=a,"undefined"!=typeof g_can_get_totp&&g_can_get_totp)?"function"==typeof sendBG&&(verbose_log("attempting to get totp from server"),sendBG({cmd:"get_totp",tld:gettldcached(b.location.href),name:a.name,id:a.id,className:a.className})):(verbose_log("set totp form"),g_totp_form=a.form)}
function chk_form_has_password(a,b,d){if(null==a||null==b||!b||!b.tagName||"FORM"!=b.tagName.toUpperCase())return!1;var c=LP_pickFormName(a,b),e=formcacheget(a,c,"is_login");if(null!=e)return e;e="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(e.length<MAX_FORM_ELEMENTS_HARD,"form "+c+" has too many inputs");if(e.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,c,"is_login",!1),!1;try{var f=gettldcached(a.location.href);if("bankofamerica.com"==f){var g=
a.getElementById("tlpvt-passcode-input");null!==g&&g.removeAttr("disabled")}}catch(u){return!1}for(var l=g=0,m=0,e=null,p=0;p<MAX_FORM_ELEMENTS_SOFT&&p<b.elements.length;p++){var h=b.elements[p];"INPUT"==h.tagName&&("password"==h.type?g++:"text"!=h.type&&"email"!=h.type||l++);if("INPUT"==h.tagName&&"submit"==h.type||"BUTTON"==h.tagName)m++,e=h}verbose_log("check for login form: prelimtxt="+l+" prelimpw="+g);if(1==m&&2>=l&&0<g&&checkButtonHint(e))return!0;for(var r=0,n=0,t=!lpIsVisible(b),q=!1,e=b.elements,
p=0;p<MAX_FORM_ELEMENTS_SOFT&&p<e.length;p++)if(h=e[p],b=!1,"FIELDSET"!=h.tagName&&(check_for_ASP(a,h),valid_by_role(a,h)&&!LP_fieldIsDisabled(h)&&!LP_treat_as_hidden(h))){if("text"==h.type&&is_watermark(h.className)&&is_watermark_password(h))try{h.type="password",decision_log(a,"DE11")}catch(u){b=!0}ASP_treat_text_as_password(h)&&(b=!0);(b||"password"==h.type)&&LP_get_input_pattern(a,h);if(1<g&&LP_passwordAlt(a,h))n++;else{var k=fieldIsDoublePassword(a,h);if("text"!=h.type||k!==DOUBLE_PW_VISIBLE&&
k!==DOUBLE_SECRET_PW_VISIBLE)if("password"==h.type||b||"text"==h.type&&k===DOUBLE_TEXT_VISIBLE||"text"==h.type&&k===DOUBLE_SECRET_TEXT_VISIBLE){if("facebook.com"!=f||"string"!=typeof h.id||!h.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/))if("tdbank.com"==f&&"string"==typeof h.name&&"user"==h.name)n++;else{if(g_fillaid&&d)return!0;if(g_aspx_hack&&isASPpage()&&do_bgiconinput)decision_log(a,"DE12");else if(!lpIsVisible(h)||g_use_wacky_disp&&!is_wacky_disp(a,h))if(q=!0,t)decision_log(a,"DE13",{param1:LP_pickFormName(a,
h)});else continue;if(0==r&&1<g&&passwordIsFake(h))n++;else if(0<r&&1<g&&LP_looksLikeOTPField(a,h))n++;else if(b=2,h="",g_aspx_hack&&isASPpage()&&do_bgiconinput&&(b=4,h=" [ASP]"),++r>=b){if(2==g&&0===l&&1===m&&(new RegExp(lpgs("ff_loginform_regexp"),"i")).exec(c))return formcacheset(a,c,"is_login",!0),!0;formcacheset(a,c,"is_login",!1);verbose_log("Password Form detection: "+c+h+" has too many password fields; do not treat as login form [PW:"+r+"/NON:"+n+"]");return null}}}else if("email"==h.type||
"text"==h.type||"textarea"==h.type||"tel"==h.type||"url"==h.type){if(!lpIsVisible(h)||g_use_wacky_disp&&!is_wacky_disp(a,h))if(t)verbose_log("EVALUATING HIDDEN FORM, NOT IGNORING HIDDEN FIELD ANYMORE "+LP_pickFormName(a,h));else continue;n++;if(g_aspx_hack&&5<n||!g_aspx_hack&&2<n)return formcacheset(a,c,"is_login",!1),verbose_log("Password Form detection: "+c+" has too many non-password fields; do not treat as login form [PW:"+r+"/NON:"+n+"]"),null}}}if(1==r)return verbose_log("Password Form detection: "+
c+" is a login form, has only one passwd field"),formcacheset(a,c,"is_login",!0),!0;if(g_aspx_hack&&isASPpage()&&do_bgiconinput&&1<r)return verbose_log("Password Form detection: "+c+" is an ASP form, treat as login form"),formcacheset(a,c,"is_login",!0),!0;q||formcacheset(a,c,"is_login",!1);return!1}function looksLikePassword(a,b){return isInputFieldPassword(a,b)}
function isInputFieldPassword(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"hidden"==b.type)return!1;try{var d=gettldcached(a.location.href)}catch(e){return!1}if(!valid_by_role(a,b))return!1;var c=!1;if("text"==b.type&&is_watermark(b.className)&&is_watermark_password(b))try{b.type="password"}catch(e){c=!0}if("text"==b.type&&(0==b.name.indexOf("pass")||0==b.name.toLowerCase().indexOf(lpgs("Password").toLowerCase())))return(new RegExp(lpgs("ff_username_regexp"),"i")).exec(b.name)&&b.form&&b.form.action&&
0<=b.form.action.indexOf("login")?!1:!0;g_aspx_hack&&isASPpage()&&do_bgiconinput&&"text"==b.type&&0<=b.value.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&(c=!0);return"password"==b.type||c?"facebook.com"==d&&"string"==typeof b.id&&b.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/)||"tdbank.com"==d&&"string"==typeof b.name&&"user"==b.name||"google.com"==d&&"string"==typeof b.id&&"Passwd-hidden"==b.id?!1:!0:!1}
function checkDocumentForLoginOrphans(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan");if(null!=b)return b;var b=[],d=[],c=[],e=0,f,g=0;if("undefined"!=typeof Math){for(var l=Math.floor(1E4*Math.random()),m=["input"],p=0;p<m.length;p++){var h=a.getElementsByTagName(m[p]),r=h.length;Checkpoint.assert(r<MAX_INPUTS_SOFT,"page has too many inputs");r>MAX_INPUTS_SOFT&&(r=MAX_INPUTS_SOFT);for(var n=0;n<r;n++)if(checkIsDisplayed(a,h[n],0,null,l)){f=h[n];if(null!=f.id&&""!=
f.id){var t=c[f.id];if(null==t)c[f.id]=!0;else continue}if(null!=f.name&&""!=f.name)if(t=d[f.name],null==t)d[f.name]=!0;else continue;if(lp_in_array(LP_pickFieldName(a,f),b))verbose_log("fieldname "+b[t]+" is blacklisted, skipping");else{var q=fieldIsDoublePassword(a,f);if(null==f.form&&("password"==f.type||"text"==f.type&&q===DOUBLE_TEXT_VISIBLE||"text"==f.type&&q===DOUBLE_SECRET_TEXT_VISIBLE)){e++;var q=[],k;k=LP_pickFieldName(a,f);f=LP_getname(f);k&&q.push(k);f&&k!=f&&q.push(f);for(f=0;f<q.length;f++)if((k=
q[f])&&0<=k.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&0<n){var u=h[n-1];k=LP_pickFieldName(a,u);var u=LP_getname(u),v=new RegExp(lpgs("ff_username_regexp"),"i");if(v.exec(k)||v.exec(u)){g++;break}}}if(2<=e&&2<=g)break}}}if(1<=e||1==g)return formcacheset(a,"fakedoc","orphan",!0),!0;formcacheset(a,"fakedoc","orphan",!1);return!1}}
function chk_form_changepw(a,b){if(null==a||null==b)return!1;for(var d=lpCheckCurrentPWField(b),c,e=null,f=null,g=1;2>=g;g++){c=!1;var e=f=null,l=-1;if(1==g){if(d)for(var m=0;m<b.elements.length;m++)if(b.elements[m]==d){l=m+1;break}}else l=0;if(-1!=l){for(m=l;m<b.elements.length;m++)if(l=b.elements[m],"FIELDSET"!=l.tagName)if(isInputFieldPassword(a,l)){if(c||!e||!f)if(f=e,e=l,c&&e&&f)break;c=!0}else c=!1;if(e&&f)break}}return null!=e&&null!=f&&null!=d?!0:!1}
function containsSubString(a,b){return a&&-1<a.replace(/\s/g,"").toLowerCase().indexOf(b.toLowerCase())}function textFieldScore(a,b){var d=0;containsSubString(a.name,b)&&d++;containsSubString(a.id,b)&&d++;containsSubString(a.className,b)&&d++;return d}
function isInputFieldTotpCode(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"hidden"==b.type)return!1;try{var d=gettldcached(a.location.href)}catch(c){return!1}if(!valid_by_role(a,b)||"text"!=b.type&&"tel"!=b.type&&"number"!=b.type)return!1;if(0<textFieldScore(b,"totp")||"salesforce.com"==d&&"tc"==b.id&&6==b.maxLength&&"tc"==b.name&&-1!=b.form.action.indexOf("Totp")||"github.com"==d&&"otp"==b.id&&"otp"==b.name&&-1!=b.form.action.indexOf("two-factor")||"live.com"==d&&"idTxtBx_SAOTCC_OTC"==b.id&&"otc"==
b.name&&8==b.maxLength)return!0;if("google.com"==d&&-1!=b.id.indexOf("PhonePin"))return!1;d=0+textFieldScore(b,"code");d+=textFieldScore(b,"pin");d+=textFieldScore(b,"verification");d+=textFieldScore(b,"2fa");d+=textFieldScore(b,"twofactor");d+=textFieldScore(b,"tfa");b.pattern&&containsSubString(b.pattern,"0-9")&&d++;b.placeholder&&(containsSubString(b.placeholder,"6")||containsSubString(b.placeholder,"six")||containsSubString(b.placeholder,"hat"))&&d++;return 0<d}
function form_get_password(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var d=LP_pickFormName(a,b),c=formcacheget(a,d,"password_field");if(null!==c)return c;if(!0===formcacheget(a,d,"nopasswords"))return null;var c=null,e,f;f="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==f&&0<f.length,"empty form?");if("undefined"==typeof Math)return null;var g=f.length;Checkpoint.assert(g<MAX_FORM_ELEMENTS_HARD,"form "+d+" too big 3");g>MAX_FORM_ELEMENTS_HARD&&
(g=MAX_FORM_ELEMENTS_HARD);var l=0;for(e=0;e<g;e++)isInputFieldPassword(a,f[e])&&l++;e=Math.floor(1E4*Math.random());for(var m=0;m<g;m++){var p=f[m];if("FIELDSET"!=p.tagName&&checkIsDisplayed(a,p,0,null,e)&&isInputFieldPassword(a,p)&&!(1<l&&(passwordIsFake(p)||LP_looksLikeOTPField(a,p)||!valid_by_role(a,p)||LP_fieldIsDisabled(p)||LP_treat_as_hidden(p)||is_search_field(a,p,!0)))){c=p;break}}null===c&&0===l&&formcacheset(a,d,"nopasswords",!0);formcacheset(a,d,"password_field",c);return c}
function form_get_username(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var d;d="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==d);var c=null,e=LP_pickFormName(a,b),f=formcacheget(a,e,"username_field");if(null!==f)return f;if("undefined"==typeof Math)return null;f=d.length;Checkpoint.assert(f<MAX_FORM_ELEMENTS_HARD,"form "+e+" too big 4 ");f>MAX_FORM_ELEMENTS_HARD&&(f=MAX_FORM_ELEMENTS_HARD);for(var g=Math.floor(1E4*Math.random()),l=0;l<f;l++){var m=
d[l];if("FIELDSET"!=m.tagName&&"hidden"!=m.type&&valid_by_role(a,m)&&!LP_fieldIsDisabled(m)&&!is_search_field(a,m,!0)&&checkIsDisplayed(a,m,0,null,g)&&("text"==m.type||"email"==m.type||looksLikeUsername(m))){if(isFirstFieldNonLoginSubForm(a,m))return null;c=m;break}}formcacheset(a,e,"username_field",c);return c}
function doc_get_orphan_username(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b;if("undefined"!=typeof Math){b=formcacheget(a,"orphans","username_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[0])return formcacheset(a,"orphans","username_field",b[0]),b[0];if(LP_has_youama(a)&&(b=LP_get_youama_fields(a))&&b.login_username)return formcacheset(a,"orphans","username_field",b.login_username),b.login_username;var d=doc_get_form_equivalents(a);
if(d&&0<d.length)for(b=0;b<d.length;b++)if("FORM"!=d[b].tagName.toUpperCase()){var c=form_get_username(a,d[b]);if(c)return formcacheset(a,"orphans","username_field",c),c}formcacheset(a,"orphans","username_field","none");return null}}
function doc_get_orphan_password(a){if(null==a)return null;if("undefined"!=typeof Math){var b=formcacheget(a,"orphans","password_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[1])return formcacheset(a,"orphans","password_field",b[1]),b[1];if(LP_has_youama(a)&&(b=LP_get_youama_fields(a))&&b.login_password)return formcacheset(a,"orphans","password_field",b.login_password),b.login_password;if((b=doc_get_form_equivalents(a))&&0<
b.length)for(x=0;x<b.length;x++)if("FORM"!=b[x].tagName.toUpperCase()){var d=form_get_password(a,b[x]);if(d)return formcacheset(a,"orphans","password_field",d),d}formcacheset(a,"orphans","password_field","none");return null}}
function set_active_username_password(a,b){if(null==a)g_popup_active_password=g_popup_active_username=null;else{var d=null,c=null;null==b?checkDocumentForLoginOrphans(a)&&(d=doc_get_orphan_username(a),c=doc_get_orphan_password(a)):(d=form_get_username(a,b),c=form_get_password(a,b));g_popup_active_username=d;g_popup_active_password=c}}
function looksLikeEmail(a,b){return null==a||null==b||"text"!=b.type&&"email"!=b.type?!1:"email"==b.type||(new RegExp(lpgs("ff_email_regexp"),"i")).exec(b.name)?!0:!1}
function is_search_field(a,b,d){if(null==a||null==b||"INPUT"!=b.tagName.toUpperCase()&&!b.getAttribute("contentEditable"))return!1;var c=null;switch(b.type){case "search":c=!0;break;case "text":break;default:"INPUT"==b.tagName.toUpperCase()&&(c=!1)}if(null!==c)return c;null===d&&(d=!1);var c=LP_pickFieldName(a,b),e=fieldcacheget(a,c,"search");if(null!=e)return e;var e=b.form,f=[];null!=e&&(f=e.elements);if(b.parentNode&&"FORM"!=b.parentNode.tagName&&b.parentNode.className&&0<=b.parentNode.className.toLowerCase().indexOf("login")&&
b.className&&0<=b.className.toLowerCase().indexOf("search"))return!1;if((null!=b.className&&0<=b.className.toLowerCase().indexOf("search")||0<=b.className.toLowerCase().indexOf("srch")||0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch")||0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch"))&&0>b.name.toLowerCase().indexOf("user")&&0>b.name.toLowerCase().indexOf("login")&&0>b.id.toLowerCase().indexOf("user")&&0>b.id.toLowerCase().indexOf("login")&&
(d||5>f.length))return fieldcacheset(a,c,"search",!0),!0;d=new RegExp(lpgs("ff_search_regexp"),"i");if(d.exec(b.name)||d.exec(b.id))if(d=b.name&&b.name.match(/[qQ]/)||b.id&&b.id.match(/[qQ]/),e=new RegExp(lpgs("ff_email_regexp"),"i"),f=new RegExp(lpgs("ff_username_regexp"),"i"),d&&b.name&&!b.name.match(/^[qQ]/)&&(!b.id||b.id&&!b.id.match(/^[qQ]/)))pass;else if(d&&b.id&&!b.id.match(/^[qQ]/)&&(!b.name||b.name&&!b.name.match(/^[qQ]/)))pass;else if(d&&(f.exec(b.name)||f.exec(b.id)||e.exec(b.name)||e.exec(b.id)))pass;
else return verbose_log("field "+c+" appears to be a search field based on regexp"),fieldcacheset(a,c,"search",!0),!0;d=b.getAttribute("placeholder");if(null!=d&&0<=d.toLowerCase().indexOf("search"))return verbose_log("field "+c+" appears to be a search field based on placeholder text"),fieldcacheset(a,c,"search",!0),True;if("rds-instances-filter-txtbx"==b.id)return verbose_log("field "+c+" appears to be a search field based on manually added searchtext"),fieldcacheset(a,c,"search",!0),!0;if(b.parentNode&&
"FORM"!=b.parentNode.tagName&&b.parentNode.className&&(0<=b.parentNode.className.toLowerCase().indexOf("search")||0<=b.parentNode.className.toLowerCase().indexOf("srch"))||"search"==b.getAttribute("role"))return fieldcacheset(a,c,"search",!0),!0;d=b.getAttribute("spellcheck");if(b.className&&0<=b.className.indexOf("tt-input")&&d&&"false"===d)return fieldcacheset(a,c,"search",!0),!0;fieldcacheset(a,c,"search",!1);return!1}
function is_date_field(a){if(!a)return!1;var b,d=/(?:date)|(?:calendar)/i,c=/(?:validate)/i;b=a.name;var e=a.id,f=a.className;if(d.exec(b)||d.exec(e)||d.exec(f))return c.exec(b)||c.exec(e)||c.exec(f)?!1:!0;if(a=a.getAttribute("placeholder"))if(a=a.toLowerCase(),-1!=a.indexOf("yyyy")||-1!=a.indexOf("/yy")||-1!=a.indexOf("mm/"))return!0;return!1}
function is_search_form(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var d=LP_pickFormName(a,b),c=formcacheget(a,d,"search");if(null!=c)return c;if(null!=b.id&&0<b.id.length&&"undefined"!=typeof b.id.toLowerCase&&(0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch"))||null!=b.name&&0<b.name.length&&"undefined"!=typeof b.name.toLowerCase&&(0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch")))return verbose_log("form "+d+" appears to be a search form based on name/id "),
formcacheset(a,d,"search",!0),!0;if("search"==b.getAttribute("role"))return formcacheset(a,d,"search",!0),!0;formcacheset(a,d,"search",!1);return!1}
function looksLikeUsername(a,b){if(!a)return!1;var d=LP_hasAngular(a.ownerDocument);if("undefined"==typeof b||null===b)b=!1;if(!b&&"text"!=a.type&&"email"!=a.type&&"url"!=a.type)return!1;var c=new RegExp(lpgs("ff_username_regexp"),"i");if(c.exec(a.name)||a.id&&c.exec(a.id))return!0;var e=a.getAttribute("placeholder");if(null!=e&&0<=e.indexOf("Login")||d&&(d=LP_getAngularAttributes(a))&&d["ng-model"]&&c.exec(d["ng-model"]))return!0;d=new RegExp(lpgs("ff_loginform_regexp"),"i");if(a.form)for(var e=
a.form.elements,f=0;f<e.length;f++)if("submit"==e[f].type&&(e[f].name&&c.exec(e[f].name)||d.exec(e[f].name)))return!0;c=/^id$|.*-id|online.*id$|.*Id$|onlineId\d?$/i;if(c.exec(a.name))return!0;if(g_is_specialsite){c=new RegExp(lpgs("ff_bankacctnum_regexp"),"i");if(c.exec(a.name))return!0;c=new RegExp(lpgs("ff_company_regexp"),"i");if(c.exec(a.name))return!0;c=new RegExp(lpgs("ff_email_regexp"),"i");if(c.exec(a.name))return!0}return!1}
function formHasUsernameField(a){if(a=a.form){a=a.elements;for(var b=0;b<a.length;b++){var d=a[b];if("text"==d.type||"email"==d.type)return!0}}return!1}var DOUBLE_TEXT_VISIBLE=1,DOUBLE_PW_VISIBLE=2,DOUBLE_SECRET_TEXT_VISIBLE=3,DOUBLE_SECRET_PW_VISIBLE=4,NOT_DOUBLE_PW=0;
function fieldIsDoublePassword(a,b){"document"==a&&(a=document,b=LP_getElementByIdOrName(a,b));if(null==a&&(a=document,!a))return!1;if(null==b||"checkbox"==b.type||"button"==b.type||"submit"==b.type||"select-one"==b.type)return NOT_DOUBLE_PW;var d,c,e=null,f=null;"undefined"!=typeof b.previousElementSibling?d=b.previousElementSibling:(d=b.previousSibling)&&null!=d.nodeType&&3==d.nodeType&&(d=d.previousSibling);"undefined"!=typeof b.nextElementSibling?c=b.nextElementSibling:(c=b.nextSibling)&&null!=
c.nodeType&&3==c.nodeType&&(c=c.nextSibling);d&&"INPUT"!=d.tagName&&(d=null);c&&"INPUT"!=c.tagName&&(c=null);d&&("undefined"!=typeof d.previousElementSibling?e=d.previousElementSibling:(e=d.previousSibling)&&null!=e.nodeType&&3==e.nodeType&&(e=e.previousSibling),e&&"INPUT"!=e.tagName&&(e=null));c&&("undefined"!=typeof c.nextElementSibling?f=c.nextElementSibling:(f=c.nextSibling)&&null!=f.nodeType&&3==f.nodeType&&(f=f.nextSibling),f&&"INPUT"!=f.tagName&&(f=null));if("undefined"!=typeof Math){var g=
Math.floor(1E4*Math.random());if("password"==b.type&&!checkIsDisplayed(a,b,-1,null,g)&&d&&"text"==d.type&&!checkIsDisplayed(a,d,-1,null,g)&&c&&"text"==c.type&&checkIsDisplayed(a,c,-1,null,g)&&f&&"text"==f.type&&checkIsDisplayed(a,f,-1,null,g)||"text"==b.type&&checkIsDisplayed(a,b,-1,null,g)&&d&&"text"==d.type&&checkIsDisplayed(a,d,-1,null,g)&&e&&"password"==e.type&&!checkIsDisplayed(a,e,-1,null,g))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double secret password hack"),g_double_secret_password_hack=
!0,DOUBLE_SECRET_TEXT_VISIBLE;if("password"==b.type&&checkIsDisplayed(a,b,-1,null,g)&&d&&"text"==d.type&&!checkIsDisplayed(a,d,-1,null,g)||"text"==b.type&&!checkIsDisplayed(a,b,-1,null,g)&&c&&"password"==c.type&&checkIsDisplayed(a,c,-1,null,g))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE;var e=null!=b&&lpIsVisible(b,!0),f=null!=d&&lpIsVisible(d,!0),g=null!=c&&lpIsVisible(c,!0),l=null!=b&&looksLikeUsername(b),m=null!=d&&
looksLikeUsername(d),p=null!=c&&looksLikeUsername(c);return"password"==b.type&&!e&&d&&"text"==d.type&&f&&!m||"text"==b.type&&e&&!l&&c&&"password"==c.type&&!g||"password"==b.type&&!e&&c&&"text"==c.type&&g&&!p||"text"==b.type&&e&&!l&&d&&"password"==d.type&&!f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_TEXT_VISIBLE):"password"==b.type&&e&&d&&"text"==d.type&&!f&&!m||"text"==b.type&&!e&&c&&"password"==c.type&&g||"password"==b.type&&e&&c&&
"text"==c.type&&!g&&!p||"text"==b.type&&!e&&d&&"password"==d.type&&f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE):NOT_DOUBLE_PW}}
function ContigPWHack(a,b,d){null===a&&(a=document);if(null===a||"undefined"==typeof a.getElementsByTagName)return!1;var c=lpCountInputFields(b);if("undefined"!=typeof Math){b=Math.floor(1E4*Math.random());if((3==c.passwordvisible||4==c.passwordvisible)&&!0===c.passwordsContiguous)for(var e=a.getElementsByTagName("input"),c=0;c<e.length&&!(100<c);c++)if(e[c]==d){if("undefined"!=typeof e[c+1]&&"password"==e[c+1].type&&"undefined"!=typeof e[c+2]&&"password"==e[c+2].type&&checkIsDisplayed(a,e[c],-1,
null,b)&&checkIsDisplayed(a,e[c+1],-1,null,b)&&checkIsDisplayed(a,e[c+2],-1,null,b))return!0;break}return!1}}
function isContigPW(a,b,d){null==b&&(b=a);var c=b.getElementsByTagName("input");if("undefined"!=typeof Math){var e=Math.floor(1E4*Math.random());for(b=0;b<c.length;b++)if(c[b]==d&&"password"==c[b].type){if("undefined"!=typeof c[b+1]&&"password"==c[b+1].type&&checkIsDisplayed(a,c[b],-1,null,e)&&checkIsDisplayed(a,c[b+1],-1,null,e)||"undefined"!=typeof c[b-1]&&"password"==c[b-1].type&&checkIsDisplayed(a,c[b],-1,null,e)&&checkIsDisplayed(a,c[b-1],-1,null,e))return!0;break}return!1}}
function get_prev_field(a,b){"undefined"!=typeof b.previousElementSibling?prev_field=b.previousElementSibling:(prev_field=b.previousSibling)&&null!=prev_field.nodeType&&prev_field.nodeType==TEXT_NODE&&(prev_field=prev_field.previousSibling)}function get_next_field(a,b){"undefined"!=typeof b.nextElementSibling?next_field=b.nextElementSibling:(next_field=b.nextSibling)&&null!=next_field.nodeType&&next_field.nodeType==TEXT_NODE&&(next_field=next_field.nextSibling)}
function isFirstFieldNonLoginSubForm(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type)return!1;if("text"==b.type){var d=new RegExp(lpgs("ff_firstname_regexp"),"i");if(d.exec(b.name)||d.exec(b.id))return!0;d=/register|signup|enroll|create/i;if(b.parentNode&&d.exec(b.parentNode.name)||d.exec(b.parentNode.id)||b.parentNode&&b.parentNode.parentNode&&(d.exec(b.parentNode.parentNode.name)||d.exec(b.parentNode.parentNode.id)))return!0}return!1}
function isUsernameFieldLoginSubForm(a,b){return null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type?!1:FoundNonLoginSubForm(a)?False:looksLikeUsername(b)?!0:!1}function FoundNonLoginSubForm(a){if(null==a)return!1;if(isASPpage()){a=getAllIconStates();var b;for(b=0;b<a.length;b++)if("formfills"==a[b].fillhint)return True}return False}
function isPasswordFieldLoginSubForm(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"hidden"==b.type)return!1;if(FoundNonLoginSubForm(a))return False;if("password"==b.type){var d=a.getElementsByTagName("INPUT"),c;for(c=0;c<d.length&&c<MAX_INPUTS_HARD&&b!=d[c];c++);if(b==d[c]&&0<c){var e=LP_pickFieldName(a,b);if(e&&e.toLowerCase().indexOf(0<=lpgs("Password"))&&(d=LP_pickFieldName(a,d[c-1]),(new RegExp(lpgs("ff_username_regexp"),"i")).exec(d)))return!0}}return!1}
function isASPpage(){var a=!1;if(g_isfirefox){var b;(b="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?a=b.g_found_aspx:verbose_log("unable to get g_found_aspx in isASPpage() for "+b?b.location.href:"null")}else a=g_found_aspx;a||(a=!1);return a}
function setASPpage(a){var b=!1;null==a&&(a=!0);if(g_isfirefox){var d;(d="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?b=d.g_found_aspx=a:verbose_log("unable to set g_found_aspx in isASPpage() for "+d?d.location.href:"null")}else g_found_aspx=a,b=!0;b||(b=!1);return b}
function checkDocumentForLoginOrphansFirstStage(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-first");if(null!=b)return b;if("undefined"!=typeof Math){for(var b=[],d=[],c=0,e=!1,f=Math.floor(1E4*Math.random()),g=["input"],l=0;l<g.length;l++)for(var m=a.getElementsByTagName(g[l]),p=0;p<m.length;p++){var h=m[p];if(20<p)break;if(!m[p].form&&checkIsDisplayed(a,m[p],0,null,f)){verbose_log("checking "+LP_pickFieldName(a,h));if(null!=h.id&&""!=h.id){var r=d[h.id];if(null==r)d[h.id]=!0;else continue}if(null!=
h.name&&""!=h.name)if(r=b[h.name],null==r)b[h.name]=!0;else continue;looksLikeUsername(h)&&c++;if(isInputFieldPassword(a,h)){e=!0;break}if(2<c)break}}if(0<c&&4>=c&&0==e)return decision_log(a,"DE27"),formcacheset(a,"fakedoc","orphan-first",!0),!0;formcacheset(a,"fakedoc","orphan-first",!1);return!1}}
function LP_looksLikeOTPField(a,b){if(!a||!b||"INPUT"!=b.tagName)return!1;var d=/^(otp|token|tokencode|mfacode)[_\W]|[_\W](otp|token|tokencode|mfacode)$|^(otp|token|tokencode|totpPin|mfacode):?$|[_\W](otp|token|tokencode|mfacode)[_\W]|(validation|verification|challenge).*code:?$/i,c=get_doc_location_href(a);gettldcached(c);var e=LP_pickFieldName(a,b);if(d.exec(e)||(e=b.getAttribute("aria-label"))&&0<e.indexOf("O-Key"))return!0;e=lpGetTextBeforeFormField(b,!1).toLowerCase();return d.exec(e)||c&&0<
c.toLowerCase().indexOf("challenge")&&e&&e.match(/([_\W]code:?$|^code[_\W])/)?!0:!1}function LP_fieldIsDisabled(a){return a?"undefined"!=typeof a.disabled&&a.disabled||"true"===a.getAttribute("aria-disabled")?!0:!1:!1}function LP_fieldIsReadOnly(a){return a?"undefined"!=typeof a.readOnly&&a.readOnly||"true"===a.getAttribute("aria-readonly")?!0:!1:!1}function LP_fieldIsDecorative(a){return a?"presentation"===a.getAttribute("role")?!0:!1:!1}
function checkDocumentForCPWOrphans(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b=formcacheget(a,"fakedoc","cpw");if(null!=b)return b;var b=null,d=0,c=a.getElementsByTagName("INPUT");Checkpoint.assert(c.length<=MAX_INPUTS_HARD,"page has too many inputs");for(var e=0;e<c.length;e++){var f=c[e];if(e>MAX_INPUTS_HARD)break;if(null==f.form){if(isInputFieldPassword(a,f)&&lpIsVisible(f)&&(d++,f=lpIsFieldCurrentPWField(f))){if(b)return!1;b=f}if(4<=d)return formcacheset(a,"fakedoc","cpw",!1),!1}}if(2<=
d&&b)return formcacheset(a,"fakedoc","cpw",!0),!0;formcacheset(a,"fakedoc","cpw",!1);return!1}
function ForceFillFieldClicked(a,b,d,c){if(!b||!c)return!1;d=b.form&&!d?LP_getname(b.form):"";var e=b.type?b.type:"";return"password"==e?LP_getname(b)?LP_setval(a,LP_getname(b),c.p,0,c.a,d,e,c.sharedsite,null,c.automaticallyFill,c.reqinfo,null,!0,c.humanize,c.reqinfo,c.realurl):LP_fill_given_field(a,b,c.p,e,c.sharedsite,c.automaticallyFill,c.a,!0,!0,c.humanize,c.reqinfo,c.realurl):""==c.u?!0:LP_getname(b)?LP_setval(a,LP_getname(b),c.u,0,c.a,d,e,c.sharedsite,null,c.automaticallyFill,c.reqinfo,null,
!0,c.humanize,c.reqinfo,c.realurl):LP_fill_given_field(a,b,c.u,e,c.sharedsite,c.automaticallyFill,c.a,!0,!0,c.humanize,c.reqinfo,c.realurl)}function ForceFillFormClicked(a,b,d,c){if(!b)return!1;if(b=b.getElementsByTagName("INPUT")){if(b=GuessUserPassFields(b,!0,!0,!0))b.text&&ForceFillFieldClicked(a,b.text,!1,c),b.password&&ForceFillFieldClicked(a,b.password,!1,c);return!0}return!1}
function GuessUserPassFields(a,b,d,c){if(!a||0>=a.length)return null;var e=document,f,g=a.length,l=null,m=null,p=!1;for(f=0;f<g;f++){var h=a[f];if(h)if(d&&(LP_fieldIsReadOnly(h)||LP_fieldIsDisabled(h)))decision_log(e,"DE24");else if(c&&!lpIsVisible(h,!0))decision_log(e,"DE25");else{if(b){var r=new RegExp(lpgs("ff_search_regexp"),"i");if(r.exec(h.name)||r.exec(h.id)){var r=h.name&&h.name.match(/[qQ]/)||h.id&&h.id.match(/[qQ]/),n=new RegExp(lpgs("ff_username_regexp"),"i"),t=new RegExp(lpgs("ff_email_regexp"),
"i");if(r&&h.name&&!h.name.match(/^[qQ]/)&&(!h.id||h.id&&!h.id.match(/^[qQ]/)))pass;else if(r&&h.id&&!h.id.match(/^[qQ]/)&&(!h.name||h.name&&!h.name.match(/^[qQ]/)))pass;else if(r&&(n.exec(h.name)||n.exec(h.id)||t.exec(h.name)||t.exec(h.id)))pass;else{decision_log(e,"DE23");continue}}}popupfill_shoulddofield(e,h,!1)||("text"!=h.type&&"tel"!=h.type&&"email"!=h.type||m||(b?(r=new RegExp(lpgs("ff_username_regexp"),"i"),r.exec(h.name)||r.exec(h.id)?(l=h,p=!0):p||(l=h)):l=h),"password"!=h.type||m||(b?
(r=new RegExp(lpgs("ff_username_regexp"),"i"),p||!r.exec(h.name)&&!r.exec(h.id)?m=h:l=h):m=h))}}a={};l&&(a.text=l);m&&(a.password=m);return isEmptyObject(a)?null:a}
function ForceFillClicked(a,b,d){var c=g_popupfill_parent;c||(c=g_popupfill_parent_last);if(!c){if(g_force_fill_active_element){var e=LP_getActiveElement(a);e&&"INPUT"==e.tagName&&LP_docHasFocus(a)&&hasIconState(a,LP_pickFieldName(a,e))&&(c=e,info_log("CV21"))}if(!c)return!1}if(!a&&(a=c.ownerDocument,!a))return!1;var e=chk_form_has_password(a,c.form),f=chk_form_ask_generate(a,c.form);return c.form&&e&&!f?ForceFillFormClicked(a,c.form,b,d)&&""!==c.value?!0:ForceFillFieldClicked(a,c,b,d):null==c.form?
ForceFillOrphanFieldClicked(a,c,d):ForceFillFieldClicked(a,c,b,d)}function isMultiStageLoginForm(a){}function LP_passwordAlt(a,b){return a&&b&&"INPUT"==b.tagName?"nyckel"==LP_pickFieldName(a,b).toLowerCase()&&"password"==b.type?!0:!1:!1}
function LP_explicit_ignored(a,b){if(!a||!b||"undefined"==typeof b.getAttribute)return!0;var d=b.getAttribute("data-lpignore");if("true"===d)return!0;d=b.dataset?b.dataset.lpignore:!1;if("true"===d)return!0;d=b.getAttribute("lpignore");return"true"===d||"true"===b.lpignore?!0:!1}function countFormEquivalents(a){var b=0,d=a.getElementsByTagName("FORM");a=LP_getFormsThreshold(a);for(var c=0;c<d.length&&c<a;c++)lpIsVisible(d[c]),b++;return b}
function LP_implicit_ignored(a,b){if(!b||!a&&(a=LP_derive_doc(),!a))return!1;var d=b.id,c=b.name,e=a.body,f=b.form;if(c&&"post_title"==c&&e&&e.className&&0<=e.className.indexOf("wp-admin")||c&&("symbols"==c||"symbol"==c)||"text"==b.type&&d&&(0<d.indexOf("_note")||0<d.indexOf("-note")))return!0;var e=new RegExp(lpgs("ff_combineddummy_regexp"),"i"),g=/member.*number/i;return!e.exec(d)&&!e.exec(c)||g.exec(d)||g.exec(c)?LP_field_is_xsrf(a,b)||f&&!popupfill_shoulddoform(a,f)?!0:!1:(decision_log(a,"DE22",
{param1:d,param2:c}),!0)}function LP_read_website_hint(a,b){}
function should_ignore_body_relative(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","ignore-relative-style");if(!0===b||!1===b)return b;LP_get_cached_body_rect(a);var b=LP_get_body_reference(a),d=LP_get_cached_body_style(a);if(d&&"relative"!=d.position)return formcacheset(a,"fakedoc","ignore-relative-style",!0),!0;d=[];b&&(d=b.children);if(d&&0<d.length)for(Checkpoint.assert(100>d.length,"too many body.children"),b=0;b<d.length&&100>b;b++)if(!lp_in_array(d[b].tagName.toUpperCase(),
["SCRIPT"])&&lp_in_array(d[b].tagName.toUpperCase(),["DIV","SECTION","FORM"])){if((b=LP_get_live_style(d[b]))&&"relative"==b.position)return formcacheset(a,"fakedoc","ignore-relative-style",!1),!1;break}formcacheset(a,"fakedoc","ignore-relative-style",!0);return!0}
function LP_iconFieldWidthOK(a,b,d){if(!a||null===b)return!1;var c=a.ownerDocument;if(!c)return verbose_log("iconFieldWidthOK: no doc???"),!1;if("undefined"==typeof d||null===d)if(isInputFieldPassword(c,a))d=!0;else{var e=a.form;e&&chk_form_has_password(c,e)&&(d=!0)}if(d){if(!(0<b&&40>b))return a?(b=a.getAttribute("size"),d=a.getAttribute("maxlength"),null==b&&(b=a.size),null==d&&(d=a.maxLength),a=""==a.style.width&&b&&2>b&&0<=b||d&&3>d&&0<=d?!1:!0):a=!1,a?!0:!1}else if(!(0<b&&100>b))return!0;return!1}
function create_icons_on_ASP(a,b){if(do_experimental_popupfill){a||(a=LP_derive_doc());if(!a)return!1;decision_log(a,"DE21",{param1:a.location.href});var d=[];if(g_do_icon_number_hint)if(g_isfirefox){var c=LP.getMatchingSites(a.location.href,SKIP_GENPWS);d.sites=c&&c.length?c.length:0}else d=g_icon_numbers;var c=a.getElementsByTagName("FORM"),e,f,g=SHOULD_DO_ALWAYS,l=LP_getFormsThreshold(a),m=0;for(f=0;f<c.length&&f<l;f++){var p=c[f].elements;chk_form_has_password(a,c[f]);chk_form_is_nonlogin_form(a,
c[f]);chk_form_ask_generate(a,c[f]);var h=form_get_username(a,c[f]),r=form_get_password(a,c[f]),n=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(n=MAX_INPUTS_HARD);for(e=0;e<p.length&&e<n;e++){var t=!1,q=p[e],k="sites";if("INPUT"==q.tagName){var u=!1;if(popupfill_shoulddofield(a,q,g)){var v=LP_fieldGetWidth(q),w=!0;if(b){if(looksLikeUsername(q)||isInputFieldPassword(a,q))k="sites",t=!0}else if(h==q)k="sites",t=!0;else if(isInputFieldPassword(a,q))q==lpCheckCurrentPWField(c[f],!0)?(k="sites",u=t=!0):
r==q?(k="sites",u=t=!0):isContigPW(a,q.form,q)?(k="generate",t=!0):(k="sites",u=t=!0);else if(isFirstFieldNonLoginSubForm(a,q))k="formfills",t=!0,w=!1;else if(isUsernameFieldLoginSubForm(a,q)||isPasswordFieldLoginSubForm(a,q))k="sites",u=t=!0;t&&LP_iconFieldWidthOK(q,v,w)&&(m++,setup_input_icon(a,q,k,d,u),!g_clickable_input||"password"==q.type&&formHasUsernameField(q)&&!g_clickable_input_on_password||LP_didFieldClickEvent(a,q)||!k||"sites"!=k||(LP_setFieldClickEvent(a,q),LP_addEventHandler(q,"click",
function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,q.form),popuptoggle(a,null,LP_getname_or_idx(a,q,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(A){}return!1},!1)))}}}}decision_log(a,
"DE1",{param1:m})}}
function check_for_ASP(a,b){if(b&&!isASPpage()&&g_aspx_hack){0!==b.name.indexOf("ctl00$")&&(null==b.form||"ctl00"!=b.form.name&&"landingform"!=b.form.name&&"landingForm"!=b.form.name&&"aspnetForm"!=b.form.name&&"aspnetForm"!=b.form.id)&&0!==b.name.indexOf("ctl00_")||isASPpage()||(setASPpage(!0),decision_log("DE20"));try{a.location&&a.location.href&&0<a.location.href.indexOf(".aspx")&&b.form&&b.form.elements&&b.form.elements.length&&6<b.form.elements.length&&!isASPpage()&&(setASPpage(!0),decision_log("DE19"))}catch(d){write_error_to_history(a,
"check_for_ASP",d)}}}
function create_icons_generic(a,b){if(do_experimental_popupfill){if(!a&&(a=LP_derive_doc(),!a))return null;decision_log(a,"DE16",{param1:a.location.href});var d=[];if(g_do_icon_number_hint)if(g_isfirefox){var c=LP.getMatchingSites(a.location.href,SKIP_GENPWS);d.sites=c&&c.length?c.length:0}else d=g_icon_numbers;var c=a.getElementsByTagName("INPUT"),e,f=c.length;e=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(e=MAX_INPUTS_HARD);Checkpoint.assert(f<=e,"page has too many inputs");f>e&&(f=e);var g=SHOULD_DO_ALWAYS,
l=checkDocumentForLoginOrphans(a);LP_firstVisibleOrphan(a);var m=0;for(e=0;e<f;e++){var p=c[e].form,h=null,r=null;p?(h=form_get_username(a,p),r=form_get_password(a,p)):(h=doc_get_orphan_username(a),r=doc_get_orphan_password(a));var n=c[e],t=!1,q="sites",k=!1;if(popupfill_shoulddofield(a,n,g)){var u=LP_fieldGetWidth(n),v=!0;if(b){if(looksLikeUsername(n)||isInputFieldPassword(a,n))q="sites",t=!0}else h==n?(q="sites",t=!0):isInputFieldPassword(a,n)?p&&n==lpCheckCurrentPWField(p,!0)?(q="sites",k=t=!0):
lpIsFieldCurrentPWField(n)?(q="sites",k=t=!0):r==n?(q="sites",k=t=!0):isContigPW(a,n.form,n)?(q="generate",t=!0):(q="sites",k=t=!0):isFirstFieldNonLoginSubForm(a,n)?(q="formfills",t=!0,v=!1):isUsernameFieldLoginSubForm(a,n)||isPasswordFieldLoginSubForm(a,n)?(q="sites",k=t=!0):null==n.form&&l&&(looksLikeUsername(n)||isInputFieldPassword(a,n))&&(q="sites",t=!0);t&&LP_iconFieldWidthOK(n,u,v)&&(m++,setup_input_icon(a,n,q,d,k),!g_clickable_input||"password"==n.type&&formHasUsernameField(n)&&!g_clickable_input_on_password||
LP_didFieldClickEvent(a,n)||!q||"sites"!=q||(LP_setFieldClickEvent(a,n),LP_addEventHandler(n,"click",function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,n.form),popuptoggle(a,null,LP_getname_or_idx(a,n,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));else if(g_input_click_intercept)try{info_log(a,
"FF12"),icon_click_handler(b)}catch(z){}return!1},!1)))}}decision_log(a,"DE2",{param1:m});return!0}}
function LP_getAngularAttributes(a,b){a||(a=LP_derive_doc());if(!b||!a)return null;for(var d={},c="ng-model ng-controller ng-repeat ng-include ng-switch ng-view ng-minlength ng-maxlength ng-pattern ng-click ng-submit ng-required".split(" "),e=0;e<c.length;e++){var f=b.getAttribute(c[e]);null!==f&&(d[c[e]]=f)}c="ng-valid ng-invalid ng-pristine ng-dirty ng-touched ng-untouched ng-pending ng-empty ng-not-empty".split(" ");for(e=0;e<c.length;e++)f=sprintf("[\\w]*%s[\\w]*",c[e]),b.className.match(f)&&
(d[c[e]]=!0);return d}function LP_hasAngular(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,d=formcacheget(a,"fakedoc","has-angular");if(null!=d)return d;var d=a.documentElement,c=a.body;c&&c.getAttribute("ng-app")||d&&d.getAttribute("ng-app")||c&&null!==c.getAttribute("ng-strict-di")||d&&null!==d.getAttribute("ng-strict-di")?b=!0:LP_getElementByXPath(a,"//*[@ng-app!='']")&&(b=!0);formcacheset(a,"fakedoc","has-angular",b);return b}
function LP_hasKnockout(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,d=formcacheget(a,"fakedoc","has-knockout");if(null!=d)return d;if(g_isie)for(var d=a.getElementsByTagName("input"),c=0;c<d.length&&c<MAX_INPUTS_HARD;c++){if(d[c].getAttribute("data-bind")){b=!0;break}}else(d=LP_getElementsByXPath(a,"//*[@data-bind != '']"))&&0<d.length&&(b=!0);formcacheset(a,"fakedoc","has-knockout",b);return b}
function LP_has_yui(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","has-yui");if(null!=b)return b;if(a.documentElement&&0<=a.documentElement.className.indexOf("yui3-js-enabled")||a.documentElement&&0==a.documentElement.id.indexOf("yui_3")||a.getElementById("yui3-css-stamp"))return formcacheset(a,"fakedoc","has-yui",!0),!0;formcacheset(a,"fakedoc","has-yui",!1);return!1}
function LP_field_is_xsrf(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=!1;b.tagName&&"INPUT"==b.tagName.toUpperCase()&&"string"==typeof b.name&&(0<=b.name.toUpperCase().indexOf("CSRF")||0<=b.name.toUpperCase().indexOf("XSRF")||0<=b.id.toUpperCase().indexOf("CSRF")||0<=b.id.toUpperCase().indexOf("XSRF"))&&(d=!0);return d}
function LP_get_youama_fields(a){a||(a=LP_derive_doc());if(!a)return null;var b;b=formcacheget(a,"orphans","youama-fields");if(null!=b)return b;b=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//input[@id='youama-email']");var d=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//input[@id='youama-password']"),c=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//button[contains(@class,'youama-ajaxlogin-button')]"),e=LP_getElementByXPath(a,
"//div[contains(@class,'youama-login-window')]"),f=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//input[@id='youama-email']"),g=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//input[@id='youama-password']"),l=LP_getElementByIdOrName(a,"youama-firstname"),m=LP_getElementByIdOrName(a,"youama-lastname"),p=LP_getElementByIdOrName(a,"youama-passwordsecond"),h=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//button[contains(@class,'youama-ajaxlogin-button')]"),
r=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]");b={login_username:b,login_password:d,login_button:c,login_form_container:e,regis_username:f,regis_password:g,regis_password_confirm:p,regis_firstname:l,regis_lastname:m,regis_button:h,regis_form_container:r};formcacheset(a,"orphans","youama-fields",b);return b}
function LP_has_youama(a){a||(a=LP_derive_doc());if(!a)return[];var b=formcacheget(a,"fakedoc","has-youama");if(null!=b)return b;if(0<a.getElementsByClassName("youama-login-window").length||0<a.getElementsByClassName("youama-register-window").length)return formcacheset(a,"fakedoc","has-youama",!0),!0;formcacheset(a,"fakedoc","has-youama",!1);return!1}
function LP_has_dijit(a){a||(a=LP_derive_doc());if(!a||!a.documentElement)return[];var b,d=a.getElementsByClassName("dijitContentPane");if(d&&0<d.length||a.documentElement.className.match(/^dj_[a-z]+|\sdj_[a-z]+/))return!0;d=a.getElementsByTagName("SCRIPT");for(b=0;b<d.length;b++)if("dojo/connect"==d[b].getAttribute("type")||"dojo/method"==d[b].getAttribute("type"))return!0;d=a.getElementsByTagName("FORM");for(b=0;b<d.length;b++)if(d[b].getAttribute("data-dojo-attach-point"))return!0;return!1}
var LP_milestone_flags=0;function LP_parser_milestone(a){if("undefined"==typeof a)return!1;LP_milestone_flags|=a;return!0}
function page_is_nemid(a){a||(a=LP_derive_doc());if(!a)return!1;var b=lp_gettld_url(punycode.URLToASCII(get_doc_location_href(document))),d="",c="",e=!1,f=formcacheget(a,"fakedoc","is-nemid");if(null!=f)return f;try{if(!get_can_xref(a,"top"))throw"xref";d=window.name;c=window.top.name}catch(g){set_can_xref(a,"top",!1)}"danid.dk"!=b&&"nemid.nu"!=b||!a.getElementById("appArea")&&"nemid_iframe"!=d&&"loginWindow"!=c||(e=!0);formcacheset(a,"fakedoc","is-nemid",e);return e}
function LP_element_is_honeypot(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=gettldcached(get_doc_location_href(a)),c=[],e,f,g,l=["lpcurrpasselt","lpcurruserelt"];if(lp_in_array(b.id,l))return!1;if(has_same_tld(d,"citi.com")){if(a.getElementById("loginForm")||a.getElementById("logon")||a.getElementById("password")||a.getElementById("PASSWORD")){e=a.getElementsByTagName("input");f=e.length;for(g=0;g<MAX_INPUTS_SOFT&&g<f;g++)e[g]&&"password"==e[g].type&&!lp_in_array(e[g].id,l)&&c.push(e[g]);
if(5==c.length&&"a"==c[0].defaultValue&&"b"==c[1].defaultValue&&"c"==c[2].defaultValue&&"d"==c[3].defaultValue&&lp_in_array(b,[c[0],c[1],c[2],c[3]]))return!0}}else if(compare_equiv_domains(d,"ebay.com")&&1===a.getElementsByName("runId2").length&&("userid"==b.id||"userid"==b.name||"pass"==b.id||"pass"==b.name||"runId2"==b.name))return!0;return compare_equiv_domains(d,"nordnet.no")&&"fake_password"==b.name?!0:!1}
function LP_page_is_lazyloader(a,b){a||(a=LP_derive_doc());if(!a)return!1;var d=!1,c=formcacheget(a,"fakedoc","is-lazyloader");if(null!=c)return c;if(LP_hasAngular(a)||LP_hasKnockout(a)||LP_has_emberjs(a))return formcacheset(a,"fakedoc","is-lazyloader",!0),!0;if(a.body&&(c=a.body.getAttribute("onload"),"string"==typeof c&&0<=c.toLowerCase().indexOf("lazyload")))return!0;var e,f,g=/requirejs|lazyload|LAB\.?js|LAB\.min\.js/i,l=/dojo/;if(!g||!l)return!1;for(var m=a.getElementsByTagName("script"),c=0;c<
m.length;c++)if(e=m[c].getAttribute("src")){id=m[c].id;if(g.exec(e)||g.exec(id)){d=!0;break}f=m[c].getAttribute("type");if("module"==f){d=!0;break}if(l.exec(e)&&(e=m[c].getAttribute("data-dojo-config"),"async: true"==e)){d=!0;break}if("microloader"==id&&m[c].getAttribute("data-app")){d=!0;break}e=m[c].getAttribute("data-requirecontext");f=m[c].getAttribute("data-requiremodule");if(e&&f){d=!0;break}}else if((e=m[c].innerHTML)&&512>e.length&&0<e.indexOf("function SRSRetry"))return!0;if(!d)for(g=a.getElementsByTagName("meta"),
c=0;c<g.length;c++)if(l=g[c].name,"string"==typeof l&&l.match(/config\/environment$/)){d=!0;break}formcacheset(a,"fakedoc","is-lazyloader",d);return d}function LP_isSinglePageApp(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","SPA");return null!=b?b:LP_hasAngular(a)||LP_hasKnockout(a)||LP_has_emberjs(a)||0<g_probablySinglePageApp||LP_url_is_single_page_app(get_doc_location_href(a))?(formcacheset(a,"fakedoc","SPA",!0),!0):!1}var g_probablySinglePageApp=0;
function LP_has_jquery(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,d=formcacheget(a,"fakedoc","has-jquery");if(null!=d)return d;for(var c=/jquery/i,e=a.getElementsByTagName("script"),f=0;f<e.length;f++)if(d=e[f].getAttribute("src"),c.exec(d)){b=!0;break}formcacheset(a,"fakedoc","has-jquery",b);return b}
function LP_init_url_history(a){a||(a=LP_derive_doc());if(!a)return!1;if("undefined"==typeof LPUH||null===LPUH||null===LPUH.url_history){LPUH={};if(null===LPUH)return!1;LPUH.url_history=[]}return!0}function LP_get_last_url_history(a){a||(a=LP_derive_doc());if(!a)return!1;LP_init_url_history(a);return LPUH&&(a=LPUH.url_history.length,0<a)?LPUH.url_history[a-1]:{}}function LP_reset_url_history(a){LP_init_url_history(a);return LPUH?(LPUH.url_history=[],!0):!1}
function LP_put_last_url_history(a){a||(a=LP_derive_doc());if(!a)return!1;LP_init_url_history(a);a=get_doc_location_href(a);var b=crc32(LP_gettime()+"%"+a);LPUH.url_history.push({href:a,href_hash:b});verbose_log("computed new hash "+b+" for "+a);return!0}function LP_has_extjs(a){}function LP_is_buttonlike(a,b){a||(a=LP_derive_doc());return a&&b?"BUTTON"==b.tagName||"INPUT"==b.tagName&&("submit"==b.type||"image"==b.type||"button"==b.type)?!0:!1:!1}var BEEPID="_lpbeep";
function LP_putBeeper(a,b,d){a||(a=LP_derive_doc());if(!a)return!1;if(a.getElementById(BEEPID))return!0;if(!d&&!a.body)return!1;var c=a.createElement("div");c.setAttribute("aria-hidden","true");c.style.display="none";c.style.left="-1000px";c.style.height="0";c.setAttribute("data-lpbeep",b);c.id=BEEPID;d?d.appendChild(c):a.body.appendChild(c);return!0}function LP_pickBeeper(a){a||(a=LP_derive_doc());if(!a)return!1;(a=a.getElementById(BEEPID))&&a.parentNode.removeChild(a);return!0}
function LP_readBeeper(a){a||(a=LP_derive_doc());if(!a)return null;if(a=a.getElementById(BEEPID)){var b=getComputedStyle(a);return{display:b.display,visibility:b.visibility,val:a.getAttribute("data-lpbeep")}}return null}
function should_fill_on_click(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var d=!1,c=b.tagName.toUpperCase(),e=b.form,f=!1,g=b.getAttribute("role");if(LP_is_buttonlike(a,b)&&e){var l=e.action,e=e.method;l&&0==l.toLowerCase().indexOf("https://")&&e&&"POST"==e.toUpperCase()&&(f=d=!0)}f||"A"!=c&&"NAV"!=c&&"navigation"!=g&&("INPUT"!=c||"submit"!=b.type)||(d=!1,f=!0);f||lp_in_array(c,"INPUT LABEL SELECT FIELDSET OPTION TEXTAREA TBODY THEAD ADDRESS BLOCKQUOTE Q PRE ABBR CITE BODY HEAD META SCRIPT STYLE MAIN ARTICLE HEADER FOOTER ASIDE DETAILS FIGURE FIGCAPTION MARK SECTION SUMMARY TIME IFRAME FRAME FRAMESET".split(" "))&&
(d=!0);return!d}function should_simulate_submit_on_click(a,b){a||LP_derive_doc();return!1}function LP_url_is_single_page_app(a){return a&&"string"==typeof a?/https?:\/\/.*#\/[a-z]/i.exec(a)?!0:!1:!1}
function LP_has_bootstrapJS(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,d=formcacheget(a,"fakedoc","has-bootstrap");if(null!=d)return d;for(var c=/bootstrap.min.js$/i,e=a.getElementsByTagName("script"),f=0;f<e.length;f++)if(d=e[f].getAttribute("src"),c.exec(d)){b=!0;break}formcacheset(a,"fakedoc","has-bootstrap",b);return b}
function LP_has_joomla(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,d=formcacheget(a,"fakedoc","has-joomla");if(null!=d)return d;for(var c=/(\/media\/jui\/js|\/templates\/joomla)/i,e=a.getElementsByTagName("script"),f=0;f<e.length;f++)if(d=e[f].getAttribute("src"),c.exec(d)){b=!0;break}formcacheset(a,"fakedoc","has-joomla",b);return b}
function LP_has_emberjs(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,d=formcacheget(a,"fakedoc","has-emberjs");if(null!=d)return d;(d=a.body)&&(0<=d.className.indexOf("ember-application")||"1"==d.getAttribute("data-ember-extension"))&&(b=!0);!b&&a.documentElement&&"1"==a.documentElement.getAttribute("data-ember-extension")&&(b=!0);if(!b)for(var d=a.getElementsByTagName("meta"),c,e=0;e<d.length;e++)if(c=d[e].name,"string"==typeof c&&c.match(/config\/environment$/)){b=!0;break}formcacheset(a,"fakedoc",
"has-emberjs",b);return b}var SPA_INDETERMINATE=0,SPA_LOADED=1,SPA_LOGIN=2,SPA_LOGINFAILED=4,SPA_ACCTMGMT=8,SPA_REGISTER=16,SPA_APP=32,SPA_INDETERMINATE_STATE="A",SPA_LOGIN_STATE="B",SPA_IN_APP_STATE="C",SPA_LOGIN_WITHIN_APP_STATE="D";
