var KEY_UP=38,KEY_DOWN=40,KEY_ENTER=13,ELEMENT_NODE=1,KEY_ESCAPE=27,KEY_F4=115,KEY_LEFT=37,KEY_RIGHT=39,KEY_HOME=36,KEY_END=35,g_do_complete=!0,g_do_svg=!0;function openCombo(a,d,c,b){b=b?b:document;a=b.getElementById(d);a.disabled||(c=gComboEx=b.getElementById(c),"block"!=c.style.display?showCombo(a,c,null,b):setStyle(c,"display","none",""),gItemNum=-1,gFocusItem=a,("undefined"!=typeof window?window:b.defaultView).setTimeout(function(){doFocus()},0))}
var g_iField=null,g_cb=null,g_combobox_button=null;function showCombo(a,d,c,b){b=b?b:document;g_iField=a;g_cb=d;null!=a&&(d=getComboButtonId(a.id),g_combobox_button=b.getElementById(d),"undefined"!=typeof a.addEventListener?a.addEventListener("move",function(a){realShowCombo(b)},!1):a.attachEvent("onmove",function(a){realShowCombo(b)}));realShowCombo(b)}function getY(a){for(var d=0;null!=a;)d+=a.offsetTop,a=a.offsetParent;return d}
function getX(a){for(var d=0;null!=a;)d+=a.offsetLeft,a=a.offsetParent;return d}
function realShowCombo(a){null==a&&(a=document);var d=getY(g_iField),c=getX(g_iField),d=d+g_iField.offsetHeight+"px",c=c+"px";g_cb.style.minWidth=g_iField.offsetWidth-14+"px";setStyle(g_cb,"top",d,"");setStyle(g_cb,"left",c,"");setStyle(g_cb,"display","block","");g_combobox_button&&setStyle(g_combobox_button,"display","","");c=LP_getAbsolutePos(a,g_iField);null!=c&&0<c.left&&(a="undefined"!=typeof window&&"undefined"!=typeof window.setTimeout?window:a.defaultView,d=a.innerWidth,null==d&&"undefined"!=
typeof getWindowWidth&&(d=getWindowWidth(a)),null!=d&&0<d&&(g_cb.style.maxWidth=parseInt(d)-parseInt(c.left)-16+"px",parseInt(g_cb.style.maxWidth)<parseInt(g_cb.style.minWidth)&&(g_cb.style.minWidth=g_cb.style.maxWidth)))}var gItemNum=0,gComboEx=null;
function focusCombo(a,d,c){a||(a=window.event);if(a){var b=a.keyCode;if("undefined"!=typeof TABKEY&&(b==TABKEY||b==SHIFTKEY)&&(b="undefined"!=typeof document&&document.location?document.location.href:"",-1!=b.indexOf("popupfilltab.html")||-1!=b.indexOf("#framesrc=LPMAGIC")))return tabfocuser(a),!1;var e="undefined"!=typeof document?document:a.view.document,b=a.keyCode;a=!0;c=gComboEx=e.getElementById(c);if(b==KEY_DOWN||b==KEY_F4){a=!1;"block"!=c.getAttribute("style.display")&&showCombo(d,c,null,e);
d=c.childNodes;c=d.length;for(b=0;null!=d[b]&&b<c;){if(d[b].nodeType==ELEMENT_NODE&&"item"==d[b].className&&"none"!=d[b].style.display){gFocusItem=d[b];break}b++}gItemNum=b;b>=c&&(gItemNum=0);setTimeout(function(){doFocus()},0);a=!1}else b!=KEY_ENTER&&b==KEY_ESCAPE&&(null!=d.val&&0<d.val.length?a=!0:(a=!1,setStyle(gComboEx,"display","none",""),gItemNum=-1));return a}}
function focusItem(a,d,c){a=c.val;for(var b=null,e=getItems(d),h=e.length,k=!1,n=0;n<h;n++)if(e[n].hasChildNodes()&&e[n].firstChild.nodeValue==a){k=!0;b=e[n];gItemNum=n;break}k||(b=addItem(d,a,e.length),gItemNum=e.length);null!=b&&(gFocusItem=b,"block"!=gComboEx.getAttribute("style.display")?(a=c.offsetLeft+"px",setStyle(d,"top",c.offsetTop+c.offsetHeight+"px",""),setStyle(d,"left",a,"")):setStyle(d,"display","none",""),setStyle(d,"display","block",""),setTimeout(function(){doFocus()},0))}
function addItem(a,d,c,b){b||(b=document);var e=b.createElement("div"),h="undefined"!=typeof d.label?d.label:d;e.val="undefined"!=typeof d.label?d.value:d;e.label=h;if("undefined"!=typeof d.label&&(e.label=d.label,"undefined"!=typeof d.image)){var k=b.createElement("img");k.src=d.image;k.style.paddingRight="15px";e.appendChild(k);e.img=k.src}d=b.createTextNode(h);e.appendChild(d);e.setAttribute("tabindex","-1");e.setAttribute("class","item");e.setAttribute("data-lpcount",c);"undefined"!=typeof e.addEventListener?
(e.addEventListener("click",function(){gItemNum=this.getAttribute("data-lpcount")}),e.addEventListener("mouseover",function(){gFocusItem=this;doFocus()})):(e.attachEvent("onclick",function(){gItemNum=e.getAttribute("data-lpcount")}),e.attachEvent("onmouseover",function(){gFocusItem=e;doFocus()}));e.setAttribute("role","listitem");e.setAttribute("origText",ofa(h));a.appendChild(e);return e}
function doComboNav(a,d,c,b){a||(a=window.event);if(a){var e=a.keyCode,h=!0;null==gComboEx&&(gComboEx=d);if(e==KEY_UP||e==KEY_DOWN){h=!1;a=0;d=getItems(gComboEx);var k=d.length;if(e==KEY_UP)for(a=gItemNum-1;0<=a&&"none"==d[a].style.display;)"none"==d[a].style.display&&a--;else{a=gItemNum+1;for(a==k&&(a=-1);0<=a&&a<k&&"none"==d[a].style.display;)"none"==d[a].style.display&&a++;a==k&&(a=-1)}gItemNum=a;gFocusItem=-1==gItemNum?b.getElementById(c):d[a];setTimeout(function(){doFocus()},0)}else if(e==KEY_ENTER||
!a.keyCode&&0<=a.button){if(d=getItems(gComboEx),e=d[gItemNum],null!=e&&"true"!=e.getAttribute("aria-disabled")){a=e.label;d=e.val;c=b.getElementById(c);c.value=a;c.val=d;"undefined"!=typeof e.img&&(c.style.background="url("+e.img+") no-repeat 2px 5px",c.style.paddingLeft="25px");if(c.onchange)c.onchange();setStyle(gComboEx,"display","none","");gItemNum=0;gFocusItem=c;setTimeout(function(){doFocus()},0)}}else e==KEY_ESCAPE&&(h=!1,setStyle(d,"display","none",""),gItemNum=0,gFocusItem=b.getElementById(c),
setTimeout(function(){doFocus()},0));return h}}function getItems(a){if(null===a)return[];var d;d=[];a=a.childNodes;for(var c=a.length,b=0;b<c;b++)a[b].nodeType!=ELEMENT_NODE||"item"!=a[b].getAttribute("class")&&"item focus"!=a[b].getAttribute("class")||(d[d.length]=a[b]);return d}
function setStyle(a,d,c,b){var e=!1;try{a.style&&a.style.setProperty&&(a.style.setProperty(d,c,b),e=!0)}catch(h){alert("exception caught setting style: "+h.message)}if(!e)try{a.style[d]=c,e=!0}catch(h){alert("exception caught setting direct style: "+h.message)}return e}var gFocusItem=null,gLastFocusItem=null;
function doFocus(){null!=gFocusItem&&(gFocusItem.focus(),gLastFocusItem&&"item focus"==gLastFocusItem.className&&(gLastFocusItem.className="item"),gFocusItem&&"item"==gFocusItem.className&&(gFocusItem.className="item focus"),gLastFocusItem=gFocusItem,gFocusItem=null)}
function create_combo(a,d,c,b,e,h,k,n,m){b||(b=document);e||(e="");var f=b.getElementById(a),q=getComboId(a);if(f&&!b.getElementById(q)&&null!==q){f.onkeydown=function(a){a||(a=window.event);return focusCombo(a,f,q)};f.onkeyup=function(a){a||(a=window.event);keyupCombo(b,a,f,q);return!1};f.setAttribute("role","textfield");f.setAttribute("aria-haspopup","true");f.setAttribute("autocomplete","off");f.style.marginRight="0px";var g=b.createElement(e+"div"),w=g;g.setAttribute("role","list");g.style.display=
"none";"undefined"!=typeof g_isie&&g_isie&&(g.style.display="none");g.setAttribute("id",q);g.setAttribute("class","dropStyle");"undefined"!=typeof g_isie&&g_isie&&(g.className="dropStyle");g.onkeydown=function(a){return doComboNav(a,this,this.id.substring(0,this.id.length-6),b)};"undefined"!=typeof g.addEventListener?g.addEventListener("click",function(a){doComboNav(a,this,this.id.substring(0,this.id.length-6),b)}):g.attachEvent("onclick",function(a){a||(a=window.event);if(!a)return!1;doComboNav(a,
w,w.id.substring(0,w.id.length-6),b)});g.style.overflowY="auto";g.style.overflowX="auto";"undefined"!=typeof g_isie&&g_isie&&(g.style.background="#fff");g.style.paddingLeft="6px";g.style.paddingRight="6px";g.style.position="absolute";g.setAttribute("autofilled","false");m?insertAfter(b.getElementById(m),g):"undefined"!=typeof b.body&&b.body?b.body.appendChild(g):f.parentNode.parentNode.appendChild(g);"undefined"!=typeof f.ownerDocument.defaultView&&"undefined"!=typeof f.ownerDocument.defaultView.addEventListener?
(f.ownerDocument.defaultView.addEventListener("click",function(c){c.target.id!=a&&close_combo(a,b)},!1),f.addEventListener("keydown",function(c){9==c.keyCode&&close_combo(a,b)},!1)):(document.attachEvent("onclick",function(c){window.event.srcElement.id!=a&&close_combo(a,b)}),document.attachEvent("onkeydown",function(c){9==window.event.keyCode&&close_combo(a,b)}));for(m=0;m<d.length;m++)addItem(g,d[m],m,b);d=("undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/pwdrop.png";g_do_svg&&(d=("undefined"==
typeof gLocalBaseUrl?"":gLocalBaseUrl)+"images/teardrop.png");if("undefined"!=typeof g_isie&&g_isie||"undefined"!=typeof g_isfirefox&&g_isfirefox)d="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAfElEQVQ4T2NkoDJgpLJ5DKMGUh6io2GIGobe3t4LGBkZ49FD9v///wu3bt2agC3ECYYhuqH4DANZQNDAgIAAgT9//hwAqtUH4ossLCwOGzZs+IArPRA0EKQRZOjv378nsLKyFuAzjCgXkpoyiXIhKYaOGkhKaGFXS/UwBABG2SEVsoLJ9AAAAABJRU5ErkJggg==";if(c&&"undefined"!=typeof LP_getAbsolutePos){var t=0,r=0,g=b.createElement(e+"div");
"undefined"!=typeof b.body&&b.body?h?insertAfter(b.getElementById(h),g):b.body.appendChild(g):f.parentNode.appendChild(g);var l=getComboButtonId(a);c=[];var u=3,x;x="undefined"!=typeof f.ownerDocument.defaultView&&"undefined"!=typeof f.ownerDocument.defaultView.getComputedStyle?f.ownerDocument.defaultView.getComputedStyle(f):f.currentStyle;e=LP_getAbsolutePos(b,f);if(!e)return;if(null!=e&&0<e.left&&0<e.top){var v;v=e.left+parseInt(e.width)+4-30;r=t=0;"undefined"!=typeof g_isie&&g_isie&&(r=-4,t=2);
c.left=v+r+"px";c.position="absolute";c.top=parseInt(e.top)+4+t+"px";"undefined"!=typeof g_isfirefox&&g_isfirefox||(c.padding=u+"px")}var p=Math.floor((30-e.height)/2);1<=p&&30>e.height&&(r=t=0,c=[],c.position="absolute",c.height=e.height-4+"px",c.width=e.height-4+"px",c.top=parseInt(e.top)+4+p+4+"px",v=e.left+parseInt(e.width)+4-30+p+4,c.left=v+p+"px",u-=2*p,0>u&&(u=0),"undefined"!=typeof g_isfirefox&&g_isfirefox||(c.padding=u+"px"));p=Math.round((e.height-30)/2);30<e.height&&(r=t=0,"undefined"!=
typeof g_isie&&g_isie&&(c=parseInt(x.borderTopWidth),r=parseInt(x.borderBottomWidth),p-=(c+r)/2,r=-5,t=c),c=[],c.left=v+r+"px",c.position="absolute",c.top=e.top+p+t+"px",u+=2*p,"undefined"!=typeof g_isfirefox&&g_isfirefox||(c.padding=u+"px"));"undefined"!=typeof g_isie&&g_isie&&(c.border="0px");f.style.textOverflow="ellipsis";f.style.whiteSpace="nowrap";h&&(g.style.marginLeft=k?k+"px":"-15px",g.style.display="inline",g.style.verticalAlign="top",g.style.marginTop="6px",n?(c=[],c.marginTop=n+"px"):
c.marginTop="-18px");h=g.ownerDocument.createElement(g_isfirefox?"image":"img");h.setAttribute("id",l);h.setAttribute("src",d);h.setAttribute("valign","middle");g.appendChild(h);l=b.getElementById(l);if(!l)return;for(m in c)c.hasOwnProperty(m)&&(l.style[m]=c[m]);l.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),b);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0}}else c||"undefined"==typeof LP_getAbsolutePos||(l=b.createElement(e+
"img"),l.id=getComboButtonId(a),null!==l.id&&(l.onclick=function(a){openCombo(a,this.id.substring(0,this.id.length-7),getComboId(this.id.substring(0,this.id.length-7)),b);null!=a?a.cancelBubble=!0:window.event.cancelBubble=!0}),l.setAttribute("src",d),l.setAttribute("valign","middle"),"undefined"!=typeof g_isopera&&g_isopera&&(l.style.position="relative",l.style.top="7px"),"undefined"!=typeof b.body&&b.body?b.body.appendChild(l):b.getElementById("main").appendChild(l),e=LP_getAbsolutePos(b,f),null!=
e&&0<e.left&&0<e.top&&(v=e.left+e.width+2,l.style.left=v+"px",l.style.position="absolute",l.style.top=e.top+"px"),p=Math.floor((30-e.height)/2),1<=p&&30>e.height&&(l.style.height=e.height+"px",l.style.width=e.height+"px",l.style.top=e.top+p+"px"),p=Math.round((e.height-30)/2),30<e.height&&(l.style.top=e.top+p+"px"));l.className+="teardrop"}}
function delete_combo_item(a,d){var c=getComboId(a);if(c=document.getElementById(c))for(var b=getItems(c),e=0;e<b.length;e++)if(b[e].innerHTML==d){for(b.splice(e,1);c.hasChildNodes();)c.removeChild(c.firstChild);for(e=0;e<b.length;e++)addItem(c,b[e].innerHTML,e);break}}function close_combo(a,d){d||(d=document);var c=getComboId(a);if(c=d.getElementById(c))"block"==c.style.display&&(setStyle(c,"display","none",""),gItemNum=-1),g_do_complete&&unhighlight_combo_all_items(d,a)}
function repopulate_combo(a,d,c){c||(c=document);var b=getComboId(a);if(b=c.getElementById(b)){for(;b.hasChildNodes();)b.removeChild(b.firstChild);for(var e=0;e<d.length;e++)addItem(b,d[e],e,c)}a=getComboButtonId(a);(c=c.getElementById(a))&&setStyle(c,"display","","")}
function destroy_combo(a,d){d||(d=document);if(!(null==a||0>=a.length))try{var c=getComboId(a),b=d.getElementById(c);if(b){for(;b.hasChildNodes();)b.removeChild(b.firstChild);b.parentNode.removeChild(b)}var e=getComboButtonId(a),h=d.getElementById(e);h&&h.parentNode.removeChild(h)}catch(k){console_log("destroy_combo error: "+k.message)}}function highlight_combo_item(a,d,c,b){return 0}function unhighlight_combo_item(a,d,c){return 0}function unhighlight_combo_all_items(a,d){return 0}
function getComboId(a){return null===a||""===a?null:a+"_combo"}function getComboButtonId(a){return null===a||""===a?null:a+"_button"}function hide_combo_item(a){null!==a&&setStyle(a,"display","none","")}function show_combo_item(a){null!==a&&setStyle(a,"display","","")}function show_all_combo_items(a,d){a||(a=document);if(!(null==d||0>=d.length)){var c=getComboId(d);if(c=a.getElementById(c))for(var c=getItems(c),b=0;b<c.length;b++)show_combo_item(c[b])}}
function combo_filter(a,d,c){a||(a=document);if(!(null===d||0>=d.length)){var b=!0,e=0;null===c&&(c="");var h=of(c,a),k=null,n=getComboId(d);if(n=a.getElementById(n)){for(var m=getItems(n),f=0;f<m.length;f++){var q="undefined"!=typeof g_isfirefox&&g_isfirefox?m[f].textContent:get_innertext(m[f]),q="undefined"==typeof q.trim?q.replace(/^\s*|\s+$/g,""):q.trim();""===("undefined"==typeof c.trim?c.replace(/^\s*|\s+$/g,""):c.trim())||0<=q.toLowerCase().indexOf(h.toLowerCase())?(show_combo_item(m[f]),highlight_combo_item(a,
d,m[f],c),b=!1,e++,k=m[f]):(hide_combo_item(m[f]),unhighlight_combo_item(a,d,m[f]))}if(b)close_combo(d,a);else if(c=n.getAttribute("autofilled"),1===e&&"false"==c){n.setAttribute("autofilled","true");if(b=a.getElementById(d))e=b.value.length,c=k.val.length,b.value=k.val,"selectionStart"in b?(b.selectionStart=e,b.selectionEnd=c):(k=b.createTextRange(),k.moveStart("character",e),k.collapse(),k.moveEnd("character",c),k.select());close_combo(d,a)}}}}
function keyupCombo(a,d,c,b){a||(a=document);d||(d=window.event);if(d&&(b=a.getElementById(b),null!==b&&null!==c)){var e=d.keyCode;if(e!=KEY_DOWN&&e!=KEY_F4&&e!=KEY_UP&&e!=KEY_ENTER&&e!=KEY_ESCAPE){if("undefined"!=typeof TABKEY&&(e==TABKEY||e==SHIFTKEY)&&(e="undefined"!=typeof document&&document.location?document.location.href:"",-1!=e.indexOf("popupfilltab.html")||-1!=e.indexOf("#framesrc=LPMAGIC")))return tabfocuser(d),!1;isComboShowing(b)||(showCombo(c,b,null,a),gItemNum=-1,setTimeout(function(){doFocus()},
0));combo_filter(a,c.id,c.value)}}}function keydownCombo(a,d,c,b){}function isComboShowing(a){return null===a?!1:"block"==a.style.display}function insertAfter(a,d){a.parentNode.insertBefore(d,a.nextSibling)};
