var LPCFG={do_popup_actions:!0,popup_show_sitename_suffix:!0,popup_show_menu_expand_visual_cue:!0,g_do_icon_number_hint:!0,g_creditcard_profile_annotate:!0,g_visual_cue_on_hover:!0,RETRY_TIMEOUT_QUANTUM:30,__FINAL:0},LPIFRAMEVARS={g_genpws:[],g_myprefs:{},g_should_set_prefs:!0,g_sites:null,g_formfills:null,g_favicons:null,g_bigicons:null,g_genpwpattern:"",g_do_40fieldicon:!1,_FINAL:0},LPpop={create_popup_obj:function(a,d){function g(a){var b=0,c;for(c in a)b++;return b}if(do_experimental_popupfill){var e=
"undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"",b=null,c=null,m=null,q=null,q=a.createElement(e+"div");q.style.display="block";q.style.border="0";if(!q)return null;var h=c=null,n=c=null,k,t,f,r=0,m=0;LPCFG.popup_show_menu_expand_visual_cue&&(m=24);t="undefined"!=typeof measureText?measureText:LP_measureText;var v={};"undefined"!=typeof d.favicons&&(v=LPJSON.parse(d.favicons));c=a.createElement(e+"div");if(!c)return null;c.setAttribute("id","popupcontainer");q.appendChild(c);h=a.createElement(e+
"table");if(!h)return null;h.setAttribute("id","lptabpopup");c.appendChild(h);c=a.createElement(e+"div");if(!c)return null;c.setAttribute("id","popupcontainerff");q.appendChild(c);n=a.createElement(e+"table");if(!n)return null;n.setAttribute("id","lptabpopupformfills");n.style.display="none";c.appendChild(n);tbodyff=a.createElement(e+"tbody");tbodyff.setAttribute("id","lptbodyff");n.appendChild(tbodyff);if("undefined"==typeof d.sites)n=0;else for(f in k=LPpop.getAutoFillArray(a,LPJSON.parse(d.sites),
!0),n=g(k),k)if(k.hasOwnProperty(f)&&null!=k[f]&&null!=k[f].useusername){var p=k[f].useusername;0>=p.length&&(p=k[f].name);var u=p,b=a.createElement(e+"tr");if(!b)return null;b.setAttribute("id","trpopuprow"+lp_ofa(f));b.setAttribute("aid",k[f].aid);b.setAttribute("sitename",k[f].name);b.setAttribute("username",k[f].useusername);b.className="popuprow";LPIFRAMEVARS.g_do_40fieldicon&&(b.style.height="39px");h.appendChild(b);c=a.createElement(e+"td");if(!c)return null;c.setAttribute("id","tdpopuprow"+
lp_ofa(f));c.setAttribute("aid",lp_ofa(k[f].aid));b.appendChild(c);"undefined"!=typeof v[k[f].aid]&&(LPIFRAMEVARS.g_do_40fieldicon?(b=LPpop.gen_image_frag(a,LPpop.lookup_bigicon(k[f].aid)),b.width="88px",b.height="22px",b.style.width="88px",b.style.height="22px"):b=LPpop.gen_image_frag(a,LPpop.lookup_favicon(k[f].aid)),b&&c.appendChild(b));if(LPIFRAMEVARS.g_do_40fieldicon){var l=a.createElement(e+"div");l.style.position="absolute";l.style.display="inline-block";l.style.left="104px"}b=a.createElement(e+
"span");if(!b)return null;b.setAttribute("id","spanpopuprow"+lp_ofa(f));b.className="popcell shortenstr";LPIFRAMEVARS.g_do_40fieldicon&&(b.style.fontSize="11px",b.style.fontWeight="bold");"undefined"!=typeof g_isedge&&g_isedge&&b.setAttribute("x-ms-format-detection","none");LP_elt_set_text(b,p);LPIFRAMEVARS.g_do_40fieldicon?(l.appendChild(b),c.appendChild(l)):c.appendChild(b);LPCFG.popup_show_menu_expand_visual_cue&&(b=LPpop.visual_cue_frag(a,"expand",f))&&(LPIFRAMEVARS.g_do_40fieldicon?l.appendChild(b):
c.appendChild(b));LPCFG.popup_show_sitename_suffix&&(b=LPpop.subscript_name_frag(a,k[f].name))&&(LPIFRAMEVARS.g_do_40fieldicon?(b.style.paddingLeft=0,l.appendChild(b)):c.appendChild(b));c=t(a,u,null,"font-size: 14px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;");c.width+20+m>r&&(r=c.width+20+m)}if("undefined"==typeof d.formfills)t=0;else for(h=LPJSON.parse(d.formfills),t=g(h),k=0;1>=k;k++)for(f in h)if(h.hasOwnProperty(f)&&null!=h[f]&&null!=h[f].decprofilename&&null!=h[f].profiletype&&
parseInt(h[f].profiletype)===k){b=a.createElement(e+"tr");if(!b)return null;b.setAttribute("id","trpopupffrow"+lp_ofa(f));b.setAttribute("ffid",h[f].ffid);b.setAttribute("profilename",h[f].decprofilename);b.setAttribute("formtype",k);""!=h[f].ccnum&&0==h[f].profiletype&&b.setAttribute("hascc","1");b.className="popuprow";tbodyff.appendChild(b);c=a.createElement(e+"td");if(!c)return null;c.setAttribute("id","tdpopupffrow"+lp_ofa(f));c.setAttribute("ffid",h[f].ffid);b.appendChild(c);"undefined"!=typeof v[h[f].ffid]&&
(LPIFRAMEVARS.g_do_40fieldicon?(b=LPpop.gen_image_frag(a,LPpop.lookup_bigicon(h[f].ffid)),b.width="88px",b.height="22px",b.style.width="88px",b.style.height="22px",b.style.backgroundColor="#666666"):b=LPpop.gen_image_frag(a,LPpop.lookup_favicon(h[f].ffid)),b&&c.appendChild(b));LPIFRAMEVARS.g_do_40fieldicon&&(l=a.createElement(e+"div"),l.style.position="absolute",l.style.display="inline-block",l.style.left="104px");u=h[f].decprofilename;b=a.createElement(e+"span");b.className="popcell shortenstr";
b.setAttribute("id","spanpopupffrow"+lp_ofa(f));LPIFRAMEVARS.g_do_40fieldicon&&(b.style.fontSize="11px",b.style.fontWeight="bold");LP_elt_set_text(b,lp_of(h[f].decprofilename,a));LPIFRAMEVARS.g_do_40fieldicon?(l.appendChild(b),c.appendChild(l)):c.appendChild(b);LPCFG.g_creditcard_profile_annotate&&1==k&&(p=a.createElement(e+"span"),p.className="cc",LP_elt_set_text(p,"("+lpgs("Credit Card")+")"),b.appendChild(p),u+=lpgs("Credit Card"));LPCFG.popup_show_menu_expand_visual_cue&&(b=LPpop.visual_cue_frag(a,
"expandff",f))&&(LPIFRAMEVARS.g_do_40fieldicon?l.appendChild(b):c.appendChild(b));c=measureText(a,u,null,"font-size: 14px;font-family: Helvetica,Arial,sans-serif;font-weight:bold;");c.width+20+m>r&&(r=c.width+20+m)}if(LPCFG.do_popup_actions){if(0<t){b=a.createElement(e+"tr");if(!b)return null;b.className="tablerow_sep";tbodyff.appendChild(b);c=a.createElement(e+"td");if(!c)return null;b.appendChild(c);m=a.createElement(e+"hr");if(!m)return null;c.appendChild(m)}}else if(0>=n&&0>=t)return null;300<
r&&(r=300);g_popupfill_widest=r;return q}},visual_cue_frag:function(a,d,g){var e=null,b="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"";if(!d||!a)return null;if(LPCFG.popup_show_menu_expand_visual_cue){e=a.createElement(b+"span");if(!e)return null;e.setAttribute("id",d+lp_ofa(g));e.setAttribute("expander","true");e.className="expander";LPCFG.g_visual_cue_on_hover&&(e.style.display="none");LPIFRAMEVARS.g_do_40fieldicon&&(e.style.paddingRight="16px");if(a=LPpop.gen_image_frag(a,"arrow.png"))a.setAttribute("id",
d+"img"+lp_ofa(g)),a.setAttribute("alt","+"),e.appendChild(a)}return e},subscript_name_frag:function(a,d){var g=null;if(!a)return null;var e="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"";d&&0<d.length&&(g=a.createElement(e+"p"),g.className="subtext",LP_elt_set_text(g,d),LPIFRAMEVARS.g_do_40fieldicon&&(g.className+=" shortenstr"));return g},gen_image_frag:function(a,d){if(!a)return null;var g="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"";if(g_isfirefox){g=a.createElement("image");
if(!g)return null;g.setAttribute("src",d);g.style.padding="2px"}else{g=a.createElement(g+"img");if(!g)return null;g.setAttribute("src",d);g.style.padding="2px";g.setAttribute("alt","")}return g},set_icon_hint_from_data:function(a,d){function g(b){var a=0,c;for(c in b)a++;return a}if(LPCFG.g_do_icon_number_hint){var e,b;"undefined"==typeof d.sites?e=0:(e=LPpop.getAutoFillArray(a,LPJSON.parse(d.sites),!0),e=g(e));"undefined"==typeof d.formfills?b=0:(b=LPJSON.parse(d.formfills),b=g(b));g_icon_numbers.sites=
e;g_icon_numbers.formfills=b;g_icon_numbers.generate=b}},getAutoFillArray:function(a,d,g){var e=[];a=punycode.URLToASCII(a.location.href);lpcanonizeUrl(a);for(var b in d)if(!d[b].genpw||g)e[b]=d[b];return e},lookup_username:function(a){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_sites&&null!==a)for(d in LPIFRAMEVARS.g_sites)if(LPIFRAMEVARS.g_sites[d]&&LPIFRAMEVARS.g_sites[d].aid==a){a=LPIFRAMEVARS.g_sites[d];if(a.useusername)return a.useusername;if(a.unencryptedUsername)return a.unencryptedUsername;break}return""},
lookup_sitename:function(a){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_sites&&null!==a)for(d in LPIFRAMEVARS.g_sites)if(LPIFRAMEVARS.g_sites[d]&&LPIFRAMEVARS.g_sites[d].aid==a){a=LPIFRAMEVARS.g_sites[d];if(a.sitename)return a.sitename;if(a.name)return a.name;break}return""},lookup_profile:function(a){var d;if(LPIFRAMEVARS&&LPIFRAMEVARS.g_formfills&&null!==a)for(d in LPIFRAMEVARS.g_formfills)if(LPIFRAMEVARS.g_formfills[d]&&LPIFRAMEVARS.g_formfills[d].ffid==a){a=LPIFRAMEVARS.g_formfills[d];if(a.decprofilename)return a.decprofilename;
if(a.decprofilename)return a.profilename;break}return""},lookup_favicon:function(a){if(LPIFRAMEVARS&&LPIFRAMEVARS.g_favicons&&null!==a)return(a=LPIFRAMEVARS.g_favicons[a])?a:null},lookup_bigicon:function(a){if(LPIFRAMEVARS&&LPIFRAMEVARS.g_bigicons&&null!==a)return(a=LPIFRAMEVARS.g_bigicons[a])?a:null},__FINAL__:0};
