var g_content_check=!0,g_bodystyle_relative=!0,g_trial_bg_expt=!0,g_ignore_lp_cache=!1,g_stylesheet_grubbing=!0,g_use_wacky_disp=!0,g_input_click_intercept=!0,g_force_fill_active_element=!1,g_create_iframe_in_top=!0,g_inframe=null,g_toplevel_iframe_exists=!1,g_iframe_docked=!0,g_combat_obfuscation=!0,g_queeg_mode=!0,g_show_safari_csp_msg=!0,g_in_lpframe=!1,LP_GETNAME_FAVOR_ID_OVER_NAME=!0,LP_GETNAME_FAVOR_NAME_OVER_ID=!1,g_popupfill_rows=0,g_popupfill_rows_FF=0,g_weasel_id=null,g_weaseled=!1,g_autofillsites=
{},g_popupfill_widest=260,g_popupfill_max=1,g_popupfill_ctr=0,g_popupfill_parent=null,g_popupfill_parent_last=null,g_isadmin=!1,CLICKABLE_ICON_ZINDEX=2147483648,popup_show_sitename_suffix=!0,popup_show_menu_expand_visual_cue=!0,g_last_field_focused=null,g_minwidth_override=0,g_minheight_override=0,g_popupfill_iframe_width_save=0,g_popupfill_iframe_height_save=0,LPICON_HEIGHT=16,LPICON_WIDTH=16,g_double_password_hack=!1,g_double_secret_password_hack=!1,g_double_password_wtf=!1,g_popup_divs={},g_input_cnt=
-1,g_form_cnt=-1,g_input_fingerprint=null,g_keyboardNav=!1,g_more_close_on_cancel=!1,g_more_enable_return=!0,create_onerow_iframe=!0,do_autofill_if_matched=!1,g_frame_css_str="",g_is_specialsite=null,g_nevers={},FORCE_OFFER_GENERATE=!0,NO_FORCE_GENERATE=!1,FORCE_SHOW_NOHITS=!0,NO_FORCE_NOHITS=!1,FORCE_SHOW_NOHITS_NOLOGIN=2,g_icon_shading=!1,g_do_icon_number_hint=!0,g_icon_hover=!0,g_icon_parent_hover=!0,g_icon_number_overrides={sites:-1,formfills:-1},g_icon_numbers={sites:0,formfills:0},g_visual_cue_on_hover=
!0,g_show_icon_only_on_focus=!1,g_show_save_success_msg=!0,g_save_suggest_msg=!1,g_creditcard_profile_annotate=!0,g_show_icon_number_for_formfills=!1,g_save_suggest_msg_seen=!1,g_change_icon_on_input=!0,g_dologin_clickable=!0,FADE_MAXSTATES=100,g_aspx_hack=!0,g_found_aspx=!1,g_clickable_input=!0,g_clickable_input_on_password=!0,g_popup_active_username=null,g_popup_active_password=null,g_extended_kbd_nav=!1,g_iframe_scroll_hack=!0,g_frame_scrollable_set=!1,g_defensive=!0,dotrans=!0,g_markov=!1,g_pw_ico=
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABMUlEQVQ4T32SgVHDMAxF6QZ0AswELRuECcoGhAloJwAmACZomAA6QbMBZYKaDRih/+UkTvHF1d0/x/L317eU2cX5WNrxoUabTRwk5Z6EtjjrtH8RcsyXAlx6FS6FneCVcbIS/oSNgNgQUQDSt/Bj1UvbnHNxIdy4eBTolYQEsOkXKIQzBL0I3NvoIGlzFN6Ftbl71gqRaAT2xJvwKFwL2R1A2Jsql6hEL7JdSlp5Oy7uhE/nukCrxDYIUI1JxGAC5L3Yg7670sGQNGJNwMXpQR+byIjoAx3mCViN8aVNFpjUXGDUozG6srvgPJkYlwnc3Qv+nJEAhNZIfDcCzfoVeA4FcPZhvEFx6ld2IZpaxn9lP6gJUAnbV+aA6uzp0yhqApBoUmdrM+Hm7BMiP2mTawInofVEEf5J2pUAAAAASUVORK5CYII=",
pw_svg=g_pw_ico,g_ff_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAvElEQVQ4T2NkoBAwIukXALL9gViBgJkPgPIbgfgDSB2yAQVAfj+RDioEqpuAbkADUKAeiB0JGLIfKN8IxCD1KC6AGYDsqgtANf+B2BDJUBCfaAM2QDUGkGMAcpjA/Qx1EVEugHkJZDlcA7EGgKJSHi0wHwL5D4g1wAGoEISRwQEgB4SJCkSQZns0Aw6SYgDICyCMDEDOJ8oL6E5HMwfsDayxQHFSBmUmUIJBdzq6C0DeWAATRE626AqJ4gMAKh82EQu8MAEAAAAASUVORK5CYII=",ff_svg=g_ff_ico,g_sites_dark_ico0="iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAANJJREFUOBHdUzsOgzAMfaDOiIETcBjUDozcjetwh3CBdsnAgLiAa1uyG+gAtJ1qyYljv+dPAgBwY72z0kEV7JXV5QzZighHJeNVnJ+IcJGfYVZVhbZt3yjW1u7edR2FEAynibyDsiw9c1EUyHMPIY1lmXbuWEX1fY9pmtA0Deq6RowRwzAoKI05KzFeZRLnWVNn4jZtNuIRiEfws8XkDsZxNL/WuVi1eZ7NxLIsbothMSKC6FYs4+7Oz0j8jIbTPD/5kB7blg6cV5yvf6YDBf8a8gSLtXzq+l6rIQAAAABJRU5ErkJggg==",
g_sites_ico="data:image/png;base64,"+g_sites_dark_ico0,sites_svg=g_sites_ico,g_close_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAl0lEQVQ4T7VTgQ2AIAyTC/RD9QO9QLxAP1A/1A9sDZgFo0CQJctcWOs6hioSTRl8hVjDGUNsR9EG3y1Bh2QKQYqaHt+zJdBIhkiCEfU6G8HB9kRX/BtllqLLzw6uQ3hjAKvJpUyvhBYgAmkkWpwZ5SVIlsBF4RA5BxojhygXzSvBkfxI/yVIXmVq41XFPCZe8f2YfHpfz0+q7C4R/Q4GAgAAAABJRU5ErkJggg==",close_svg=g_close_ico;
function getnumbericon(a,b,d,e){var c=0;(b=getIconState(b.ownerDocument,LP_pickFieldName(a,b)))&&"undefined"!=typeof b.fillhintnumber&&"sites"==b.fillhint&&(c=b.fillhintnumber,isNaN(parseFloat(c))||!isFinite(c)?c=0:10<=c&&(c=9));"undefined"!=typeof e&&(c=0<=e&&9>=e?e:0);e=[g_sites_light_ico,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAUBJREFUOBGVVE2ORUAQLvIS4gwzEysHkHgnkMiEc4zEJXCMNwtWTmDh3UGcYoaFhZUFCzFVnu4wIaiE+vvq6+6qTgthGH6O4/jA7x1OiCAIPwj7CoLgSXDxSjEVzAt9k01CBKdWfsFf/2WNuEwc2YqigKZpK9glAlVVwTTNbQJZlnlCkiTAZnF/mePB2biRdhwHdF2HJEmgaRrwPA+qqoI4jle5/8XkXzrCFoHg+/5ICdpm13UTho7Q9/0WnsfwiL/ouHwHrJgQR8WEwVG+oXpMPaDAkdzvd7AsC8qyhCiKJjiRnCKwbRsMw9hcQ5zv9maSBeu6hjRNYRgGFuKaCNwjkjzPoSiK1d1gDDecQobOBwswzabD/D3Np7AHOIrvNpHmPI+Kc2RZBm3bcp8wuwSIot7QQ0PznoR6wYSK0Xb/AGVLcWwc7Ng3AAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAXtJREFUOBGVUj2LwkAUnIjBICIIKe8gWKRKo2BvYXMgWNlYWZ3gn1B/htekibWVcH1aIVV+wQULCxsRtMrtrGYv8RLUB8nuvjczu+9DWywWH3EcL8X3jidM07QfAfucz+ffhJdeIZNwu+iLexoFnrr5Cr/+05xSOvBoX61WYdt2BvaSgGVZ6PV6+QKGYahApVKBKJY6p2PKeduUufb7fbTbbaxWKxwOB0ynU+x2O7ium4ndk3l+KYU8AW02m8UM8Jnn81limMLlcsnDK59IMRKHiXpBQibiEZkY0co3sSxlDegoMsdx0O12Ua/XEUUR1us1jsejhFNEvaBIgK07nU4IwxDNZhOdTicDLXO205OViYrDZrORLg5Qq9VSdUpwJSEwoUjiuF+FOEzTxGAwwH6/x3a7zUD+piXjBpLukDwej2XenufJdNLQhzUYjUao1WpoNBpywIbDYZqPwi6wz6xyEATQdV2ROKmJEVMoIECszdL3ffb7n5EsnJNf8S6HAZZBgLIAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAYdJREFUOBGVVLuKwkAUPTErioVgY5WF2AhpFKz8AC0W0vgTK9injvkMt7HyB6zWSuy1s1WRXUJQ0cJCxSLOnSSzcYmaDGTmPs45M3fuEMmyrA/XdXvse0eMIUnSD4N9drvdb4KnkpCJ4G/0RTYNEoi1swf35jAnFU68snO5HMrl8h0skYCqqmg0GtEC2WxWJDKZDNhlCT+cE0HfeKNV13XUajUMBgPs93t0Oh3Yto1+v3+X+08mP1EJUQKSaZouJeiY5/OZY6iEy+UShRcxVuIvc9riBAGZEK/IhGGtVNjS43dAgWej2WyiUqlAlmWs12sMh0OcTicuIk7wTOBwOGA+n2O5XELTNJRKJQFP+W9bBKKM6XSK4/GIfD4Px3G4UIAjgXYckXq9DkVRsN1ukU6nAz7+XosIeUbQHfKIcL1eUa1W0Wq1MB6PMZlMODDWJRqGgd1uh0KhwEmbzYavND0UoD77rcJoNEKxWOS1LxYLrFYrLkCYhwIMQXdDPxplNptxQngiMmFuABiQmENn7wkAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAV9JREFUOBGVVLuKg0AUvcpCQiB/sAuCYBNMYWtrs0Gwyi+s4E8k4kdItrHKL8h+h612uwRsBDtTiDtnYmbHxTy8kMx9nHP0zr2ohGH43nXdgf3e6AlTFOWbwT72+/0X4OoUMgj9gz7hwyDw1JMv8Mu/zFHlwiN/sViQYRgD2CQBTdPIcZxxgfl8Lgqz2YzYZYlYrolk77zgdF2XLMui4/FIVVVREAR0Op0oSZJB7T8Z8aQWxgSU3W7XoYDXbJqGY9DC+Xwew4sca/GHBb54gysZiEdkYNgoX9lxEAJI3rPtdkts+0jXdQGDyFMCpmnSarUSRNlR+92WcwN/uVzSZrPhUxkU+gAC/j0Rz/OormvK85xTsI2y/W2LnGX+dTroW7a2bSmKIpHiiySiESeOY55dr9dk2zalaTpA3RTAnHHLZVlyQpZlvJWiKIQAMDcFGAp3gw8N5k0QuoohBpkd/i9CoHzgkM8LEwAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAXFJREFUOBGVVDGKwkAUfZHFaBBS2riQSrC18QJpAvbeYAVbD6DxFm4TELyA1R7BKmUgjRa7pAwELKKF2XljEuMSN/HDZOb//96b+X+GKLZtW0mSrMV4Rw1TFOVbwD6Wy+UX4Y1XyCSkG31yTaNArZ1v8Nu3yGkUE1VrTdPQ7/cfYC8JGIYB0zTLBVqtVp5QVRWiWblfzOXBdPHGeTweYzgcYrvdIgxDzGYzBEEAx3Eecn/J9F8qoUxAWSwWCRM8ZhzHEsMSzudzGT6PiRJ/hDPNT5CRiagiEyOusiemtewBA//ZZDLBYDDIIavVCtfrVYrUEmi324iiCPv9XoqQnFkjfduZXzpToNlsykdUJBNMgWmViO/78DwPuq7DsizwQWV2fy1ZJJ2z26Hb6XRwOp0wGo2kwG63g+u6ElmrB/P5XApQ6HK54HA4pNsATwV4z+lVYbPZoNvtys6zHDaURsxTAZFnb/ij6R2PR3AUjWRifgHmko6KAvVfRAAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAYJJREFUOBGVVLuKwkAUPRFRY2GlhRKDVRpBMFgJgRQ2C37HCvmCdOpnuE0qWzvZBf8hTbC2SLAKqQQfTXbumAy6xE0cmMx9nHNm5t4h0nK5/IjjeMVmFwWGJEk+g30uFosfgpfeIRMh2eiLbBokUGjnO/z+feSUHhN5dr1eh6ZpT7C3BHq9HiaTSbZArVYTiWq1ClYs4T/mRDAxyrROp1Pouo71eo0oimBZFo7HIxzHecr9JZP/1hWyBKT5fB5Tgo55uVw4hq5wvV6z8CLGrhgwZyZOkJIJkUcmDGulwpYVrwEF8oZhGOj3+2g2m7xWh8OBi4gT/CcwHo9hmiZ838d2u+WFTvGl5G2nfuY6Go04WZZlqKqK2+0mcCQwyxNpNBpQFAWVSgXD4RCDwUAIlFkXvpmnikhipN0h93w+43Q6YbPZwLZtdDodAS9UA8/z0G63+QMjJhUwHS+7QH1OWoXdbocwDNFqtRAEAfb7PecT5qUAQ1Bt6EejsAnXddNNBZkwv/3KjSrHve9/AAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAWVJREFUOBGVVL2Kg0AQHuXAxDKdcAeprI1NXiCN4HOc4EvEvISQa6xSW+bAJwg26hMEEkQstDU23s7qrnp4FzOw7vx88+3uzKBwOByMpmmOZH3ADBEE4UZgn47jfCNcfCUZE7qDvlBHQYJZJ7fw9jvMEYeBZ7osy6Cq6gj2EsF6vYbdbjdNsFgseECSJCDF4vYwxp2d8oa7aZqg6zqcTicoigJs24Y0TcHzvFHsdzLaLz1hikDY7/cNBvCaVVVRDD7h8XhM4bmPPPFODIvfgCUj4lkyYkgr38l2pDVAx39Cpm4UjuMYfN+nJLMIzuczJVAUBTRNowVmjGI328ye3C+XC+DCOtV1DVEUcRwSWHNIVqsVncIkSUY16qeFc7YK6w5zG4YB2+0WXNeFPM+Ze94c4NU3mw1cr9dRMrL8WUTsc9cqWC6XEAQB3G74K+gFMXwOejfXsDZ3tMqyhDAMIcsyHuxi1g985oWXD2O18QAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAZdJREFUOBGVVD2LwkAQfTEHfhTXqIXggY0KNoKtEBBsDv0Zh0JI5w9Qf4bXWPkHBPHqWKq1CFaeWImIwS8w5Hai2UskxLiw2Zk3b97uziwR2u32p2EYHTY/4GMIgvDLaLVWq/VD9MAryZRw3+ibbBok4GvnG/32tecE7IFndiQSQSaTcdBeEkilUiiXy+4CoVCIB4LBIFixuG+PcfBuvNFarVZRKBTQ6/Ww3W4hyzLW6zW63a4j9phM/ktXcBMQms2mQQE65vl8Njl0hcvl4sbnGLviijl1fgIrmRjPkonDWplkS8esAQFeI51OQ5IkxGIxLJdLDAYD7Pd7U4SfwEugWCwiGo1iNBohm80il8txeuD+tjngZsxmM4TDYeTzeRyPRywWC04jgfozkd1uB13XEY/HzTafTicu8P9aOHQzrO6Q12g0sNls0O/3oSgKJpMJhsOhSfRVg8PhgEQigUqlAlEUQb41RMt4XEul0hfD3gmfz+e4Xq/mnE6nGI/H1AF67iuvNlJt6EeT1DQNqqo69qBkBtT/ANzCmpZx1xTXAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAZ9JREFUOBGVU7uKwkAUPXmID5AttNyFYBGwsLGwFBUFF/wOhfyE5jPcxkZt/IHFxg+wsZJtrFwS8NWIohZm545xNkp8XcjMnbnnnJk790YyTfPTcZwm+z7whEmSNGWwaqPR+Ca4/AqZCO5BX+STkcBTJ5/gp9HLkb2BR34kEoGu6xewlwQ0TUOxWPQXCIVCIhAMBsEeS6y9MbHpOirNlUoF6XQanU4Hq9UKhmHAsiy0Wq2L2DWZ1i+l4Ccg1et1hwJ0zd1uxzGUwn6/98OLPZbiL1vUxA3OZEI8IhOGlfKdTU3+BrThZ5lMBoVCAev1Gr1eD7PZDIFAALIs80NIRNzAT4DIw+EQm80G2WyWQ1KpFHK5nICr1NvezhIR5iyXSyQSCUSjUSiKgnK5jGQyCVVVEYvF0O12oeTz+R+GJfk3L5n8yWTC+yEej3OxwWCA4/GI7XaLfr/P0/jvlis2VadUKvH+IFK73YZt2yCxcDiM6ZR+SuDuI45GI4zHY8zncxwOB05YLBZ8Pg83BajOjEilummEuVeFmtssvgJurPYHGEKbZ/T0eqIAAAAASUVORK5CYII="];
b=[g_sites_ico,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAQZJREFUOBGlUzsOgzAMfaDOiIGx6sBhUFuJkTOwIK4DN+nMwA04QduBgRsglNqWkqZACxRLDo4/L89xAIAL6Z1UrVTOPZMa2VKsD+EaEYdWdv4jXAt3S2UQBIjjeFKiaS1+kyRRTdPoPAEyDHzfN8ie58F1TQh2zHGEucmVrLIs0XUdoihCGIZo2xZVVUmSHTNVlvE+xnJuNaUnoql7U9SCIqpmT4Bz9oP81z1jZKJPXubQJ74sy1Tf96qu63FsGaAoCqVlDMCXyL38FJo90jQFMZjNW/0zDcMwaeFAkDfS0ww097oou98BM/gmPKKjHczzXF6p5ZMxWvsP80o7vuDx2PReHtILYnasIXV5JlsAAAAASUVORK5CYII=","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAVVJREFUOBGlUztug0AQHUwaCiMXiAKlcmXJh7BEYSWWcOeCM1BzFzpqizNQcAEqCgponBSIT0FBPZndiM3ijxySkQbm897MLDsAALyTXkjxl8qwb6RC5pDHJozDRaEnC/5FGBcWc5iGYYDjODeUcayn79PphFmWjTheSEywWq1EZV3XYbEQKZBzisInF1iOCoIA2raF/X4P6/UaqqqCJEk4SM4JlmT8tJGCc01+JhpzPBvSEZBGFT4VvGd/UPzwn2tkg36yx73qIua6LuZ5jsMwYBzHaFmWyDHu02+w2+2gaRo4n89g2zZ4nseaTuRC3qSq7KuqinSleDwekYnv+9fY5z/TdrvFruv4Ei2Xy5sCk3EkhwM3mw3SXmCapmia5jWZ+Q+Fg4ui4KP3fY91XWMURZMiLw/p31f0GoYhaJomYGVZCpsMfo1yQLYP5LBlmXSUfL5IXwuez/wpTD7ZAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAWRJREFUOBGlU7GOgkAQHbnrSAxGK3IVUPId5M7EDlpKvoCaXM8P8AWUfoCJhYWdjQkaa++MGLWmIZmb3YQ54Lg7vZtkd9/OvHn7NgsAAC809jTwxiG4zzQ47mmuDhE9Mno0i+RfQvSCck/naDSCyWTypaWy9evqeR5mWVbxpBA70DSNlfv9PigKl6Be6/Wkc+ZKVpIkcLlcwHEcMAwD8jyHxWIhSfUad9XA5zG15L1Q3olsVndDugKSVd6TYBd+o/z4P88ojL6LqUu9kYvjGI/HI16vV5xOpzgcDrn+QAKvQuWnsCwLSADO5zO4rgur1Qq22y237Amx4nc4DENcLpe4Xq9xMBjU+bf9TIfDAcuyxDRNUdf1hgBbaQEmqaoqse/7KCKKIq49tpo6t6fTCXa7HZimKeubzYZ5ze+S0xKId34SKAgCsG0biqKA2WwG8/lcEmiSz1ht2uuYEkKE7bawqI0/AJ5yzXcdXYlXAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAATFJREFUOBGlU71thUAMNki0iAIqJAoGgC1Q8iRKGhagYRImoGECagZgADomICkoEBMgXWy/x+V4QF5ILPnw+ee7z74DAOAddUAVv1TKfUOVcqV4PYRqWDRcyfkXoVrQr1Tatg1xHO9KVlovv0mSiL7v1zwGkgwsy5LIpmmCrssQqDFNY+Yyl7PKsoRpmiCKIvB9H8ZxhLZtOUmNySrF+D5GcV41uSekufYmsAWBVOUeAY/sD/Tf/nONRPSTliP0na+ua0GCc3qOvQZI05SLzwCGn1i4rivmeRZd1zHIMwO6hQyVBnIoVVXBMAzQNA3HHcfZ5G1fxSZ0/0fw2I13WRYwDGPjO9vwsIIgEKRFUXALWZbthngGQG3J5DAMRZ7nwvM86cP4aesEenskqAWqzQ/pC316ypnGH23GAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAVBJREFUOBGlUjFug1AMdVJGRBFiQWKBC3CDDhlQi8TIwszMVbJyCyRukDswdExaFGXIyBj4tV1hCERN01ry52G/52///wEA3tA/0NUvnbiv6GKPiIdNSMO2wpWCfzHSwvoRpW3bEMfxQjK0dfebJImq63rgcSHpwDRNqWwYBqzXkoJpbrXizoXLrKIo4Hw+QxiG4Ps+nE4n2O12TJrmRDUB4zaT4KOQZ8I2h9kUjqCwVfnHgrfwJ8aj/1wjNdrQcqv6VawsSzU1TdMkr1GFe2ZZFjRNA9vtlqld14mEDpFm+dGogK7r/IgulwtgN8J/QvSO/oL+LNEZcF0XDocDBEEAaZryFe/3+xlr+StzOo7DOM9zPoosyyS3lI0RIfV9r47Ho6Jv27bK8zzJXb/LUUyIzsYlsNlsuH2av6oqHofiaHyN33C5RhiiIrLbDFMu+gKOqr2ygs1s2AAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAVVJREFUOBGlUzFug1AMNRwAZcjYMrDmGEhRG4mRA5ALMESZOEPmZM6YmQswZYSBkSktCgNiRJEyuLYlXJpQ0aSW/L+//Z6/jT8AAO+kJ1L8ozL2jVTlEXJ3CXNEDFrZ+YwwF8xHmNPpFDzPu6N0ZY3uvu9jnucdThJpBZPJRDNblgWmqSHoxwxDKlesoHa7HdR1DfP5HBzHgaqqIEkSAfVjyuoZ39f0nI+a0hOV2fWG1AJSqXqmhEP2B/kX/xkjF/rJy1D2O18URZhlGV4uF3Rdtx8fT7Ber/F6veJ2u8Xlcom2bWsCbuFE+sql/CZFUUBZljKdtm1htVpB0zQKH/2ZuGzWOI6RJQxDrUCzDBgKOp/PmKYp8qRY9vu9xgZ46lLQZrMRIrUhexAEGvv5LpUrBs/5hS1+1vTxYDabwfF4hMPhIABaZIzd4XZfkIOT6G03tjykL2vv49Mx20TiAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAASNJREFUOBGlUzFuhEAMNCg1UPACoKWAR6AEiZKWB1DxFxpqXsAXeAAdL7hLQUFJixx7JZzlArkjseTFa8/MejEAAHyQ38jxRWfsO7nYFfJ2CHOUGbRy8i/GXDCvMF3XhSzLflC2tp4+8zzHcRw3nBKSDhzHEWXLssA0pQR6zTBU54JVqKZpYJ5nSJIEPM+DaZqg73sF0mvC0oLvY7Tk1VDdidrc7oZ0BaRWZU+CR/Gd8ul/xsiNfvJypL7L4YO1bSv1N1Z4ZlVVKUgcx1AUBQzDsKPcaCeKv8Vd1+GyLGjbto5/7WcKggDXdUUaq07m+NR2wLqu1ZsIw3CXP2VTQYA8Ym6dPi7JafVTDZ6zIvi+j2VZYhRFjwKMObWUKiJC8RE5/QKVk87a+e76sgAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAWJJREFUOBGlUjtuwkAQfbZEiyhwY7lyB6UPgRKQS5+AIh2i4CYUUHMFDmBcuUWIksIiEULI9gEAMZnZyBuTgAzJSLM7O5+3b3YHAF5Zt6z0oEruC6uWZ4qLS6RGicGrOP8iUgvzmcpmswnf93+VFLQq9yAIaL1eF3kKSDNoNBoauV6vwzR1COWYYSjmOldlTadTpGmKTqcD13Wx3+8RRZFKKsd0Vcn4vqbkfNZUPTHNojfiFoip6jMD3rLf2d/9zzcK0Q9ZbqFf+Xq9HsVxTHme03w+J8dxyvFqgMViQfzINBqNSGQ4HF4BbKtYDAYDulwutFqtFFCr1dIA8gtvrPIgdyVJEpxOJ7TbbWw2G2RZdje3HNC37HY7CsOQeEboeDzSeDzWsYfm4HA4wPM8TCYT1Go1yLmQ67ksvF+7tOWIads2+v0+LMvCcrnEbDbD+XyWkPpGMW5Jl50Coun+sNUgfQJBOtg7An3ZOAAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAXJJREFUOBGlUS1vwmAQfmCGNIQhUE1mUE2owyEmyUZAIPgHWGRdNQKB5i/0L6CoBQthwcEmSCChECTJ7d5b+u5dSrexXfK8vd49z33kAOCZsWHQL6G4Twxtt4jjJkojluFXBf9iSovsLcpSqYRWq5WQxGP9+O10OjSfz2OeFNITFItFXblQKCCb1SmYuUxGJtdcYY1GI+z3e9TrdZTLZWy3W4RhKCQzp1WG89nGCN7qyk48Zrwb8QrEo+p/LnjNf+V44z9nVIO+qedadYn1ej06Ho+0XC7JdV2JWZYlExq69AJRFFG/36fJZEJBEEiBbrdLw+FQN1UrbBgPjITNZjOJ2baN9XoN9d9ut5HL5TCdTtFsNnHHjBfGI+Ne2MYzHo+h7u44DlarFXzfx+VykZN7nofT6WSwky4NBgM6HA602+2oWq3K2FyMarXalxWS0o8IVSoV5PN5LBYLnM/nNF5qXN1Zd0rxFSfVGpz5rojKNd4BkoTNHvr9McEAAAAASUVORK5CYII="];
LP_has_highdef_display(a.defaultView)&&(e=[g_40_icons["16x18_lite@2x"],g_40_icons["16x18_1_lite@2x"],g_40_icons["16x18_2_lite@2x"],g_40_icons["16x18_3_lite@2x"],g_40_icons["16x18_4_lite@2x"],g_40_icons["16x18_5_lite@2x"],g_40_icons["16x18_6_lite@2x"],g_40_icons["16x18_7_lite@2x"],g_40_icons["16x18_8_lite@2x"],g_40_icons["16x18_9_lite@2x"]],b=[g_40_icons["16x18_dark@2x"],g_40_icons["16x18_1_dark@2x"],g_40_icons["16x18_2_dark@2x"],g_40_icons["16x18_3_dark@2x"],g_40_icons["16x18_4_dark@2x"],g_40_icons["16x18_5_dark@2x"],
g_40_icons["16x18_6_dark@2x"],g_40_icons["16x18_7_dark@2x"],g_40_icons["16x18_8_dark@2x"],g_40_icons["16x18_9_dark@2x"]]);return d?b[c]:e[c]}
var g_sites_light_ico0="iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC",g_sites_light_ico="data:image/png;base64,"+g_sites_light_ico0,
g_pw_light_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACIUlEQVQ4EX2TOYhTURSG87IMihDsjGghBhFBmHFDHLWwSqcikk4RRKJgk0KL7C8bMpWpZtIqNkEUl1ZCgs0wOo0SxiLMDApWlgOPrH7/5b2QkYwX7jvn/uc//zl3edZ4PPbNGvF4fC4ajR5VrNvt/mo0Gr1ZPOtfgWw2e9Lv9+chX7cs64CS4Oxg3o9GI7tUKv0Q5o1dAiTfCgQCLwnOkfQOu+oSLyJ2A783HA7vIPLGxX0TgVwud4HKn0nc7Pf7N6vV6oZHkkX8FPG3uMfgXC0Wi2vCg/poUKGGcagQI3k7k8mcp5slcGswGDwpl8tfwGJg3xB6Dvey8vz6oH4C3iXcFYjbwiDeo1KafafkC3NjK7iL5ESFGQEUF7Sg+ifZdDp9GnMF/KGmfBdT2HCwZ7TwtrBPC7rQaav6Iv48rqZwg+F+p8hOMBj0IbxfMdMBrW5pAVGV/ztINByENkU0t5BIJEKRSOQ3Aj+Z57iFs1R5NK3EQS6HQqF1zmQdzpFWq3W42WwOTAf1er1PF2USFlC+qxMvFAr3HcexWX+QX6lUvsKpkTyPSEXJkw6MQ4S38Ljdbi8rmM/nY+CvgNcQqdH6U/xrYK9t244jZv6ByUOSiDdIfgBZ12U6dHEHu9TpdIr8F0OP692CtzaW/a6y3y0Wx5kbFHvGuXzkgf0xhKnPzA4UTyaTB8Ph8AvcHi3fnsrZ7Wore02YViqVOrRXXPhfqP8j6MYlawoAAAAASUVORK5CYII=",
g_ff_light_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==",g_close_light_ico=
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA3UlEQVQ4EaVTOQ7CMBCMETShzcdo4CVOkyJykQb/AXoaPsQT0uLGRZhZxVIirSMDljberOfwaaZpqv5pe5Kttce6rs8QO5SIGWNiCOHhvX+LAMko3hAlfMGAw/6+47fUmdjUEkcEUvGXPicwwqFFxDlaiI+agSoA0tU550G4MJizpgnIJioDQ9/3LxCfHEN+QjcouEqdgQbM1XICHd3pzJhn0mki6hJwH1oQiZdpI+9YKxYAsAFhuWnLfKWTW8IKtPUjAnCLWyBtLHFkD/gweLdx1l89JgobkDSD4toHHT5aJu9+N80AAAAASUVORK5CYII=",g_svgs={},NAV_BAR_HEIGHT_CSS=42,NO_CREATE=!1,OK_CREATE=!0;
function check_nevers(a,b,d){if(a){b={show_for_formfill:!0,show_for_save:!0,show_for_autofill:!0,show_for_generate:!0,show_for_clickable_icon:!0};if(null==g_nevers)return null;if(null==d||0>=d.length)d=a.location.href;a=lpcanonizeUrl(d);d=lpcanonizeUrl(lp_gettld_url(d));for(var e=0;e<LP_objectSize(g_nevers);e++){var c=g_nevers[e];0==c.domain&&lpcanonizeUrl(c.url)!=a||1==c.domain&&d!=lpcanonizeUrl(lp_gettld_url(c.url))||("neverformfills"==c.type?b.show_for_formfill=!1:"neveraccounts"==c.type?b.show_for_save=
!1:"neverautofills"!=c.type&&"neverautologins"!=c.type&&("nevergenerates"==c.type?b.show_for_generate=!1:"nevershowicons"==c.type&&(b.show_for_clickable_icon=!1)))}return b}}
function checkIsDisplayed(a,b,d,e,c,f){if(!f||b==a.body||null==b||50<d)return!0;if(null==e)try{e=gettldcached(a.location.href)}catch(k){return!1}d="undefined"!=typeof window&&window?window:a.defaultView;for(c=b;c&&c!=a.body;)try{var h=LP_getComputedStyle(d,c);if(null==h||"none"==h.display||"hidden"==h.visibility||!(null==c.offsetHeight||""===c.offsetHeight||1<c.offsetHeight||"hidden"!=h.overflow)||"expedia.com"==e&&"-1px"==h.marginTop&&1==c.offsetHeight||"dropbox.com"==e&&"register-partial-container"==
b.id&&50>c.offsetHeight)return!1;c=c.parentNode}catch(k){break}return!0}function createPopupFill(a,b){LPpop.set_icon_hint_from_data(a,b)}function getAutoFillArray(a,b,d){var e=[];a=punycode.URLToASCII(a.location.href);lpcanonizeUrl(a);for(var c in b)if(!b[c].genpw||d)e[c]=b[c];return e}
function dosavesiteicon(a){var b=LP_derive_doc();a=a?1:0;var d=[""],e=null!=g_popupfill_parent_last?g_popupfill_parent_last.form:null;null==e&null==g_popupfill_parent_last&&(e=null!=g_popupfill_parent?g_popupfill_parent.form:null);verbose_log("current input form is "+LP_getname(e));if(e){for(var c=e.elements,f=0,h=0,k=0,p=0;p<c.length;p++)if("FIELDSET"!=c.tagName){var q=c[p].type;"password"==q?h++:"text"==q||"tel"==q||"email"==q?f++:"textarea"==q&&k++}1==f&&1==h&&0==k?g_isfirefox?LP.lpOpenEditWindow(0):
((c=LP_get_form_save(e,!1,[],!0))&&0!=c.length||(c+=LP_get_form_save_orphans(d,!0)),b={url:punycode.URLToASCII(get_doc_location_href(b)),formdata2:c},sendBG({cmd:"savethesite",notificationdata:b,iframe:a})):g_isfirefox?LP.lpOpenEditWindow(0,!1,!1,null,!0):(c=LP_get_form_save(e,!1,[],!0),e=!1,c&&0<c.length&&(e=!0),c+=LP_get_form_save_orphans(d,!0,e),b={url:punycode.URLToASCII(get_doc_location_href(b)),formdata2:c},sendBG({cmd:"savethesite",notificationdata:b,iframe:a}))}else g_isfirefox?LP.lpOpenEditWindow(0,
!1,!1,null,!0):(info_log(b,"DE14"),c=LP_get_form_save_orphans(d,!0),b={url:punycode.URLToASCII(get_doc_location_href(b)),formdata2:c},sendBG({cmd:"savethesite",notificationdata:b,iframe:a}))}
function setupIcons(a,b,d){a||(a=LP_derive_doc());if(!a)return!1;if("undefined"!=typeof g_cpwbot&&g_cpwbot&&"undefined"!=typeof g_in_cpwbot&&g_in_cpwbot)return info_log(a,"CA25"),!1;if(do_experimental_popupfill){if("undefined"!=typeof g_isie&&g_isie){if("securelogin.globeop.com"==a.location.hostname&&!d){setTimeout(function(){setupIcons(a,b,!0)},10);return}if(init_LPfn()&&LPfn)LPfn.ie_reset_popupfillhint(),LPfn.ie_setup_event_handlers(a);else return verbose_log("Danger, Will Robinson"),!1}if(g_isfirefox&&
LP&&20>LP.lp_getFFVersionFloat())return!1;"undefined"!=typeof g_isfirefox&&g_isfirefox?(a.g_input_cnt=countInputs(a,!1,!0),a.g_form_cnt=countFormEquivalents(a),a.g_input_fingerprint=computeFingerprint(a),a.g_did_setupInputObserver=!1):(g_input_cnt=countInputs(a),g_form_cnt=countFormEquivalents(a),g_input_fingerprint=computeFingerprint(a),validate_input_indexes(a));var e=LP_getloggedin(),c=!1;if(g_dologin_clickable||!g_dologin_clickable&&e)c=!0;try{var f;f="undefined"!=typeof punycode?punycode.URLToASCII(a.location.href):
a.location.href;if(lp_url_is_lastpass(f)||LP_should_ignore_this_doc(a))return!1}catch(p){return!1}checkForTotpForm(a,"setupIcons")&&verbose_log("found totpform - setupIcons");if(c&&(b||checkForLoginForm(a)||checkDocumentForLoginOrphans(a)||checkForNonLoginForm(a)||checkForSignupForm(a)||checkDocumentForCPWOrphans(a)||checkDocumentForLoginFirstStageForm(a)||checkDocumentForLoginOrphansFirstStage(a))){e=gettldcached(get_doc_location_href(a));g_isfirefox||"undefined"!=typeof g_isie&&g_isie||sendBG({cmd:"getpopupfillsites",
tld:e,url:f});g_do_icon_number_hint&&(g_icon_number_overrides={sites:-1,formfills:-1});f="undefined"!=typeof window&&window?window:a.defaultView;e=LP_get_last_url_history(a);e||(LP_put_last_url_history(a),e=LP_get_last_url_history(a));var h=e.href,k=e.href_hash;f.setTimeout(function(){if(!g_isie){var c=LP_get_last_url_history(a).href_hash;if(get_doc_location_href(a)!==h||k!==c)return LP_put_last_url_history(a),formcachereset(a),fieldcachereset(a),setupIcons(a,b,d),!1}doc_create_clickable_icons(a,
"",SHOULD_DO_ALWAYS,b)},50)}}"function"==typeof setupInputObserver&&setupInputObserver(a);g_isfirefox||g_isie||!g_create_iframe_in_top||("undefined"!=typeof g_iscasper&&g_iscasper&&(window=a.defaultView),g_inframe=LP_inIframe(window));return!0}
function do_icon_number_hint(a,b,d){if("undefined"!=typeof g_icon_number_overrides){null==a||"undefined"!=typeof parseInt&&0>parseInt(a)||"undefined"==typeof parseInt&&0>a?g_icon_number_overrides.sites=-1:g_icon_number_overrides.sites=a;null==b||"undefined"!=typeof parseInt&&0>parseInt(b)||"undefined"==typeof parseInt&&0>b?g_icon_number_overrides.formfills=-1:g_icon_number_overrides.formfills=b;if(!d&&(d=LP_derive_doc(),!d))return;refresh_input_all_icon_bg(d);g_isfirefox&&LP&&"undefined"!=typeof g_icon_number_in_toolbar&&
g_icon_number_in_toolbar&&LP.lp_handle_buttons_all("refresh")}}function closepopupfills(a,b){!is_your_popup_showing(a)||g_isfirefox||"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk&&"undefined"!=typeof g_save_opened&&!g_save_opened?closepopupfills_real(a,b):(g_iframeclose_starttime=null,LP_waitfor_close_ack(closepopupfills_real,b))}
function closepopupfills_real(a,b){if(do_experimental_popupfill&&(a||(a=LP_derive_doc()),a)){g_isfirefox?clear_popup_heartbeat(g_popup_iframe_doc):g_isie||sendBG({cmd:"clear_popup_heartbeat"});"undefined"!=typeof g_popup_iframe_doc&&(g_popup_iframe_doc=null);g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&LP_inIframe(window)&&toplevel_iframe_state_get()&&sendBG({cmd:"closepopuptoplevel"});var d,e=a.getElementsByTagName("iframe"),c=[];for(d=0;d<e.length;d++)c[d]=e[d];for(d=0;d<e.length;d++){var f=c[d];
if("undefined"!=typeof f.id&&null!=f.id){var h=LPMAGICIFRAME;0==f.id.indexOf(h)&&(h=f.id.substr(h.length),null!=LP_getElementByIdOrName(a,h)&&revert_clickable_icon(a,h),info_log(a,"FF1",{param1:f.id}),g_iframe_dims={},f.parentNode&&(f.parentNode.removeChild(f),b&&bg.sendLpImprove("infieldclose",{source:"form",option:b})))}}do_icon_number_hint(-1,-1,a);if(g_double_password_hack||g_double_secret_password_hack)if(g_double_secret_password_hack=g_double_password_hack=!1,g_input_cnt=0,g_isfirefox){for(d=
LP.getBrowser().contentWindow;null!=d.top&&d.top!=d;)d=d.top;d=lpGetBrowserForDocument(d.document);LP.checkShouldRecheck(d)}else g_double_password_wtf?(g_form_cnt=g_input_cnt=0,g_pending_recheck||checkShouldRecheck()):(formcachereset(a),fieldcachereset(a),setupIcons(a));g_popupfill_parent_last=g_popupfill_parent;g_popupfill_parent=null;g_minheight_override=g_minwidth_override=g_popupfill_iframe_height_save=g_popupfill_iframe_width_save=g_popupfill_ctr=0;"undefined"!=typeof g_isie&&g_isie&&"undefined"!=
typeof init_LPfn&&init_LPfn()&&LPfn&&LPfn.ie_set_kbdnav(!1)}}function popupfill_resize(a){do_experimental_popupfill&&(a||(a=document?document:LP.getBrowser().contentDocument),null==a&&"undefined"!=typeof g_isfirefox&&g_isfirefox?end_weasel():0<get_doc_location_href(a).indexOf(".xul")||(relocate_popupfill_clickables(a),relocate_popupfill_iframes(a),0==g_weaseled&&weasel(100),g_weaseled=!0))}
function visual_cue_frag(a,b){var d="";if(null===a||0>=a.length)return d;popup_show_menu_expand_visual_cue&&(d="",g_visual_cue_on_hover&&(d=" style='display:none;'"),d="<span id='"+a+lp_ofa(b)+"' expander='true' class='expander' "+d+"><img id='"+a+"img"+lp_ofa(b)+"' src='arrow.png' />  </span>\n");return d}
function destroy_clickables(a){do_experimental_popupfill&&(a||(a=document),null!=a&&(end_weasel(a),closepopupfills(a),closeclickableicons(a),g_save_suggest_msg&&setTimeout(function(){destroy_save_suggest_msg(a,MSGDIVID,null);return!1},0),g_isie&&remove_LPfn()))}function sort_popupfill_bylasttouch(a,b){return(null==b||null==b.last_touch||0==b.last_touch?1073741824:b.last_touch)-(null==a||null==a.last_touch||0==a.last_touch?1073741824:a.last_touch)}
function doc_create_clickable_icons(a,b,d,e){if(do_experimental_popupfill){b=0;if(!a&&(a=g_isfirefox&&LP?LP.getBrowser().contentDocument:document,!a))return;if(g_isfirefox){var c=LP.lpGetCurrentWindow().document,f="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument;verbose_log("doc_create_clickable_icons: xuldoc is "+c.location.href);verbose_log("doc_create_clickable_icons: passed doc is "+a.location.href);verbose_log("doc_create_clickable_icons: toplevel doc is "+
f.location.href)}(c=9==a.nodeType?a.body:null)||(c=a.getElementsByTagName("body")[0]);if(c){c=!1;if(g_isfirefox){if(never_icons(lpcanonizeUrl(a.location.href),lp_gettld_url(a.location.href))||never_icons(lpcanonizeUrl(f.location.href),lp_gettld_url(f.location.href)))return;c=!0}else{var f=check_nevers(a,g_nevers,a.location.href),h=!0,k=!0,p=!0,q=!0;null!=f&&(h=f.show_for_formfill,k=f.show_for_save,p=f.show_for_autofill,q=f.show_for_clickable_icon);(0<g_popupfill_rows&&p||0==g_popupfill_rows&&k||h)&&
q&&(c=!0)}if(c){var f=a.getElementsByTagName("input"),m,c={},A=checkDocumentForLoginOrphans(a)||checkDocumentForLoginOrphansFirstStage(a),w=checkDocumentForCPWOrphans(a),B=checkDocumentForLoginFirstStageForm(a);if(g_aspx_hack&&!isASPpage())for(m=0;m<f.length&&5>m&&!isASPpage();m++)check_for_ASP(a,f[m]);var x=null;if("undefined"!=typeof Math){var E=Math.floor(1E4*Math.random()),F=f.length;if(g_aspx_hack&&isASPpage())create_icons_on_ASP(a,e);else if(A||w||B)create_icons_generic(a,e);else{var C=MAX_INPUTS_SOFT;
LP_exceedInputsThreshold(a)||(C=MAX_INPUTS_HARD);for(m=0;m<F&&m<C;m++)if(e||popupfill_shoulddofield(a,f[m],d))try{var g=f[m],l=LP_pickFormName(a,g.form),r=A||B||chk_form_has_password(a,g.form),v=w||chk_form_is_nonlogin_form(a,g.form);if(e)if(looksLikeUsername(f[m]))r=!0,v=!1,decision_log(a,"FF2",{param1:LP_pickFieldName(a,g)});else if(isInputFieldPassword(a,g))r=!0,v=!1,decision_log(a,"FF3",{param1:LP_pickFieldName(a,g)});else{decision_log(a,"FF4",{param1:LP_pickFieldName(a,g)});continue}var t=chk_form_ask_generate(a,
g.form),u=!1;null!=x&&null!=l&&l!=x&&(u=!0,t=chk_form_ask_generate(a,g.form,u));var y=LP_fieldGetWidth(g);if(null==c[l]||!(1<=c[l])||isInputFieldPassword(a,g)||r&&!t||g_show_icon_only_on_focus||isASPpage()&&isFirstFieldNonLoginSubForm(a,g))if(g_isfirefox&&(r||v||t)||(r&&(0<g_popupfill_rows&&p||0==g_popupfill_rows&&k)||(v&&!r||t)&&h)&&q)if(!r&&!t||LP_iconFieldWidthOK(g,y,!0))if(r||t||!v||LP_iconFieldWidthOK(g,y,!1))if(r||t||v||LP_iconFieldWidthOK(g,y,!1)){var n;if(v&&is_search_field(a,g,!0))decision_log(a,
"FF8",{param1:LP_pickFieldName(a,g)});else if(v&&LP_fieldIsReadOnly(g))decision_log(a,"FF9",{param1:LP_pickFieldName(a,g)});else if(r&&!t?(x=l,g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"sites"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(n="sites")):r&&t?(u=!1,(new RegExp(lpgs("ff_loginform_regexp"),"i")).exec(l)&&(u=!0),g_aspx_hack&&isASPpage()||u?(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"sites"}):
g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(n="sites")):(decision_log(a,"FF10",{param1:l}),g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"formfills"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"formfills"}),g_do_icon_number_hint&&(n=isInputFieldPassword(a,g)?g.form&&lpCheckCurrentPWField(g.form)?"sites":"generate":"formfills"))):!r&&t&&chk_form_changepw(a,g.form)?(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,
rowtype:"sites"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"sites"}),g_do_icon_number_hint&&(n="sites")):w?g_do_icon_number_hint&&(n="sites"):(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:l,rowtype:"formfills"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:l,rowtype:"formfills"}),g_do_icon_number_hint&&(n="formfills")),checkIsDisplayed(a,g,0,null,E)){decision_log(a,"FF11",{param1:LP_pickFieldName(a,g),param2:l});if(g_do_icon_number_hint){u=[];if(g_isfirefox){n||
(n="sites");var z=LP.getMatchingSites(a.location.href,SKIP_GENPWS);u[n]=z&&z.length?z.length:0}else u=g_icon_numbers;if(isASPpage()&&isFirstFieldNonLoginSubForm(a,g))setup_input_icon(a,g,"formfills",u);else{if("formfills"==n&&!isFirstFieldNonLoginSubForm(a,g)&&!lpIsVisible(g,!0)&&g.form&&lpIsVisible(g.form))continue;else isInputFieldPassword(a,g)&&lpIsVisible(g,!0)&&"formfills"==n&&(n="generate");setup_input_icon(a,g,n,u)}}else setup_input_icon(a,g);b++;g_isfirefox||g_save_suggest_msg&&n&&1>g_icon_numbers.sites&&
LP_addEventHandler(g,"click",function(b){var c=LP_getEventTarget(b);setTimeout(function(){do_save_suggest_msg(c,a)},0);LP_stopEventPropagation(b);return!1},!1);g_clickable_input&&(bg.get("LPContentScriptFeatures").is_infield_enabled||"password"!=g.type||!formHasUsernameField(g)||g_clickable_input_on_password)&&(bg.get("LPContentScriptFeatures").is_infield_enabled?(LP_setFieldClickEvent(a,g),realLaunchPopup=LP_addEventHandler(g,"focus",launchPopup,!1)):LP_didFieldClickEvent(a,g)||"sites"!=n||(LP_setFieldClickEvent(a,
g),realLaunchPopup=LP_addEventHandler(g,"click",launchPopup,!1)));null==c[l]?c[l]=1:c[l]++}else decision_log(a,"FF13",{param1:LP_pickFieldName(a,g),param2:l})}else decision_log(a,"FF7",{param1:LP_pickFieldName(a,g)});else decision_log(a,"FF6",{param1:LP_pickFieldName(a,g)});else decision_log(a,"FF5",{param1:LP_pickFieldName(a,g)})}catch(D){verbose&&alert("error: "+D.message+" stack: "+D.stack)}decision_log(a,"DE3",{param1:b})}g_isfirefox||(0==g_weaseled&&setTimeout(function(){weasel(100)},500),g_weaseled=
!0)}}}}}var realLaunchPopup,launchPopup=function(a){var b;if(b=g_isfirefox&&LP?LP.getBrowser().contentDocument:document){var d=LP_getEventTarget(a),e=LPMAGIC+LP_pickFieldName(b,d);if(null!=b.getElementById(e))g_clickable_input_on_password?is_your_popup_showing(b)||conditional_create_popup(b,d,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(b,ai.form),popuptoggle(b,null,LP_pickFieldName(b,d),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));else if(g_input_click_intercept)try{info_log(b,"FF12"),icon_click_handler(a)}catch(c){}return!1}};
function create_clickable_icon_on_active_field(a,b){if(do_experimental_popupfill){if(!popupfill_shoulddofield(a,b,!1))return;var d=!0,e=check_nevers(document,g_nevers,document.location.href);null!=e&&(d=e.show_for_clickable_icon);var e=checkDocumentForLoginOrphans(a)||checkDocumentForLoginOrphansFirstStage(a),c=checkDocumentForLoginFirstStageForm(a),f;if(b.form&&lpIsVisible(b.form)){var h=null,h=LP_pickFormName(document,b.form),c=e||c||chk_form_has_password(document,b.form);chk_form_is_nonlogin_form(document,
b.form);g_is_specialsite&&looksLikeUsername(b)&&(c=!0);var k=chk_form_ask_generate(document,b.form);c&&!k||g_is_specialsite?(sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"sites"}),g_do_icon_number_hint&&(f="sites")):g_aspx_hack&&isASPpage()?(sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"sites"}),g_do_icon_number_hint&&(f="sites")):!c&&k&&chk_form_changepw(document,b.form)?(sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"sites"}),g_do_icon_number_hint&&(f="sites")):(c=form_get_username(a,b.form),
k=form_get_password(a,b.form),g_do_icon_number_hint?(f=isInputFieldPassword(a,b)||c==b||k==b?"sites":"formfills",sendBG({cmd:"setpopupfillhint",formid:h,rowtype:f})):sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"formfills"}))}checkForTotpForm(a,"create_clickable_icon_on_active_field")&&verbose_log("found totpform - create_clickable_icon_on_active_field");if(e||g_is_specialsite||checkForLoginForm(document)){var p=punycode.URLToASCII(document.location.href),q=lp_gettld_url(p);setTimeout(function(){sendBG({cmd:"getpopupfillsites",
tld:q,url:p})},0);d&&(LP_getname_or_idx(document,b,LP_GETNAME_FAVOR_ID_OVER_NAME),g_do_icon_number_hint?setTimeout(function(){var c=LP_pickFieldName(a,b),d=!1;(c=getIconState(a,c))&&c.fillhint&&(f=c.fillhint,d=c.no_check_generate);setup_input_icon(document,b,f,g_icon_numbers,d)},50):setTimeout(function(){setup_input_icon(document,b)},50),g_save_suggest_msg&&f&&1>g_icon_numbers.sites&&b.addEventListener("click",function(a){var b=a.target;setTimeout(function(){do_save_suggest_msg(b,document)},0);a.preventDefault();
a.stopPropagation();return!1},!1),!g_clickable_input||"password"==b.type&&formHasUsernameField(b)&&!g_clickable_input_on_password||LP_didFieldClickEvent(document,b)||!f||"sites"!=f||(LP_setFieldClickEvent(document,b),LP_addEventHandler(b,"click",function(a){a=a.target;var c=LPMAGIC+LP_getname_or_idx(document,a,LP_GETNAME_FAVOR_ID_OVER_NAME);null!=document.getElementById(c)&&(g_clickable_input_on_password?is_your_popup_showing(document)||conditional_create_popup(document,a,FORCE_SHOW_NOHITS_NOLOGIN):
(set_active_username_password(document,b.form),popuptoggle(document,null,LP_getname_or_idx(document,b,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)));return!1},!1)))}"undefined"!=typeof firstfill&&firstfill&&decision_log(a,"DE4",{param1:0})}return!0}
function ff_get_iframe_pos(a,b,d,e,c){if(!g_isfirefox||!c)return null;var f;b=null;d=[];try{var h=c.getElementsByTagName("iframe");for(f=0;f<h.length&&50>f;f++)url_is_lpfirefox_iframe(h[f].src)||(d[d.length]=h[f]);h=c.getElementsByTagName("frame");for(f=0;f<h.length&&50>f;f++)d[d.length]=h[f];if(a&&a==c)try{a=g_popup_iframe_doc.defaultView.parent.document.g_popupfill_parent.ownerDocument}catch(m){verbose_log("frame lookup error: "+m)}var k=getIconState(a,e);if(k)if(h=f=a=null,k&&k.inframe){verbose_log("Input is in frame!");
for(k=k=0;k<d.length;k++){f=null;verbose_log("Trying frame "+d[k].src);try{f=d[k].contentDocument;var p=LP_getElementByIdOrName(f,e);if(p&&"INPUT"==p.tagName){verbose_log("Found INPUT "+e+" in "+f.location.href);h=LP_getAbsolutePos(c,d[k]);break}}catch(m){verbose_log("Error frame traverse "+m.message);return}}if(f&&h&&(verbose_log("computing iframe position [against iframe]"),a=LP_getElementByIdOrName(f,e))){var q=ff_calculate_iframe_pos(f,a,0<g_minwidth_override?g_minwidth_override:0);b={posx:parseInt(q.posx)+
h.left+"px",posy:parseInt(q.posy)+h.top+"px"};verbose_log("computed x="+b.posx+" y="+b.posy)}}else null==k||isEmptyObject(k)?verbose_log("data object is missing for "+e):(verbose_log("computing iframe position [against toplevel]"),(a=LP_getElementByIdOrName(c,e))&&(b=ff_calculate_iframe_pos(c,a,0<g_minwidth_override?g_minwidth_override:0)))}catch(m){verbose&&alert("ff_pos "+m.message)}return b}
function should_ignore_autocompleteoff_bypref(a,b){if(!b||!a&&((a=b.ownerDocument)||(a=LP_derive_doc()),!a))return!0;var d=!1;"undefined"!=typeof lpdontfillautocompleteoff&&(d=lpdontfillautocompleteoff?!0:!1);return d&&"off"==b.getAttribute("autocomplete")?(verbose_log("pref+autocomplete=off, not filling "+LP_getname(b)),!0):!1}
function LP_get_input_pattern(a,b){if(!a||!b)return null;var d=LP_pickFieldName(a,b),e=fieldcacheget(a,d,"input_pattern");if(null!=e)return e;(e=b.getAttribute("pattern"))&&(e=e.trim());LP_hasAngular(a)&&(e=b.getAttribute("ng-pattern"));if(!e)return null;-1==e.indexOf("?:")&&-1==e.indexOf("$")&&(e="^(?:"+e+")$");fieldcacheset(a,d,"input_pattern",e);return e}
function LP_get_input_pattern_desc(a,b){if(!a||!b)return null;var d=b.getAttribute("title");if(d)return d;if(d=b.getAttribute("aria-describedby"))if(d=a.getElementById(d))return LP_elt_get_text(d);return null}function LP_test_input_pattern(a,b){if(!a||!b)return null;var d=LP_get_input_pattern(a,b);return d?(d=new RegExp(d),d.exec(b.value)?!0:!1):!1}
function LP_get_generate_password_with_pattern(a,b){if(!a)return null;var d,e,c=[],f=a.getElementsByTagName("input");for(e=0;e<f.length&&e<MAX_INPUTS_HARD;e++)d=f[e],b&&d.form!=b||"password"!=d.type||LP_explicit_ignored(a,d)||LP_implicit_ignored(a,d)||c.push({elt:d,score:0});if(0>=c.length)return null;for(e=0;e<c.length;e++)if(d=c[e].elt,LP_get_input_pattern(a,d)&&(c[e].score+=10),f=new RegExp(lpgs("ff_currpass_regexp"),"i"),f.exec(LP_getname(d,!1))||f.exec(LP_getname(d,!0)))c[e].score-=5;c.sort(function(a,
b){return b.score-a.score});return 0<c[0].score?c[0].elt:null}
function LP_cleanup_on_logout(a,b){a||(a=LP_derive_doc());if(!a)return!1;if(null===b||"undefined"==typeof b)b=0;if(5<b)return!0;var d=!0,e="lpcurrpasselt lpcurruserelt _lpinvis __lpsadmsgdiv __lpsavemsgdiv __lpsuggestmsgdiv __lpresultdiv __lpseleniumbitsdiv".split(" ");try{for(var c=0;c<e.length;c++){var f=document.getElementById(e[c]);f&&f.parentNode.removeChild(f);g_queeg_mode&&(f=document.getElementById(e[c]))&&LP_cleanup_on_logout(a,b+1)}if(a.script_stash){for(c in a.script_stash)a.script_stash.hasOwnProperty(c)&&
(f=a.script_stash[c])&&f.parentNode&&f.parentNode.removeChild(f);a.script_stash={}}}catch(h){d=!1}reset_lpsaveforminfo_vars(a);reset_forcefill_without_fillbest();return d}function LP_request_iframe_close(a){a||(a=LP_derive_doc());if(!a||!a.location)return!1;"undefined"!=typeof g_isie&&g_isie?LPfn.request_iframe_close():g_isfirefox?pass:sendBG({cmd:"iframe_close_request",docstate:get_docstate(a),initiate_timestamp:LPPerl.time()});return!0}
function LP_iframe_close_intent_handler(a){"undefined"!=typeof a.value&&(g_iframecloseval=a.value);return!0}
function LP_waitfor_close_ack(a,b,d){"undefined"==typeof d&&(d=0);var e=LP_gettime(),c=LP_derive_doc();if(null===g_iframeclose_starttime)return null===e&&(e=0),g_isie||(g_iframecloseval=CLOSE_CONFIRM_INITIAL),g_iframeclose_starttime=e,LP_request_iframe_close(c),setTimeout(function(){LP_waitfor_close_ack(a,b,d+1)},10),!0;if(g_iframecloseval===CLOSE_CONFIRM_INITIAL){if(e-g_iframeclose_starttime>g_iframeclose_timeout||500*d>g_iframeclose_timeout)return a(b);setTimeout(function(){LP_waitfor_close_ack(a,
b,d+1)},500);return!0}if(g_iframecloseval&CLOSE_CONFIRM_SAFECLOSEBITS)return a(b);if(lpConfirmYesNo(lpgs("Are you sure you want to close this window?  You will lose your unsaved changes.")))return g_iframecloseval=CLOSE_CONFIRM_OKCLOSE,a(b);g_iframecloseval=CLOSE_CONFIRM_NOCLOSE}
function reset_lpsaveforminfo_vars(a){"undefined"!=typeof a&&"undefined"!=typeof a.LPlpsaveforminfo&&delete a.LPlpsaveforminfo;"undefined"!=typeof a&&"undefined"!=typeof a.LPlpsaveforminfoaddurid&&delete a.LPlpsaveforminfoaddurid;return!0}
var g_iframecloseval=null,g_iframeclose_timeout=5E3,g_iframeclose_starttime=null,CLOSE_CONFIRM_INITIAL=0,CLOSE_CONFIRM_CHECKING=1,CLOSE_CONFIRM_NOCLOSE=2,CLOSE_CONFIRM_OKCLOSE=4,CLOSE_CONFIRM_LOGGEDOUT=5,CLOSE_CONFIRM_TERMINATE=6,CLOSE_CONFIRM_NO_POPUP=7,CLOSE_CONFIRM_SAFECLOSEBITS=4,CLOSE_CONFIRM_NOCLOSEBITS=0;
