var g_new_superbar=!0;"undefined"!=typeof g_isfirefox&&g_isfirefox&&(g_new_superbar=!1);
var SB_icons={savesite:{id:"SB_addico",alt:gs("Save Site"),src:g_40_icons.Add,dock:"left",tooltiptext:gs("Save Password to Vault"),clickfn:function(a){savesite_popupaction_iframe(LP_derive_doc(),a,null)}},sites:{id:"SB_siteico",alt:gs("Sites"),src:g_40_icons.Sites,dock:"left",tooltiptext:gs("Saved Passwords"),clickfn:function(a){sites_popupaction(a,LP_derive_doc())}},formfill:{id:"SB_ffico",alt:gs("Form Fills"),src:g_40_icons.FormFill,dock:"left",tooltiptext:gs("Form Fill Profiles"),clickfn:function(a){formfillprofile_popupaction(a,
LP_derive_doc())}},generate:{id:"SB_genico",alt:gs("Generate"),src:g_40_icons.Generate,dock:"left",tooltiptext:gs("Generate"),clickfn:function(a){generate_popupaction(a)}},never:{id:"SB_nevico",alt:gs("Never"),src:g_40_icons.Disable,dock:"left",tooltiptext:gs("Disable"),clickfn:function(a){never_popupaction(a,LP_derive_doc(),"close")}},close:{id:"SB_closeico",alt:gs("Close"),src:g_40_icons.Close,dock:"right",tooltiptext:gs("Close"),clickfn:function(a){close_popupaction(LP_derive_doc(),"close")}}};
function set_new_superbox_40(a,b){if(!a)return null;var f="undefined"!=typeof g_isfirefox&&g_isfirefox?"html:":"",c=null;verbose&&times&&(times.createbox=LP_gettime());c=function(a,c){if(!a||!c)return null;var d=a.createElement(f+"div");d.id="headerdiv";d.className="bg40dialog";c.appendChild(d);verbose&&times&&(times.createheader=LP_gettime());LP_addEventHandler(d,"selectstart",function(){return!1});return d}(a,b);if(!c)return null;(function(a,c){verbose&&times&&(times.doiconsstart=LP_gettime());
var d,l=a.createElement(f+"div");l.id="SB_iconbox";l.className="super40height bg40header";l.setAttribute("role","navigation");c.appendChild(l);for(d in SB_icons)if(SB_icons.hasOwnProperty(d)){var h=a,g=l,b=SB_icons[d];if(h&&g){var e,k=h.createElement(f+"a");k.id=b.id+"_a";e="super40icon";"right"==b.dock?(e+=" floatright",b.tooltiptext&&(e+=" tooltip40super")):(e+=" floatleft",b.tooltiptext&&(e+=" tooltip40superlong"));k.setAttribute("draggable","false");k.className=e;g.appendChild(k);g=b;h&&g?(e=
h.createElement(f+"input"))?(e.id=g.id+"_img",e.type="button",g.tooltiptext||e.setAttribute("title",g.alt),e.setAttribute("aria-label",g.alt),e.className=sprintf("bg40header super40icon_icon %s",e.id),g=e):g=null:g=null;k.appendChild(g);g_isie&&(g.style.display="none",g=b,h&&g?(e=h.createElement("INPUT"),e.id=g.id+"_img_ie",e.type="image",g_isie?e.src=g.src:e.setAttribute("src",g.src),e.setAttribute("alt",g.alt),g.tooltiptext||e.setAttribute("title",g.alt),e.width=16,e.height=16,e.className="super40icon_icon_ie",
g=e):g=null,k.appendChild(g));b.tooltiptext&&(h=h.createElement(f+"span"),LP_elt_set_text(h,b.tooltiptext),k.appendChild(h))}}verbose&&times&&(times.doiconsdone=LP_gettime());return!0})(a,c);(function(a,c){if(!a||!c)return!1;var d=a.createElement(f+"div");d.id="SB_titlebox";d.className="super40height bg40title super40title unselectable";g_isie&&10>LP_getDocumentMode(a)&&d.setAttribute("unselectable","on");var b=a.createElement(f+"span");b.id="SB_titlebox_txt";b.setAttribute("draggable","false");b.className=
"super40title";LP_elt_set_text(b,gs("What would you like to do?"));d.appendChild(b);verbose&&(b=a.createElement(f+"span"),b.id="debug_txt",b.style.display="inline",b.style.fontSize="10px",b.style.marginLeft="5px",d.appendChild(b));c.appendChild(d);verbose&&times&&(times.createtitle=LP_gettime());return!0})(a,c);(function(a){if(!a)return!1;for(var b in SB_icons)if(SB_icons.hasOwnProperty(b)){var c=a.getElementById(SB_icons[b].id+"_img");c&&LP_addEventHandler(c,"click",SB_icons[b].clickfn)}return!0})(a)}
function update_title40(a,b){if(!a)return!1;var f=a.getElementById("SB_titlebox_txt"),c="";switch(b){case "sites":case "never":case "formfill":case "generate":case "savesite":c=SB_icons[b].alt;break;case "zerostate":c=gs("What would you like to do?");break;case "delete":c=gs("Delete Site");break;case "deleteff":c=gs("Delete Formfill Profile");break;case "more":c=gs("More")}c&&LP_elt_set_text(f,c);return!0}
function set_active_img40(a,b){if(!a)return!1;var f,c,h,k=SB_icons[b];switch(b){case "sites":case "never":case "formfill":case "generate":case "savesite":for(f in SB_icons)if(SB_icons.hasOwnProperty(f))if(c=SB_icons[f].id+"_img",h=SB_icons[f].id+"_active",f==b){var d=a.getElementById(k.id+"_img");d&&0<=d.className.indexOf(c)&&(d.className=d.className.replace(c,h))}else(d=a.getElementById(SB_icons[f].id+"_img"))&&0<=d.className.indexOf(h)&&(d.className=d.className.replace(h,c));break;default:for(f in SB_icons)SB_icons.hasOwnProperty(f)&&
(c=SB_icons[f].id+"_img",h=SB_icons[f].id+"_active",d=a.getElementById(c))&&(d.className=d.className.replace(h,c))}return!0}function reveal_real_icons(a){for(var b in SB_icons){var f=a.getElementById(SB_icons[b].id+"_img_ie"),c=a.getElementById(SB_icons[b].id+"_img");f&&c&&(f.style.display="none",c.style.display="block")}return!0}"undefined"!=typeof g_isie&&g_isie&&LP_addEventHandler(window,"load",function(){reveal_real_icons(document)});
