var PreferencesDialog=function(h){Dialog.call(this,h,{additionalHeaderClasses:"icon",title:Strings.translateString("Preferences"),closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.hotkeyFields={}};PreferencesDialog.prototype=Object.create(Dialog.prototype);PreferencesDialog.prototype.constructor=PreferencesDialog;
(function(){var h={usepopupfill:!0,enablenamedpipes:!0,language:!0},l=function(b){var a=[];b.ctrlKey&&a.push("control");b.metaKey&&a.push("meta");b.altKey&&a.push("alt");b.shiftKey&&a.push("shift");if(a.length>b.shiftKey)switch(b.which){case 16:case 17:case 18:case 91:case 92:break;default:this.setValue(b.which,a.join(" "))}switch(b.which){case 8:case 46:this.clear();break;case 9:break;default:b.preventDefault(),b.stopPropagation()}},g=function(b,a){DialogInput.Input.apply(this,arguments);this.keyCode=
0;this.mods="";(function(a){a.input.bind("keydown",function(b){l.call(a,b)})})(this)};g.prototype=Object.create(DialogInput.Input.prototype);g.prototype.constructor=g;g.prototype.setValue=function(){var b=null,a=null;return function(c,k){var e="";if(k&&c){var e=k.split(" "),d;null===a&&(a={control:Strings.translateString("Ctrl"),meta:Strings.translateString("Meta"),alt:Strings.translateString("Alt"),shift:Strings.translateString("Shift")});d=a;for(var f=0,g=e.length;f<g;++f)e[f]=d[e[f]];null===b&&
(b={33:Strings.translateString("Page Up"),34:Strings.translateString("Page Down"),35:Strings.translateString("End"),36:Strings.translateString("Home"),37:Strings.translateString("Left"),38:Strings.translateString("Up"),39:Strings.translateString("Right"),40:Strings.translateString("Down"),189:"-",219:"[",220:"\\",221:"]",186:";",222:"'",188:",",187:"+",190:".",191:"/",106:"*",192:"~",124:Strings.translateString("Print Screen")});d=b;void 0!==d[c]?e.push(d[c]):e.push(String.fromCharCode(c).toUpperCase());
e=e.join("+");this.keyCode=c;this.mods=k}else this.keyCode=0,this.mods="";DialogInput.Input.prototype.setValue.call(this,e)}}();var d=function(b,a){DialogInput.Input.apply(this,arguments);this.checkboxField=$("#"+this.input.attr("checkboxField"));(function(a){var b=null;void 0===a.checkboxField.attr(Dialog.prototype.DIALOG_FIELD)&&(a.checkboxField.bind("change",function(){a.checkboxField.prop("checked")?null!==b&&(a.setValue(b),b=null):(b=a.getValue(),a.setValue(""))}),a.onChange(function(b){a.checkboxField.prop("checked",
0<b?!0:!1)}))})(this)};d.prototype=Object.create(DialogInput.Input.prototype);d.prototype.constructor=d;d.prototype.enable=function(){DialogInput.Input.prototype.enable.apply(this,arguments);this.checkboxField.prop("disabled",!1)};d.prototype.disable=function(){DialogInput.Input.prototype.disable.apply(this,arguments);this.checkboxField.prop("disabled",!0)};d.prototype.buildError=function(){return this.buildErrorElement({element:this.input.parent().children()})};d.prototype.setValue=function(b){("number"!==
typeof b||0<b)&&DialogInput.Input.prototype.setValue.apply(this,arguments)};d.prototype.validate=function(b,a,c){return c&&(c=parseInt(c),isNaN(c)||0>c)?(b.addError(a,Strings.translateString("Value must be greater than or equal to %1.",0)),!1):!0};var m=function(){for(var b=LPProxy.getFormFillModels(),a=[{value:0,label:""}],c=0,d=b.length;c<d;++c){var e=b[c];a.push({value:e.getID(),label:e.getName()})}return a},n=function(){var b=[],a=bg.get("g_langs"),c;for(c in a)b.push({value:c,label:a[c]});return b};
PreferencesDialog.prototype.setupButtons=function(b){Dialog.prototype.setupButtons.apply(this,arguments);this.resetDefaultsButton=$(LPTools.createElement("button","nbtn btn_midi wbtn dynamicWidth leftButton"));this.resetDefaultsButton.bind("click",this.createHandler(this.resetDefaults));this.buttonContainer.prepend(this.resetDefaultsButton)};PreferencesDialog.prototype.resetDefaults=function(){for(var b=this.currentViewElement.find("["+this.DIALOG_FIELD+"]"),a={},c=0,d=b.length;c<d;++c)a[b[c].getAttribute(this.DIALOG_FIELD)]=
!0;this.populateFields(bg.Preferences.getDefault(a))};PreferencesDialog.prototype.leftMenuChange=function(b){this.resetDefaultsButton.text(Strings.translateString("Restore '%1' Defaults",b.text()))};PreferencesDialog.prototype.getHotKeyPreferenceNames=function(){var b={},a;for(a in this.hotkeyFields)b[a+"KeyCode"]=!0,b[a+"Mods"]=!0;return b};PreferencesDialog.prototype.getData=function(){var b=Dialog.prototype.getData.apply(this,arguments),a;for(a in this.hotkeyFields){var c=this.hotkeyFields[a];
b[a+"KeyCode"]=c.keyCode;b[a+"Mods"]=c.mods}return b};PreferencesDialog.prototype.defaultFields=function(b){b.defaultData=$.extend(b.defaultData,bg.Preferences.get(DialogInput.getProperties(this.inputFields)));this.inputFields.defaultffid.setOptions(m());this.inputFields.language.setOptions(n());Dialog.prototype.defaultFields.apply(this,arguments);var a=bg.Preferences.get(this.getHotKeyPreferenceNames()),c;for(c in this.hotkeyFields)this.hotkeyFields[c].setValue(a[c+"KeyCode"],a[c+"Mods"]);a=bg.get("g_prefoverrides");
-1<a.logoffclosebrowser?(this.inputFields.logoffWhenCloseBrowser.setValue(a.logoffclosebrowser),this.inputFields.logoffWhenCloseBrowserVal.setValue(a.logoffclosebrowser),this.inputFields.logoffWhenCloseBrowserVal.disable()):this.inputFields.logoffWhenCloseBrowserVal.enable();-1<a.logoffidle?(this.inputFields.idleLogoffVal.setValue(a.logoffidle),this.inputFields.idleLogoffVal.disable()):this.inputFields.idleLogoffVal.enable();bg.get("g_flags").pollIntervalSetByPolicy?this.inputFields.pollServerVal.disable():
this.inputFields.pollServerVal.enable()};PreferencesDialog.prototype.clearFields=function(){Dialog.prototype.clearFields.apply(this,arguments);for(var b in this.hotkeyFields)this.hotkeyFields[b].clear()};var p=function(b){return function(a){var c=b.getValue();c&&(b.clear(),LPTools.requireBinary(function(){b.setValue(c)}))}};PreferencesDialog.prototype.initialize=function(b){this.initializeInputFields(b.find("input[checkboxField]"),function(a){return new d(a,this)});Dialog.prototype.initialize.apply(this,
arguments);for(var a=b.find("input[hotkeyField]"),c=0,k=a.length;c<k;++c){var e=a[c],h=e.getAttribute("hotkeyField");this.hotkeyFields[h]=new g(e,this)}var a=LPPlatform.getUnavailablePreferences(),f;for(f in a)a[f]&&(b.find("input["+this.DIALOG_FIELD+"="+f+"]").closest("tr").detach(),b.find("select["+this.DIALOG_FIELD+"="+f+"]").closest("tr").detach(),b.find("input[hotkeyField="+f+"]").closest("tr").detach());a=LPPlatform.getPreferencesRequiringBinary();for(f in a)a[f]&&(c=this.inputFields[f])&&c.input.bind("change",
p(c));bg.get("LPContentScriptFeatures").is_infield_enabled||document.getElementById("infieldPopupEnabled").parentElement.parentElement.remove();bg.get("g_hidelogoffprefs")&&$("#securityPrefs").remove();bg.get("g_hideappearancebox")&&$("#appearancePrefs").remove();bg.get("g_hidehelptranslate")&&$("#helpTranslateButton").remove();bg.get("g_issafari")?$("#iconMenuItem").LP_hide():$("#helpTranslateButton").bind("click",function(){bg.openURL(bg.get("base_url")+"translate.php")})};PreferencesDialog.prototype.validate=
function(b){var a=Dialog.prototype.validate.apply(this,arguments);b.autoautoVal&&10>b.autoautoVal&&(this.addError("autoautoVal",Strings.translateString("Value must be greater than or equal to %1.",10)),a=!1);b.pollServerVal&&5>b.pollServerVal&&(this.addError("pollServerVal",Strings.translateString("Value must be greater than or equal to %1.",5)),a=!1);return a};PreferencesDialog.prototype.checkForRestartOrLogoff=function(b,a){for(var c in h)if(b[c]!==this.originalData[c]){dialogs.alert.open({title:Strings.translateString("Restart Required"),
text:Strings.translateString("You must restart your browser before all of the changes will take effect."),handler:a,closeHandler:a});return}(this.originalData.logoffWhenCloseBrowser&&0===this.originalData.logoffWhenCloseBrowserVal)!==(b.logoffWhenCloseBrowser&&0===b.logoffWhenCloseBrowserVal)?dialogs.alert.open({title:Strings.translateString("Logoff Required"),text:Strings.translateString("You must restart Chrome or logoff and back in to get 'Logoff on Browser Close' changes to take effect."),handler:a,
closeHandler:a}):a()};PreferencesDialog.prototype.handleSubmit=function(){var b=function(a){var b=this.getChanges(a);this.checkForRestartOrLogoff(a,this.createHandler(function(){bg.Preferences.set(b);LPPlatform.handlePreferenceChanges(b);this.close(!0)}))};return function(a){(a.logoffWhenCloseBrowser||a.idleLogoffEnabled)&&(bg.Preferences.get("rememberpassword")||bg.get("g_master_password_saved"))?dialogs.confirmation.open({title:Strings.translateString("Remember Password"),text:Strings.translateString("You currently have LastPass set to remember your password.  Doing so essentially makes the automatically log out options you've chosen useless.  Would you like LastPass to stop remembering your password?"),
handler:this.createHandler(function(){bg.Preferences.set("rememberpassword",!1);bg.deletesavedpw(bg.get("g_username"));b.call(this,a)}),closeHandler:this.createHandler(b,a)}):b.call(this,a)}}()})();
