function lpPutUserPref(a,b){"undefined"==typeof g_userprefs&&(g_userprefs=getBG().g_userprefs);if("undefined"==typeof g_userprefs[a]||g_userprefs[a]!=b)g_userprefs_changed[a]=!0;g_userprefs[a]=b}function lpPutGblPref(a,b){"undefined"==typeof g_gblprefs&&(g_gblprefs=getBG().g_gblprefs);if("undefined"==typeof g_gblprefs[a]||g_gblprefs[a]!=b)g_gblprefs_changed[a]=!0;g_gblprefs[a]=b}
function lpGetPref(a,b){"undefined"==typeof g_userprefs&&(g_userprefs=getBG().g_userprefs);if("undefined"!=typeof g_userprefs&&"undefined"!=typeof g_userprefs[a])return g_userprefs[a];"undefined"==typeof g_gblprefs&&(g_gblprefs=getBG().g_gblprefs);return"undefined"!=typeof g_gblprefs&&"undefined"!=typeof g_gblprefs[a]?g_gblprefs[a]:b}
function dodefault(){var a=get_innertext(document.getElementById("default"));if(0<=a.indexOf("General"))document.getElementById("logoffWhenCloseBrowserVal").value=0,document.getElementById("logoffWhenCloseBrowser").checked=!1,document.getElementById("idleLogoffVal").value="",document.getElementById("idleLogoffEnabled").checked=!1,document.getElementById("openpref").value="tabs",document.getElementById("htmlindialog").checked=g_isfirefoxsdk,document.getElementById("highlightFields").checked=!0,document.getElementById("automaticallyFill").checked=
!0,document.getElementById("showvault").checked=!1,document.getElementById("showAcctsInGroups").checked=!0,document.getElementById("hideContextMenus").checked=!1,document.getElementById("defaultffid").value=0,document.getElementById("donotoverwritefilledfields").checked=!1;else if(0<=a.indexOf("Notifications"))document.getElementById("showNotifications").checked=!0,document.getElementById("showGenerateNotifications").checked=!1,document.getElementById("showFormFillNotifications").checked=!1,document.getElementById("showNotificationsAfterClick").checked=
!1,document.getElementById("showFillNotificationBar").checked=!1,document.getElementById("showSaveNotificationBar").checked=!0,document.getElementById("showSaveSiteNotifications").checked=!1,document.getElementById("notificationsBottom").checked=!1,document.getElementById("showChangeNotificationBar").checked=!0,document.getElementById("showmatchingbadge").checked=!0,document.getElementById("usepopupfill").checked=!0;else if(0<=a.indexOf("Hotkeys")){getBG().g_is_mac?(optionsData.HotKeys.generateHkKeyCode=
0,optionsData.HotKeys.generateHkMods="",optionsData.HotKeys.recheckHkKeyCode=0,optionsData.HotKeys.recheckHkMods="",optionsData.HotKeys.searchHkKeyCode=0,optionsData.HotKeys.searchHkMods="",optionsData.HotKeys.nextHkKeyCode=33,optionsData.HotKeys.nextHkMods="meta",optionsData.HotKeys.prevHkKeyCode=34,optionsData.HotKeys.prevHkMods="meta",optionsData.HotKeys.homeHkKeyCode=0,optionsData.HotKeys.homeHkMods="",optionsData.HotKeys.openpopoverHkKeyCode=220,optionsData.HotKeys.openpopoverHkMods="meta"):
(optionsData.HotKeys.generateHkKeyCode=71,optionsData.HotKeys.generateHkMods="alt",optionsData.HotKeys.recheckHkKeyCode=73,optionsData.HotKeys.recheckHkMods="alt",optionsData.HotKeys.searchHkKeyCode=87,optionsData.HotKeys.searchHkMods="alt",optionsData.HotKeys.nextHkKeyCode=33,optionsData.HotKeys.nextHkMods="alt",optionsData.HotKeys.prevHkKeyCode=34,optionsData.HotKeys.prevHkMods="alt",optionsData.HotKeys.homeHkKeyCode=72,optionsData.HotKeys.homeHkMods="control alt",optionsData.HotKeys.openpopoverHkKeyCode=
220,optionsData.HotKeys.openpopoverHkMods="alt");optionsData.HotKeys.submitHkKeyCode=0;optionsData.HotKeys.submitHkMods="";optionsData.HotKeys.saveallHkKeyCode=0;optionsData.HotKeys.saveallHkMods="";optionsData.HotKeys.logoffHkKeyCode=0;optionsData.HotKeys.logoffHkMods="";optionsData.HotKeys.defaultffidHkKeyCode=0;optionsData.HotKeys.defaultffidHkMods="";for(var a="generateHk recheckHk searchHk nextHk prevHk homeHk submitHk saveallHk logoffHk defaultffidHk openpopoverHk".split(" "),b=0;b<a.length;b++)writeHotKeyValue(a[b])}else 0<=
a.indexOf("Advanced")?(document.getElementById("autoautoEnabled").checked=!0,document.getElementById("autoautoVal").value="25",document.getElementById("warninsecureforms").checked=!1,document.getElementById("dontfillautocompleteoff").checked=!1,document.getElementById("pollServerEnabled").checked=!0,document.getElementById("pollServerVal").value="15",document.getElementById("recentUsed").checked=!0,document.getElementById("recentUsedCount").value="10",document.getElementById("searchNotes").checked=
!0,document.getElementById("openloginstart").checked=!1,document.getElementById("storeLostOTP").checked=!0,document.getElementById("enablenewlogin").checked=!0,document.getElementById("clearfilledfieldsonlogoff").checked=!1,document.getElementById("toplevelmatchingsites").checked=!1):0<=a.indexOf("Icons")&&(document.getElementById("icons2").checked=!0)}function fix_userhash(a){return""==a&&is_edge()?"global":a}
function lpReadAllPrefs(a){var b=g_username_hash&&""!=g_username_hash?g_username_hash:"";g_userprefs={};g_identity="";var c=opendb();createPrefsTable(c);if(c){var d=function(b,d){g_gblprefs={};for(var c=0;c<d.rows.length;c++){var e=d.rows.item(c).username_hash,f=d.rows.item(c).prefname,k=d.rows.item(c).prefvalue;e!=fix_userhash("")?"language"!=f&&(g_userprefs[f]=k,"identity"==f&&(g_identity=k)):g_gblprefs[f]=k}if(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)c=lpGetPref("language",""),include_language(c);
start_idle_checker();"undefined"==typeof g_gblprefs.generateHkKeyCode&&setup_default_hotkeys();setup_hotkeys();"undefined"!=typeof g_gblprefs.server&&(c=g_gblprefs.server,""==c||"lastpass.com"!=c&&"lastpass.eu"!=c||(0==base_url.indexOf("https://preprod.lastpass.com")||0==base_url.indexOf("https://lpdev.lastpass.com"))&&"lastpass.com"==c||(base_url="https://"+c+"/"));g_prefs_read=!0;console_log("read: "+d.rows.length+" preferences");a&&a(d.rows.length)};if(g_indexeddb){var e={rows:{item:function(a){return this[a]},
length:0}},k=c.transaction("LastPassPreferences","readonly").objectStore("LastPassPreferences").index("username_hash");k.openCursor(IDBKeyRange.only(fix_userhash(b))).onsuccess=function(a){(a=a.target.result)?(e.rows[e.rows.length]=a.value,e.rows.length++,a["continue"]()):b!=fix_userhash("")?k.openCursor(IDBKeyRange.only(fix_userhash(""))).onsuccess=function(a){(a=a.target.result)?(e.rows[e.rows.length]=a.value,e.rows.length++,a["continue"]()):d(null,e)}:d(null,e)}}else c.transaction(function(a){a.executeSql("SELECT * FROM LastPassPreferences where username_hash=? or username_hash=?",
[b,""],d,function(a,b){console_log(b)})})}else a&&a()}
function setup_default_hotkeys(){g_is_mac?(lpPutGblPref("generateHkKeyCode",0),lpPutGblPref("generateHkMods",""),lpPutGblPref("recheckHkKeyCode",0),lpPutGblPref("recheckHkMods",""),lpPutGblPref("searchHkKeyCode",0),lpPutGblPref("searchHkMods",""),lpPutGblPref("nextHkKeyCode",33),lpPutGblPref("nextHkMods","meta"),lpPutGblPref("prevHkKeyCode",34),lpPutGblPref("prevHkMods","meta"),lpPutGblPref("homeHkKeyCode",0),lpPutGblPref("homeHkMods",""),lpPutGblPref("openpopoverHkKeyCode",220),lpPutGblPref("openpopoverHkMods",
"meta")):(lpPutGblPref("generateHkKeyCode",71),lpPutGblPref("generateHkMods","alt"),lpPutGblPref("recheckHkKeyCode",73),lpPutGblPref("recheckHkMods","alt"),lpPutGblPref("searchHkKeyCode",87),lpPutGblPref("searchHkMods","alt"),lpPutGblPref("nextHkKeyCode",33),lpPutGblPref("nextHkMods","alt"),lpPutGblPref("prevHkKeyCode",34),lpPutGblPref("prevHkMods","alt"),lpPutGblPref("homeHkKeyCode",72),lpPutGblPref("homeHkMods","control alt"),lpPutGblPref("openpopoverHkKeyCode",220),lpPutGblPref("openpopoverHkMods",
"alt"));lpPutGblPref("submitHkKeyCode",0);lpPutGblPref("submitHkMods","");lpPutGblPref("saveallHkKeyCode",0);lpPutGblPref("saveallHkMods","");lpPutGblPref("logoffHkKeyCode",0);lpPutGblPref("logoffHkMods","");lpPutGblPref("defaultffidHkKeyCode",0);lpPutGblPref("defaultffidHkMods","");lpWriteAllPrefs()}
function lpWriteAllPrefs(){var a=g_isfirefoxsdk,b=opendb();createPrefsTable(b);if(b)if(g_indexeddb){b=b.transaction("LastPassPreferences","readwrite").objectStore("LastPassPreferences");if(null!=g_username_hash&&""!=g_username_hash)for(var c in g_userprefs_changed)b.put({username_hash:fix_userhash(g_username_hash),prefname:c,prefvalue:g_userprefs[c],userkey:g_username_hash+"_"+c});g_userprefs_changed={};for(c in g_gblprefs_changed)b.put({username_hash:fix_userhash(""),prefname:c,prefvalue:g_gblprefs[c],
userkey:"_"+c});g_gblprefs_changed={}}else b.transaction(function(b){var c="",d="",f=[],h=0;a&&(c="REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES ");if(null!=g_username_hash&&""!=g_username_hash)for(var g in g_userprefs_changed)a?(c+=d+"(?, ?, ?)",d=", ",f.push(g_username_hash),f.push(g),f.push(g_userprefs[g]),h++):b.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",[g_username_hash,g,g_userprefs[g]],function(a,b){},function(a,
b){console_log(b)});g_userprefs_changed={};for(g in g_gblprefs_changed)a?(c+=d+"(?, ?, ?)",d=", ",f.push(""),f.push(g),f.push(g_gblprefs[g]),h++):b.executeSql("REPLACE INTO LastPassPreferences (username_hash, prefname, prefvalue) VALUES (?, ?, ?)",["",g,g_gblprefs[g]],function(a,b){},function(a,b){console_log(b)});g_gblprefs_changed={};a&&0<h&&b.executeSql(c,f,function(a,b){},function(a,b){console_log(b)})});start_idle_checker()}optionsData={HotKeys:{}};
function capturehk(a,b){var c;c=""+(b.ctrlKey?"control":"");c+=b.metaKey?(""!=c?" ":"")+"meta":"";c+=b.altKey?(""!=c?" ":"")+"alt":"";c+=b.shiftKey?(""!=c?" ":"")+"shift":"";if(""==c||"shift"==c)c=getBG().g_is_mac?"meta":"alt";if(8==b.keyCode||127==b.keyCode||46==b.keyCode)optionsData.HotKeys[a+"KeyCode"]=0;else{if(32>=b.keyCode||91==b.keyCode)return;optionsData.HotKeys[a+"KeyCode"]=0!=b.keyCode?b.keyCode:b.charCode}optionsData.HotKeys[a+"Mods"]=c;writeHotKeyValue(a)}
function writeHotKeyValue(a){var b=optionsData.HotKeys[a+"KeyCode"],c=document.getElementById(a),d="";if(0!=b){a=optionsData.HotKeys[a+"Mods"];"string"!=typeof a&&(a="");a=a.split(" ");for(var e in a)"control"==a[e]&&(d+=gs("Ctrl")+"+"),"meta"==a[e]&&(d+=gs("Meta")+"+"),"alt"==a[e]&&(d+=gs("Alt")+"+"),"shift"==a[e]&&(d+=gs("Shift")+"+")}if(0!=b){b=parseInt(b);switch(b){case 33:d+=gs("Page Up");break;case 34:d+=gs("Page Down");break;case 35:d+=gs("End");break;case 36:d+=gs("Home");break;case 37:d+=
gs("Left");break;case 38:d+=gs("Up");break;case 39:d+=gs("Right");break;case 40:d+=gs("Down");break;case 189:d+="-";break;case 219:d+="[";break;case 220:d+="\\";break;case 221:d+="]";break;case 186:d+=";";break;case 222:d+="'";break;case 188:d+=",";break;case 187:d+="+";break;case 190:d+=".";break;case 191:d+="/";break;case 106:d+="*";break;case 192:d+="~";break;case 124:d+=gs("Print Screen");break;default:d+=String.fromCharCode(b).toUpperCase()}c.value=d}else c.value=""}
function fixhk(a,b){32>optionsData.HotKeys[a+"KeyCode"]&&(optionsData.HotKeys[a+"Mods"]="",writeHotKeyValue(a));b.cancelBubble=!0;b.stopPropagation()}var last_idle_check=0,idle_checker_started=!1;
function start_idle_checker(){if(0==last_idle_check&&!idle_checker_started){var a=parseInt(lpGetPref("idleLogoffVal",0));lpdbg("idle","starting idle checker, idleLogoffVal is "+lpGetPref("idleLogoffVal",0));0<a&&(last_idle_check=lp_get_gmt_timestamp(),idle_checker_started=!0,setTimeout(function(){idle_checker()},1E4))}}var last_active_time=0,enable_native_idle=!0;
function idle_checker(){var a=parseInt(lpGetPref("idleLogoffVal",0));lpdbg("idle","checking idle, idleLogoffVal is "+lpGetPref("idleLogoffVal",0));if(0<a){var b=60*a,c=function(c){var d=!1,e=lp_get_gmt_timestamp();"active"==c?last_active_time=lp_get_gmt_timestamp():"locked"==c?d=b<e-last_active_time:"idle"==c&&(d=!0);var h=!0;0!=last_idle_check&&0!=b&&(d||b<e-last_idle_check)&&(console_log("IDLE CHECKER ISSUING LOGOFF: idleLogoffVal="+a+" isidle="+d+" limit="+b+" currtime="+e+" last_idle_check="+
last_idle_check+" state="+c+" last_active_time="+last_active_time),lplogoff_if(),h=!1);h&&(last_idle_check=e)},d=function(a){a?call_binary_function("get_idle_ms",function(a){a=parseInt(a/1E3);c(b<a?"idle":"active")}):enable_native_idle&&"undefined"!=typeof chrome&&"undefined"!=typeof chrome.idle&&chrome.idle.queryState(b,c)};have_binary_function("get_idle_ms")?can_check_idle(d):d(!1)}setTimeout(function(){idle_checker()},1E4)}var g_can_check_idle=-1;
function can_check_idle(a){-1!=g_can_check_idle?a(g_can_check_idle?!0:!1):g_is_linux&&have_binary_function("can_check_idle")?call_binary_function("can_check_idle",function(b){g_can_check_idle=b?1:0;a(g_can_check_idle?!0:!1)}):(g_can_check_idle=1,a(!0))};
