LPServer.sharing=LPServer.sharing||{};
LPServer.sharing.individual=function(){var z=function(){var e={noemailspecified:function(a,c){c.error(LPServer.ext.translate("Please enter at least one email and try again."))},usernameisnotvalidemail:function(a,c){var g=LPServer.getRecordsFromResponse(a,"email",LPServer.getAttrInt(a,"numinvalid",0));c.error(LPServer.ext.translate("The following emails are invalid: %1",g.join(", ")))},toomanyemails:function(a,c){var g=LPServer.getAttrInt(a,"numexcess");"1"===g?c.error(LPServer.ext.translate("You are trying to share with too many people.  Please remove at least %1 email and try again.",
g)):c.error(LPServer.ext.translate("You are trying to share with too many people.  Please remove at least %1 emails and try again.",g))},cantsharewithself:function(a,c){c.error(LPServer.ext.translate("You can not share with yourself."))}},d=function(a,c,g){this.email=a;this.pubkey=c;this.encpass=g},m=function(a,c){this.aid=a.getAttribute("aid");this.username=LPServer.ext.decrypt(a.getAttribute("username"),c);this.password=LPServer.ext.decrypt(a.getAttribute("password"),c);this.name=LPServer.ext.decrypt(a.getAttribute("name"),
c);this.grouping=LPServer.ext.decrypt(a.getAttribute("grouping"),c);this.extra=LPServer.ext.decrypt(a.getAttribute("extra"),c);this.attachkey=LPServer.ext.decrypt(a.getAttribute("attachkey"),c);this.afids=this.parseFields(a.getAttribute("afids"),c);this.otherafids=this.parseFields(a.getAttribute("otherafids"),c);this.accts_notes=this.parseFields(a.getAttribute("accts_notes"),c);this.accts_usernames=this.parseFields(a.getAttribute("accts_usernames"),c);this.accts_passwords=this.parseFields(a.getAttribute("accts_passwords"),
c);this.template=a.getAttribute("template")};m.prototype.parseFields=function(a,c){var g=[];if(a){a=a.split("^");for(var b=0,d=a.length;b<d;++b){var f=a[b];""!==f&&(f=a[b].split("&"),g.push({name:f[0],value:LPServer.ext.decrypt(f[1],c)}))}}return g};m.prototype.encrypt=function(){var a=function(a,c){return a?LPServer.ext.encryptCBC(a,c):""},c=function(c,b){for(var g=JSON.parse(JSON.stringify(c)),f=0,d=g.length;f<d;++f)g[f].value=a(g[f].value,b);return g};return function(g){return{username:a(this.username,
g),password:a(this.password,g),name:a(this.name,g),grouping:a(this.grouping,g),extra:a(this.extra,g),attachkey:a(this.attachkey,g),afids:c(this.afids,g),otherafids:c(this.otherafids,g),accts_notes:c(this.accts_notes,g),accts_usernames:c(this.accts_usernames,g),accts_passwords:c(this.accts_passwords,g)}}}();var b=function(a,c,g,b){for(var d=0,f=g.length;d<f;++d)a[c+b+d+"name"]=g[d].name,a[c+b+d+"value"]=g[d].value;a[c+"num"+b]=g.length},h=function(a,c){var b=LPServer.getAttrInt(a,"numemails",0);1===
b?c.success(LPServer.ext.translate("Share sent to %1.",LPServer.getAttr(a,"email0",""))):c.success(LPServer.ext.translate("Share sent to %1 recipients.",b))},v=function(a,c){for(var b=[],d=0,h=a.length;d<h;++d){var f=a[d];f&&b.push({email:f,reason:c})}return b},l=function(a,c){var g=LPServer.getAttrInt(a,"numsharesok",0);if(0<g){for(var e=[],p=0;p<g;++p){var f=LPServer.getAttr(a,"emailok"+p,""),n=LPServer.getAttr(a,"emailokpubkeyhex"+p,""),k=LPServer.getAttr(a,"emailencp"+p,"");e.push(new d(f,n,k))}for(var f=
c.params.key,p=[],n=LPServer.getNodes(a,"encdata"),k=0,l=n.length;k<l;++k)p.push(new m(n[k],f));f={cmd:"share",sharemessage:"",giveshare:c.params.giveshare?1:0,numemails:e.length,numaids:p.length,fromrole:0,sharesyncpush:0,shareautopull:0,reportname:[]};n=0;for(k=e.length;n<k;++n){var t=e[n],l=LPServer.ext.createRandomHexString(64),l=LPServer.ext.hex2bin(l),w=new LPServer.ext.RSAKey;LPServer.ext.parsePublicKey(w,t.pubkey);var u=w.encrypt(l),w="email"+n;f[w]=t.email;f["sharekeyenchex"+n]=u;f["sharekeyenchexsig"+
n]="";t.encpass&&(f["encpass"+n]=t.encpass);for(t=0;t<p.length;++t){var u=p[t],r=u.encrypt(l);1==c.params.logname&&f.reportname.push({aid:u.aid,name:u.name});var q=w+"aid"+t;f[q]=u.aid;f[q+"username"]=r.username;f[q+"password"]=r.password;f[q+"name"]=r.name;f[q+"grouping"]=r.grouping;f[q+"extra"]=r.extra;f[q+"attachkey"]=r.attachkey;f[q+"template"]=u.template;b(f,q,r.afids,"afid");b(f,q,r.otherafids,"otherafid");b(f,q,r.accts_notes,"accts_notes");b(f,q,r.accts_usernames,"accts_usernames");b(f,q,r.accts_passwords,
"accts_passwords")}}LPServer.xmlRequest({url:"showshare.php",data:f,callbacks:{shareok:h},userSupplied:c})}e=LPServer.getAttrInt(a,"numsharesdne",0);0<e&&c.callbacks&&c.callbacks.invite&&c.callbacks.invite({emails:LPServer.getRecordsFromResponse(a,"emaildne",e)});k=LPServer.getAttr(a,"sharingwithself","");e=LPServer.getAttrInt(a,"numsharesinv",0);p=LPServer.getAttrInt(a,"numsharesuns",0);f=LPServer.getAttrInt(a,"numsharesspa",0);n=LPServer.getAttrInt(a,"numsharesres",0);(k||0<e||0<p||0<f||0<n)&&c.callbacks&&
c.callbacks.problems&&(k=v([k],LPServer.ext.translate("You can not share with yourself.")),k=k.concat(v(LPServer.getRecordsFromResponse(a,"emailinv",e),LPServer.ext.translate("Invalid email address."))),k=k.concat(v(LPServer.getRecordsFromResponse(a,"emailuns",p),LPServer.ext.translate("The user must login to LastPass at least once to permit sharing."))),k=k.concat(v(LPServer.getRecordsFromResponse(a,"emailspa",f),LPServer.ext.translate("The user does not want to receive emails from LastPass."))),
k=k.concat(v(LPServer.getRecordsFromResponse(a,"emailres",n),LPServer.ext.translate("Sharing is restricted by a LastPass Enterprise policy."))),c.callbacks.problems(k));0===g&&c.error()};return function(a){a.callbacks=LPServer.extend(a.callbacks,e);for(var b={cmd:"getclientdata",shareeusername:a.params.emails,numaids:a.params.aids.length},d=0,h=a.params.aids.length;d<h;++d)b["aid"+d]=a.params.aids[d];LPServer.xmlRequest({url:"showshare.php",data:b,callbacks:{getclientdataack:l},userSupplied:a})}}(),
A=function(){var e=function(d,e){e.success(LPServer.ext.translate("Share revoked from %1",e.params.email))};return function(d){LPServer.xmlRequest({url:"showshare.php",data:{cmd:"unshare",aid:d.params.id,username:d.params.email},callbacks:{unshareok:e},userSupplied:d})}}(),B=function(){var e=function(b,d){d.success(LPServer.ext.translate("Share accepted."))},d=function(b,d,e){return(b=LPServer.ext.decrypt(b,d))?LPServer.ext.encryptCBC(b,e):""},m=function(b){var h=b.params.key,m=b.params.pendingShareKey,
l=b.params.pendingShare,a={cmd:"acceptshare",msgtosharer:"",aid:l.id,newgroup:LPServer.ext.encryptCBC(b.params.group,h),name:d(l.sharename,m,h),grouping:d(l.sharegroup,m,h),username:d(l.username,m,h),password:d(l.password,m,h),extra:d(l.extra,m,h),attachkey:d(l.attachkey,m,h)};a.newname=b.params.name?LPServer.ext.encryptCBC(b.params.name,h):a.name;var c=l.save_all?"otherafid":"afid",g;for(g in l.shareafids){var x=l.shareafids[g];x&&(x=d(x,m,h));a[c+g]=x}LPServer.xmlRequest({url:"showacceptshare.php",
data:a,callbacks:{acceptshareok:e},userSupplied:b})};return function(b){b.params.pendingShare?m(b):b.params.id&&y(LPServer.extend({},b,{params:{id:b.params.id},success:function(d){b.params.pendingShare=d.pendingShare;var e=new LPServer.ext.RSAKey;LPServer.ext.parsePrivateKey(e,LPServer.ext.extractPrivateKey(d.privateKey,b.params.key));b.params.pendingShareKey=e.decrypt(b.params.pendingShare.sharekeyenchex);m(b)}}))}}(),C=function(){var e=function(d,e){e.success(LPServer.ext.translate("Share rejected."))};
return function(d){LPServer.xmlRequest({url:"showacceptshare.php",data:{cmd:"rejectshare",aid:d.params.id},callbacks:{rejectshareok:e},userSupplied:d})}}(),D=function(){var e=function(d,e){if(e.callbacks&&e.callbacks.problems){var b=[],h=LPServer.getAttrInt(d,"numalready",0);0<h&&(h=LPServer.getRecordsFromResponse(d,"emailalready",h).join(", "),b.push(LPServer.ext.translate("You have already invited the following friends: %1. Please send them a reminder using your personal email as the email invitation sent by LastPass might not have reached them.",
h)));h=LPServer.getAttrInt(d,"numspam",0);0<h&&(h=LPServer.getRecordsFromResponse(d,"emailspam",h).join(", "),b.push(LPServer.ext.translate("The following friends have marked your invitations as spam: %1.",h)));0<b.length&&e.callbacks.problems(b)}b=LPServer.getAttrInt(d,"numsent",0);1===b?e.success(LPServer.ext.translate("%1 was invited. We will send you a notification email when they join LastPass so you can retry sharing your data with them.",LPServer.getAttr(d,"emailsent0",""))):1<b?e.success(LPServer.ext.translate("%1 friends were invited. We will send you a notification email when any of them join LastPass so you can retry sharing your data with them.",
b)):e.error()};return function(d){for(var m={cmd:"invite",numemails:d.params.emails.length},b=0,h=d.params.emails.length;b<h;++b)m["email"+b]=d.params.emails[b];LPServer.xmlRequest({url:"showshare.php",data:m,callbacks:{inviteack:e},userSupplied:d})}}(),y=function(e){LPServer.jsonRequest({url:"getReceivedShareInfo.php",data:e.params&&e.params.id?{aid:e.params.id}:null,userSupplied:e})};return{shareItems:z,unshareItem:A,acceptShare:B,rejectShare:C,inviteFriends:D,getSentShareData:function(e){LPServer.jsonRequest({url:"getSentShareInfo.php",
data:e.params&&e.params.id?{aid:e.params.id}:null,userSupplied:e})},getReceivedShareData:y}}();
