var SettingsDialog=function(e,c){c=void 0===c?{}:c;c.closeButtonEnabled=!0;c.additionalHeaderClasses=void 0===c.additionalHeaderClasses?[]:c.additionalHeaderClasses;c.additionalHeaderClasses.push("leftIcon");Dialog.call(this,e,c)};SettingsDialog.prototype=Object.create(Dialog.prototype);SettingsDialog.prototype.constructor=SettingsDialog;
(function(e){var c={},d={},b=null,a=null,h=function(p){return function(k){a!==k.target&&(b.menu.hide(),b.content.hide(),a.removeAttribute("class"),b=c[p],a=k.target,b.menu.show(),b.content.show(),a.setAttribute("class","selected"))}},q=function(a){return function(c){b.content!==a&&(b.content.hide(),b.menuItem.removeAttribute("class"),b.content=a,b.menuItem=c.target,b.content.show(),b.menuItem.setAttribute("class","selected"))}};SettingsDialog.prototype.setup=function(a,b,c){Dialog.prototype.setup.apply(this,
arguments);for(var f=d.paymentHistory.children[0].children[0],k=f.children[0].nextElementSibling;k;){var e=k.nextElementSibling;f.removeChild(k);k=e}b.addPaymentHistoryRows(f)};var r=function(){for(var a=e.getElementById("settingsContent"),b=0,c=a.children.length;b<c;++b){var f=a.children[b];d[f.getAttribute("settingGroup")]=f}},t=function(){for(var a=e.getElementById("settingsLeftMenu"),b=0,n=a.children.length;b<n;++b){var f=a.children[b],g={};g.menu=$(f);for(var m=0;m<f.children.length;++m){var l=
f.children[m],h=$(d[l.getAttribute("settingGroup")]);0===m&&(l.setAttribute("class","selected"),g.menuItem=l,g.content=h);LPPlatform.addEventListener(l,"click",q(h))}c[f.getAttribute("settingGroup")]=g}},u=function(e){e=e.children[0].children[1];for(var d=0,n=e.children.length;d<n;++d){var f=e.children[d],g=f.getAttribute("settingGroup");0===d&&(b=c[g],b.menu.show(),b.content.show(),a=f,a.setAttribute("class","selected"));LPPlatform.addEventListener(f,"click",h(g))}};SettingsDialog.prototype.initialize=
function(a){Dialog.prototype.initialize.apply(this,arguments);$("table").each(function(){for(var a=$(this).find("tr"),b=0,c=a.length;b<c;++b)0!==b%2&&a[b].setAttribute("class","odd")});a.children[0].appendChild(a.children[1].children[0]);r();t();u(a)};SettingsDialog.prototype.initializeDataBindings=function(a){a=e.getElementById("settingsContent");for(var b=0,c=a.children.length;b<c;++b){var d=$(a.children[b]),g=d.attr("settingGroup"),d=d.find("["+this.DIALOG_FIELD+"]"),h=new DialogInput.NestedFields;
this._inputFields[g]=h;for(g=0;g<d.length;++g){var l=d[g];h[l.getAttribute(this.DIALOG_FIELD)]=new DialogInput.Input(l)}}}})(document);var PaymentHistory=function(e){this.data=e};
PaymentHistory.prototype.template=function(){var e=[],c;for(c in this.data){var d=this.data[c],b=document.createElement("tr"),a=document.createElement("td");a.textContent=d.timecreated;b.appendChild(a);a=document.createElement("td");a.textContent=d.product;b.appendChild(a);a=document.createElement("td");a.textContent=d.paymentprovider;b.appendChild(a);a=document.createElement("td");a.textContent=d.orderid;b.appendChild(a);a=document.createElement("td");a.textContent=d.unitcost;b.appendChild(a);a=
document.createElement("td");a.textContent=d.quantity;b.appendChild(a);a=document.createElement("td");a.textContent=d.duration;b.appendChild(a);a=document.createElement("td");a.textContent="$"+d.unitcost*d.quantity+" "+d.currency;b.appendChild(a);a=document.createElement("td");a.textContent="Refund";b.appendChild(a);e.push(b)}return e};var AccountSettings=function(e){this.data=e;void 0!==this.data.paymentHistory&&(this.data.paymentHistory=new PaymentHistory(this.data.paymentHistory))};
AccountSettings.prototype.getFormData=function(){var e={},c;for(c in this.data){var d=this.data[c],b={},a;for(a in d){var h=d[a];b[a]=null!==h&&"object"===typeof h?h.value:h}e[c]=b}return e};var appendChildren=function(e,c){for(var d=0,b=c.length;d<b;++d)e.appendChild(c[d])};AccountSettings.prototype.addPaymentHistoryRows=function(e){var c=document.createElement("tbody");appendChildren(c,this.data.paymentHistory.template());appendChildren(e,c.children)};
AccountSettingsService=function(e){var c=LPProxy.getBaseURL()+"getAccountSettings.php";return{call:function(d,b){e.ajax({url:c,success:function(a){a=new AccountSettings(JSON.parse(a));d(a)},error:b})}}}($);
