var SharedFolderDialog=function(k){Dialog.call(this,k,{additionalHeaderClasses:["icon"],closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.folder=this.existingUsers=null};SharedFolderDialog.prototype=Object.create(Dialog.prototype);SharedFolderDialog.prototype.constructor=SharedFolderDialog;
(function(k){SharedFolderDialog.prototype.initialize=function(a){Dialog.prototype.initialize.apply(this,arguments);(function(a){var c=document.getElementById("sharedFolderDialogUserTypeahead");LPProxy.isEnterpriseUser()?(c=new BloodhoundDropdown(c,{identify:function(a){return"group"===a.type?a.cgid:a.uid},remote:{url:LPProxy.getBaseURL()+"typeahead_remote.php?grp=1&q=%QUERY",wildcard:"%QUERY"}},{optionLabel:function(a){var b=a.name;"companyuser"===a.type?""===b?b=a.email:""!==a.email&&(b+=" ("+a.email+
")"):b+=" ("+Strings.Vault.USER_GROUP+")";return b},ignore:function(d,b){return a.existingUsers[d]||void 0===b.type&&!LPFeatures.allowShareOutsideEnterprise()}}),c.onChange(function(d,b){d=$.extend({},d);var c=SharedFolderUser;"group"===d.type&&(d.uid=d.cgid,delete d.cgid,c=SharedFolderUserGroup);d.username=d.email;delete d.email;c=new c(d,a.folder);c._pending=!0;a.addNewUser(c);a.existingUsers[b]=!0}),a.inputFields.friends=c):a.inputFields.friends=c=new TypeaheadDropdown(c);c.autocomplete=function(c){var b=
c.target.value;if(null===this.hint&&b){for(var b=a.parseFriendsInput(b),d=0,e=b.length;d<e;++d)a.addNewUser(b[d]);c.preventDefault()}TypeaheadDropdown.prototype.autocomplete.apply(this,arguments)};Topics.get(Topics.REMOVED_SHARED_FOLDER_USER).subscribe(function(c){delete a.existingUsers[c.getID()];a.showHideInviteInput()});$("#sharedFolderDialogInviteButton").bind("click",function(){a.submit()})})(this)};SharedFolderDialog.prototype.parseFriendsInput=function(a){var e=[];a=a.split(",");for(var c=
0,d=a.length;c<d;++c){var b=a[c].trim(),f;-1<b.indexOf("@")?(b=b.match(Constants.EmailAddressRegularExpression))&&1===b.length&&(f=new SharedFolderUser({username:b[0]},this.folder)):b&&(f=new SharedFolderUserGroup({name:b},this.folder));f&&(f._pending=!0,f.setEditable(!0),e.push(f))}return e};SharedFolderDialog.prototype.validate=function(a){var e=Dialog.prototype.validate.apply(this,arguments);a.friends&&0===this.parseFriendsInput(a.friends).length&&(this.addError("friends","You must enter a valid email or group name."),
e=!1);return e};SharedFolderDialog.prototype.defaultFields=function(a){a.defaultData=$.extend({readonly:!0,hidePasswords:!0},a.defaultData);Dialog.prototype.defaultFields.call(this,a)};SharedFolderDialog.prototype.addNewUser=function(a){this.containers.newMembers||(this.containers.newMembers=new Container([],{additionalItemClasses:"dialogItem"}),this.containers.newMembers.initialize(document.getElementById("sharedFolderDialogNewUsersContainer")));this.containers.newMembers.addChild(a);this.inputFields.friends.clear();
this.inputFields.friends.focus()};SharedFolderDialog.prototype.setup=function(a,e){Dialog.prototype.setup.apply(this,arguments);this.containers.existingMembers&&(this.containers.existingMembers.initialize(k.getElementById("folderMembers")),this.showHideInviteInput())};SharedFolderDialog.prototype.showHideInviteInput=function(){LPProxy.isEnterpriseUser()||(5<this.containers.existingMembers.getItemChildren().length?($("#sharedFolderMaxMembers").show(),$("#sharedFolderDialogInvites").hide()):($("#sharedFolderMaxMembers").hide(),
$("#sharedFolderDialogInvites").show()))};SharedFolderDialog.prototype.open=function(a){this.folder=a;(function(e){LPRequest.makeDataRequest(LPProxy.getSharedFolderMembers,{params:{shareid:a.getID()},success:function(c){for(var d=[],b=0,f=c.users.length;b<f;++b)d.push(new SharedFolderUser(c.users[b],a));b=0;for(f=c.groups.length;b<f;++b)d.push(new SharedFolderUserGroup(c.groups[b],a));e.containers.existingMembers=new Container(d);e.existingUsers={};b=0;for(f=d.length;b<f;++b)e.existingUsers[d[b].getID()]=
!0;Dialog.prototype.open.call(e,{title:Strings.translateString("Manage Shared Folder")+": "+e.folder.getShareGroupName()})},error:function(){Topics.get(Topics.DIALOG_LOADED).publish()}})})(this)};SharedFolderDialog.prototype.getInvitedMembers=function(){var a=this.containers.newMembers?this.containers.newMembers.getItems():[];return a=a.concat(this.parseFriendsInput(this.inputFields.friends.getValue()))};SharedFolderDialog.prototype.getData=function(){var a=Dialog.prototype.getData.apply(this,arguments);
a.newMembers={};a.updatedPermissions=[];var e=this.getInvitedMembers();if(0<e.length)for(var c=0,d=e.length;c<d;++c){var b=e[c];a.newMembers[b.getUsername()]={uid:b.getID(),type:b.getType()}}else for(e=this.containers.existingMembers.getItemChildren(),c=0,d=e.length;c<d;++c)b=e[c],b.isModified()&&a.updatedPermissions.push({uid:b.getID(!0),give:b.getCheckboxValue("give"),readonly:b.getCheckboxValue("readonly"),canadminister:LPProxy.isEnterpriseUser()?b.getCheckboxValue("can_administer"):"0"});return a};
SharedFolderDialog.prototype.handleSubmit=function(a){var e=$.extend(a,{sharedFolder:this.folder._data,shareInfo:this.folder._shareInfo});LPTools.hasProperties(a.newMembers)?LPRequest.makeRequest(LPProxy.addSharedFolderMembers,{params:e,requestSuccessOptions:{closeDialog:!1},success:this.createDynamicHandler(function(c){for(var d=[],b=this.getInvitedMembers(),e=0,h=b.length;e<h;++e){var g=b[e];c[g.getUsername()]&&(g._pending=!1,g._data.readonly=a.readonly?"1":"0",g._data.give=a.hidePasswords?"0":
"1",g._data.can_administer=a.can_administer?"1":"0",g.rebuild(),d.push(g));g._parent&&g._parent.removeChild(g)}this.containers.existingMembers.addChild(d);this.showHideInviteInput();this.inputFields.friends.clear()})}):0<a.updatedPermissions.length?LPRequest.makeRequest(LPProxy.updateSharedFolderMemberPermissions,{params:e,success:this.createHandler(function(){for(var c=this.containers.existingMembers.getItemChildren(),d={},b=0,e=c.length;b<e;++b){var h=c[b];d[h.getID(!0)]=h}b=0;for(e=a.updatedPermissions.length;b<
e;++b)c=a.updatedPermissions[b],d[c.uid].updatePermissions(c)})}):this.close()}})(document);
