var data=null,existing=null,origusername=null,origpassword=null,attachnum=0,attaches=[],removedattach=[],g_eye_show=!0,g_eyeimgid=null,g_start_time=null,POLL_MAXTIME=3E5,g_pwlen=0,pass=!0,g_sharedfromaid=!1,g_pw_field_ids=[],ENABLE_ONLY=!0,g_do_keyaccel=!0,KEY_S=83,event_handlers={};
function fix_event_handlers(){lpdbg("site","fixing event handlers");for(var a in event_handlers){lpdbg("site","setting event handler for "+a);var c=document.getElementById("fields").contentWindow.document.getElementById(a);c?(c.onclick=event_handlers[a],lpdbg("site","set event handler for "+a)):lpdbg("site","could not find "+a)}}
function onLoad(a){clearData();if(a){var c=getBG(),f;c.g_site_data&&(f=c.g_site_data.aid);if("undefined"==typeof f)data=c.g_site_data;else{data=c.g_site_data;var b=!1;"undefined"!==typeof c.g_site_data.save_all&&1==c.g_site_data.save_all&&(b=!0);a=get_record(f);for(var k in a)data[k]=a[k]}c.g_generatedpw&&(document.getElementById("pwprotect").style.visibility="hidden",document.getElementById("pwprotectlabel").style.visibility="hidden");(existing=data&&"undefined"!=typeof get_record_id(data)&&get_record_id(data)&&
""!=get_record_id(data)&&"0"!=get_record_id(data))&&!c.LPISLOC&&c.g_showhistorylinks&&(document.getElementById("usernamehistory").style.display="inline",document.getElementById("passwordhistory").style.display="inline");if(data){a=issharedfolder(c.g_shares,data.group);var e=0==a?c.g_local_key:a.sharekey;"http://sn"==data.url&&c.loglogin(get_record_id(data));a=!1;if(is_application(data)){document.getElementById("usernamehistory").style.display="none";document.getElementById("passwordhistory").style.display=
"none";set_innertext(document.getElementById("urltext"),gs("Application:"));document.getElementById("url").value=data.appname;var d=0,h=0,g;for(g in data.fields)if(data.fields.hasOwnProperty(g))if(""==data.fields[g].type){if(1<++d)break}else if("password"==data.fields[g].type&&1<++h)break;if(1!=d||1!=h)a=!0}else d=AES._utf8_decode(data.url),!existing&&0<=d.indexOf("homelocal")||(document.getElementById("url").value=d);event_handlers={};data.editfields?(document.title=is_application(data)?gs("Edit Application Fields"):
gs("Edit Site Fields"),document.getElementById("siteactions").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("namegrouprow").style.display="none",document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("notesrow1").style.display="none",document.getElementById("notesrow2").style.display="none",document.getElementById("advsettingswrap").style.display="none",document.getElementById("cpwfieldbtn").style.display="none",
document.getElementById("fieldsrow2").style.display="block",document.getElementById("fields").contentWindow.document.body.appendChild(getFieldsHTMLNodes(e))):data.save_all||a?(document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("fieldsrow1").style.display="block",document.getElementById("fieldsrow2").style.display="block",existing?(document.title=is_application(data)?gs("Edit Application"):gs("Edit Site"),document.getElementById("fields").contentWindow.document.body.appendChild(getFieldsHTMLNodes(e))):
(document.title=gs("Add Site"),document.getElementById("fields").contentWindow.document.body.appendChild(getDataHTML()))):data.sn?(document.title=existing?gs("Edit Secure Note"):gs("Add Secure Note"),document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("urlrow").style.display="none",document.getElementById("addrow").style.display="block",showadvpane()):existing?(is_application(data)?(document.title=gs("Edit Application"),document.getElementById("username").value=
getusernamefromacct(data),document.getElementById("password").value=getpasswordfromacct(data),origusername=c.lpmenc(document.getElementById("username").value,!0,e),origpassword=c.lpmenc(document.getElementById("password").value,!0,e)):(document.title=gs("Edit Site"),document.getElementById("username").value=data.unencryptedUsername,g_pwlen=(a=c.lpmdec(data.password,!0,e))?a.length:-1,g_pwlen=""==data.password?0:g_pwlen,document.getElementById("password").value=a,origusername=data.username,origpassword=
data.password),document.getElementById("editfields").style.display="inline"):(document.title=gs("Add Site"),document.getElementById("username").value=data.username,document.getElementById("password").value=data.password,disable_CPWButton());fix_event_handlers();document.getElementById("exnotehist").style.display=existing?"block":"none";existing||"undefined"==typeof data.addsite||-1!=AES._utf8_decode(data.url).indexOf("homelocal")||(document.getElementById("group").value=get_default_group(data.url),
document.getElementById("name").value=c.getname_url(data.url));existing?(document.getElementById("name").value=data.name,document.getElementById("group").value=data.group,a=c.lpmdec(data.extra,!0,e),document.getElementById("notes").value=a,document.getElementById("fav").checked="1"==data.fav,document.getElementById("pwprotect").checked=data.pwprotect,document.getElementById("autologin").checked=data.autologin&&"0"!=data.autologin,is_application(data)?document.getElementById("never_autofill_td").style.visibility=
"hidden":document.getElementById("never_autofill").checked=data.never_autofill):data.sn&&(document.getElementById("group").value=gs("Secure Notes"));1==data.sn&&(document.getElementById("favcheck").style.display="none",document.getElementById("never_autofill_td").style.display="none",document.getElementById("autologingrp").style.visibility="hidden")}existing&&!data.editfields?(document.getElementById("del").style.display="inline-block",a=get_record(get_record_id(data)),document.getElementById("share").style.display=
c.LPISLOC||a.genpw||"undefined"!=typeof a.sharedfromaid&&null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid||"undefined"!=typeof a.sharefolderid||is_application(a)||!c.g_sharing_enabled?"none":"inline-block"):(document.getElementById("del").style.display="none",document.getElementById("share").style.display="none");a=[];for(f in c.g_sites)c.check_ident_aid(f)&&(d=c.g_sites[f].group,""==d||lp_in_array(d,a)||(a[a.length]=d));for(f in c.g_securenotes)c.check_ident_aid(f)&&
(d=c.g_securenotes[f].group,""==d||lp_in_array(d,a)||(a[a.length]=d));for(f in c.g_applications)c.check_ident_appaid(f)&&(d=c.g_applications[f].group,""==d||lp_in_array(d,a)||(a[a.length]=d));a.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});existing||(""==document.getElementById("url").value?document.getElementById("url").focus():document.getElementById("name").focus());if(!existing&&data&&!data.save_all&&!data.noreplace){d=c.getsites(lp_gettld_url(data.url),!0);f=[];for(g in d)f[f.length]=
g;f.sort(function(a,b){return c.g_sites[a].name.toLowerCase()<c.g_sites[b].name.toLowerCase()?-1:1});d=document.getElementById("replaceexistingsiteaid");for(g=0;g<f.length;g++)h=c.g_sites[f[g]].name,typeof c.g_sites[f[g]].useusername&&""!=c.g_sites[f[g]].useusername&&(h+=" ("+c.g_sites[f[g]].useusername+")"),d.options[d.options.length]=new Option(h,f[g]);if(1<d.options.length)for(g=1;4>=g;g++)document.getElementById("addreplacerow"+g).style.display="block"}LP_decimate_children(document.getElementById("metercontainer"));
document.getElementById("metercontainer").appendChild(ghetto_meter(280,!0,document));stylize_ghetto_meter(document,280);update_password_meter("",document.getElementById("password").value);data&&data.last_pwchange_gmt&&pw_age_update(data.last_pwchange_gmt);show_cpw_button(data);my_aid=get_record_id(data);buildSecureNotes(existing);onResize();create_combo("group",a,!0,document,"","group",-22,5);setup_eye_events(document);(getBG().g_is_win||getBG().g_is_mac||getBG().g_is_linux)&&setTimeout(function(){decryptThumbnails(e)},
0);document.getElementById("advsettings").addEventListener("click",showadvpane);document.getElementById("lp_docwrite_site14a").addEventListener("click",showadvpane);document.getElementById("fav").addEventListener("change",echoFavorite);echoFavorite();null!==document.getElementById("name")&&null!==document.getElementById("notestype")&&(document.getElementById("name").addEventListener("keyup",function(){setTimeout(updateFormHeading,100)}),updateFormHeading());data&&data.openchpw&&show_cpw_dialog("new");
data=c.g_site_data;for(k in c.g_site_data)data[k]=c.g_site_data[k];b&&(data.save_all=!0);c.g_site_data=null}else get_data("site",function(){onLoad(!0)})}
function updateFormHeading(){""!=document.getElementById("notestype").value?set_innertext(document.getElementById("dynheader"),document.getElementById("name").value+" - "+document.getElementById("notestype").value+(1==data.sn?" "+gs("Secure Note"):"")):(document.getElementById("dynheader").style.display="none",document.getElementById("dynbody").style.backgroundColor="transparent")}
function showadvpane(){var a=document.getElementById("advsettings"),c=document.getElementById("checkboxrow1");a.classList.toggle("turn90");c.classList.toggle("displaynone")}
function echoFavorite(){document.getElementById("fav").checked?(document.getElementById("echo_favorite").src="images/favorite.png",set_innertext(document.getElementById("lp_docwrite_site15"),gs("Remove Favorite")),set_innertext(document.getElementById("lp_docwrite_site34"),gs("Remove Site from Favorites"))):(document.getElementById("echo_favorite").src="images/not_favorite.png",set_innertext(document.getElementById("lp_docwrite_site15"),gs("Make Favorite")),set_innertext(document.getElementById("lp_docwrite_site34"),
gs("Add Site to Favorites")))}function decryptThumbnails(a){if("undefined"!=typeof data&&null!==data&&1==data.sn&&(document.getElementById("lpaddattach").style.display="block","undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)){getBG();num_attachments=data.attaches.length;for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&(addThumbnail(data.attaches[c].id,data.attaches[c].mimetype,data.attaches[c].bytes,data.attaches[c].filename,data.attachkey,a),num_attachments--)}}
function buildSecureNotes(a){0==issharedfolder(getBG().g_shares,data.group).give&&(g_sharedfromaid=1);if("undefined"!=typeof data&&null!==data&&"undefined"!=typeof data.sn&&1==data.sn){document.getElementById("notesrow0").style.display="block";document.getElementById("notesrow1").style.display="none";document.getElementById("notehistory").style.display=a?"inline-block":"none";document.getElementById("group").style.width="auto";document.getElementById("group").spellcheck=!1;var c=document.getElementById("notestype").val,
f=[],b;for(b in sntemplates){var k="undefined"!=typeof sntemplateicons[b]?sntemplateicons[b]:geticonurl("sn");f[f.length]={label:gs(b),image:k,value:b}}a||(create_combo("notestype",f,!0,document,"","notestype",-22,5),document.getElementById("notestype").addEventListener("click",function(){openCombo(null,"notestype","notestype_combo",document)}));a&&(c=getNoteValue("NoteType",document.getElementById("notes").value));c&&"undefined"!=typeof sntemplates[c]||(c="Generic");init_attachment_action_menu();
document.getElementById("autologingrp").setAttribute("colspan","0");a=document.getElementById("pwaginggrp");null!=a&&a.setAttribute("colspan","2");buildForm(c);onResize()}else document.getElementById("attachtabletr").style.width="0px"}function disable_CPWButton(){document.getElementById("cpwbtnmini").classList.add("btn_disabled");document.getElementById("cpwfieldbtn")&&document.getElementById("cpwfieldbtn").classList.add("btn_disabled")}
function disable_SaveButton(){document.getElementById("save").classList.add("btn_disabled")}function enable_SaveButton(){document.getElementById("save").classList.remove("btn_disabled")}function update_SaveButton(a){var c=document,f=c.getElementById("save");c&&f&&(check_for_changes()?0<=f.className.indexOf("btn_disabled")&&enable_SaveButton():a!=ENABLE_ONLY&&-1==f.className.indexOf("btn_disabled")&&disable_SaveButton())}
function buildForm(a){var c=document.getElementById("notestype");c.value=gs(a);c.val=a;var f="undefined"!=typeof sntemplateicons[a]?sntemplateicons[a]:geticonurl("sn");c.style.background="url("+f+") no-repeat 2px 2px"+(existing?" rgb(238,238,238)":" rgb(249,249,249)");document.getElementById("notesrow2").style.display="Generic"==a?"block":"none";document.getElementById("notesrow3").style.display="Generic"==a?"none":"block";document.getElementById("notestype").disabled=existing?!0:!1;if("Generic"!=
a){for(c=document.getElementById("dynamicnotes");c.hasChildNodes()&&0<c.childNodes.length;)c.removeChild(c.firstChild);f=sntemplates[a];a=document.createElement("table");a.style.width="100%";a.style.borderSpacing="0px";for(var b in f){var k=document.createElement("tr"),e=document.createElement("td");e.style.whiteSpace="nowrap";var d=document.createElement("td");d.style.width="100%";var h=document.createTextNode(gsproper(b)+":");e.appendChild(h);var g=h=null;if("text"==f[b])h=document.createElement("input"),
h.type="text",h.spellcheck=!1,h.id="note_"+b,h.style.width="100%",h.style.fontFamily="Courier",existing&&(h.value=getNoteValue(b,document.getElementById("notes").value),"Private Key"==b&&(g=document.createElement("a"),set_innertext(g," Copy Key"),g.style.textDecoration="none",g.style.cursor="pointer",g.style.height="15px",g.style.align="right",-1==h.value.indexOf("-----BEGIN")&&-1==h.value.indexOf("END-----")?g.onclick=function(){var a=document.getElementById("note_Private Key").value;getBG().copytoclipboard(a)}:
g.onclick=function(){var a=document.getElementById("note_Private Key");pkelparse=a.value.split(/-----BEGIN.*KEY----- | -----END.*KEY-----/);pkelarmor=a.value.split(/-----/);var a="",b;for(b in pkelparse[1])a=":"!=pkelparse[1].charAt(b-1)?a+pkelparse[1][b].replace(/\u0020/g,"\n"):a+pkelparse[1][b];pktotal="-----"+pkelarmor[1]+"-----\n"+a+"\n-----"+pkelarmor[3]+"-----";getBG().copytoclipboard(pktotal);return!1})),"Password"==b&&(h.type="password",g=document.createElement("img"),g.id="note_eye_img",
g.src="images/eye-shown.png",g.style.textDecoration="none",g.style.position="relative",g.style.top="6px",g.style.left="-22px",g.onclick=function(){if(g_sharedfromaid)return alert(gs("This is a shared site. You are not permitted to view the password.")),!1;var a=document.getElementById("note_Password");-1!==document.getElementById("note_eye_img").src.indexOf("images/eye-shown.png")?document.getElementById("note_eye_img").src="images/eye-hidden.png":document.getElementById("note_eye_img").src="images/eye-shown.png";
a.type="password"==a.type?"text":"password"});else if("date"==f[b]||"datemoyr"==f[b]){h=document.createElement("span");h.style.width="100%";var n=document.createElement("select");n.id="note_"+b+"_mo";n.style.width="auto";var l="January February March April May June July August September October November December".split(" "),m;for(m in l)n.options[n.options.length]=new Option(gs(l[m]),l[m]);var r=null;if(existing&&((r=getNoteValue(b,document.getElementById("notes").value))&&(r=r.split(",")),r&&0<r.length))for(var q in l)if(l[q]==
r[0]||gs(l[q])==r[0]){n.value=l[q];break}h.appendChild(n);if("date"==f[b]){n=document.createElement("select");n.id="note_"+b+"_day";for(m=1;31>=m;m++)n.options[n.options.length]=new Option(m,m);r&&1<r.length&&(n.value=r[1]);h.appendChild(n)}n=document.createElement("input");n.type="text";n.maxLength=4;n.size=4;n.spellcheck=!1;n.id="note_"+b+"_yr";l="date"==f[b]?2:1;r&&r.length>l&&(n.value=r[l]);h.appendChild(n)}else if("textarea"==f[b])e.style.verticalAlign="top",h=document.createElement("textarea"),
h.cols=30,h.spellcheck=!1,h.rows=7,h.id="note_"+b,h.style.width="100%",h.style.fontFamily="Courier",existing&&(h.value=getNoteValue(b,document.getElementById("notes").value,!0));else continue;d.appendChild(h);null!==g&&d.appendChild(g);k.appendChild(e);k.appendChild(d);a.appendChild(k)}b=document.createElement("fieldset");b.appendChild(a);c.appendChild(b);updateFormHeading()}}function onResize(){}
function fix_addreplace(){document.getElementById("addnewsite").checked?(document.getElementById("url").disabled=!1,document.getElementById("name").disabled=!1,document.getElementById("group").disabled=!1,document.getElementById("username").disabled=!1,document.getElementById("password").disabled=!1,document.getElementById("notes").disabled=!1,document.getElementById("fav").disabled=!1,document.getElementById("never_autofill").disabled=!1,document.getElementById("pwprotect").disabled=!1,document.getElementById("autologin").disabled=
!1,document.getElementById("replaceexistingsiteaid").disabled=!0):document.getElementById("replaceexistingsite").checked&&(document.getElementById("url").disabled=!0,document.getElementById("name").disabled=!0,document.getElementById("group").disabled=!0,document.getElementById("username").disabled=!0,document.getElementById("password").disabled=!0,document.getElementById("notes").disabled=!0,document.getElementById("fav").disabled=!0,document.getElementById("never_autofill").disabled=!0,document.getElementById("pwprotect").disabled=
!0,document.getElementById("autologin").disabled=!0,document.getElementById("replaceexistingsiteaid").disabled=!1)}
function getSecureNoteFromFields(){if("undefined"!=typeof data&&data&&1==data.sn){var a=document.getElementById("notestype").val;if("Generic"==a||"none"==document.getElementById("notesrow0").style.display)return document.getElementById("notes").value;var c="NoteType:"+a+"\n",f;for(f in sntemplates[a])"text"==sntemplates[a][f]?c+=f+":"+document.getElementById("note_"+f).value+"\n":"date"==sntemplates[a][f]||"datemoyr"==sntemplates[a][f]?(c+=f+":"+document.getElementById("note_"+f+"_mo").value,"date"==
sntemplates[a][f]&&(c+=","+document.getElementById("note_"+f+"_day").value),c+=","+document.getElementById("note_"+f+"_yr").value+"\n"):"textarea"==sntemplates[a][f]&&(c+=f+":"+document.getElementById("note_"+f).value+"\n");return c}return document.getElementById("notes").value}function get_decrypted_attachdata(a){for(var c in g_encatt)if("undefined"!=typeof g_encatt[c].id&&g_encatt[c].id==a)return g_encatt[c].data;return""}
function dosave(a,c){var f=document.getElementById("replaceexistingsite").checked;if(f&&0==document.getElementById("replaceexistingsiteaid").selectedIndex)alert(gs("Please Make a Selection"));else{var b=getBG();if(b.lploggedin)if(data.editfields){var k=issharedfolder(b.g_shares,data.group);if(checkreadonly(k)){var e=0==k?b.g_local_key:k.sharekey;if(is_application(data)){var d=get_record(get_record_id(data));d.last_touch=lp_get_gmt_timestamp();for(var h in d.fields){var g=d.fields[h],n=document.getElementById("fields").contentWindow.document.getElementById(g.htmlid);
n&&(g.value=b.lpmenc(n.value,!0,e))}var l="appaid="+b.en(d.appaid);for(h in d.fields)g=d.fields[h],l+="&fieldid"+h+"="+b.en(g.id)+"&fieldtype"+h+"="+b.en(g.type)+"&fieldvalue"+h+"="+b.en(crypto_btoa(g.value));l+=0==k?"":"&sharedfolderid="+b.en(k.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(l,d)}else checkFieldsForUpdates(e);getBG().close_editfieldsopener();setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}}else{var m=punycode.URLToASCII(trim(document.getElementById("url").value)),n=document.getElementById("name").value,l=document.getElementById("group").value,r=document.getElementById("username").value,d=document.getElementById("password").value,q=getSecureNoteFromFields(),u=document.getElementById("fav").checked,y=document.getElementById("never_autofill").checked,t=document.getElementById("pwprotect").checked,A=document.getElementById("autologin").checked;if(0<g_pwlen&&0==d.length||-1==g_pwlen&&
0==d.length)if(e=gs("Are you sure you want to save an empty password?"),!confirm(e))return;k=issharedfolder(b.g_shares,l);if(!1===k&&0==l.toLowerCase().indexOf("shared-"))alert(gs("Sorry - group names starting with 'Shared-' are created by LastPass to indicate groups shared with other people. Please use a different name."));else if(checkreadonly(k)){var z=!1;if(existing&&l!=data.group){if(z=issharedfolder(b.g_shares,data.group),!checkmove(k,z))return}else existing&&(z=k);e=existing?0==z?b.g_local_key:
z.sharekey:0==k?b.g_local_key:k.sharekey;f&&(A=b.g_sites[document.getElementById("replaceexistingsiteaid").value],n=A.name,l=A.group,k=issharedfolder(b.g_shares,l),e=0==k?b.g_local_key:k.sharekey,q=b.lpmdec(A.extra,!0,e),u="1"==A.fav,y=A.never_autofill,t=A.pwprotect,A=A.autologin);if(""==n)alert(gs("You must enter a name."));else{if(45E3<q.length)if(confirm(gs("The notes field contains too much data.  You may store a maximum of 45,000 characters per note.\n\nWould you like us to truncate the note for you?  You will lose some of your data.")))q=
q.substring(0,45E3);else return;var B=!1;if(existing&&l!=data.group&&(k||z)){var p=[get_record_id(data)],v=[];v[get_record_id(data)]=l;B=!0;if(!b.moveIntoSharedFolder(k,z,p,v,!1,!0))return}if(existing&&is_application(data)){d=get_record(get_record_id(data));d.last_touch=lp_get_gmt_timestamp();m=getusernamefromacct(d);f=getpasswordfromacct(d);for(h in d.fields)if(g=d.fields[h],n=document.getElementById("fieldsrow2"),"none"!=window.getComputedStyle(n).display){if(n=document.getElementById("fields").contentWindow.document.getElementById(g.htmlid))g.value=
b.lpmenc(n.value,!0,e)}else""==g.type&&b.lpmdec_acct(g.value,!0,d,b.g_shares)==m?g.value=b.lpmenc(document.getElementById("username").value,!0,e):"password"==g.type&&b.lpmdec_acct(g.value,!0,d,b.g_shares)==f&&(g.value=b.lpmenc(document.getElementById("password").value,!0,e));d.name=document.getElementById("name").value;d.group=document.getElementById("group").value;d.appname=document.getElementById("url").value;g=getSecureNoteFromFields();g!=b.lpmdec(d.extra,!0,e)&&(d.extra=lpmenc(g,!0,e));d.fav=
document.getElementById("fav").checked?"1":"0";d.pwprotect=document.getElementById("pwprotect").checked;d.autologin=document.getElementById("autologin").checked?"1":"0";var w=d.group;k&&(d.sharefolderid=k.id,w=w.substr(k.decsharename.length+1));if(l!=data.group&&(k||z))p=[get_record_id(data)],v=[],v[get_record_id(data)]=l,b.moveIntoSharedFolder(k,z,p,v,!1,!1,!0);else{l="ajax=1&extjs=1&cmd=updatelpaa&name="+b.en(b.lpenc(d.name,e))+"&grouping="+b.en(b.lpenc(w,e))+"&appname="+b.en(d.appname)+"&extra="+
b.en(crypto_btoa(d.extra))+"&appaid="+b.en(d.appaid);"1"==d.fav&&(l+="&fav=on");d.pwprotect&&(l+="&pwprotect=on");"1"==d.autologin&&(l+="&autologin=on");for(h in d.fields)g=d.fields[h],l+="&fieldid"+h+"="+b.en(g.id)+"&fieldtype"+h+"="+b.en(g.type)+"&fieldvalue"+h+"="+b.en(crypto_btoa(g.value));l+=0==k?"":"&sharedfolderid="+b.en(k.id);(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.increment_local_accts_version();b.rewritelocalfile();b.saveSite(l,d)}setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}else{p=existing?data.sn?b.g_securenotes[get_record_id(data)]:b.g_sites[get_record_id(data)]:b.createNewAcct();w=!1;for(h in attaches)attaches.hasOwnProperty(h)&&"undefined"!=typeof attaches[h]&&(w=!0);if(w&&!c){"undefined"==typeof p.attachkey||""==p.attachkey?(v=SHA256(lpCreatePass(32,1,1,1,1,1,1,1)),g_attachkey=b.lpenc(v,e)):g_attachkey=p.attachkey;var v=AES.hex2bin(b.lpdec(g_attachkey,e)),x=[];for(h in attaches)attaches.hasOwnProperty(h)&&"undefined"!=typeof attaches[h]&&(attaches[h].filename=
lpenc(attaches[h].filename,v),x[x.length]={id:attaches[h].id,bytes:attaches[h].bytes});if(x.length){b.fastEncryptAttachments(v,x,function(a){g_encatt=a;dosave(null,!0)});return}}v=lp_gettld_url(AES._utf8_encode(m));if(existing&&!data.sn&&p.tld!=v&&!a&&b.g_prompts.view_pw_prompt)b.security_prompt(function(){dosave(1,c)});else{existing&&!p.sn&&b.fix_tlds(p.tld,v,get_record_id(data));p.genpw=!1;p.name=n;B||(p.group=l);"http://sn"==m?(p.url=m,p.sn=1):p.url=AES._utf8_encode(m);p.tld=v;p.unencryptedUsername=
r;r!=b.lpmdec(p.username,!0,e)&&(p.username=b.lpmenc(r,!0,e));d!=b.lpmdec(p.password,!0,e)&&(p.password=b.lpmenc(d,!0,e));q!=b.lpmdec(p.extra,!0,e)&&(p.extra=b.lpmenc(q,!0,e));p.fav=u?"1":"0";p.autologin=A;p.never_autofill=y;p.pwprotect=t;existing||(p.aid="0");0!=k&&(p.sharefolderid=k.id,0==k.give&&(p.sharedfromaid=1,g_sharedfromaid=!0));B="";x=[];if(w){if("undefined"==typeof p.attachkey||""==p.attachkey)p.attachkey=g_attachkey,B+="&attachkey="+b.en(p.attachkey);p.attachpresent="1";p.retrieveattach=
1;w=0;for(h in attaches)attaches.hasOwnProperty(h)&&"undefined"!=typeof attaches[h]&&(B+="&filename"+w+"="+b.en(attaches[h].filename),B+="&mimetype"+w+"="+b.en(attaches[h].mimetype),B+="&attachid"+w+"="+b.en(attaches[h].id),B+="&attachbytes"+w+"="+b.en(get_decrypted_attachdata(attaches[h].id)),"undefined"==typeof x.add&&(x.add=[]),x.add[x.add.length]=existing?{id:p.aid+"-"+attaches[h].id,mimetype:attaches[h].mimetype,parent:p.aid,filename:attaches[h].filename}:{id:attaches[h].id,mimetype:attaches[h].mimetype,
filename:attaches[h].filename},w++)}if(0<removedattach.length)for(p.retrieveattach=1,h=0;h<removedattach.length;h++)B+="&rmattach"+h+"="+b.en(removedattach[h]),"undefined"==typeof x.remove&&(x.remove=[]),x.remove[x.remove.length]=removedattach[h];w=l;k&&(w=l.substr(k.decsharename.length+1));if(existing){if(m!=data.url||n!=data.name||l!=data.group||r!=data.unencryptedUsername||d!=b.lpmdec(data.password,!0,e)||q!=b.lpmdec(data.extra,!0,e)||u!=("1"==data.fav)||y!=data.never_autofill||t!=data.pwprotect||
A!=data.autologin||0<attaches.length||0<removedattach.length){p.sn?b.g_securenotes[p.aid]=p:b.g_sites[p.aid]=p;for(h in p.fields)p.fields.hasOwnProperty(h)&&(f=p.fields[h],is_encrypted_field(f.type)&&null!=origpassword&&""!=origpassword&&null!=f.value&&""!=f.value&&b.lpmdec_acct(f.value,!0,p,b.g_shares)==b.lpmdec_acct(origpassword,!0,p,b.g_shares)&&"password"==f.type&&(f.value=p.password),!is_encrypted_field(f.type)||null==origusername||""==origusername||null==f.value||""==f.value||b.lpmdec_acct(f.value,
!0,p,b.g_shares)!=b.lpmdec_acct(origusername,!0,p,b.g_shares)||"text"!=f.type&&"email"!=f.type&&"tel"!=f.type&&"url"!=f.type||(f.value=p.username));if(l!=data.group&&(k||z)){p=[get_record_id(data)];v=[];v[get_record_id(data)]=l;b.moveIntoSharedFolder(k,z,p,v,!1,!1,!0);setTimeout(function(){getBG().closecurrenttab("site.html")},0);return}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_site(get_record_id(data));b.applyattacharraychanges(x);b.increment_local_accts_version();b.rewritelocalfile();
l="ajax=1&extjs=1&name="+b.en(b.lpenc(n,e))+"&url="+b.en(AES.url2hex(m))+"&grouping="+b.en(b.lpenc(w,e))+"&username="+b.en(crypto_btoa(p.username))+"&password="+b.en(crypto_btoa(p.password))+"&extra="+b.en(crypto_btoa(p.extra))+"&openid_url=&aid="+b.en(get_record_id(data))+"&basic_auth=0&isbookmark=0&localupdate=1";l=l+(t?"&pwprotect=on":"")+(y?"&never_autofill=on":"")+(A?"&autologin=on":"");l+=u?"&fav=on":"";l+=0==k?"":"&sharedfolderid="+b.en(k.id);"http://sn"==m&&"undefined"!==typeof b.g_loglogins&&
b.g_loglogins&&(l+="&n="+AES.url2hex(n));"http://sn"!=p.url&&"http://group"!=p.url&&8==(b.g_loglogins&8)&&(l+="&un="+en(AES.bin2hex(b.lpmdec_acct(origusername,!0,p,b.g_shares))));l+=B;p.attacharraychanges=x;p.newvalues=[];b.saveSite(l,p);k=b.getsites(v,!0);if(d!=b.lpmdec(data.password,!0,e)&&1<array_length(k)){h=b.lpmdec(data.password,!0,e);l=!1;z=","+get_record_id(data)+",";for(g in k)getpasswordfromacct(b.g_sites[g])==h&&get_record_id(data)!=g?l=!0:z+=","+g+",";l&&b.openLinkedSites(d,v,z)}}data.save_all&&
checkFieldsForUpdates(e)}else p.fields=[],h=[],l=updateAndEncryptData2(b,p.username,p.password,p.fields,p,h,e),l="name="+b.en(b.lpenc(n,e))+"&grouping="+b.en(b.lpenc(w,e))+"&data="+b.en(b.bin2hex(l))+"&extra="+b.en(b.lpenc(q,e))+(t?"&pwprotect=on":"")+(y?"&never_autofill=on":"")+(A?"&autologin=on":"")+(u?"&fav=on":""),l+="&extjs=1&localupdate=1",l+=0==k?"":"&sharedfolderid="+b.en(k.id),"undefined"!=typeof data.realm&&(p.realm_data=b.lpmenc(data.realm,!0,e),p.basic_auth="1",l+="&basic_auth=1&realm="+
b.en(b.lpenc(data.realm,e))),"http://sn"==m&&(e=getNoteValue("NoteType",q),p.notetype=e,l+=e&&""!=e?"&notetype="+b.en(e):""),f&&(l+="&replacing=1"),l+=B,data.save_all?(p.save_all=!0,l+="&ajax=1&aid=0&save_all=1&url="+b.en(AES.url2hex(m))+"&openid_url=&username=&password=",p.newvalues=h,b.saveAllSite(l,p)):"undefined"!=typeof data.formdata?(l+="&ref="+b.en(AES.url2hex(m)),f&&(l+="&aid="+b.en(document.getElementById("replaceexistingsiteaid").value)),"undefined"!=typeof data.createacct&&data.createacct&&
"undefined"!=typeof data.username_field&&(p.fields=[],l+="&createacct=1&username_field="+b.en(data.username_field)),p.newvalues=h,b.saveSiteFromSubmit(l,p)):(l+="&ajax=1&aid=0&url="+b.en(AES.url2hex(m))+"&openid_url=&username="+b.en(crypto_btoa(p.username))+"&password="+b.en(crypto_btoa(p.password)),p.newvalues=h,p.attacharraychanges=x,b.saveSite(l,p));setTimeout(function(){getBG().closecurrenttab("site.html")},0)}}}}}else console_log("Not logged in!")}}
function checkFieldsForUpdates(a){var c=getBG(),f=document.getElementById("fields").contentWindow.document,b=!1,k;for(k in data.fields){var e=data.fields[k];if(is_encrypted_field(e.type)){var d=f.getElementById(e.htmlid);if(d&&"undefined"!=typeof d.value&&c.lpmdec(e.value,!0,a)!=d.value){var b=!0,h=c.lpmenc(d.value,!0,a);""!=e.value&&""!=c.g_sites[get_record_id(data)].username&&e.value==c.g_sites[get_record_id(data)].username&&""!=d.value&&(c.g_sites[get_record_id(data)].username=h,c.g_sites[get_record_id(data)].unencryptedUsername=
d.value);""!=e.value&&""!=c.g_sites[get_record_id(data)].password&&e.value==c.g_sites[get_record_id(data)].password&&""!=d.value&&(c.g_sites[get_record_id(data)].password=h);e.value=h}}else"checkbox"==e.type||"radio"==e.type?(d=e.checked,h=f.getElementById(e.htmlid)&&f.getElementById(e.htmlid).checked,d!=h&&(b=!0,e.checked=h)):"select-one"==e.type&&e.faketype&&(d=f.getElementById(e.htmlid))&&"undefined"!=typeof d.value&&e.value!=d.value&&(b=!0,e.value=d.value)}if(b){if(g_issafari||g_isopera||g_ismaxthon||
g_isfirefoxsdk)c.update_site(get_record_id(data)),c.update_fields(get_record_id(data),data.fields);c.increment_local_accts_version();c.rewritelocalfile();a="update=1&aid="+c.en(get_record_id(data))+"&urid=0";b="";d=[];for(k in data.fields)if(e=data.fields[k],e.htmlid&&f.getElementById(e.htmlid))if(h=data.editfields&&""==e.formname?"_"+e.name:"_"+e.formname+"_"+e.name,is_encrypted_field(e.type)){var g=f.getElementById(e.htmlid).value;d.push(g);g=crypto_btoa(e.value);b+=h+"="+c.en(g)+"&"}else"checkbox"==
e.type?f.getElementById(e.htmlid).checked&&(b+=h+"="+c.en(e.value)+"&"):"select-one"==e.type&&e.faketype&&(g=f.getElementById(e.htmlid).value,b+=h+"="+c.en(g)+"&");b+="&auto=1";f=issharedfolder(c.g_shares,data.group);b+=0==f?"":"&sharedfolderid="+c.en(f.id);c.saveFields(a,b,{aid:data.aid,newvalues:d})}}
function updateAndEncryptData2(a,c,f,b,k,e,d){for(var h="",g="undefined"!=typeof data.formdata?data.formdata.split("\n"):[],n=!1,l=0,m=0,r=0;r<g.length;r++){var q=g[r],q=q.split("\t");if(4==q.length||5==q.length)"text"==q[3]||"email"==q[3]||"tel"==q[3]||"url"==q[3]?l++:"password"==q[3]&&m++}0!=l||2!=m||data.save_all||(n=!0);for(r=0;r<g.length;r++)if(q=g[r],q=q.split("\t"),4==q.length||5==q.length){var l=data.save_all?decodeURIComponent(q[0]):"0",m=decodeURIComponent(q[1]),u=decodeURIComponent(q[2]),
y=getBG().lpmenc(u,!0,d),q=q[3];if("text"==q||"password"==q||"hidden"==q||"textarea"==q||"email"==q||"tel"==q||"url"==q){if("email"==q&&u==data.username&&(y=c),"tel"==q&&u==data.username&&(y=c),"url"==q&&u==data.username&&(y=c),"text"==q&&u==data.username&&(y=c),"password"==q&&n?(y=c,n=!1):"password"==q&&u==data.password&&(y=f),u=lpmdec(y,!0,d),e&&e.push(u),h+=l+"\t"+a.en(m)+"\t"+a.en(crypto_btoa(y))+"\t"+a.en(q)+"\n","hidden"!=q){var t={};t.otherfield=data.save_all;t.name=m;t.type=q;t.value=y;t.checked=
!1;t.formname=data.save_all?l:"";t.urid="0";t.otherlogin="0";t.url="";b[b.length]=t}}else if("action"==q)h+=l+"\taction\t"+a.en(u)+"\taction\n",k.action=AES.url2hex(u);else if("method"==q)h+=l+"\tmethod\t"+a.en(u)+"\tmethod\n",k.method=u;else if(h+=l+"\t"+a.en(m)+"\t"+a.en(u)+"\t"+a.en(q)+"\n","checkbox"==q||"radio"==q||"select-one"==q)t={},t.otherfield=data.save_all,t.name=m,t.type=q,"checkbox"==q||"radio"==q?(t.checked="-1"==u.substring(u.length-2),t.value=u.substring(0,u.length-2)):t.value=u,t.formname=
data.save_all?l:"",t.urid="0",t.otherlogin="0",t.url="",b[b.length]=t}return h}
function getDataHTML(){var a=newelt("div"),c=newelt("link");c.type="text/css";c.href="general.css";a.appendChild(c);for(var c=data.formdata.split("\n"),f=0;f<c.length;f++){var b=c[f].split("\t");if(4==b.length||5==b.length){var k=data.save_all?decodeURIComponent(b[0]):"0",e=decodeURIComponent(b[1]),d=decodeURIComponent(b[2]),b=b[3],k=uniqid(k+"_"+e);if("text"==b||"password"==b||"email"==b||"tel"==b||"url"==b){var h=newelt("label");set_innertext(h,e);var g=newelt("input","",k);g.name=e;g.type=b;g.value=
d;a.appendChild(h);a.appendChild(g);"password"==b&&(event_handlers[k+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1},g_eyeimgid=k+"toggleimg",e=newelt("a","eye",k+"toggle"),d=newelt("img","",g_eyeimgid),d.alt=gs("[Show]"),d.src="images/eye-shown.png",e.appendChild(d),a.appendChild(e));a.appendChild(newelt("br"))}else if("textarea"==b)b=newelt("label"),set_innertext(b,e),k=newelt("textarea"),
k.readonly=!0,k.name=e,k.style.verticalAlign="top",set_innertext(k,d),a.appendChild(b),a.appendChild(k),a.appendChild(newelt("br"));else if("select-one"==b)b=newelt("select"),b.name=e,e=newelt("option"),e.value=d,set_innertext(e,d),b.appendChild(e),a.appendChild(b),a.appendChild(newelt("br"));else if("checkbox"==b||"radio"==b)if(checked="-1"==d.substring(d.length-2)?" checked":"","radio"!=b||""!=checked)d=d.substring(0,d.length-2),k=newelt("input"),k.type=b,k.value=d,k.disabled=!0,0<checked.length&&
(k.checked=!0),d=newelt("label"),set_innertext(d,e),a.appendChild(k),a.appendChild(d),a.appendChild(newelt("br"))}}return a}function showaddfield(){var a=getBG(),a=issharedfolder(a.g_shares,data.group);checkreadonly(a)&&(a=document.getElementById("fields").contentWindow.document,a.getElementById("addfield").style.display="block",a.getElementById("newname").focus())}
function doaddfield(){var a=getBG(),c=issharedfolder(a.g_shares,data.group);if(checkreadonly(c)){var f=document.getElementById("fields").contentWindow.document,b=f.getElementById("newname").value,k=f.getElementById("newtype").value,e=k;"select-one"==e&&(e="text");var d=f.getElementById("newformname")?f.getElementById("newformname").value:"";if(""==b)alert(gs("You must enter a name."));else{for(var h in data.fields)if(data.fields[h].name==b&&(data.editfields||data.fields[h].formname==d)){alert(gs("You must enter a unique name."));
return}var g=uniqid(d+"_"+b),n=newelt("div");if("text"==k||"password"==k||"select-one"==k||"email"==k||"tel"==k||"url"==k){var l=newelt("label");set_innertext(l,b);var m=newelt("input","",ofja(g));m.type=ofja(e);l.appendChild(m);n.appendChild(l);"password"==k&&(g_eyeimgid=g+"toggleimg",m=newelt("a","eye",ofja(g)),m.id=ofja(g)+"toggle",m.href="#",m.className="eye",l=newelt("img","",ofja(g_eyeimgid)),l.id=ofja(g_eyeimgid),l.alt=gs("[Show]"),m.appendChild(l),n.appendChild(m))}else"textarea"==k?(m=newelt("textarea",
"",ofja(g)),n.appendChild(m)):"checkbox"==k&&(m=newelt("input","",ofja(g)),l=newelt("label"),l["for"]=ofja(g),set_innertext(l,b),n.appendChild(m),n.appendChild(l));m=newelt("a","",ofja(g)+"delete");l=newelt("div","","");set_innertext(m,"[ - ]");m.href="#";set_innertext(l,b);m.appendChild(l);m=f.createElement("div");m.id=g+"_div";m.appendChild(n);f.body.appendChild(m);event_handlers={};"password"==k&&(event_handlers[g+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,
this.id.length-6)),this);return!1});event_handlers[g+"delete"]=function(){var a=this.id.substring(0,this.id.length-6)+"_div";parent.delete_field(a,this.children[0].value,"");return!1};lpdbg("site","1 added event handler for "+g+"delete");fix_event_handlers();m={};m.otherfield=!data.editfields;m.name=b;m.type=k;"select-one"==k&&(m.faketype=e);m.value="";m.formname=d;m.checked=!1;m.urid="0";m.otherlogin="0";m.url="";m.htmlid=g;e=0;for(h in data.fields)data.fields.hasOwnProperty(h)&&h>e&&(e=h);"string"==
typeof e&&(e=parseInt(e));0===data.fields.length?data.fields[0]=m:data.fields[e+1]=m;(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&a.update_fields(get_record_id(data),data.fields);a.increment_local_accts_version();a.rewritelocalfile();b="add=1&aid="+a.en(data.aid)+"&urid=0&name="+a.en(b)+"&type="+k;data.editfields||(b+="&formname="+a.en(d));b+="&auto=1";c=0==c?"":"sharedfolderid="+a.en(c.id);a.saveFields(b,c,{aid:data.aid});f.getElementById("newname").value="";f.getElementById("newtype").selectedIndex=
0;f.getElementById("newformname")&&(f.getElementById("newformname").value="");f.getElementById("addfield").style.display="none"}}}function newelt(a,c,f){a=document.createElement(a);c&&(a.className=c);f&&(a.id=f);return a}
function getFieldsHTMLNodes(a){var c=getBG(),f=document.createElement("div"),b=newelt("link","","");b.rel="stylesheet";b.src="general.css";b.type="text/css";f.appendChild(b);if(!is_application(data)){event_handlers.addfieldlink=function(){parent.showaddfield();return!1};event_handlers.doaddfield=function(){parent.doaddfield()};b=newelt("a","");b.href="#";b.id="addfieldlink";set_innertext(b,gs("Add Field"));f.appendChild(b);f.appendChild(document.createElement("br"));b=newelt("div","","addfield");
b.style.display="none";var k=newelt("label"),e=newelt("input","","newname");e.type="text";set_innertext(k,gs("Name:"));k.appendChild(e);b.appendChild(k);b.appendChild(newelt("br"));k=newelt("label");set_innertext(k,gs("Type:"));var e=newelt("select","","newtype"),d=newelt("option","","");d.value="text";set_innertext(d,gs("Text"));var h=newelt("option","","");h.value="password";set_innertext(h,gs("Password"));var g=newelt("option","","");g.value="select-one";set_innertext(g,gs("Select"));var n=newelt("option",
"","");n.value="checkbox";set_innertext(n,gs("Checkbox"));e.appendChild(d);e.appendChild(h);e.appendChild(g);e.appendChild(n);k.appendChild(e);b.appendChild(k);b.appendChild(newelt("br"));data.editfields||(d=newelt("label"),set_innertext(d,gs("Form Name:")),d.appendChild(newelt("input","","newformname")),b.appendChild(d));d=newelt("input","","doaddfield");d.type="button";d.value=gs("Add");b.appendChild(d);b.appendChild(newelt("br"));b.appendChild(newelt("br"));f.appendChild(b)}var b=[],l;for(l in data.fields){var m=
data.fields[l],d=m.formname,k=is_application(data)?l:m.name,e=g=m.value?m.value:"",n=m.type,h=k+"_"+n+"_"+g;if("undefined"==typeof b[h]){b[h]=!0;h=uniqid(d+"_"+k);m.htmlid=h;d=newelt("div");if(is_application(data)&&""==n||"text"==n||"password"==n||"email"==n||"tel"==n||"url"==n)e=crypto_btoa(g),g=c.lpmdec(g,!0,a),m=newelt("input","",ofja(h)),m.value=g,g=newelt("label"),set_innertext(g,k),g.appendChild(m),d.appendChild(g),"password"==n&&(event_handlers[h+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,
this.id.length-6)),this);return!1},g=newelt("a","",ofja(h)+"toggle"),g.href="#",n=newelt("span","",""),set_innertext(n,gs("[Show]")),g.appendChild(n),d.appendChild(g),m.type="password",g_pw_field_ids.push(h));else if("textarea"==n)e=crypto_btoa(g),g=c.lpmdec(g,!0,a),n=newelt("label"),set_innertext(n,k),m=document.createElement("textarea","",ofja(h)),set_innertext(m,g),n.appendChild(m),d.appendChild(n);else if("select-one"==n){n=newelt("label");set_innertext(n,k);var m=newelt("select","",ofja(h)),
r=newelt("option");r.value=g;set_innertext(r,g);m.appendChild(r);n.appendChild(m);d.appendChild(n)}else if("checkbox"==n||"radio"==n){g=m.checked?" checked":"";if("radio"==n&&""==g)continue;g=newelt("input","",ofja(h));g.type=ofja(n);g.checked=m.checked;d.appendChild(g);g=newelt("label");g["for"]=ofja(h);set_innertext(g,k);d.appendChild(g)}else continue;is_application(data)||(event_handlers[h+"delete"]=function(){var a=this.children,b=encodeURIComponent(get_innertext(a[0])),a=AES.hex2bin(get_innertext(a[1])),
c=this.id.substring(0,this.id.length-6)+"_div";parent.delete_field(c,b,a);return!1},lpdbg("site","2 added event handler for "+h+"delete"),g=newelt("a","",ofja(h)+"delete"),set_innertext(g,"[ - ]"),g.href="#",n=newelt("div","",ofja(h)+"value"),m=newelt("div","",ofja(h)+"origval"),n.style.display="none",set_innertext(n,k),m.style.display="none",set_innertext(m,AES.bin2hex(e)),d.appendChild(g),g.appendChild(n),g.appendChild(m));k=newelt("div","",ofja(h)+"_div");k.appendChild(d);f.appendChild(k)}}return f}
function delete_field(a,c,f){try{if(confirm(gs("Are you sure you would like to delete this field?"))){var b=getBG(),k=issharedfolder(b.g_shares,data.group);if(checkreadonly(k)){var e=document.getElementById("fields").contentWindow.document;if(e.getElementById(a)){e.getElementById(a).style.display="none";for(var d in data.fields)if(data.fields.hasOwnProperty(d)&&data.fields[d].name==c){var h=data.fields[d].value;is_encrypted_field(data.fields[d].type)&&(h=crypto_btoa(h));h==f&&("undefined"!=typeof data.fields.splice?
data.fields.splice(d,1):delete data.fields[d])}(g_issafari||g_isopera||g_ismaxthon||g_isfirefoxsdk)&&b.update_fields(get_record_id(data),data.fields);b.increment_local_accts_version();b.rewritelocalfile();var g="delete=1&aid="+b.en(get_record_id(data))+"&urid=0&name="+b.en(c)+"&value="+b.en(f),g=g+"&auto=1",n=0==k?"":"sharedfolderid="+b.en(k.id);b.saveFields(g,n,{aid:data.aid})}else alert("Sorry, deletion of the field failed. Please re-save the site.")}}}catch(l){console_log("caught exception in delete_field: "+
l.message)}}function dodel(){getBG().deleteAid(get_record_id(data),window,!1,!1,function(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)})}function doshare(){if(!check_for_changes()||confirm(gs("Are you sure you want to share this item?  Doing so will cause you to lose any changes you have made to this item!"))){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&share="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}
function docancel(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)}var HISTORY={USERNAME:0,PASSWORD:1,EXTRA:2};
function show_history(a){if(!check_for_changes()||confirm(gs("Are you sure you want to view history?  Doing so will cause you to lose any changes you have made to this item!"))){var c="";a==HISTORY.USERNAME?c="username":a==HISTORY.PASSWORD?c="password":a==HISTORY.EXTRA&&(c="note");a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&"+c+"history="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}var logged=!1;
function toggle_password(a,c,f){if("password"==a.type){if(existing){var b=getBG();if(null!=data.sharedfromaid&&""!=data.sharedfromaid&&"0"!=data.sharedfromaid&&"null"!=data.sharedfromaid){alert(gs("This is a shared site. You are not permitted to view the password."));return}if(b.g_prompts.view_pw_prompt){g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?b.security_prompt(function(b){a.type="text";c.children[0].children[0].src=get_eye_src(a.type,
"glow");c.children[0].children[0].setAttribute("alt",gs("[Hide]"));set_innertext(c.children[0].children[1],gs("Hide Password"))}):b.security_prompt(function(){a.type="text";set_innertext(c,gs("[Hide]"))});return}}existing&&!logged&&(b.loglogin(get_record_id(data)),logged=!0);a.type="text";g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type,"glow"),c.children[0].children[0].setAttribute("alt",gs("[Hide]")),
set_innertext(c.children[0].children[1],gs("Hide Password"))):set_innertext(c,gs("[Hide]"))}else a.type="password",g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(a.type),c.children[0].children[0].setAttribute("alt",gs("[Show]")),set_innertext(c.children[0].children[1],gs("Show Password"))):set_innertext(c,gs("[Show]"))}function gsproper(a){return gs(a+"proper")!=a+"proper"?gs(a+"proper"):gs(a)}
function check_for_changes(){var a=getBG(),c=document.getElementById("url").value,f=document.getElementById("name").value,b=document.getElementById("group").value,k=document.getElementById("username").value,e=document.getElementById("password").value,d=getSecureNoteFromFields(),h=document.getElementById("fav").checked,g=document.getElementById("never_autofill").checked,n=document.getElementById("pwprotect").checked,l=document.getElementById("autologin").checked,m=issharedfolder(a.g_shares,b),m=0==
m?a.g_local_key:m.sharekey;return is_application(data)?c!=data.appname||f!=data.name||b!=data.group||k!=getusernamefromacct(data)||e!=getpasswordfromacct(data)||d!=a.lpmdec(data.extra,!0,m)||h!=("1"==data.fav)||n!=data.pwprotect||l!=("1"==data.autologin):c!=data.url||f!=data.name||b!=data.group||k!=data.unencryptedUsername||e!=a.lpmdec(data.password,!0,m)||d!=a.lpmdec(data.extra,!0,m)||h!=("1"==data.fav)||g!=data.never_autofill||n!=data.pwprotect||l!=data.autologin}
function doeditfields(){var a=getBG();if(!check_for_changes()||confirm(is_application(data)?gs("LoseChangesApp"):gs("LoseChanges"))){a.g_site_data=[];for(var c in data)a.g_site_data[c]=data[c];a.g_site_data.editfields=1;a.set_editfieldsopener(window);a.openURL(getchromeurl("site.html"),null,a.g_site_data)}}function showattach(a){a.getAttribute("src_hidden")&&a.getAttribute("src_hidden").length?getBG().showImageAttach(a.getAttribute("src_hidden")):openattach(a)}
function openattach(a){var c=a.getAttribute("filename")?a.getAttribute("filename"):"";getBG().openAttach(get_record_id(data),a.getAttribute("attachid"),c)}function addattach(){getBG().have_binary()?getBG().addAttach(function(){getBG().g_ischrome&&addattachcb()}):confirm(gs("This feature requires the binary version of this browser extension.  Would you like to install it now?"))&&getBG().install_binary()}
function addThumbnail(a,c,f,b,k,e){var d=get_extension_from_mimetype(c),h=check_filename_badchars(d),g=null,g=h==FILENAME_FRAGMENT_VALID?"."+d:0==h.length||h==FILENAME_FRAGMENT_EMPTY?"":"."+gs(d);if(k&&e)try{var n=AES.hex2bin(lpdec(k,e));b=lpdec(b,n)}catch(m){b=""}if(null===b||""==b)b="attachment"+num_attachments+g;d=document.getElementById("attachtable");h=document.createElement("tr");g=document.createElement("td");g.id=a;g.style.height="28px";g.style.width="80%";g.style.background="url('images/paperclip.png') no-repeat 2px 2px #e6e6e6";
var l=document.createElement("span");l.style.fontWeight="bold";l.style.position="relative";l.style.left="32px";l.style.top="6px";l.style.cursor="pointer";l.appendChild(document.createTextNode(b));f&&""!=f&&0==c.indexOf("data:image")?(l.setAttribute("attachid",a),k?(getBG().fastDecryptAttachment(a,c,f,k,e,function(a){getBG().g_ischrome&&(a&&a.length?l.setAttribute("src_hidden",c+";base64,"+a):l.setAttribute("src_hidden",""))}),l.addEventListener("click",function(){attachment_action_menu(this,showattach)})):
(f&&f.length?l.setAttribute("src_hidden",c+";base64,"+f):l.setAttribute("src_hidden",""),getBG().have_binary()?l.addEventListener("click",function(){attachment_action_menu(this,showattach)}):l.addEventListener("click",function(){showattach(this)}))):(l.setAttribute("attachid",a),getBG().have_binary()?l.addEventListener("click",function(){attachment_action_menu(this,openattach)}):l.addEventListener("click",function(){openattach(this)}));f=document.createElement("span");f.className="attachx";f.setAttribute("attachid",
a);f.addEventListener("click",function(){rmattach(this)});set_innertext(f,"\u00a0\u00a0\u00a0\u00a0\u00a0");g.appendChild(l);g.appendChild(f);h.appendChild(g);d.insertBefore(h,d.firstChild);attachnum++}function createAttachId(){for(;;){var a=Math.floor(99999*Math.random()),c;for(c in data.attaches)if(data.attaches.hasOwnProperty(c)&&data.attaches[c].id==get_record_id(data)+"-"+a)break;for(c=0;c<attaches.length&&("undefined"==typeof attaches[c]||attaches[c].id!=a);c++);return a}}
function rmattach(a){a=a.getAttribute("attachid");if(confirm(gs("Are you sure you would like to remove this attachment?"))){if("undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&a==data.attaches[c].id&&(removedattach[removedattach.length]=a);delete attaches[a];delThumbnail(a)}}
function delThumbnail(a){for(var c=document.getElementById("attachtable"),f=0;f<c.children.length;f++){var b=c.children[f];if(b.children&&b.children.length&&b.children[0].id==a){c.removeChild(b);break}}}
function attachment_action_doSave(){if(null!=open_attach_target){var a=open_attach_target.getAttribute("filename")?open_attach_target.getAttribute("filename"):"";getBG().exportAttachment(get_record_id(data),open_attach_target.getAttribute("attachid"),a)}else alarm("error, trying to save an attachment that does not exist");close_attach_list()}
function clearData(){for(var a=document.getElementsByTagName("input"),c=0;c<a.length;c++)"button"!=a[c].type&&(a[c].value="");a=document.getElementsByTagName("textarea");for(c=0;c<a.length;c++)a[c].value=""}function uniqid(a){a||(a="");return"a"+SHA256(a+"_"+(new Date).getTime()+"_"+Math.floor(100*Math.random()))}function setup_eye_events(a){g_eye_show&&(a.getElementById("passwordtoggle"),a.getElementById("passwordtoggleimg").style.verticalAlign="bottom")}
function eye_over(a){if(null!=a&&null!=a.target){var c=document.getElementById("passwordtoggleimg"),f=document.getElementById("password");a.target==c&&(c.src=get_eye_src(f.type,"glow"))}}function eye_out(a){if(null!=a&&null!=a.target){var c=document.getElementById("passwordtoggleimg"),f=document.getElementById("password");a.target==c&&(c.src=get_eye_src(f.type))}}function get_eye_src(a,c){return"password"==a?"images/eye-shown.png":"images/eye-hidden.png"}var CPW_WAKETIME=97,my_aid=null;
function docpwbtn(a){var c=getBG(),f=document;if(!f||!c||!data)return!1;var b=data.aid;a=data.url;g_cpwbot&&a?"undefined"!=typeof c.dopwchange?(g_start_time=(new Date).getTime(),c.cpwbot_preinit(),g_cpw_progress_ctr=20,show_cpw_dialog("progress"),setTimeout(function(){insert_cpw_placeholder_msg(f,gs("LastPass is loading..."))},5003),setTimeout(function(){cpw_status_check()},CPW_WAKETIME),g_ischrome?get_selected_tab(null,function(a){c.dopwchange(b,!1,a)}):c.dopwchange(b,!1)):pass:pass;return!1}
function docpwdebug(a){var c=getBG();a=document;if(!a||!c||!data)return!1;if(g_cpwbot){if(document.getElementById("cpwmsgdiv"))return!1;c=a.createElement("div");c.style.height="200px";c.style.width="100%";c.style.overflow="auto";c.style.backgroundColor="blue";c.style.color="yellow";c.style.padding="3px";c.id="cpwmsgdiv";var f=a.getElementById("sitebody");f?f.appendChild(c):a.body.appendChild(c)}return!1}var g_cpw_progress_ctr=0,g_lastmsg="";
function cpw_status_check(){var a=getBG(),c=document;if(!c||!a||!data)return!1;var f=!1,b=!1,k=!1,e=!1,d=!1,h=!1;(c=c.getElementById("cpwmsgdiv"))&&(g_ischrome?set_innertext(c,a.cpwbot_get_user_debug_messages()):a.cpwbot_get_user_debug_messages());g_ischrome?(a=a.cpwbot_get_dialog_msg(),cpw_progress_update(a)):a.cpwbot_get_dialog_msg();a=get_current_state(!0);lpdbg("site","BG.current_state is "+a);switch(a){case "FAIL":b=f=!0;break;case "CAPTCHA":k=b=f=!0;break;case "DOCAPTCHA":e=!0;break;case "TIMEOUT":h=
b=f=!0;break;case "FAIL_PW_SAVED":d=b=f=!0;break;case "DONE":case "OK":f=!0;break;case 0:case null:f=!1}form_refresh();e?g_start_time=(new Date).getTime():(new Date).getTime()>g_start_time+POLL_MAXTIME&&(b=f=!0,lpdbg("site","max timeout"));f?(b?k?show_cpw_dialog("captcha"):h?show_cpw_dialog("timeout"):d?show_cpw_dialog("fail_pw_saved"):show_cpw_dialog("fail"):show_cpw_dialog("dismiss"),g_ischrome?setTimeout(function(){form_refresh()},3001):setTimeout(function(){get_data("siterefresh",function(){form_refresh()})},
3001)):setTimeout(function(){cpw_status_check()},CPW_WAKETIME)}
function form_refresh(){var a=getBG(),c=document;if(!(c&&a&&data&&a.lploggedin))return!1;var f=(new Date).getTime(),b=0;if(my_aid){var k=get_record(my_aid,!0);if(k){var e="";"undefined"!=typeof a.g_pending_pw_change&&(e=a.lpdec_acct(a.g_pending_pw_change[my_aid],k,a.g_shares));var d=getpasswordfromacct(k);if(k.save_all)for(c=document.getElementById("fields").contentWindow.document,b=0;b<g_pw_field_ids.length;b++){var h=c.getElementById(g_pw_field_ids[b]);if(h){var g=h.value;d&&h&&e&&e!=d&&(d==g||
e==g)&&(lpdbg("site","using pending pw instead of g_sites"),d=e);d&&h&&(g===d?console.warn("REFRESH: no change"):g&&d&&(h.value=d,lpdbg("site","REFRESH: reset password iframe field from "+(a.g_show_pw_in_logs?g:"REDACTED")+" to "+(a.g_show_pw_in_logs?d:"REDACTED"))));update_SaveButton()}}else h=c.getElementById("password"),g=h.value,d&&h&&e&&e!=d&&(d==g||e==g)&&(lpdbg("site","using pending pw instead of g_sites"),d=e,b=f/1E3),d&&h&&g!==d&&g&&d&&(h.value=d,lpdbg("site","REFRESH: reset password from "+
(a.g_show_pw_in_logs?g:"REDACTED")+" to "+(a.g_show_pw_in_logs?d:"REDACTED")),e=issharedfolder(a.g_shares,data.group),data.password=a.lpmenc(d,!0,0==e?a.g_local_key:e.sharekey),0<b?pw_age_update(b):pw_age_update(k.last_pwchange_gmt),update_password_meter("",c.getElementById("password").value),update_SaveButton())}}return!1}
function show_cpw_button(a){var c=getBG(),f=document;if(!f||!c||!a)return!1;var b=!1;!g_cpwbot&&"undefined"!=typeof c.g_cpwbot&&c.g_cpwbot&&(g_cpwbot=c.g_cpwbot);c=issharedfolder(c.g_shares,a.group);a&&(c?(checkreadonly(c,!0)?(b=!1,lpdbg("site","in shared folder, writable")):(b=!0,lpdbg("site","in shared folder, readonly")),"1"===c.associative&&lpdbg("site","entry is in linked account")):a.individualshare?null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?(lpdbg("site",
"individual share, readonly"),b=!0):(lpdbg("site","individual share, writable"),b=!1):b=!1);if(g_cpwbot&&a&&"1"==a.pwch&&!b)if(a.save_all)enable_cpw_field_btn(document);else{if(a=f.getElementById("cpwbtnmini"))a.addEventListener("click",function(a){document.getElementById("cpwbtnmini").classList.contains("btn_disabled")||show_cpw_dialog("new")}),a.style.fontSize="12px",a.style.display="inline-block";if(a=f.getElementById("pwspacer"))a.style.display="inline-block",a.style.width="50px"}else{if(a=f.getElementById("cpwbtnmini"))a.style.display=
"none";if(a=f.getElementById("pwspacer"))a.style.display="none";if(f=f.getElementById("cpwfieldbtn"))f.style.display="none"}}
function pw_age_update(a){var c=getBG(),f=document;if(!f||!c||!data)return!1;a=parseInt(a);c=(new Date).getTime();c=null===c?0:parseInt(c/1E3)-0;if(!a||"number"!=typeof a||!c||isNaN(a)||isNaN(c)||c<a){a="";if(c=f.getElementById("pwagelabel"))c.style.display="none";pass}else f.getElementById("pwagelabel"),a=c-a,60>a?a=a.toString()+" "+(1==a?gs("second"):gs("seconds")):3600>a?(a=parseInt(a/60),a=a.toString()+" "+(1==a?gs("minute"):gs("minutes"))):86400>a?(a=parseInt(a/3600),a=a.toString()+" "+(1==a?
gs("hour"):gs("hours"))):604800>a?(a=parseInt(a/86400),a=a.toString()+" "+(1==a?gs("day"):gs("days"))):2592E3>a?(a=parseInt(a/604800),a=a.toString()+" "+(1==a?gs("week"):gs("weeks"))):31536E3>a?(a=parseInt(a/2592E3),a=a.toString()+" "+(1==a?gs("month"):gs("months"))):(a=parseInt(a/31536E3),a=a.toString()+" "+(1==a?gs("year"):gs("years")));c=f.getElementById("pwagediv");c.style.fontStyle="italic";c&&(set_innertext(c,a),f.getElementById("pwagelabel").style.display="inline")}
function hide_cpw_dialog(){var a=getBG(),c=document;if(!c||!a||!data)return!1;c.getElementById("pwcontainer");var f=c.getElementById("cpwdialog");f&&(f.style.display="none");if(c=c.getElementById("modalbg"))c.style.display="none";"undefined"!=typeof a.cpwbot_halt&&(c=get_current_state(),"FAIL"!=c&&"CAPTCHA"!=c&&"DONE"!=c&&"OK"!=c&&"TIMEOUT"!=c&&0!=c&&null!==c&&a.cpwbot_halt());data&&data.openchpw&&a.close_cpw_tabs()}var event_flags=0,EV_CX=1,EV_OK=2,g_cpw_heard_from_bg=!1;
function append_text_with_b(a,c){var f=c.indexOf("<b>"),b=c.indexOf("</b>");a.appendChild(a.ownerDocument.createTextNode(c.substring(0,f)));var k=a.ownerDocument.createElement("b");set_innertext(k,c.substring(f+3,b));a.appendChild(k);a.appendChild(a.ownerDocument.createTextNode(c.substring(b+4)))}
function show_cpw_dialog(a,c,f,b,k){var e=getBG(),d=document;if(!d||!e||!data)return!1;d.getElementById("notesrow1");d.getElementById("pwcontainer");e=d.getElementById("modalbg");e.style.width=d.body.clientWidth;e.style.height=d.body.clientHeight;e.style.display="block";var h=d.getElementById("dlghdg"),e=d.getElementById("dlghtml");e.style.fontSize="12px";var g=d.getElementById("bcnd"),n=d.getElementById("bokd"),l=d.getElementById("bdis"),m=null;g&&0==(event_flags&EV_CX)&&(g.addEventListener("click",
function(a){hide_cpw_dialog()}),d.getElementById("dlgclose").addEventListener("click",function(a){hide_cpw_dialog()}),l.addEventListener("click",function(a){hide_cpw_dialog()}),event_flags|=EV_CX);n&&0==(event_flags&EV_OK)&&(n.addEventListener("click",function(a){docpwbtn(a);return!1}),event_flags|=EV_OK);set_innertext(g,gs("No, Thanks"));set_innertext(n,gs("Change Password Now"));set_innertext(l,gs("Dismiss"));set_innertext(h,sprintf(gs("%s Password One-Click Change"),"LastPass"));switch(a){case "new":g_cpw_heard_from_bg=
!1;LP_decimate_children(e);b=d.createElement("p");set_innertext(b,sprintf(gs("%s will now attempt to change your password to a strong, generated password that will be saved in your vault and known only to you."),"LastPass"));e.appendChild(b);e.appendChild(d.createElement("br"));b=d.createElement("p");append_text_with_b(b,sprintf(gs("In order to complete the process, %s will have to log in to %s and navigate through a number of windows quickly. It is normal to see windows flashing and changing quickly, and may take several moments. We'll let you know when you're all set!"),
"LastPass","<b>"+of(data.name)+"</b>"));e.appendChild(b);g.style.display="block";n.style.display="block";l.style.display="none";break;case "progress":LP_decimate_children(e);k=d.createElement("b");set_innertext(k,gs("Overall Progress:"));e.appendChild(k);e.appendChild(d.createElement("br"));k=d.createElement("div");k.className="progress_container";b=d.createElement("div");b.className="progress_bar";b.id="progress_bar";k.appendChild(b);e.appendChild(k);k=d.createElement("div");k.id="stepbystep";e.appendChild(k);
k=d.createElement("div");k.id="advanced";e.appendChild(k);d.getElementById("progress_bar").style.width="10%";g.style.display="none";n.style.display="none";l.style.display="none";break;case "update":d.getElementById("progress_bar").style.width=c+"%";f&&(e=d.createElement("p"),"DOCAPTCHA"==get_current_state()&&(e.className="boldred"),g=d.createTextNode(f),e.appendChild(g),d.getElementById("stepbystep").appendChild(e),g_cpw_heard_from_bg||(g_cpw_heard_from_bg=!0,(m=d.getElementById("cpw_placeholder_msg"))&&
m.parentNode.removeChild(m)));b&&(e=d.createElement("i"),g=d.createTextNode(gs("Complete!")),e.appendChild(g),(b=d.getElementById("stepbystep").lastChild)&&b.appendChild(e));k&&(e=d.createElement("p"),g=d.createTextNode(k),e.appendChild(g),d.getElementById("advanced").appendChild(e));break;case "dismiss":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");append_text_with_b(b,sprintf(gs("Congratulations! Your password for %s was updated, and is now saved in your LastPass vault. Your change will sync on every device."),
"<b>"+of(data.name)+"</b>"));e.appendChild(b);g.style.display="none";n.style.display="none";l.style.display="block";set_innertext(l,gs("OK"));break;case "fail":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");append_text_with_b(b,sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),"<b>"+of(data.name)+"</b>"));e.appendChild(b);g.style.display="none";n.style.display=
"none";l.style.display="block";break;case "captcha":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");set_innertext(b,gs("Unable to proceed, the website does not allow automated password change."));e.appendChild(b);g.style.display="none";n.style.display="none";l.style.display="block";break;case "timeout":LP_decimate_children(e);e.appendChild(d.createElement("br"));e.appendChild(d.createElement("br"));b=d.createElement("p");set_innertext(b,
gs("Timed out waiting for the page to load.  Retry?"));e.appendChild(b);g.style.display="none";n.style.display="none";l.style.display="block";break;case "fail_pw_saved":LP_decimate_children(e),e.appendChild(d.createElement("br")),e.appendChild(d.createElement("br")),b=d.createElement("p"),append_text_with_b(b,sprintf(gs("We're sorry. We were not able to change your password automatically for %s. Your password was not changed."),"<b>"+of(data.name)+"</b>")+gs("The random password that was generated has been saved to your vault.")),
e.appendChild(b),g.style.display="none",n.style.display="none",l.style.display="block"}k=d.getElementById("cpwdialog");k.style.display="block";k.style.height="250px";k.style.width="470px";k.style.left=(parseInt(d.body.clientWidth)-470)/2+"px";k.style.top=(parseInt(d.body.clientHeight)-470)/2+"px";g_ischrome||(g_cpwbot_pwchangestate="init_state_dingbats")}
function notehist(){var a=getBG();a.unlock_plug2web();a.openbaseurl("?ac=1&notehistory="+a.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}var g_cpwbot_pwchangestate=null;function cpw_progress_update(a){a&&a!=g_lastmsg&&(g_lastmsg=a,g_cpw_progress_ctr+=20,90<g_cpw_progress_ctr&&(g_cpw_progress_ctr=95),show_cpw_dialog("update",g_cpw_progress_ctr,a,!1,""))}
function get_current_state(a){if(g_ischrome)return getBG().cpwbot_getpwchangestate();var c=g_cpwbot_pwchangestate;a&&getBG().cpwbot_getpwchangestate();return c}
function enable_cpw_field_btn(a){var c=a.getElementById("cpwfieldbtn");c&&(c.addEventListener("click",function(c){a.getElementById("cpwfieldbtn").classList.contains("btn_disabled")||a.getElementById("cpwbtnmini").classList.contains("btn_disabled")||show_cpw_dialog("new")}),c.style.fontSize="12px",c.style.display="inline-block",c.style.marginTop="5px",c.style.marginBottom="5px")}
function accelerator_key_handler(a){if(!g_do_keyaccel)return!0;if(!a||!a.keyCode)return!1;var c=!0,f=!1;try{"undefined"!=typeof navigator&&"undefined"!=typeof navigator.platform&&0==navigator.platform.toLowerCase().indexOf("mac")&&(c=!1,f=!0)}catch(k){}var b=document;if(!b)return!1;switch(a.keyCode){case KEY_S:if(a.ctrlKey&&f||a.altKey&&c)"function"!=typeof a.preventDefault&&a.preventDefault(),is_savebtn_disabled(b)||dosave(),LP_stopEventPropagation(a)}return!0}
function is_savebtn_disabled(a){a||(a=document);return(a=a.getElementById("save"))?0<=a.className.indexOf("btn_disabled"):!0}function insert_cpw_placeholder_msg(a,c){a||(a=document);var f=a.getElementById("cpw_placeholder_msg");if(c&&!g_cpw_heard_from_bg&&null===f){var f=a.createElement("p"),b=a.createTextNode(c);f.id="cpw_placeholder_msg";f.appendChild(b);a.getElementById("stepbystep").appendChild(f)}};
