function addTileBox(a,d){var g,c,f,b=!1;if("undefined"!=typeof a.sharerusername)g=a.id,c=gs("Share offer from")+":",f=of(getBG().hex2bin(a.sharerusername)),b=!0;else{if(typeof a.url&&"http://group"==a.url)return;g="undefined"!=typeof a.aid?a.aid:a.appaid;c=a.name;f=getusernamefromacct(a)}var h=getBG(),k=h.geticonurlfromrecord(a,!0),h=h.getbigiconurlfromrecord(a);null==k&&null==h&&(h=gLocalBaseUrl+"images/logos/lastpass.png");h||"http://sn"==a.url&&ofa("undefined"!=typeof a.notetype&&""!=a.notetype?
a.notetype:"Generic");c&&of(c);f&&of(f);c=document.createElement("div");c.className="tile";c.setAttribute("acctid",g);b?c.setAttribute("pending","1"):c.setAttribute("draggable","true");document.getElementById(d)?document.getElementById(d).appendChild(c):console.error("cannot find parent: "+d)}
function addGroupBox(a,d,g){d||(d="#thegrid");var c=get_div_id();g_groupidmap[a]=c;g_idgroupmap[c]=a;g="undefined"!=typeof g[a]?"grpopen":"grpclose";0==a.indexOf("_")&&(a=a.substring(1));a=of(a);$("<a class='tiletoplink' acctid='_"+c+"'><div class='bigfolder'><div class='"+g+"'></div><p class='name'>"+a+"</p></div></a><div id='c_"+c+"' class='cont'></div>").appendTo($(d))}
function setupTileEvents(){$(".tiletoplink").unbind("click");$(".tile").unbind("mouseover");$(".tile").unbind("contextmenu");$(".tile").unbind("dragstart");$(".tiletoplink").click(function(a){var d=getNodeAcctId(a.target);if(""!=d)if("_"==d[0]){a=getBigFolder(a.target);var g=getOpenedGroups(),c="#c"+d,d=getgroupnamefromid(d.substr(1),!0);"undefined"!=typeof g[d]?(closeTileGroup(c),d=$(a).children(".grpopen"),$(d).addClass("grpclose"),$(d).removeClass("grpopen")):(openTileGroup(c),d=$(a).children(".grpclose"),
$(d).addClass("grpopen"),$(d).removeClass("grpclose"));saveGroupState()}else ls(d)});$(".tile").mouseover(function(a){process_mouseover(a)});$(".tile").bind("contextmenu",function(a){process_rightclk(a);return!1});$(".tile").bind("dragstart",function(a){g_dragid=getNodeAcctId(a.target)})}
function process_rightclk(a){setTimeout(function(){$.contextMenu.create(function(){var a=getBG(),g={};g[gs("Move Selected to Group")]=function(){a.lpevent("v_multmov");openMoveGroup(n)};g[gs("Delete Selected")]=function(){a.lpevent("v_multd");a.deleteAid(ids,window,!1,!1,function(){for(var a=0;a<saved.length;a++)$.tree.focused().cut(saved[a])})};return[g]},{theme:"vista"}).show(t,a)},100)}
function process_mouseover(a){var d=getBG(),g=getTile(a.target);if(g&&!$(g).children(".tileoverlay").length){var c=getNodeAcctId(a.target),f=get_record(c),b=!1;null==f&&"undefined"!=typeof d.g_applications[c]&&(f=d.g_applications[c],b=!0);if(null==f)getTile(a.target).hasAttribute("pending")&&(gs("Accept"),gs("Reject"),b=document.createElement("div"),b.id="hoverlaytop",b.className="tileoverlay",b.acctid=c,g.appendChild(b),$("#hoverlayaccept,#hoverlayreject").unbind("click"),$("#hoverlayaccept").click(function(a){a=
getNodeAcctId(a.target);accept(a)}),$("#hoverlayreject").click(function(a){a=getNodeAcctId(a.target);reject(a)}));else{a=!b&&"http://sn"!=f.url;var h=!b&&f&&"undefined"==typeof f.sharefolderid&&("undefined"==typeof f.sharedfromaid||null==f.sharedfromaid||""==f.sharedfromaid||"0"==f.sharedfromaid||"null"==f.sharedfromaid)&&d.g_sharing_enabled,d=!b&&"http://sn"!=f.url&&("undefined"==typeof g_issafari&&"undefined"==typeof g_isopera&&"undefined"==typeof g_ismaxthon&&"undefined"==typeof g_isfirefoxsdk||
"function"==typeof d.can_copy_to_clipboard&&d.can_copy_to_clipboard()||"undefined"!=typeof g_is_safari);a?gs("Launch Site"):gs("Edit Note");d&&gs("Copy Password");h&&gs("Share");gs("Edit");b&&(c="app"+c);b=document.createElement("div");b.id="hoverlaytop";b.className="tileoverlay";g.appendChild(b);b.setAttribute("acctid",c);$("#hoverlayedit,#hoverlayshare,#hoverlaylaunch,.vaultcheck,#hoveroverlaycopy").unbind("click");$("#hoverlayedit").click(function(a){a=getNodeAcctId(a.target);e(a)});$("#hoverlayshare").click(function(a){a=
getNodeAcctId(a.target);s(a)});$("#hoverlaylaunch").click(function(a){a=getNodeAcctId(a.target);ls(a)});$("#hoverlaycopy").click(function(a){a=getNodeAcctId(a.target);getBG().copypassword(a)});$(".vaultcheck").click(function(a){var b=a.target.checked;a=getTile(a.target);b?$(a).css("border","1px solid yellow"):$(a).css("border","1px solid transparent")})}$(".tile").unbind("mouseout");$(".tile").mouseout(function(a){a=$(a.toElement);"hoverlaytop"!=a.attr("id")&&0==a.parents("div#hoverlaytop").length&&
$(".tileoverlay").remove()})}}function closeTileGroup(a){$(a).hide()}function openTileGroup(a){$(a).show()}function getNodeAcctId(a){if(a&&a.hasAttribute("acctid"))return a.getAttribute("acctid");for(var d="";""==d&&a.parentNode&&a.parentNode!=a;)if(a=a.parentNode,a.hasAttribute("acctid")){d=a.getAttribute("acctid");break}return d}function getTile(a){for(;a.parentNode&&a.parentNode!=a;)if(a=a.parentNode,"tile"==a.className)return a;return null}
function getBigFolder(a){if(-1!=a.className.indexOf("bigfolder"))return a;for(;a.parentNode&&a.parentNode!=a;)if(a=a.parentNode,-1!=a.className.indexOf("bigfolder"))return a;return null}
function createTileData(a,d){var g=[],c=[],f=""==path?"_"+gs("(none)"):path;if(""==d){if("undefined"!=typeof a[f])for(var b=0;b<a[f].length;b++)"http://group"==a[f][b].url?c.push(a[f][b].group):g.push(a[f][b])}else for(b=0;b<a.length;b++)"http://group"==a[b].url?c.push(a[b].group):g.push(a[b]);b=getBG();g.sort(b.lp_sort_case_insensitive_name);c=getSubfolders(path,a,c);c.sort(function(a,b){return a.toLowerCase().localeCompare(b.toLowerCase())});for(b=c.length-1;0<=b;b--)""==d?g.unshift(c[b]):-1!=c[b].toLowerCase().indexOf(d)&&
g.unshift(c[b]);return g}
function createTile(a,d,g,c){g_groupidmap=[];g_idgroupmap=[];c=""!=c;for(var f=0;f<a.length;f++){var b=a[f],h=checkParentGroups(b,g);addGroupBox(b,h,g)}$(".bigfolder").bind("dragover",function(a){var b=getNodeAcctId(a.target);if(""!=b&&"_"==b[0]){var c=getBigFolder(a.target),b=getgroupnamefromid(b.substr(1),!0);b!=gs("favorites")&&b!=g_xlat_runame&&b!=g_xlat_pendingname&&$(c).addClass("bigfolderdroptarget")}a.preventDefault();a.stopPropagation()});$(".bigfolder").bind("dragleave",function(a){var b=
getBigFolder(a.target);$(b).removeClass("bigfolderdroptarget");a.preventDefault();a.stopPropagation()});$(".bigfolder").bind("drop",function(a){var b=getNodeAcctId(a.target);if(""!=b&&"_"==b[0]){var c=getBigFolder(a.target);$(c).removeClass("bigfolderdroptarget");b=getgroupnamefromid(b.substr(1),!0);a.originalEvent.dataTransfer.getData("id");console.error(g_dragid+" DROPPED IN "+b);getBG().moveSelectedToGroup(b.substr(1),g_dragid)}a.preventDefault();a.stopPropagation()});for(f=0;f<a.length;f++){var b=
a[f],h="c_"+g_groupidmap[b],k=d[b];k.sort(getBG().lp_sort_case_insensitive_name);for(var l=0;l<k.length;l++)addTileBox(k[l],h);c||"undefined"!=typeof g[b]||((b=document.getElementById(h))?b.style.display="none":console.error("no parent "+h))}}function checkParentGroups(a,d){var g=a.split("/");if(1==g.length)return null;for(var c="",f=0;f<g.length;f++)c+=(""==c?"":"/")+g[f],0==$("#contents"+c).length&&addGroupBox(a,"#contents"+c,d);return"#"+c};
