"undefined"!==typeof LPPlatform&&LPPlatform.addEventListener(document,"keydown",function(a){try{switch(a.keyCode||a.which){case 13:"checkbox"!==a.target.type?Topics.get(Topics.ENTER).publish(a):a.target.checked=!a.target.checked;break;case 27:Topics.get(Topics.ESCAPE).publish(a);break;case 37:Topics.get(Topics.LEFT_ARROW).publish(a);break;case 38:Topics.get(Topics.UP_ARROW).publish(a);break;case 39:Topics.get(Topics.RIGHT_ARROW).publish(a);break;case 40:Topics.get(Topics.DOWN_ARROW).publish(a)}}catch(e){LPPlatform.logException(e)}});
LPTools={};
(function(a){var e=[];a.setDragItems=function(a){e=a};a.getDragItems=function(){return e};a.buildItemButton=function(c){var b=Constants.ACTION_BUTTONS[c];return a.createElement("button",{"class":"itemButton "+b.css,vaultaction:c,title:Strings.Vault[b.title],allowmultiple:!1})};a.setupMiddleEllipsis=function(a){var b=a.find(".textOverflowContainer"),c=Math.ceil(b.get(0).children[0].getBoundingClientRect().width);a=c+Math.ceil(a.find(".textTail").get(0).getBoundingClientRect().width);c=a-c;b.css("max-width",
a);b.css("padding-right",c);b.css("margin-right",-c)};a.requireBinary=function(a){bg.have_binary()?a():LPPlatform.supportsBinary()?dialogs.confirmation.open({title:Strings.translateString("Install Binary Component"),text:Strings.translateString("This feature requires the binary version of this browser extension. Would you like to install it now?"),handler:function(){bg.install_binary()}}):dialogs.alert.open({title:Strings.translateString("Not Supported"),text:Strings.translateString("This feature requires an external binary component, which is currently not supported on this platform.")})};
a.isType=function(a,b){return Object.prototype.toString.call(a)==="[object "+b+"]"};a.getURLParams=function(){var a={},b=document.location.href.split("?");if(2===b.length)for(var b=b[1].split("&"),d=0;d<b.length;++d){var f=b[d].split("=");2===f.length&&(a[f[0]]=f[1])}return a};a.setContent=function(c,b){c.empty();if(b)if("string"===typeof b){for(var d=b.indexOf("<br/>");-1<d;)c.append(document.createTextNode(b.substring(0,d))),c.append(document.createElement("br")),b=b.substring(d+5),d=b.indexOf("<br/>");
c.append(document.createTextNode(b))}else if(a.isType(b,"Array"))for(var d=0,f=b.length;d<f;++d){var k=b[d];"string"===typeof k&&(k=a.createElement("p","dialogText",k));c.append(k)}else c.append(b)};a.hideContextMenu=function(c){null!==c&&(c.removeClass("bottomAligned"),c.hide(),a.removeKeyBoardNavigation())};a.displayContextMenu=function(a,b){var c=$(b);a.clientY>window.innerHeight/2?(c.addClass("bottomAligned"),c.css("bottom",window.innerHeight-a.clientY),c.css("top","")):(c.css("top",a.clientY),
c.css("bottom",""));c.css("left",a.clientX);c.show();return c};a.getProperties=function(a){var b=[],c;for(c in a)b.push(c);return b};a.openAlerts=function(){var c=function(c,d,f){return function(){"function"===typeof c&&c();a.openAlerts(d,f)}};return function(a,d){if(0<a.length){var b=a.shift();$.extend(b,{handler:c(b.handler,a,d),closeHandler:c(b.closeHandler,a,d)});dialogs[b.type].open(b)}else d&&d()}}();a.buildDialogItemContainer=function(c){for(var b=a.createElement("div","dialogItemContainer noSelect"),
d={display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,allowDrag:!1,additionalItemClasses:"dialogItem noItemButtons"},f=0,k=c.length;f<k;++f){var h=c[f].newDisplayObject();b.appendChild(h.build(d))}return b};a.buildEmptyPlaceholder=function(c,b,d){return"ul"===d.tagName.toLocaleLowerCase()?a.createElement("li","emptyPlaceholder "+b,c):a.createElement("div","emptyPlaceholder "+b,c)};a.get_gmt_timestamp=function(){var a=(new Date).getTime();return parseInt(a/1E3)};a.ContextMenuItem=function(c,b){this.getAction=
function(){return c};this.build=function(d,f,k){var h=void 0!==b&&"undefined"!==typeof b.submenu&&b.submenu,e=null;void 0!==b&&"undefined"!==typeof b.divider&&b.divider&&(e="divider");h&&(e+=" subMenuOption");e=a.createElement("li",{"class":e,vaultaction:c});e.textContent=void 0===b||"undefined"===typeof b.text?Strings.Vault[Constants.CONTEXT_MENU_ITEMS[c]]:b.text;d.appendChild(e);h?(e.appendChild(a.createElement("div")),f=a.createElement("ul","subMenu"),e.appendChild(f),function(c,b){var f=null,
e=!1,h=function(){e&&(b.hide("fast"),a.addKeyBoardNavigation(d.children),Topics.get(Topics.LEFT_ARROW).unsubscribe(h))},g=function(a){e=!0;k(a);Topics.get(Topics.LEFT_ARROW).subscribe(h)};c.bind("click",g);c.bind("mouseenter",function(a){f=setTimeout(function(){g(a)},200)});c.bind("mouseleave",function(){f&&clearTimeout(f);h()})}($(e),$(f))):LPPlatform.addEventListener(e,"click",f)}};a.parseUserSpecificMenu=function(c,b){for(var d=c.firstElementChild;d;){var f=d.getAttribute("user");if(null!==f){for(var f=
f.split("|"),e=!0,h=0,g=f.length;h<g;++h)if(b===f[h]){e=!1;break}e?$(d).hide():d.removeAttribute("style")}a.parseUserSpecificMenu(d,b);d=d.nextElementSibling}};a.buildSentShareItems=function(a,b){var c=[];if(b)for(var f=0,e=b.length;f<e;++f){var h=b[f];"1"===h.state?c.push(new AcceptedSentSharedItem(a,h)):"2"===h.state?c.push(new DeclinedSentSharedItem(a,h)):c.push(new PendingSentSharedItem(a,h))}return c};a.openShareDialog=function(c,b){if(c&&1===c.length&&void 0===b)LPRequest.makeDataRequest(LPProxy.getSentShareData,
{params:{id:c[0].getID()},requestSuccessOptions:{closeDialog:!1},success:function(b){a.openShareDialog(c,b)},error:function(){Topics.get(Topics.DIALOG_LOADED).publish()}}),Topics.get(Topics.DIALOG_LOADING).publish();else if(b&&!dialogs.share.loadedJS())dialogs.share.loadJS(function(){a.openShareDialog(c,b)});else{var d=b?a.buildSentShareItems(c[0],b.sent[c[0].getID()]):null;dialogs.share.open(c,d,b?b.friends:null)}};a.objectsToArray=function(){for(var a=[],b=0,d=arguments.length;b<d;++b){var f=arguments[b],
e;for(e in f)a.push(f[e])}return a};a.createEventHandler=function(a){return function(b){a.handleEvent(b)}};a.getAttribute=function(a,b,d){for(var c=b.getAttribute(d);null===c&&b!==a;)if(b=b.parentElement,null!==b)c=b.getAttribute(d);else break;return c};a.removeDOMChildren=function(a){if(a)for(var b=a.childNodes.length;b--;)a.removeChild(a.lastChild)};a.removeDOMChildrenFrom=function(a,b){if(a)for(;b;){var c=b;b=b.nextElementSibling;a.removeChild(c)}};a.createElement=function(){return function(a,
b,d){var c=document.createElement(a);if("string"===typeof b||b instanceof Array)b={"class":b};if("input"===a||"textarea"===a)b=$.extend(b,{spellcheck:!1});if("object"===typeof b)for(var e in b){var h=b[e];if(void 0!==h&&null!==h){a=c;var g=e;h instanceof Array?a.setAttribute(g,h.join(" ")):a.setAttribute(g,h)}}void 0!==d&&(c.textContent=d);return c}}();a.addClass=function(a,b){if(null!==a){b instanceof Array&&(b=b.join(" "));var c=a.getAttribute("class");c&&(b=c+" "+b);a.setAttribute("class",b)}};
a.getOption=function(a,b,d){a&&void 0!==a[b]&&(d=a[b]);return d};(function(){var c=null,b=-1,d=null,e=null,k=null,h=null,g=null,l=function(a){return c&&-1<a&&a<c.length?c[a]:null},n=function(a,c){var d=l(b);d&&d.removeClass("hover");b=a;if(d=l(b))d.addClass("hover"),c&&g&&g.focusHandler&&g.focusHandler(d)},q=function(a){h=!0;$(document.body).unbind("mousemove",q)};a.disableMouse=function(a){h&&(h=!1,$(document.body).bind("mousemove",q))};var r=function(a){h&&(a=$(a.target),n(parseInt(a.closest("[navindex]").attr("navindex"))))},
t=function(a){var b=a.offsetParent();b.scrollTop(Math.max(b.scrollTop()+b.height(),b.scrollTop()+a.position().top+a.outerHeight())-b.height())},v=function(a){var b=a.offsetParent();b.scrollTop(Math.min(b.scrollTop(),b.scrollTop()+a.position().top))},u=function(d){var e;b===c.length-1?(e=0,v(c[e])):(e=b+1,t(c[e]));n(e,!0);a.disableMouse();d.preventDefault();d.stopPropagation()},w=function(d){var e;1>b?(e=c.length-1,t(c[e])):(e=b-1,v(c[e]));n(e,!0);a.disableMouse();d.preventDefault();d.stopPropagation()},
x=function(a){if(a){var b=new Event(d,{bubbles:!0});a.get(0).dispatchEvent(b)}},y=function(){var c=l(b);if(c){if(e){var d=c.find(e);d.length&&(c=d)}x(c);a.disableMouse()}return!1},z=function(){x(l(b));return!1};a.setNavIndex=function(a){n(a);(a=l())&&a.get(0).scrollIntoView()};a.getNavIndex=function(){return b};a.addKeyBoardNavigation=function(f,m){if(0<f.length){c=[];b=-1;null===h&&(h=!0);d=a.getOption(m,"mouseEvent","click");e=a.getOption(m,"rightArrowSelector",null);k=a.getOption(m,"useRightArrow",
!0);g=m;for(var l=0,n=f.length;l<n;++l){var p=$(f[l]);p.attr("navindex",l);p.unbind("mouseenter",r);p.bind("mouseenter",r);p.hasClass("hover")&&(b=l);c.push(p)}Topics.get(Topics.DOWN_ARROW).subscribe(u);Topics.get(Topics.UP_ARROW).subscribe(w);Topics.get(Topics.ENTER).subscribeFirst(z);k&&Topics.get(Topics.RIGHT_ARROW).subscribe(y);a.getOption(m,"selectFirst",!1)&&a.setNavIndex(0)}else a.removeKeyBoardNavigation()};a.removeKeyBoardNavigation=function(){c=null;Topics.get(Topics.DOWN_ARROW).unsubscribe(u);
Topics.get(Topics.UP_ARROW).unsubscribe(w);Topics.get(Topics.RIGHT_ARROW).unsubscribe(y);Topics.get(Topics.ENTER).unsubscribe(z)}})();a.addZebraStriping=function(a){a=$(a).find("tr");for(var b=0,c=a.length;b<c;++b)0!==b%2?$(a[b]).addClass("odd"):$(a[b]).removeClass("odd")};var g=function(a){a=a.target.previousElementSibling;a.checked=!a.checked};a.buildCheckbox=function(c,b){var d=b?b.checkboxAttributes:void 0,d=$.extend(d,{"class":"checkbox",type:"checkbox"}),d=a.createElement("input",d),e=a.createElement("label",
c,a.getOption(b,"text",void 0));a.getOption(b,"addClickHandler",!0)&&LPPlatform.addEventListener(e,"click",g);var k=a.createElement("div");k.appendChild(d);k.appendChild(e);return k};a.buildRadioButton=function(c,b,d){c=a.createElement("input",{"class":"radio",type:"radio",name:c});b=a.createElement("label",b,d);LPPlatform.addEventListener(b,"click",g);d=a.createElement("div");d.appendChild(c);d.appendChild(b);return d};a.hasProperties=function(a){if(a)for(var b in a)return!0;return!1};a.createSelectElement=
function(c,b){var d=a.createElement("select",b);$(d).addClass("dialogInput selectDropdown");a.setSelectOptions(d,c);return d};a.setSelectOptions=function(c,b){a.removeDOMChildren(c);for(var d=0,e=b.length;d<e;++d){var g=b[d],h="object"===typeof g?g.value:g;c.appendChild(a.createElement("option",{value:h},"object"===typeof g&&g.label?g.label:h))}};a.createTimezoneSelect=function(){var c=[{value:"-12:00,0",label:"(-12:00) "+Strings.translateString("International Date Line West")},{value:"-11:00,0",
label:"(-11:00) "+Strings.translateString("Midway Island, Samoa")},{value:"-10:00,0",label:"(-10:00) "+Strings.translateString("Hawaii")},{value:"-09:00,1",label:"(-09:00) "+Strings.translateString("Alaska")},{value:"-08:00,1",label:"(-08:00) "+Strings.translateString("Pacific Time (US & Canada)")},{value:"-07:00,0",label:"(-07:00) "+Strings.translateString("Arizona")},{value:"-07:00,1",label:"(-07:00) "+Strings.translateString("Mountain Time (US & Canada)")},{value:"-06:00,0",label:"(-06:00) "+Strings.translateString("Central America, Saskatchewan")},
{value:"-06:00,1",label:"(-06:00) "+Strings.translateString("Central Time (US & Canada), Guadalajara, Mexico City")},{value:"-05:00,0",label:"(-05:00) "+Strings.translateString("Indiana, Bogota, Lima, Quito, Rio Branco")},{value:"-05:00,1",label:"(-05:00) "+Strings.translateString("Eastern Time (US & Canada)")},{value:"-04:30,0",label:"(-04:30) "+Strings.translateString("Caracas")},{value:"-04:00,1",label:"(-04:00) "+Strings.translateString("Atlantic Time (Canada), Manaus, Santiago")},{value:"-04:00,0",
label:"(-04:00) "+Strings.translateString("La Paz")},{value:"-03:30,1",label:"(-03:30) "+Strings.translateString("Newfoundland")},{value:"-03:00,1",label:"(-03:00) "+Strings.translateString("Greenland, Brasilia, Montevideo")},{value:"-03:00,0",label:"(-03:00) "+Strings.translateString("Buenos Aires, Georgetown")},{value:"-02:00,1",label:"(-02:00) "+Strings.translateString("Mid-Atlantic")},{value:"-02:00,0",label:"(-02:00) "+Strings.translateString("South Georgia")},{value:"-01:00,1",label:"(-01:00) "+
Strings.translateString("Azores")},{value:"-01:00,0",label:"(-01:00) "+Strings.translateString("Cape Verde Is.")},{value:"00:00,0",label:"(00:00) "+Strings.translateString("Casablanca, Monrovia, Reykjavik")},{value:"00:00,1",label:"(00:00) "+Strings.translateString("GMT: Dublin, Edinburgh, Lisbon, London")},{value:"+01:00,1",label:"(+01:00) "+Strings.translateString("Amsterdam, Berlin, Rome, Vienna, Prague, Brussels")},{value:"+01:00,0",label:"(+01:00) "+Strings.translateString("West Central Africa")},
{value:"+02:00,1",label:"(+02:00) "+Strings.translateString("Amman, Athens, Istanbul, Beirut, Cairo, Jerusalem")},{value:"+02:00,0",label:"(+02:00) "+Strings.translateString("Harare, Pretoria")},{value:"+03:00,1",label:"(+03:00) "+Strings.translateString("Baghdad")},{value:"+03:00,0",label:"(+03:00) "+Strings.translateString("Kuwait, Riyadh, Nairobi, Moscow, St. Petersburg, Volgograd")},{value:"+03:30,1",label:"(+03:30) "+Strings.translateString("Tehran")},{value:"+04:00,0",label:"(+04:00) "+Strings.translateString("Abu Dhabi, Muscat, Tbilisi, Izhevsk")},
{value:"+04:00,1",label:"(+04:00) "+Strings.translateString("Baku, Yerevan")},{value:"+04:30,0",label:"(+04:30) "+Strings.translateString("Kabul")},{value:"+05:00,1",label:"(+05:00) "+Strings.translateString("GMT+5")},{value:"+05:00,0",label:"(+05:00) "+Strings.translateString("Islamabad, Karachi, Tashkent, Ekaterinburg")},{value:"+05:30,0",label:"(+05:30) "+Strings.translateString("Chennai, Kolkata, Mumbai, New Delhi, Sri Jayawardenepura")},{value:"+05:45,0",label:"(+05:45) "+Strings.translateString("Kathmandu")},
{value:"+06:00,0",label:"(+06:00) "+Strings.translateString("Astana, Dhaka, Novosibirsk")},{value:"+06:00,1",label:"(+06:00) "+Strings.translateString("Almaty")},{value:"+06:30,0",label:"(+06:30) "+Strings.translateString("Yangon (Rangoon)")},{value:"+07:00,1",label:"(+07:00) "+Strings.translateString("GMT+7")},{value:"+07:00,0",label:"(+07:00) "+Strings.translateString("Bangkok, Hanoi, Jakarta, Krasnoyarsk")},{value:"+08:00,0",label:"(+08:00) "+Strings.translateString("Beijing, Hong Kong, Singapore, Taipei, Irkutsk")},
{value:"+08:00,1",label:"(+08:00) "+Strings.translateString("Ulaan Bataar, Perth")},{value:"+09:00,1",label:"(+09:00) "+Strings.translateString("GMT+9")},{value:"+09:00,0",label:"(+09:00) "+Strings.translateString("Seoul, Osaka, Sapporo, Tokyo, Yakutsk")},{value:"+09:30,0",label:"(+09:30) "+Strings.translateString("Darwin")},{value:"+09:30,1",label:"(+09:30) "+Strings.translateString("Adelaide")},{value:"+10:00,0",label:"(+10:00) "+Strings.translateString("Brisbane, Guam, Port Moresby, Vladivostok")},
{value:"+10:00,1",label:"(+10:00) "+Strings.translateString("Canberra, Melbourne, Sydney, Hobart")},{value:"+11:00,0",label:"(+11:00) "+Strings.translateString("Magadan, Solomon Is., New Caledonia")},{value:"+12:00,1",label:"(+12:00) "+Strings.translateString("Auckland, Wellington")},{value:"+12:00,0",label:"(+12:00) "+Strings.translateString("Fiji, Kamchatka, Marshall Is.")},{value:"+13:00,0",label:"(+13:00) "+Strings.translateString("Nuku'alofa")}];return function(b){return a.createSelectElement(c,
b)}}()})(LPTools);
Constants={ACTION_OPEN_MOVE_TO_SUB_FOLDER_MENU:"openMoveToSubFolderMenu",ACTION_OPEN_MOVE_TO_FOLDER_MENU:"openMoveToFolderMenu",ACTION_MOVE_TO_FOLDER:"moveToFolder",ACTION_SAVE:"save",ACTION_DELETE:"delete",ACTION_SHARE:"share",ACTION_COPY_USERNAME:"copyUsername",ACTION_COPY_PASSWORD:"copyPassword",ACTION_COPY_URL:"copyURL",ACTION_EDIT:"edit",ACTION_LAUNCH:"launch",ACTION_GO_TO_URL:"goToURL",ACTION_TOGGLE_OPEN:"toggleOpen",ACTION_RENAME:"rename",ACTION_ACCEPT:"acceptShare",ACTION_REJECT:"rejectShare",ACTION_ENABLE:"enable",
ACTION_TOGGLE_SELECT:"toggleSelect",ACTION_CREATE_SUB_FOLDER:"createSubFolder",ACTION_OPEN_ALL:"openAll",ACTION_OPEN_MORE_OPTIONS:"openMoreOptions",ACTION_COPY_NOTE:"copyNote",ACTION_FILL:"fillForm",ACTION_OPEN:"open",ACTION_REVOKE:"revoke",ACTION_EMAIL:"email",ACTION_CANCEL:"cancel",ACTION_REMOVE:"remove",ACTION_PURGE:"purge",ACTION_PURGE_SHARED_FOLDER:"purgeSharedFolder",ACTION_RESTORE:"restore",ACTION_RESTORE_SHARED_FOLDER:"restoreSharedFolder",ACTION_UNLINK:"unlink",ACTION_STOP_DOWNLOADING:"stopDownloading",
ACTION_START_DOWNLOADING:"startDownloading",ACTION_FILL_SITE:"fillSite",ACTION_CLONE:"clone",ACTION_ADD:"add",ACTION_MANAGE:"manage",ACTION_ACCESS:"access",ACTION_COPY_KEY:"copyKey",ACTION_DASHBOARD:"dashboard",ACTION_UPGRADE:"upgrade",USER_FREE:"Free User",USER_PREMIUM:"Premium User",USER_ENTERPRISE:"Enterprise User",USER_ENTERPRISE_ADMIN:"Enterprise Admin",USER_TEAMS:"Teams User",USER_TEAMS_ADMIN:"Teams Admin",EmailAddressRegularExpression:/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*/g};
(function(a){a.ACTION_BUTTONS={};a.ACTION_BUTTONS[a.ACTION_EDIT]={title:"EDIT",css:a.ACTION_EDIT};a.ACTION_BUTTONS[a.ACTION_SHARE]={title:"SHARE",css:a.ACTION_SHARE};a.ACTION_BUTTONS[a.ACTION_DELETE]={title:"DELETE",css:a.ACTION_DELETE};a.ACTION_BUTTONS[a.ACTION_ACCEPT]={title:"ACCEPT",css:a.ACTION_ACCEPT};a.ACTION_BUTTONS[a.ACTION_REJECT]={title:"REJECT",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_LAUNCH]={title:"LAUNCH",css:null};a.ACTION_BUTTONS[a.ACTION_ENABLE]={title:"ENABLE",css:null};a.ACTION_BUTTONS[a.ACTION_ACCESS]=
{title:"REQUEST_ACCESS",css:null};a.ACTION_BUTTONS[a.ACTION_REVOKE]={title:"REVOKE",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_EMAIL]={title:"RESEND",css:a.ACTION_EMAIL};a.ACTION_BUTTONS[a.ACTION_CANCEL]={title:"CANCEL_INVITE",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_REMOVE]={title:"REMOVE",css:a.ACTION_REJECT};a.ACTION_BUTTONS[a.ACTION_PURGE]={title:"PURGE",css:a.ACTION_DELETE};a.ACTION_BUTTONS[a.ACTION_PURGE_SHARED_FOLDER]={title:"PURGE",css:a.ACTION_DELETE};a.ACTION_BUTTONS[a.ACTION_RESTORE]=
{title:"RESTORE",css:a.ACTION_RESTORE};a.ACTION_BUTTONS[a.ACTION_RESTORE_SHARED_FOLDER]={title:"RESTORE",css:a.ACTION_RESTORE};a.ACTION_BUTTONS[a.ACTION_MANAGE]={title:"MANAGE",css:a.ACTION_EDIT};a.ACTION_BUTTONS[a.ACTION_UNLINK]={title:"UNLINK",css:a.ACTION_DELETE};a.CONTEXT_MENU_ITEMS={};a.CONTEXT_MENU_ITEMS[a.ACTION_EDIT]="EDIT";a.CONTEXT_MENU_ITEMS[a.ACTION_SHARE]="SHARE";a.CONTEXT_MENU_ITEMS[a.ACTION_DELETE]="DELETE";a.CONTEXT_MENU_ITEMS[a.ACTION_GO_TO_URL]="GO_TO_URL";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_USERNAME]=
"COPY_USERNAME";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_PASSWORD]="COPY_PASSWORD";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_URL]="COPY_URL";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN_MOVE_TO_FOLDER_MENU]="MOVE_TO_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN_MOVE_TO_SUB_FOLDER_MENU]="MOVE_TO_SUB_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_ACCEPT]="ACCEPT";a.CONTEXT_MENU_ITEMS[a.ACTION_REJECT]="REJECT";a.CONTEXT_MENU_ITEMS[a.ACTION_ENABLE]="ENABLE";a.CONTEXT_MENU_ITEMS[a.ACTION_RENAME]="RENAME_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_CREATE_SUB_FOLDER]=
"CREATE_SUB_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN_ALL]="OPEN_ALL";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_NOTE]="COPY_NOTE";a.CONTEXT_MENU_ITEMS[a.ACTION_COPY_KEY]="COPY_KEY";a.CONTEXT_MENU_ITEMS[a.ACTION_FILL]="FILL";a.CONTEXT_MENU_ITEMS[a.ACTION_OPEN]="OPEN";a.CONTEXT_MENU_ITEMS[a.ACTION_SAVE]="SAVE";a.CONTEXT_MENU_ITEMS[a.ACTION_REVOKE]="REVOKE";a.CONTEXT_MENU_ITEMS[a.ACTION_EMAIL]="RESEND";a.CONTEXT_MENU_ITEMS[a.ACTION_CANCEL]="CANCEL_INVITE";a.CONTEXT_MENU_ITEMS[a.ACTION_REMOVE]="REMOVE";a.CONTEXT_MENU_ITEMS[a.ACTION_PURGE]=
"PURGE";a.CONTEXT_MENU_ITEMS[a.ACTION_PURGE_SHARED_FOLDER]="PURGE";a.CONTEXT_MENU_ITEMS[a.ACTION_RESTORE]="RESTORE";a.CONTEXT_MENU_ITEMS[a.ACTION_RESTORE_SHARED_FOLDER]="RESTORE";a.CONTEXT_MENU_ITEMS[a.ACTION_UNLINK]="UNLINK_PERSONAL";a.CONTEXT_MENU_ITEMS[a.ACTION_STOP_DOWNLOADING]="STOP_DOWNLOADING";a.CONTEXT_MENU_ITEMS[a.ACTION_START_DOWNLOADING]="START_DOWNLOADING";a.CONTEXT_MENU_ITEMS[a.ACTION_FILL_SITE]="AUTO_FILL";a.CONTEXT_MENU_ITEMS[a.ACTION_CLONE]="CLONE";a.CONTEXT_MENU_ITEMS[a.ACTION_MANAGE]=
"MANAGE_FOLDER";a.CONTEXT_MENU_ITEMS[a.ACTION_ACCESS]="REQUEST_ACCESS";a.CONTEXT_MENU_ITEMS[a.ACTION_DASHBOARD]="OPEN_DASHBOARD";a.CONTEXT_MENU_ITEMS[a.ACTION_UPGRADE]="UPGRADE_PREMIUM";a.HISTORY_TYPES={PASSWORD:0,USERNAME:1,NOTE:2}})(Constants);
(function(a){a.fn.extend({LP_show:function(){this.removeClass("displaynone")},LP_hide:function(){this.addClass("displaynone")},LP_removeAttr:function(a){for(var e=0,c=this.length;e<c;++e)this.get(e).removeAttribute(a)},LP_addSearchHandlers:function(e,g){var c=a(LPTools.createElement("div","searchInputContainer"));this.before(c);c.append(this);var b="searchCloseButton";e&&(b+=" "+e);var d=a(LPTools.createElement("div",{"class":b,title:Strings.translateString("Clear Search")}));c.append(d);var f,k=
function(a){clearTimeout(f);f=setTimeout(function(){try{g(a)}catch(m){LPPlatform.logException(m)}},150)};(function(a){d.bind("click",function(b){a.val("");b.stopPropagation();b.preventDefault()})})(this);this.LP_input("search",function(a){0<a.length?c.addClass("populated"):c.removeClass("populated");k(a)});return this},LP_createToggle:function(){return function(){for(var a=0,g=this.length;a<g;++a){var c=this.get(a);if("INPUT"===c.nodeName&&"checkbox"===c.getAttribute("type")&&"LABEL"===c.nextElementSibling.nodeName){var b=
LPTools.createElement("div","toggleButton");b.appendChild(LPTools.createElement("div"));c.nextElementSibling.appendChild(b)}}return this}}(),LP_addPasswordEye:function(){var e=function(a,b,d){a.passwordShown=!1;a.attr("type","password");b.attr("title",Strings.Vault.SHOW_PASSWORD);b.removeClass("selected");d&&b.text(Strings.Vault.SHOW)},g=function(a,b,d){switch(a.attr("type")){case "password":a.passwordShown=!0;a.attr("type","text");b.attr("title",Strings.Vault.HIDE_PASSWORD);b.addClass("selected");
d&&b.text(Strings.Vault.HIDE);break;case "text":e(a,b,d)}d&&a.css("padding-right",b.outerWidth())};return function(c){this.addClass("password");var b=a(LPTools.createElement("div","relative"));this.before(b);b.append(this);b.css({margin:this.css("margin")});this.css("margin","0");var d=a(LPTools.createElement("button",{"class":"showPassword iconButton",title:Strings.Vault.SHOW_PASSWORD}));b.append(d);(function(f,k){var h=LPTools.getOption(c,"textual",!1);h&&(d.addClass("textual"),d.text(Strings.Vault.SHOW),
f.one("focus",function(){f.css("padding-right",d.outerWidth())}));d.bind("click",function(){"password"===f.attr("type")&&k?k(function(){g(f,d,h)}):g(f,d,h)});f.hidePassword=function(){e(f,d,h)};if(LPTools.getOption(c,"includeGenerateButton",!1)){f.LP_input("passwordGenerate",function(a){a?b.removeClass("empty"):(f.hidePassword(),b.addClass("empty"))});var m=a(LPTools.createElement("button",{"class":"generatePassword iconButton",title:Strings.Vault.GENERATE_PASSWORD}));b.append(m);m.bind("click",function(){dialogs.generatePassword.open({input:f,
fillGenerated:!1,saveOptions:{source:"vault"}})})}})(this,LPTools.getOption(c,"checkPermissionHandler",null));this.val(this.val());return this}}(),LP_reflow:function(){for(var a=0;a<this.length;++a)this.get(a).offsetHeight;return this},LP_scrollParent:function(){var e;if(1===this.length)for(var g=this.get(0).parentElement;g;){var c=a(g);if("auto"===c.css("overflow")&&c.css("max-height")){e=g;break}g=g.parentElement}return a(e)},LP_input:function(a,g){var c=this;a=a?"."+a:"";c.unbind("keypress"+a);
c.unbind("keyup"+a);c.unbind("input"+a);var b=function(a){a=a.which;31<a&&g(c.val()+String.fromCharCode(a))};c.bind("keypress"+a,b);var d=function(a){switch(a.keyCode||a.which){case 8:case 46:g(c.val())}};c.bind("keyup"+a,d);var e=function(){c.unbind("keypress"+a,b);c.unbind("keyup"+a,d);c.unbind("input"+a,e)};c.bind("input"+a,e);c.bind("input"+a,function(){g(c.val())});c.val=function(a){return function(){1===arguments.length&&g(arguments[0]);return a.apply(c,arguments)}}(this.val)}})})(jQuery);
NotifyException=function(a){Topics.get(Topics.ERROR).publish(a);this.message=a;this.stack=Error().stack};NotifyException.prototype=Object.create(Error.prototype);NotifyException.prototype.name="InvalidArgumentException";NotifyException.prototype.constructor=NotifyException;AttachmentKeyException=function(){NotifyException.call(this,Strings.translateString("Could not decrypt attachment key."))};AttachmentKeyException.prototype=Object.create(NotifyException.prototype);
AttachmentKeyException.prototype.name="AttachmentKeyException";AttachmentKeyException.prototype.constructor=AttachmentKeyException;
