/*
 typeahead.js 0.10.1
 https://github.com/twitter/typeahead.js
 Copyright 2013 Twitter, Inc. and other contributors; Licensed MIT
*/
(function(g){var e={isMsie:function(){return/(msie|trident)/i.test(navigator.userAgent)?navigator.userAgent.match(/(msie |rv:)(\d+(.\d+)?)/i)[2]:!1},isBlankString:function(c){return!c||/^\s*$/.test(c)},escapeRegExChars:function(c){return c.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")},isString:function(c){return"string"===typeof c},isNumber:function(c){return"number"===typeof c},isArray:g.isArray,isFunction:g.isFunction,isObject:g.isPlainObject,isUndefined:function(c){return"undefined"===
typeof c},bind:g.proxy,each:function(c,e){g.each(c,function(d,b){return e(b,d)})},map:g.map,filter:g.grep,every:function(c,e){var d=!0;if(!c)return d;g.each(c,function(b,a){if(!(d=e.call(null,a,b,c)))return!1});return!!d},some:function(c,e){var d=!1;if(!c)return d;g.each(c,function(b,a){if(d=e.call(null,a,b,c))return!1});return!!d},mixin:g.extend,getUniqueId:function(){var c=0;return function(){return c++}}(),templatify:function(c){function e(){return String(c)}return g.isFunction(c)?c:e},defer:function(c){setTimeout(function(){c()},
0)},debounce:function(c,e,d){var b,a;return function(){var f=this,h=arguments,l,m;l=function(){b=null;d||(a=c.apply(f,h))};m=d&&!b;clearTimeout(b);b=setTimeout(function(){l()},e);m&&(a=c.apply(f,h));return a}},throttle:function(c,e){var d,b,a,f,h,l;h=0;l=function(){h=new Date;a=null;f=c.apply(d,b)};return function(){var m=new Date,g=e-(m-h);d=this;b=arguments;0>=g?(clearTimeout(a),a=null,h=m,f=c.apply(d,b)):a||(a=setTimeout(function(){l()},g));return f}},noop:function(){}},v=function(c,g){function d(a){this.maxSize=
a||100;this.size=0;this.hash={};this.list=new b}function b(){this.head=this.tail=null}function a(a,b){this.key=a;this.val=b;this.prev=this.next=null}e.mixin(d.prototype,{set:function(b,h){var f=this.list.tail;this.size>=this.maxSize&&(this.list.remove(f),delete this.hash[f.key]);(f=this.hash[b])?(f.val=h,this.list.moveToFront(f)):(f=new a(b,h),this.list.add(f),this.hash[b]=f,this.size++)},get:function(a){if(a=this.hash[a])return this.list.moveToFront(a),a.val}});e.mixin(b.prototype,{add:function(a){this.head&&
(a.next=this.head,this.head.prev=a);this.head=a;this.tail=this.tail||a},remove:function(a){a.prev?a.prev.next=a.next:this.head=a.next;a.next?a.next.prev=a.prev:this.tail=a.prev},moveToFront:function(a){this.remove(a);this.add(a)}});return d}(this),y=function(){function c(b){this.prefix=["__",b,"__"].join("");this.ttlKey="__ttl__";this.keyMatcher=new RegExp("^"+this.prefix)}function g(b){return JSON.stringify(e.isUndefined(b)?null:b)}var d;try{d=window.localStorage,d.setItem("~~~","!"),d.removeItem("~~~")}catch(b){d=
null}e.mixin(c.prototype,d&&window.JSON?{_prefix:function(b){return this.prefix+b},_ttlKey:function(b){return this._prefix(b)+this.ttlKey},get:function(b){this.isExpired(b)&&this.remove(b);return JSON.parse(d.getItem(this._prefix(b)))},set:function(b,a,f){e.isNumber(f)?d.setItem(this._ttlKey(b),g((new Date).getTime()+f)):d.removeItem(this._ttlKey(b));return d.setItem(this._prefix(b),g(a))},remove:function(b){d.removeItem(this._ttlKey(b));d.removeItem(this._prefix(b));return this},clear:function(){var b,
a,f=[],h=d.length;for(b=0;b<h;b++)(a=d.key(b)).match(this.keyMatcher)&&f.push(a.replace(this.keyMatcher,""));for(b=f.length;b--;)this.remove(f[b]);return this},isExpired:function(b){b=JSON.parse(d.getItem(this._ttlKey(b)));return e.isNumber(b)&&(new Date).getTime()>b?!0:!1}}:{get:e.noop,set:e.noop,remove:e.noop,clear:e.noop,isExpired:e.noop});return c}(),z=function(){function c(a){a=a||{};this._send=a.transport?k(a.transport):g.ajax;this._get=a.rateLimiter?a.rateLimiter(this._get):this._get}function k(a){return function(b,
f){var h=g.Deferred();a(b,f,function(a){e.defer(function(){h.resolve(a)})},function(a){e.defer(function(){h.reject(a)})});return h}}var d=0,b={},a=6,f=new v(10);c.setMaxPendingRequests=function(b){a=b};c.resetCache=function(){f=new v(10)};e.mixin(c.prototype,{_get:function(h,c,e){function l(a){e&&e(a);f.set(h,a)}function m(){d--;delete b[h];g.onDeckRequestArgs&&(g._get.apply(g,g.onDeckRequestArgs),g.onDeckRequestArgs=null)}var g=this,k;(k=b[h])?k.done(l):d<a?(d++,b[h]=this._send(h,c).done(l).always(m)):
this.onDeckRequestArgs=[].slice.call(arguments,0)},get:function(a,b,c){var h;e.isFunction(b)&&(c=b,b={});(h=f.get(a))?e.defer(function(){c&&c(h)}):this._get(a,b,c);return!!h}});return c}(),A=function(){function c(a){a=a||{};a.datumTokenizer&&a.queryTokenizer||g.error("datumTokenizer and queryTokenizer are both required");this.datumTokenizer=a.datumTokenizer;this.queryTokenizer=a.queryTokenizer;this.datums=[];this.trie={ids:[],children:{}}}function k(a){a=e.filter(a,function(a){return!!a});return a=
e.map(a,function(a){return a.toLowerCase()})}function d(a){for(var b={},h=[],c=0;c<a.length;c++)b[a[c]]||(b[a[c]]=!0,h.push(a[c]));return h}function b(a,b){function f(a,b){return a-b}var c=0,d=0,e=[];a=a.sort(f);for(b=b.sort(f);c<a.length&&d<b.length;)a[c]<b[d]?c++:(a[c]>b[d]||(e.push(a[c]),c++),d++);return e}e.mixin(c.prototype,{bootstrap:function(a){this.datums=a.datums;this.trie=a.trie},add:function(a){var b=this;a=e.isArray(a)?a:[a];e.each(a,function(a){var f;f=b.datums.push(a)-1;a=k(b.datumTokenizer(a));
e.each(a,function(a){var h,c;h=b.trie;for(a=a.split("");c=a.shift();)h=h.children[c]||(h.children[c]={ids:[],children:{}}),h.ids.push(f)})})},get:function(a){var f=this,h;a=k(this.queryTokenizer(a));e.each(a,function(a){var c,d;if(h&&0===h.length)return!1;c=f.trie;for(a=a.split("");c&&(d=a.shift());)c=c.children[d];if(c&&0===a.length)c=c.ids.slice(0),h=h?b(h,c):c;else return h=[],!1});return h?e.map(d(h),function(a){return f.datums[a]}):[]},serialize:function(){return{datums:this.datums,trie:this.trie}}});
return c}(),r=function(){return{local:function(c){c=c.local||null;e.isFunction(c)&&(c=c.call(null));return c},prefetch:function(c){var k;k={url:null,thumbprint:"",ttl:864E5,filter:null,ajax:{}};if(c=c.prefetch||null)c=e.isString(c)?{url:c}:c,c=e.mixin(k,c),c.thumbprint="0.10.1"+c.thumbprint,c.ajax.type=c.ajax.type||"GET",c.ajax.dataType=c.ajax.dataType||"json",!c.url&&g.error("prefetch requires url to be set");return c},remote:function(c){function k(a){return function(b){return e.debounce(b,a)}}function d(a){return function(b){return e.throttle(b,
a)}}var b;b={url:null,wildcard:"%QUERY",replace:null,rateLimitBy:"debounce",rateLimitWait:300,send:null,filter:null,ajax:{}};if(c=c.remote||null)c=e.isString(c)?{url:c}:c,c=e.mixin(b,c),c.rateLimiter=/^throttle$/i.test(c.rateLimitBy)?d(c.rateLimitWait):k(c.rateLimitWait),c.ajax.type=c.ajax.type||"GET",c.ajax.dataType=c.ajax.dataType||"json",delete c.rateLimitBy,delete c.rateLimitWait,!c.url&&g.error("remote requires url to be set");return c}}}();window.Bloodhound=function(){function c(b){b&&(b.local||
b.prefetch||b.remote)||g.error("one of local, prefetch, or remote is required");this.limit=b.limit||5;this.sorter=k(b.sorter);this.dupDetector=b.dupDetector||d;this.local=r.local(b);this.prefetch=r.prefetch(b);this.remote=r.remote(b);this.cacheKey=this.prefetch?this.prefetch.cacheKey||this.prefetch.url:null;this.index=new A({datumTokenizer:b.datumTokenizer,queryTokenizer:b.queryTokenizer});this.storage=this.cacheKey?new y(this.cacheKey):null}function k(b){function a(a){return a.sort(b)}function f(a){return a}
return e.isFunction(b)?a:f}function d(){return!1}c.tokenizers={whitespace:function(b){return b.split(/\s+/)},nonword:function(b){return b.split(/\W+/)}};e.mixin(c.prototype,{_loadPrefetch:function(b){function a(a){a=b.filter?b.filter(a):a;f.add(a);f._saveToStorage(f.index.serialize(),b.thumbprint,b.ttl)}var f=this,h;(h=this._readFromStorage(b.thumbprint))?(this.index.bootstrap(h),h=g.Deferred().resolve()):h=g.ajax(b.url,b.ajax).done(a);return h},_getFromRemote:function(b,a){var f=this,h;b=b||"";h=
encodeURIComponent(b);h=this.remote.replace?this.remote.replace(this.remote.url,b):this.remote.url.replace(this.remote.wildcard,h);"function"==typeof shouldSearchGroups&&shouldSearchGroups()&&(h+="&grp=1");return this.transport.get(h,this.remote.ajax,function(b){b=f.remote.filter?f.remote.filter(b):b;a(b)})},_saveToStorage:function(b,a,f){this.storage&&(this.storage.set("data",b,f),this.storage.set("protocol",location.protocol,f),this.storage.set("thumbprint",a,f))},_readFromStorage:function(b){var a,
f,h;this.storage&&(a=this.storage.get("data"),f=this.storage.get("protocol"),h=this.storage.get("thumbprint"));b=h!==b||f!==location.protocol;return a&&!b?a:null},initialize:function(){function b(){a.add(a.local)}var a=this,f;f=this.prefetch?this._loadPrefetch(this.prefetch):g.Deferred().resolve();this.local&&f.done(b);this.transport=this.remote?new z(this.remote):null;this.initialize=function(){return f.promise()};return f.promise()},add:function(b){this.index.add(b)},get:function(b,a){function f(b){var f=
c.slice(0);e.each(b,function(a){!e.some(f,function(b){return h.dupDetector(a,b)})&&f.push(a);return f.length<h.limit});a&&a(h.sorter(f))}var h=this,c,d=!1;c=this.index.get(b);c=this.sorter(c).slice(0,this.limit);c.length<this.limit&&this.transport&&(d=this._getFromRemote(b,f));!d&&a&&a(c)},ttAdapter:function(){return e.bind(this.get,this)}});return c}();var B={position:"relative",display:"inline-block"},C={position:"absolute",top:"0",left:"0",borderColor:"transparent",boxShadow:"none"},t={position:"relative",
verticalAlign:"top",backgroundColor:"transparent"},D={position:"relative",verticalAlign:"top"},E={position:"absolute",top:"100%",left:"0",zIndex:"100",display:"none"},F={display:"block"},G={whiteSpace:"normal"},H={left:"0",right:"auto"},I={left:"auto",right:" 0"};e.isMsie()&&e.mixin(t,{backgroundImage:"url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7)"});e.isMsie()&&7>=e.isMsie()&&e.mixin(t,{marginTop:"-1px"});var w=function(){function c(c){c&&c.el||g.error("EventBus initialized without el");
this.$el=g(c.el)}e.mixin(c.prototype,{trigger:function(c){var d=[].slice.call(arguments,1);this.$el.trigger("typeahead:"+c,d)}});return c}(),u=function(){function c(a,c,e,g){if(!e)return this;c=c.split(b);e=g?d(e,g):e;for(this._callbacks=this._callbacks||{};g=c.shift();)this._callbacks[g]=this._callbacks[g]||{sync:[],async:[]},this._callbacks[g][a].push(e);return this}function e(a,b,c){return function(){for(var f,h=0;!f&&h<a.length;h+=1)f=!1===a[h].apply(b,c);return!f}}function d(a,b){return a.bind?
a.bind(b):function(){a.apply(b,[].slice.call(arguments,0))}}var b=/\s+/,a=function(){return window.setImmediate?function(a){setImmediate(function(){a()})}:function(a){setTimeout(function(){a()},0)}}();return{onSync:function(a,b,d){return c.call(this,"sync",a,b,d)},onAsync:function(a,b,d){return c.call(this,"async",a,b,d)},off:function(a){var c;if(!this._callbacks)return this;for(a=a.split(b);c=a.shift();)delete this._callbacks[c];return this},trigger:function(c){var f,d,g,k,q;if(!this._callbacks)return this;
c=c.split(b);for(g=[].slice.call(arguments,1);(f=c.shift())&&(d=this._callbacks[f]);)k=e(d.sync,this,[f].concat(g)),q=e(d.async,this,[f].concat(g)),k()&&a(q);return this}}}(),J=function(c){function g(b,a,c){for(var f=[],d=0;d<b.length;d++)f.push(e.escapeRegExChars(b[d]));b=c?"\\b("+f.join("|")+")\\b":"("+f.join("|")+")";return a?new RegExp(b):new RegExp(b,"i")}var d={node:null,pattern:null,tagName:"strong",className:null,wordsOnly:!1,caseSensitive:!1};return function(b){function a(b,c){for(var f,
d=0;d<b.childNodes.length;d++)if(f=b.childNodes[d],3===f.nodeType){c(f);break}else a(f,c)}var f;b=e.mixin({},d,b);b.node&&b.pattern&&(b.pattern=e.isArray(b.pattern)?b.pattern:[b.pattern],f=g(b.pattern,b.caseSensitive,b.wordsOnly),a(b.node,function(a){var d,h;if(d=f.exec(a.data))wrapperNode=c.createElement(b.tagName),b.className&&(wrapperNode.className=b.className),h=a.splitText(d.index),h.splitText(d[0].length),wrapperNode.appendChild(h.cloneNode(!0)),a.parentNode.replaceChild(wrapperNode,h);return!!d}))}}(window.document),
x=function(){function c(a){var c=this,d,l,m,n;a=a||{};a.input||g.error("input is missing");d=e.bind(this._onBlur,this);l=e.bind(this._onFocus,this);m=e.bind(this._onKeydown,this);n=e.bind(this._onInput,this);this.$hint=g(a.hint);this.$input=g(a.input).on("blur.tt",d).on("focus.tt",l).on("keydown.tt",m);0===this.$hint.length&&(this.setHintValue=this.getHintValue=this.clearHint=e.noop);if(e.isMsie())this.$input.on("keydown.tt keypress.tt cut.tt paste.tt",function(a){b[a.which||a.keyCode]||e.defer(e.bind(c._onInput,
c,a))});else this.$input.on("input.tt",n);this.query=this.$input.val();this.$overflowHelper=k(this.$input)}function k(a){return g('<pre aria-hidden="true"></pre>').css({position:"absolute",visibility:"hidden",whiteSpace:"nowrap",fontFamily:a.css("font-family"),fontSize:a.css("font-size"),fontStyle:a.css("font-style"),fontVariant:a.css("font-variant"),fontWeight:a.css("font-weight"),wordSpacing:a.css("word-spacing"),letterSpacing:a.css("letter-spacing"),textIndent:a.css("text-indent"),textRendering:a.css("text-rendering"),
textTransform:a.css("text-transform")}).insertAfter(a)}function d(a){return a.altKey||a.ctrlKey||a.metaKey||a.shiftKey}var b;b={9:"tab",27:"esc",37:"left",39:"right",13:"enter",38:"up",40:"down"};c.normalizeQuery=function(a){return(a||"").replace(/^\s*/g,"").replace(/\s{2,}/g," ")};e.mixin(c.prototype,u,{_onBlur:function(a){this.resetInputValue();this.trigger("blurred")},_onFocus:function(a){this.trigger("focused")},_onKeydown:function(a){var c=b[a.which||a.keyCode];this._managePreventDefault(c,a);
c&&this._shouldTrigger(c,a)&&this.trigger(c+"Keyed",a)},_onInput:function(a){this._checkInputValue()},_managePreventDefault:function(a,b){var c,f;switch(a){case "tab":c=this.getHintValue();f=this.getInputValue();c=c&&c!==f&&!d(b);break;case "up":case "down":c=!d(b);break;default:c=!1}c&&b.preventDefault()},_shouldTrigger:function(a,b){var c;switch(a){case "tab":c=!d(b);break;default:c=!0}return c},_checkInputValue:function(){var a,b,d;a=this.getInputValue();b=this.query;d=(b=c.normalizeQuery(a)===
c.normalizeQuery(b))?this.query.length!==a.length:!1;b?d&&this.trigger("whitespaceChanged",this.query):this.trigger("queryChanged",this.query=a)},focus:function(){this.$input.focus()},blur:function(){this.$input.blur()},getQuery:function(){return this.query},setQuery:function(a){this.query=a},getInputValue:function(){return this.$input.val()},setInputValue:function(a,b){this.$input.val(a);!b&&this._checkInputValue()},getHintValue:function(){return this.$hint.val()},setHintValue:function(a){this.$hint.val(a)},
resetInputValue:function(){this.$input.val(this.query)},clearHint:function(){this.$hint.val("")},getLanguageDirection:function(){return(this.$input.css("direction")||"ltr").toLowerCase()},hasOverflow:function(){var a=this.$input.width()-2;this.$overflowHelper.text(this.getInputValue());return this.$overflowHelper.width()>=a},isCursorAtEnd:function(){var a,b;a=this.$input.val().length;b=this.$input[0].selectionStart;return e.isNumber(b)?b===a:document.selection?(b=document.selection.createRange(),
b.moveStart("character",-a),a===b.text.length):!0},destroy:function(){this.$hint.off(".tt");this.$input.off(".tt");this.$hint=this.$input=this.$overflowHelper=null}});return c}(),p=function(){function c(b){b=b||{};b.templates=b.templates||{};b.source||g.error("missing source");b.name&&!/^[_a-zA-Z0-9-]+$/.test(b.name)&&g.error("invalid dataset name: "+b.name);this.query=null;this.highlight=!!b.highlight;this.name=b.name||e.getUniqueId();this.source=b.source;this.displayFn=k(b.display||b.displayKey);
this.templates=d(b.templates,this.displayFn);this.$el=g('<div class="tt-dataset-%CLASS%"></div>'.replace("%CLASS%",this.name))}function k(b){function a(a){return a[b]}b=b||"value";return e.isFunction(b)?b:a}function d(b,a){function c(b){return"<p>"+a(b)+"</p>"}return{empty:b.empty&&e.templatify(b.empty),header:b.header&&e.templatify(b.header),footer:b.footer&&e.templatify(b.footer),suggestion:b.suggestion||c}}c.extractDatasetName=function(b){return g(b).data("ttDataset")};c.extractValue=function(b){return g(b).data("ttValue")};
c.extractDatum=function(b){return g(b).data("ttDatum")};e.mixin(c.prototype,u,{_render:function(b,a){function c(){var c,d;c=g('<span class="tt-suggestions"></span>').css(F);d=e.map(a,function(a){var b;b=k.templates.suggestion(a);b='<div class="tt-suggestion">%BODY%</div>'.replace("%BODY%",b);a=g(b).data("ttDataset",k.name).data("ttValue",k.displayFn(a)).data("ttDatum",a);a.children().each(function(){g(this).css(G)});return a});c.append.apply(c,d);k.highlight&&J({node:c[0],pattern:b});return c}function d(){return k.templates.header({query:b,
isEmpty:!n})}function l(){return k.templates.footer({query:b,isEmpty:!n})}if(this.$el){var k=this,n;this.$el.empty();n=a&&a.length;!n&&this.templates.empty?this.$el.html(k.templates.empty({query:b,isEmpty:!0})).prepend(k.templates.header?d():null).append(k.templates.footer?l():null):n&&this.$el.html(c()).prepend(k.templates.header?d():null).append(k.templates.footer?l():null);this.trigger("rendered")}},getRoot:function(){return this.$el},update:function(b){var a=this;this.query=b;this.source(b,function(c){b===
a.query&&a._render(b,c)})},clear:function(){this._render(this.query||"")},isEmpty:function(){return this.$el.is(":empty")},destroy:function(){this.$el=null}});return c}(),K=function(){function c(c){var b=this,a,d,h;c=c||{};c.menu||g.error("menu is required");this.isOpen=!1;this.isEmpty=!0;this.datasets=e.map(c.datasets,k);a=e.bind(this._onSuggestionClick,this);d=e.bind(this._onSuggestionMouseEnter,this);h=e.bind(this._onSuggestionMouseLeave,this);this.$menu=g(c.menu).on("click.tt",".tt-suggestion",
a).on("mouseenter.tt",".tt-suggestion",d).on("mouseleave.tt",".tt-suggestion",h);e.each(this.datasets,function(a){b.$menu.append(a.getRoot());a.onSync("rendered",b._onRendered,b)})}function k(c){return new p(c)}e.mixin(c.prototype,u,{_onSuggestionClick:function(c){this.trigger("suggestionClicked",g(c.currentTarget))},_onSuggestionMouseEnter:function(c){this._removeCursor();this._setCursor(g(c.currentTarget),!0)},_onSuggestionMouseLeave:function(c){this._removeCursor()},_onRendered:function(){(this.isEmpty=
e.every(this.datasets,function(c){return c.isEmpty()}))?this._hide():this.isOpen&&this._show();this.trigger("datasetRendered")},_hide:function(){this.$menu.hide()},_show:function(){this.$menu.css("display","block")},_getSuggestions:function(){return this.$menu.find(".tt-suggestion")},_getCursor:function(){return this.$menu.find(".tt-cursor").first()},_setCursor:function(c,b){c.first().addClass("tt-cursor");!b&&this.trigger("cursorMoved")},_removeCursor:function(){this._getCursor().removeClass("tt-cursor")},
_moveCursor:function(c){var b,a;this.isOpen&&(a=this._getCursor(),b=this._getSuggestions(),this._removeCursor(),c=b.index(a)+c,c=(c+1)%(b.length+1)-1,-1===c?this.trigger("cursorRemoved"):(-1>c&&(c=b.length-1),this._setCursor(b=b.eq(c)),this._ensureVisible(b)))},_ensureVisible:function(c){var b,a,d;b=c.position().top;c=b+c.outerHeight(!0);a=this.$menu.scrollTop();d=this.$menu.height()+parseInt(this.$menu.css("paddingTop"),10)+parseInt(this.$menu.css("paddingBottom"),10);0>b?this.$menu.scrollTop(a+
b):d<c&&this.$menu.scrollTop(a+(c-d))},close:function(){this.isOpen&&(this.isOpen=!1,this._removeCursor(),this._hide(),this.trigger("closed"))},open:function(){this.isOpen||(this.isOpen=!0,!this.isEmpty&&this._show(),this.trigger("opened"))},setLanguageDirection:function(c){this.$menu.css("ltr"===c?H:I)},moveCursorUp:function(){this._moveCursor(-1)},moveCursorDown:function(){this._moveCursor(1)},getDatumForSuggestion:function(c){var b=null;c.length&&(b={raw:p.extractDatum(c),value:p.extractValue(c),
datasetName:p.extractDatasetName(c)});return b},getDatumForCursor:function(){return this.getDatumForSuggestion(this._getCursor().first())},getDatumForTopSuggestion:function(){return this.getDatumForSuggestion(this._getSuggestions().first())},update:function(c){e.each(this.datasets,function(b){b.update(c)})},empty:function(){e.each(this.datasets,function(c){c.clear()});this.isEmpty=!0},isVisible:function(){return this.isOpen&&!this.isEmpty},destroy:function(){this.$menu.off(".tt");this.$menu=null;
e.each(this.datasets,function(c){c.destroy()})}});return c}(),L=function(){function c(a){var b,c,d;a=a||{};a.input||g.error("missing input");this.autoselect=!!a.autoselect;this.minLength=e.isNumber(a.minLength)?a.minLength:1;this.$node=k(a.input,a.withHint);b=this.$node.find(".tt-dropdown-menu");c=this.$node.find(".tt-input");d=this.$node.find(".tt-hint");this.eventBus=a.eventBus||new w({el:c});this.dropdown=(new K({menu:b,datasets:a.datasets})).onSync("suggestionClicked",this._onSuggestionClicked,
this).onSync("cursorMoved",this._onCursorMoved,this).onSync("cursorRemoved",this._onCursorRemoved,this).onSync("opened",this._onOpened,this).onSync("closed",this._onClosed,this).onAsync("datasetRendered",this._onDatasetRendered,this);this.input=(new x({input:c,hint:d})).onSync("focused",this._onFocused,this).onSync("blurred",this._onBlurred,this).onSync("enterKeyed",this._onEnterKeyed,this).onSync("tabKeyed",this._onTabKeyed,this).onSync("escKeyed",this._onEscKeyed,this).onSync("upKeyed",this._onUpKeyed,
this).onSync("downKeyed",this._onDownKeyed,this).onSync("leftKeyed",this._onLeftKeyed,this).onSync("rightKeyed",this._onRightKeyed,this).onSync("queryChanged",this._onQueryChanged,this).onSync("whitespaceChanged",this._onWhitespaceChanged,this);b.on("mousedown.tt",function(a){e.isMsie()&&9>e.isMsie()&&(c[0].onbeforedeactivate=function(){window.event.returnValue=!1;c[0].onbeforedeactivate=null});a.preventDefault()})}function k(a,b){var c,f,e,k;c=g(a);f=g('<span class="twitter-typeahead" style="width:100%"></span>').css(B);
e=g('<span class="tt-dropdown-menu"></span>').css(E);k=c.clone().css(C).css(d(c));k.val("").removeData().addClass("tt-hint").removeAttr("id name placeholder").prop("disabled",!0).attr({autocomplete:"off",spellcheck:"false"});c.data("ttAttrs",{dir:c.attr("dir"),autocomplete:c.attr("autocomplete"),spellcheck:c.attr("spellcheck"),style:c.attr("style")});c.addClass("tt-input").attr({autocomplete:"off",spellcheck:!1}).css(b?t:D);try{!c.attr("dir")&&c.attr("dir","auto")}catch(q){}return c.wrap(f).parent().prepend(b?
k:null).append(e)}function d(a){return{backgroundAttachment:a.css("background-attachment"),backgroundClip:a.css("background-clip"),backgroundColor:a.css("background-color"),backgroundImage:a.css("background-image"),backgroundOrigin:a.css("background-origin"),backgroundPosition:a.css("background-position"),backgroundRepeat:a.css("background-repeat"),backgroundSize:a.css("background-size")}}function b(a){var b=a.find(".tt-input");e.each(b.data("ttAttrs"),function(a,c){e.isUndefined(a)?b.removeAttr(c):
b.attr(c,a)});b.detach().removeData("ttAttrs").removeClass("tt-input").insertAfter(a);a.remove()}e.mixin(c.prototype,{_onSuggestionClicked:function(a,b){var c;(c=this.dropdown.getDatumForSuggestion(b))&&this._select(c)},_onCursorMoved:function(){var a=this.dropdown.getDatumForCursor();this.input.clearHint();this.input.setInputValue(a.value,!0);this.eventBus.trigger("cursorchanged",a.raw,a.datasetName)},_onCursorRemoved:function(){this.input.resetInputValue();this._updateHint()},_onDatasetRendered:function(){this._updateHint()},
_onOpened:function(){this._updateHint();this.eventBus.trigger("opened")},_onClosed:function(){this.input.clearHint();this.eventBus.trigger("closed")},_onFocused:function(){this.dropdown.empty();this.dropdown.isOpen||0!=this.minLength||this.dropdown.update("");this.dropdown.open()},_onBlurred:function(){this.dropdown.close()},_onEnterKeyed:function(a,b){var c,d;c=this.dropdown.getDatumForCursor();d=this.dropdown.getDatumForTopSuggestion();c?(this._select(c),b.preventDefault()):this.autoselect&&d&&
(this._select(d),b.preventDefault())},_onTabKeyed:function(a,b){var c;(c=this.dropdown.getDatumForCursor())?(this._select(c),b.preventDefault()):this._autocomplete()},_onEscKeyed:function(){this.dropdown.close();this.input.resetInputValue()},_onUpKeyed:function(){var a=this.input.getQuery();!this.dropdown.isOpen&&a.length>=this.minLength&&this.dropdown.update(a);this.dropdown.open();this.dropdown.moveCursorUp()},_onDownKeyed:function(){var a=this.input.getQuery();!this.dropdown.isOpen&&a.length>=
this.minLength&&this.dropdown.update(a);this.dropdown.open();this.dropdown.moveCursorDown()},_onLeftKeyed:function(){"rtl"===this.dir&&this._autocomplete()},_onRightKeyed:function(){"ltr"===this.dir&&this._autocomplete()},_onQueryChanged:function(a,b){this.input.clearHint();this.dropdown.empty();b.length>=this.minLength&&this.dropdown.update(b);this.dropdown.open();this._setLanguageDirection()},_onWhitespaceChanged:function(){this._updateHint();this.dropdown.open()},_setLanguageDirection:function(){var a;
this.dir!==(a=this.input.getLanguageDirection())&&(this.dir=a,this.$node.css("direction",a),this.dropdown.setLanguageDirection(a))},_updateHint:function(){var a,b,c,d;(a=this.dropdown.getDatumForTopSuggestion())&&this.dropdown.isVisible()&&!this.input.hasOverflow()&&(b=this.input.getInputValue(),c=x.normalizeQuery(b),d=e.escapeRegExChars(c),c=a.value,/\/^http[s]?:\//.exec(d)||(c=""!==a.raw.a?a.raw.a:a.raw.domain),a=new RegExp("^(?:"+d+")(.*$)","i"),a=a.exec(c),this.input.setHintValue(b+(a?a[1]:"")))},
_autocomplete:function(){var a,b;a=this.input.getHintValue();b=this.input.getQuery();a&&b!==a&&this.input.isCursorAtEnd()&&((a=this.dropdown.getDatumForTopSuggestion())&&this.input.setInputValue(a.value),this.eventBus.trigger("autocompleted",a.raw,a.datasetName))},_select:function(a){this.input.clearHint();this.input.setQuery(a.value);this.input.setInputValue(a.value,!0);this._setLanguageDirection();this.eventBus.trigger("selected",a.raw,a.datasetName);this.dropdown.close();e.defer(e.bind(this.dropdown.empty,
this.dropdown))},open:function(){this.dropdown.open()},close:function(){this.dropdown.close()},getQuery:function(){return this.input.getQuery()},setQuery:function(a){this.input.setInputValue(a)},destroy:function(){this.input.destroy();this.dropdown.destroy();b(this.$node);this.$node=null}});return c}();(function(){var c,k;c=g.fn.typeahead;k={initialize:function(c,b){b=e.isArray(b)?b:[].slice.call(arguments,1);c=c||{};return this.each(function(){var a=g(this),d;e.each(b,function(a){a.highlight=!!c.highlight});
d=new L({input:a,eventBus:new w({el:a}),withHint:e.isUndefined(c.hint)?!0:!!c.hint,minLength:c.minLength,autoselect:c.autoselect,datasets:b});a.data("ttTypeahead",d)})},open:function(){return this.each(function(){var c;(c=g(this).data("ttTypeahead"))&&c.open()})},close:function(){return this.each(function(){var c;(c=g(this).data("ttTypeahead"))&&c.close()})},val:function(c){function b(){var a;(a=g(this).data("ttTypeahead"))&&a.setQuery(c)}function a(a){var b;if(a=a.data("ttTypeahead"))b=a.getQuery();
return b}return arguments.length?this.each(b):a(this.first())},destroy:function(){return this.each(function(){var c=g(this),b;if(b=c.data("ttTypeahead"))b.destroy(),c.removeData("ttTypeahead")})}};g.fn.typeahead=function(c){return k[c]?k[c].apply(this,[].slice.call(arguments,1)):k.initialize.apply(this,arguments)};g.fn.typeahead.noConflict=function(){g.fn.typeahead=c;return this}})()})(window.jQuery);
