var tabnames="treepane ffpane identpane sharepane credmonpane entpane videopane".split(" "),g_activetab=null,g_lasttab="",g_partnername="";this.inittabs=function(){g_activetab=document.getElementById("sites");g_activetab.className+=" activetab"};
this.ontabchange=function(b){for(var a=0;a<tabnames.length;a++)document.getElementById(tabnames[a])&&(document.getElementById(tabnames[a]).style.display="none",g_activetab&&(g_activetab.className=trim(g_activetab.className.replace("activetab",""))));a=document.getElementById("q")?document.getElementById("q"):document.getElementById("lpsearchstr");""!=g_lasttab&&a&&""!=a.value&&"undefined"!=typeof maintabs&&(a.value="",SearchTree(g_lasttab));a=b.getAttribute("tabid");document.getElementById(tabnames[a]).style.display=
"block";g_lasttab=b.id;g_activetab=b;g_activetab.className+=" activetab";document.getElementById("expandcollapse")&&(document.getElementById("expandcollapse").style.display="0"==a?"":"none");document.getElementById("creategrouprow")&&(document.getElementById("creategrouprow").style.display="0"==a?"":"none");"sites"==g_lasttab&&"function"==typeof fix_nosites&&fix_nosites();"ff"==g_lasttab&&populateff("");"ident"==g_lasttab&&populateident("");"shares"==g_lasttab&&"function"==typeof populateshares_remote&&
populateshares_remote();"credmon"==g_lasttab&&populatealerts("");"enterprise"==g_lasttab&&loadenterprise();"video"==g_lasttab?loadvideo():hidevideo();updateActionMenu(a)};
this.updateActionMenu=function(b){if(-1==window.location.href.indexOf("showdeleted")){var a="Add Site;Add Profile;Add Identity;;Add Profile;;".split(";");document.getElementById("addsite").style.display="   none  none none none".split(" ")[b];document.getElementById("addsecurenote").style.display=" none none none none none none none".split(" ")[b];"undefined"!=typeof document.getElementById("addsitetext").innerText?document.getElementById("addsitetext").innerText="undefined"!=typeof translations[a[b]]?
translations[a[b]]:a[b]:"undefined"!=typeof document.getElementById("addsitetext").textContent&&(document.getElementById("addsitetext").textContent="undefined"!=typeof translations[a[b]]?translations[a[b]]:a[b]);document.getElementById("actions_separator")&&(document.getElementById("actions_separator").style.display="none"==document.getElementById("addsite").style.display&&"none"==document.getElementById("addsecurenote").style.display&&"none"==document.getElementById("creategrouprow").style.display?
"none":"block")}};this.geturltoload=function(b){b=("undefined"!=typeof baseurl?baseurl:"")+b;""!=g_partnername&&(b+=(0<=b.indexOf("?")?"&":"?")+"partnername="+encodeURIComponent(g_partnername));return b=b.replace("?&","?")};
this.loadenterprise=function(){var b=document.getElementById("entpane");if(!document.getElementById("entiframe")){var a=document.createElement("iframe");a.id="entiframe";a.type="content";a.className="overviewiframe";a.setAttribute("src",geturltoload("enterprise_overview2.php"));b.appendChild(a)}};
this.loadvideo=function(){var b=document.getElementById("videopane");if(!document.getElementById("videoiframe")){var a=document.createElement("iframe");a.id="videoiframe";a.type="content";a.className="overviewiframe";a.setAttribute("src",geturltoload("video_overview.php"));b.appendChild(a)}};this.hidevideo=function(){try{var b=document.getElementById("videoiframe");if(b){var a=document.getElementById("videopane");a&&b.parentNode==a&&a.removeChild(b)}}catch(f){}};
this.append_link=function(b,a,f,k,l,g,d){var c=document.createElement("a");c.setAttribute("href",a);c.setAttribute("id",f);k&&c.setAttribute("title",k);a=document.createElement("img");a.setAttribute("src",l);a.setAttribute("class","border0px");c.appendChild(a);g&&c.appendChild(document.createTextNode(g));b.appendChild(c);d&&b.appendChild(document.createTextNode(d))};
this.populateffcommon=function(b,a,f){var k="undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl;f=document.getElementById("ffpane");if(0==b.length&&"undefined"==typeof g_no_overview){if(!document.getElementById("ffiframe")){for(;f.children.length;)f.removeChild(f.children[0]);b=document.createElement("iframe");b.id="ffiframe";b.type="content";b.className="overviewiframe";b.setAttribute("src",geturltoload("formfill_overview.php"));b.setAttribute("frameborder","0");f.appendChild(b)}}else{for(;f.children.length;)f.removeChild(f.children[0]);
a=a.toLowerCase();var l=document.createElement("table");l.className="vault-table";for(var g={},d=0;d<b.length;d++){var c=b[d],n="string"==typeof c.decprofilename?c.decprofilename:c.profilename;if(""==a||-1!=n.indexOf(a)){var m=document.createElement("tr");m.className="table-row";var h=document.createElement("td"),e=document.createElement("td");0==d?(h.className+=" firstrowleft",e.className+=" firstrowright"):d==b.length-1&&(h.className+=" lastrowleft",e.className+=" lastrowright");e.align="right";
append_link(h,"#","launchffid"+c.ffid,null,k+"images/vaultff.png",n);g["launchffid"+c.ffid]=function(){openff(this.id.substring(10));return!1};append_link(e,"#","editffid"+c.ffid,gs("Edit"),k+"images/vaultedit.png",null," | ");g["editffid"+c.ffid]=function(){openff(this.id.substring(8));return!1};"undefined"==typeof g_hideprofilecopy&&(append_link(e,"#","copyffid"+c.ffid,gs("Copy"),k+"images/vaultcopy.png",null," | "),g["copyffid"+c.ffid]=function(){copyff(this.id.substring(8));return!1});append_link(e,
"#","deleteffid"+c.ffid,gs("Delete"),k+"images/vaultdelete.png");g["deleteffid"+c.ffid]=function(){delff(this.id.substring(10));return!1};m.appendChild(h);m.appendChild(e);l.appendChild(m)}}f.appendChild(l);for(d in g)document.getElementById(d).onclick=g[d]}};
function populateidentcommon(b,a){for(var f=document.getElementById("identpane");f.children.length;)f.removeChild(f.children[0]);var k="undefined"==typeof gLocalBaseUrl?"":gLocalBaseUrl;a=a.toLowerCase();var l=document.createElement("table");l.className="vault-table";for(var g={},d=0;d<b.length;d++){var c=b[d],n="string"==typeof c.deciname?c.deciname:c.iname;if(""==a||-1!=n.indexOf(a)){var m=document.createElement("tr");m.className="table-row";var h=document.createElement("td"),e=document.createElement("td");
0==d?(h.className+=" firstrowleft",e.className+=" firstrowright"):d==b.length-1&&(h.className+=" lastrowleft",e.className+=" lastrowright");e.align="right";append_link(h,"#","launchident"+c.iid,null,k+"images/vaultidentity.png",n);g["launchident"+c.iid]=function(){openident(this.id.substring(11));return!1};append_link(e,"#","editident"+c.iid,gs("Edit"),k+"images/vaultedit.png",null," | ");g["editident"+c.iid]=function(){openident(this.id.substring(9));return!1};"undefined"==typeof g_hideidentcopy&&
(append_link(e,"#","copyident"+c.iid,gs("Copy"),k+"images/vaultcopy.png",null," | "),g["copyident"+c.iid]=function(){copyident(this.id.substring(9));return!1});append_link(e,"#","deleteident"+c.iid,gs("Delete"),k+"images/vaultdelete.png");g["deleteident"+c.iid]=function(){delident(this.id.substring(11));return!1};m.appendChild(h);m.appendChild(e);l.appendChild(m)}}f.appendChild(l);for(d in g)document.getElementById(d).onclick=g[d]}
function cleariframe(b){try{if(document.getElementById(b))for(;document.getElementById(b).children.length;)document.getElementById(b).removeChild(document.getElementById(b).children[0])}catch(a){}};
