Strings={};
(function(b){Topics.get(Topics.INITIALIZED).subscribe(function(){b.translateStrings(b.Vault)});b.Vault={EDIT:"Edit",SHARE:"Share",DELETE:"Delete",LAUNCH:"Launch",ADMIN_CONSOLE:"Admin Console",HELP_CENTER:"Help Center",ACCOUNT_SETTINGS:"Account Settings",LOGOUT:"Logout",ACCEPT:"Accept",REJECT:"Reject",ENABLE:"Enable",COPY_USERNAME:"Copy Username",COPY_PASSWORD:"Copy Password",COPY_URL:"Copy URL",MOVE_TO_FOLDER:"Move to Group",MOVE_TO_SUB_FOLDER:"Move to Sub-Group",DELETE_FOLDER:"Delete Group",RENAME_FOLDER:"Rename Group",
SHARE_FOLDER:"Share Folder",RENAME:"Rename",CREATE_SUB_FOLDER:"Create Sub-Group",OPEN_ALL:"Open All Sites",COPY_NOTE:"Copy Note",COPY_KEY:"Copy Key",FILL:"Fill",OPEN:"Open",SAVE:"Save",CANCEL:"Cancel",REVOKE:"Revoke Access",RESEND:"Resend Invitation",CANCEL_INVITE:"Cancel Invitation",REMOVE:"Remove",PURGE:"Purge",RESTORE:"Restore",CLOSE:"Close",MAXIMIZE:"Maximize",MINIMIZE:"Minimize",EDIT_ACCESS:"Edit Access",UNLINK_PERSONAL:"Unlink Personal Account",STOP_DOWNLOADING:"Stop Downloading Folder",START_DOWNLOADING:"Start Downloading Folder",
CONFIRM_REQUEST_ACCESS:"Confirm Request Access",VAULT_TOGGLE:"Toggle LastPass 3.0",AUTO_FILL:"Auto Fill",DELETED:"deleted",ADDED:"added",RENAMED:"renamed",SAVED:"saved",REMOVED:"removed",ACCEPTED:"accepted",DECLINED:"declined",PURGED:"purged",RESTORED:"restored",FOLDER_PURGE:"this folder's items",SELECTED_PURGE:"the selected items",CLONE:"Clone",MORE_OPTIONS:"More Options",MANAGE:"Manage",MANAGE_FOLDER:"Manage Folder",REQUEST_ACCESS:"Request Access",SHARED_WITH:"Shared with",SHARED_BY:"Shared by",
PENDING_SHARE:"Pending share",LAST_USED:"Last used",WAITING_PERIOD:"Waiting period",ACCESS_PENDING:"Access pending until",ACCESS_GRANTED:"Access granted",ACCOUNT_LINKED:"Account linked",GO_TO_URL:"Go to URL",UNEXPECTED_ERROR:"An unexpected error has occurred",READ_ONLY:"Read-Only",EMERGENCY_ACCESS_RECIPIENT:"Emergency Access Recipient",UNLINK:"Unlink",GENERATED:"Generated",NOT_DOWNLOADED:"Not downloaded",LINKED:"Linked",OUTSIDE_ENT:"Outside Enterprise",NO_SHARING_KEYS:"No Sharing Keys",GENERATED_PREFIX:"Generated Password for",
PURGE_ALL:"Purge All",LINKED_PERSONAL_ACCOUNT:"Linked Personal Account",EMERGENCY_ACCESS:"Emergency Access",COLLAPSE_ALL:"Collapse All",EXPAND_ALL:"Expand All",COMPACT_VIEW:"Show Compact View",LARGE_VIEW:"Show Large View",SHOW_PASSWORD:"Show Password",HIDE_PASSWORD:"Hide Password",GENERATE_PASSWORD:"Generate Password",ERROR:"Error",YES:"Yes",NO:"No",OPEN_DASHBOARD:"Open Dashboard",UPGRADE_PREMIUM:"Upgrade to Premium",SHOW:"SHOW",HIDE:"HIDE",NONE_GROUP:"(none)",NO_FOLDER:"No folder",AGO:"ago",NEVER:"Never",
JUST_NOW:"just now",SECOND:"second",SECONDS:"seconds",MINUTE:"minute",MINUTES:"minutes",HOUR:"hour",HOURS:"hours",DAY:"day",DAYS:"days",WEEK:"week",WEEKS:"weeks",MONTH:"month",MONTHS:"months",YEAR:"year",YEARS:"years",SITE:"Site",APPLICATION:"Application:",GROUP:"Group:",SECURE_NOTE:"Secure Note",FORM_FILL:"Form Fill",IDENTITY:"Identity",USER:"User",USER_GROUP:"User Group",SHARED_FOLDER:"Shared Folder",ADD_FOLDER:"Add New Folder",SHARE_ITEMS:"Share Item",ADD_FORM_FILL:"Add Form Fill",ADD_NOTE:"Add Secure Note",
ADD_SITE:"Add Site",ADD_SHARED_FOLDER:"Add Shared Folder",ADD_IDENTITY:"Add Identity",GIVE_EMER_ACCESS:"Give Emergency Access",ADD_CREDIT_MON:"Enable Credit Monitoring",DUUMY_TERMINATING_ENTRY:""};b.VaultDynamic={CONFIRM_PURGE:"Are you sure you want to purge %1? It will be permanently deleted from LastPass.",CONFIRM_RESTORE:"Are you sure you want to restore %1 to your vault?"};b.Consts={NONE_GROUP:"(none)"};b.translateString=function(d){"undefined"!==typeof bg?d=bg.StringUtils.translate.apply(bg.StringUtils,
arguments):"undefined"!==typeof StringUtils&&(d=StringUtils.translate.apply(StringUtils,arguments));if(1<arguments.length){for(var b=[],c=1,g=arguments.length;c<g;++c){var a=arguments[c];if("object"===typeof a){var e=d.indexOf("%"+c);b.push(document.createTextNode(d.substring(0,e)));b.push(LPTools.createElement(a.type,a.attributes,a.text));d=d.substring(e+2)}}if(0<b.length)return 0<d.length&&b.push(d),b}return d};b.translate=function(d,k){for(var c,g,a=d;a;){if(3===a.nodeType)a.textContent=this.translateString(a.textContent);
else if(1===a.nodeType){var e=a.getAttribute("placeholder");null!==e&&a.setAttribute("placeholder",this.translateString(e));e=a.getAttribute("title");null!==e&&a.setAttribute("title",this.translateString(e));if(null!==a.getAttribute("compoundtranslation")){e=a;c="";g=[];for(var f=e.firstChild;f;)3===f.nodeType?c+=f.textContent:1===f.nodeType&&(c+="%"+g.length+f.textContent+"%"+g.length,g.push(f)),f=f.nextSibling;c=b.translateString(c);LPTools.removeDOMChildren(e);for(var f=c.indexOf("%"),h=null;-1<
f;){var l=c.substring(0,f);null===h?(e.appendChild(document.createTextNode(l)),h=parseInt(c.charAt(f+1))):((h=g[h])?(h.textContent=l,e.appendChild(h)):e.appendChild(document.createTextNode(l)),h=null);c=c.substring(f+2);f=c.indexOf("%")}0<c.length&&e.appendChild(document.createTextNode(c))}else b.translate(a.firstChild)}a=a.nextSibling}};b.translateStrings=function(d){for(var k in d)d[k]=b.translateString(d[k])};return b})(Strings);
