function postacctsload(){var a,b={};for(a=0;a<g_sites.length;a++)g_sites[a].url=AES.hex2url(g_sites[a].url),"undefined"!=typeof g_sites[a].username&&(g_sites[a].unencryptedUsername=lpmdec_acct(g_sites[a].username,!0,g_sites[a],g_shares)),g_SUPPORTSINGLE||(g_sites[a].pwch=!1),b[g_sites[a].aid]=g_sites[a];g_sites=b;b={};for(a=0;a<g_securenotes.length;a++)b[g_securenotes[a].aid]=g_securenotes[a];g_securenotes=b;b={};for(a=0;a<g_applications.length;a++)g_applications[a].appname=AES.hex2url(g_applications[a].appname),
b[g_applications[a].appaid]=g_applications[a];g_applications=b;for(a=0;a<g_identities.length;a++)g_identities[a].deciname=lpdec(g_identities[a].iname);"function"==typeof get_data_handler&&get_data_handler()}lploggedin=!0;g_server_accts_version=g_local_accts_version=-1;g_identities=[];g_formfills=[];g_pendings=[];base_url="";g_sites={};g_securenotes={};g_premium_exp=g_iscompanyadmin=g_teamsenterprisemodel=g_enterpriseuser=0;g_applications={};g_shares=[];g_username_hash=lp_username=g_username=null;
g_prompts={};g_maxid=[];g_groups={};g_prefoverrides={};lp_attaches=[];g_attachversion=[];g_emer_sharers=[];g_emer_sharees=[];g_note_templates=[];g_reminders=[];lpversion="4.0";g_uid=null;g_icons=[];g_bigicons=[];g_identity="undefined"!==typeof iid&&iid?iid:Preferences.get("identity");g_nofolder_feature_enabled=!1;
function get_accts(){$.ajax({type:"POST",url:base_url+"getaccts.php",data:"mobile=1&b64=1&shap=1&includependingsharedfolders=1&includesharedfolderformfillprofiles=1&includeemergencyaccess=1&requestsrc=newvault&hasplugin="+encodeURIComponent(lpversion)+"&u="+encodeURIComponent(g_username_hash),dataType:"text",success:function(a){a=atob(a);g_sites=[];g_securenotes=[];g_prompts=[];g_formfills=[];g_identities=[];g_pendings=[];g_maxid=[];g_groups=[];g_prefoverrides=[];g_shares=[];g_applications=[];lp_attaches=
[];g_attachversion=[];g_emer_sharers=[];g_emer_sharees=[];g_note_templates=[];g_reminders=[];g_pending_shares=[];parsemobile(a,a.length,100,0,postacctsload,g_sites,g_securenotes,g_prompts,g_formfills,g_identities,null,null,!0,!1,null,g_pendings,null,g_maxid,null,g_groups,g_prefoverrides,lp_rsaprivatekeyhex,g_shares,null,null,null,g_applications,lp_attaches,g_attachversion,null,null,null,g_emer_sharers,g_emer_sharees,null,g_note_templates,g_pending_shares,g_reminders)}})}
function process_icons(a,b){if(a&&(a=a.split(":"),a.length))for(var d=a[0],e=0,f=a.length;e+1<f;e+=2){var c=parseInt(a[e+1]);if(0===d.indexOf("lp")&&0<c){var d=d.substring(2),h=a[e+2].substring(0,c);b?g_bigicons[AES.hex2bin(d)]=h:g_icons[d]=h;d=a[e+2].substring(c)}}}
function get_icons(a){$.ajax({type:"POST",url:base_url+"geticon.php",data:"big=1&versionchrome=1&username="+encodeURIComponent(g_username)+"&domain=all",dataType:"text",success:function(b){"latest"!=b&&"nodata"!=b&&process_icons(b,!0);a&&a()}})}get_personal_linked=function(){for(var a=0;a<g_shares.length;a++)if("undefined"!=typeof g_shares[a].associative&&1==g_shares[a].associative)return g_shares[a].id;return""};get_securityChallengeScore=function(a){a(null)};
getbigicon=function(a){a=lp_gettld_url(a);return"undefined"!=typeof g_bigicons[a]?"data:image/png;base64,"+g_bigicons[a]:null};get_method_async=function(a){a()};geticonurlfromrecord=function(a,b){return is_application(a)?"lps lpapp"+a.fiid:"lps lp"+a.aid};unlock_plug2web=function(){g_plug2web_last_initiated=parseInt((new Date).getTime()/1E3)};get_last_reprompt_time=function(){"undefined"==typeof last_reprompt_time&&(last_reprompt_time=Preferences.get("lastreprompttime"));return last_reprompt_time};
set_last_reprompt_time=function(){last_reprompt_time=(new Date).getTime();Preferences.set("lastreprompttime",last_reprompt_time)};get_key_iterations=function(){return 5E3};(function(){var a={};lpevent=function(b){b="w"+b;a[b]=a.hasOwnProperty(b)?a[b]+1:1};setInterval(function(){if(g_prompts.improve){var b=!1,d;for(d in a){b=!0;break}b&&LPServer.xmlRequest({url:"poll_server.php",data:a});a={}}},1E4)})();
processCS=function(a,b,d){"ipcgetdata"==b.cmd&&"undefined"!=typeof g_plug2web_last_initiated&&g_plug2web_last_initiated>=parseInt((new Date).getTime()/1E3)-20&&(d=lpParseUri(b.url),a=d.directory.replace(/^\/~[^/]*/,""),d=d.file.replace(/#/,""),"/"==a&&"acctsiframe.php"==d&&(a={cmd:"ipcgotdata",username:g_username,key:btoa(g_local_key),version:lpversion,identity:g_identity,iterations:get_key_iterations(g_username)},b.callback(a)))};openimport=function(){window.open(base_url+"import.php")};
openexport=function(){window.open(base_url+"export.php")};openseccheck=function(){window.open(base_url+"?securitychallenge=1&lpnorefresh=1")};openentconsole=function(){window.open(base_url+"enterprise_home.php")};loggedOut=function(){send_website_event("logoff");setTimeout(function(){top.location.href=base_url+"logout.php?token="+g_token},500)};get_saved_logins=function(){};have_binary=function(){return canopensaveattach};install_binary=function(){window.open(base_url+"installer/")};
addAttach=function(a){addattach_callback=a;attachkey=SHA256(get_random_password());send_website_event("getattach",attachkey)};
openAttach=function(a,b,d){for(var e=0;e<lp_attaches.length;e++)if(lp_attaches[e].id==b){if("undefined"===typeof lp_attaches[e].data||""===lp_attaches[e].data){var f={getattach:lp_attaches[e].storagekey};"undefined"!=typeof g_securenotes[a].sharefolderid&&(f.sharedfolderid=g_securenotes[a].sharefolderid);$.ajax({global:!1,type:"POST",cache:!1,dataType:"json",url:"show_website.php",data:f,success:function(c){""!=c&&(lp_attaches[e].data=c,openAttach(a,b,d))},failure:function(a){alert("error")}});break}send_website_event("openattach",
lpdec_acct(g_securenotes[a].attachkey,g_securenotes[a],g_shares),lp_attaches[e].data,lp_attaches[e].mimetype)}};
exportAttachment=function(a,b,d){for(var e=0;e<lp_attaches.length;e++)if(lp_attaches[e].id==b){if("undefined"===typeof lp_attaches[e].data||""===lp_attaches[e].data){var f={getattach:lp_attaches[e].storagekey};"undefined"!=typeof g_securenotes[a].sharefolderid&&(f.sharedfolderid=g_securenotes[a].sharefolderid);$.ajax({global:!1,type:"POST",cache:!1,dataType:"json",url:"show_website.php",data:f,success:function(c){""!=c&&(lp_attaches[e].data=c,exportAttachment(a,b,d))},failure:function(a){alert("error")}});
break}send_website_event("saveattach",lpdec_acct(g_securenotes[a].attachkey,g_securenotes[a],g_shares),lp_attaches[e].data,lp_attaches[e].mimetype)}};can_copy_to_clipboard=function(){return!1};fastEncryptAttachments=function(a,b,d){var e=[],f;for(f in b)b.hasOwnProperty(f)&&"undefined"!=typeof b[f]&&e.push({id:b[f].id,data:enccbc(b[f].bytes,a)});d(e)};gotourl=function(a){g_sites[a].url&&(a=g_sites[a].url,a.match(/^[a-z]+?\:\/\//i)||(a="http://"+a),window.open(a))};increment_local_accts_version=function(){g_local_accts_version++};
refreshsites=function(){get_accts()};request_native_messaging=function(){send_website_event("request_native_messaging")};rewritelocalfile=function(){};editAid=function(a,b,d,e){e&&send_website_event("auto_pwchg",a,"0")};switch_identity=function(a){send_website_event("switchidentity",a);g_identity=""+a;Preferences.set("identity",g_identity);document.cookie="iid="+encodeURIComponent(g_identity)};
launch=function(a){g_hasplugin?(document[g_manualformname].aid.value=a,document[g_manualformname].submitbtn.click()):pa(function(){window.open(base_url+"launch.php?id="+encodeURIComponent(a)+"&shareid="+encodeURIComponent("undefined"!=typeof g_sites[a].sharefolderid?g_sites[a].sharefolderid:0)+"&method=web&token="+g_token)},g_prompts.login_site_prompt||g_sites[a].pwprotect)};launchApp=function(a){launch("app"+a)};
check_ident_aid=function(a){if(""===g_identity)return!0;for(var b=0;b<g_identities.length&&g_identities[b].iid!=g_identity;b++);if(b>=g_identities.length)return!1;b=g_identities[b];"undefined"==typeof b.aidarr&&(b.aidarr=b.aids.split(","));return lp_in_array(a,b.aidarr)};
check_ident_appaid=function(a){if(""===g_identity)return!0;for(var b=0;b<g_identities.length&&g_identities[b].iid!=g_identity;b++);if(b>=g_identities.length)return!1;b=g_identities[b];"undefined"==typeof b.appaidarr&&(b.appaidarr=b.appaids.split(","));return lp_in_array(a,b.appaidarr)};
openall=function(a,b){var d=[],e=!1,f;for(f in g_sites)if(check_ident_aid(f)){var c=g_sites[f];c.group==a&&"http://group"!=c.url&&(d.push(c),e=e||c.pwprotect)}if(0!==d.length)if(b||!e&&!g_prompts.login_site_prompt)for(e=0;e<d.length;e++)window.open(d[e].url);else pa(function(){openall(a,!0)},!0)};openAllSites=function(a){for(var b=0;b<a.length;b++)window.open(a[b].url)};
openfavorites=function(a){a=[];var b=!1,d;for(d in g_sites){var e=g_sites[d];check_ident_aid(d)&&"1"==e.fav&&(a.push(e),b=b||e.pwprotect)}if(0===a.length)alert(StringUtils.translate("You do not have any Favorites yet."));else if(skip_reprompt||!b&&!g_prompts.login_site_prompt)for(d=0;d<a.length;d++)window.open(a[d].url);else pa(function(){openfavorites(!0)},!0)};
createNewAcct=function(){return{aid:"",name:"",group:"",url:"",tld:"",extra:"",fav:"0",sharedfromuid:"",username:"",unencryptedUsername:"",password:"",pwprotect:0,genpw:0,sn:0,last_touch:lp_get_gmt_timestamp(),autologin:0,never_autofill:0,realm_data:"",fiid:"",custom_js:"",submit_id:"",captcha_id:"",urid:"0",basic_auth:"0",method:"",action:"",individualshare:!1,fields:[]}};
addEmptyGroup=function(a,b,d){var e=issharedfolder(g_shares,a);if(checkreadonly(e)){var f=!1===e?g_local_key:e.sharekey,c=a;if(e){if(!checkreadonly(e))return;c=a.substr(e.decsharename.length+1)}var h=createNewAcct();h.url="http://group";h.group=a;h.aid="0";a="ajax=1&extjs=1&name=&url="+encodeURIComponent(AES.url2hex(h.url))+"&grouping="+encodeURIComponent(lpenc(c,f))+"&username=&password=&extra=&aid=0&openid_url=&isbookmark=0";a+=!1===e?"":"&sharedfolderid="+en(e.id);a+=get_identity_param();a+="&token="+
g_token;$.ajax({type:"POST",url:base_url+"show_website.php",data:a,dataType:"text",success:function(a){a=$(jQuery.parseXML(a)).find("result");a.length&&(h.aid=a.attr("aid"),add_ident_aid(h.aid),b(h),g_sites[h.aid]=h)},failure:d})}};
checkmultiplefolders=function(a){for(var b=!1,d=null,e=!0,f=0;f<a.length;f++){var c=get_record(a[f]);if(c)if(c=issharedfolder(g_shares,c.group))if(b){e=!1;break}else if(null===d)d=c.decsharename;else{if(d!=c.decsharename){e=!1;break}}else if(null!==d){e=!1;break}else b=!0}e||alert(StringUtils.translate("Sorry, you cannot perform this operation on a mix of shared and non-shared folders, or multiple shared folders at once."));return e};
get_record=function(a){return"undefined"==typeof a?null:is_application(a)?g_applications[a.substring(3)]:"undefined"!==typeof g_sites&&"undefined"!==typeof g_sites[a]?g_sites[a]:"undefined"!==typeof g_securenotes&&"undefined"!==typeof g_securenotes[a]?g_securenotes[a]:null};
deleteAid=function(a,b,d,e,f){b=a.split(",");if(!checkmultiplefolders(b))return!1;d="";for(e=a=0;e<b.length;e++){var c=b[e];if(is_application(id)){if(!check_ident_appaid(c))continue}else if(!check_ident_aid(c))continue;var h=get_record(c);if(h){d+=(""===d?"":",")+c;if("undefined"!=typeof h.sharefolderid){a=h.sharefolderid;var g=issharedfolder(g_shares,h.group);if(!checkreadonly(g))return!1}is_application(h)&&"undefined"!=typeof g_applications[h.appaid]?delete g_applications[h.appaid]:"undefined"!=
typeof g_sites[c]?delete g_sites[c]:"undefined"!=typeof g_securenotes[c]&&delete g_securenotes[c]}}if(""===d)return!1;b="ajax=1&extjs=1&delete=1&aid="+en(d);b+=get_identity_param();0!==a&&(b+="&sharedfolderid="+en(a));b+="&token="+g_token;$.ajax({type:"POST",url:base_url+"show_website.php",data:b,dataType:"text"});f&&f();return!0};get_identity_param=function(){return"&iid="+encodeURIComponent(g_identity)};
deleteGroup=function(a,b,d){var e=[],f;for(f in g_sites)g_sites[i].group===a&&e.push(f);for(f in g_securenotes)g_securenotes[i].group===a&&e.push(f);for(f in g_applications)g_applications[i].group===a&&e.push(f);return deleteAid(e.join(","),b,!1,!0,d)};
deleteformfill=function(a,b,d,e,f,c,h){b=!1;for(d=0;d<g_formfills.length;d++)if(g_formfills[d].ffid==a){b=issharedfolder(g_shares,"undefined"!=typeof g_formfills[d].group?g_formfills[d].group:"");g_formfills.splice(d,1);break}a="deleteext=1&ffid="+encodeURIComponent(a);a+=!1===b?"":"&sharedfolderid="+encodeURIComponent(b.id);a+=get_identity_param();a+="&method="+encodeURIComponent(getBG().get_method());a+="&token="+g_token;a+="&src=website";h&&(a+="&source="+encodeURIComponent(h));$.ajax({type:"POST",
url:base_url+"formfill.php",data:a,dataType:"text",success:f,failure:c});return!0};
moveSelectedToGroup=function(a,b,d,e,f){d=d||{};d.successCallback=e;d.errorCallback=f;var c=void 0!==d.skipConfirm?d.skipConfirm:!1;b=b.split(",");e=issharedfolder(g_shares,a);var h=null;if(checkreadonly(e)){var g=!1;for(f=0;f<b.length;f++){h=get_record(b[f]);h=issharedfolder(g_shares,h.group);if(!checkreadonly(h)||!checkmove(e,h))return;!e&&!h||e&&h&&e.id===h.id||(g=!0)}if(g){g=[];for(f=0;f<b.length;f++)g[b[f]]=a;moveIntoSharedFolder(e,h,b,g,!1,!1,c,d)}else{c=[];h=[];if(a===StringUtils.translate("favorites"))for(f=
0;f<b.length;f++)(g=get_record(b[f]))&&"0"==g.fav&&(c[c.length]=b[f]);(0<b.length||0<c.length||0<h.length)&&changeGroupAndFavorites(b,c,h,a,e,d)}}};
changeGroupAndFavorites=function(a,b,d,e,f,c){for(var h=d="",g="",k=0;k<a.length;k++){var l=a[k],n=get_record(l);n&&e!=StringUtils.translate("favorites")&&(n.group=e,d+=g+l,g=",")}g="";for(k=0;k<b.length;k++)if(l=b[k],n=get_record(l))n.fav="1",h+=g+l,g=",";g_local_accts_version++;g_server_accts_version++;rewritelocalfile();c&&c.successCallback&&c.successCallback();a=!1===f?g_local_key:f.sharekey;b=e;f&&(b=e.substr(f.decsharename.length+1));e="aids="+encodeURIComponent(d)+"&newfavaids="+encodeURIComponent(h)+
"&oldfavaids="+encodeURIComponent("")+"&newgrp="+encodeURIComponent(lpenc(b,a))+"&xml=1";e+=0==f?"":"&sharedfolderid="+en(f.id);$.ajax({type:"POST",url:base_url+"groups.php",data:e,dataType:"text"})};
renameGroup=function(a,b){if(a!=StringUtils.translate("favorites")){var d=issharedfolder(g_shares,a);if(0!=d&&d.decsharename==a)alertfrombg("You cannot rename a top level Shared folder");else{var e=issharedfolder(g_shares,b);if(checkmove(e,d)&&checkreadonly(e)&&checkreadonly(d)){var f=0==e?g_local_key:e.sharekey,c;e&&b.substr(e.decsharename.length+1);if(e||d){var f=[],h=[],g=[g_sites,g_securenotes,g_applications];e&&b.substr(e.decsharename.length+1);for(var k in g){var l=g[k],n;for(n in l)if(l.hasOwnProperty(n)&&
(c=l[n],c.group==a||0==c.group.indexOf(a+"\\\\"))){f[f.length]=get_record_id(c);var m=b;c.group!=a&&0<c.group.indexOf("\\\\")&&(m=b+c.group.substr(c.group.indexOf("\\\\")));h[get_record_id(c)]=m}}moveIntoSharedFolder(e,d,f,h,!1,!1,!1)}else{g=[g_sites,g_securenotes,g_applications];d=[];h=[];m=[];for(k in g)for(n in l=g[k],l)if(l.hasOwnProperty(n))if(c=l[n],c.group==a)c.group=b,"undefined"==typeof d[a]?(m[m.length]=a,h[a]=get_record_id(c)):h[a]+=","+get_record_id(c),c=b,e&&(c=c.substr(e.decsharename.length+
1)),d[a]=c;else if(0==c.group.indexOf(a+"\\\\")){var p=c.group;c.group=c.group.replace(a+"\\\\",b+"\\\\");"undefined"==typeof d[p]?(m[m.length]=p,h[p]=get_record_id(c)):h[p]+=","+get_record_id(c);c=c.group;e&&(c=c.substr(e.decsharename.length+1));d[p]=c}g_local_accts_version++;rewritelocalfile();g="xml=1";for(k=0;k<m.length;k++)g+="&ids"+k+"="+encodeURIComponent(h[m[k]])+"&newgrp"+k+"="+encodeURIComponent(lpenc(d[m[k]],f));g+=0==e?"":"&sharedfolderid="+en(e.id);$.ajax({type:"POST",url:base_url+"groups.php",
data:g,dataType:"text"})}}}}};get_record_id=function(a){return is_application(a)?"app"+a.appaid:a.aid};is_application=function(a){return"string"==typeof a?0===a.indexOf("app"):a&&"undefined"!=typeof a.appaid};moveIntoSharedFolder_orig=moveIntoSharedFolder;
moveIntoSharedFolder=function(a,b,d,e,f,c,h,g){f=Object.prototype.toString.call(d);if("[object Array]"===f)if("object"===typeof d[0]&&"string"===typeof d[0].aid){f="A,";for(var k in d)d.hasOwnProperty(k)&&"string"==typeof d[k].aid&&(f+=(""==f?"":",")+d[k].aid);d=f}else d="B,"+d.join(",");else if("[object Object]"===f){f="C,";for(k in d)d.hasOwnProperty(k)&&(f+=(""==f?"":",")+k);d=f}else d="[object String]"===f?"D,"+d:"E,"+d;g||(g={});var l=g.successCallback?g.successCallback:function(){};g.successCallback=
function(){l();get_accts()};h&&(g.skipConfirm=!0);h="";for(k in e)if(e.hasOwnProperty(k)){h=e[k];break}return moveIntoSharedFolder_orig(b?b.id:"",a?a.id:"",h,d,"",g,"newvault")};getBG=function(){return this};
saveSite=function(a,b,d,e){a+="&method="+encodeURIComponent(getBG().get_method());a+="&auto=1"+get_identity_param();a+="&token="+g_token;b.postdata=a;b.posturl=base_url+(is_application(b)?"addapp.php":"show_website.php");$.ajax({type:"POST",url:b.posturl,data:a,dataType:"text",success:function(a){a=$(jQuery.parseXML(a));var c=a.find("result");if(c.length){0==b.aid&&(b.aid=c.attr("aid"),add_ident_aid(b.aid));(a=c.attr("attacherror"))&&""!=a&&alert(a);for(var f=0,g=[];null!=c.attr("att_"+f);)g[c.attr("att_"+
f)]=[],g[c.attr("att_"+f)].key=c.attr("attstorekey_"+f),g[c.attr("att_"+f)].size=c.attr("attsize_"+f),f++;if("undefined"!=typeof b.attacharraychanges&&(!a||""==a)){if("undefined"!=typeof b.attacharraychanges.add)for(var k in b.attacharraychanges.add)b.attacharraychanges.add.hasOwnProperty(k);applyattacharraychanges(b.attacharraychanges)}b.sn?g_securenotes[b.aid]=b:g_sites[b.aid]=b;d(b)}else c=a.find("error"),c.length&&e(c.attr("response"))},failure:e})};
saveFields=function(a,b,d,e,f){b+="&method="+encodeURIComponent(getBG().get_method());$.ajax({type:"POST",url:base_url+"fields.php?"+a,data:b,dataType:"text",success:e,failure:f})};
changePassword=function(a,b,d,e,f){for(var c=[],h=0,g=0;g<b.length;g++)if(g_sites[b[g]]){var k=lpmdec_acct(g_sites[b[g]].password,!0,g_sites[b[g]],g_shares);if(k!=a&&(c[c.length]=b[g],g_sites[b[g]].password=lpmenc_acct(a,!0,g_sites[b[g]],g_shares),g_sites[b[g]].fields))for(var l=0;l<g_sites[b[g]].fields.length;l++)"password"==g_sites[b[g]].fields[l].type&&lpmdec_acct(g_sites[b[g]].fields[l].value,!0,g_sites[b[g]],g_shares)==k&&(g_sites[b[g]].fields[l].value=g_sites[b[g]].password);"undefined"!=typeof g_sites[b[g]].sharefolderid&&
(h=g_sites[b[g]].sharefolderid)}b=c;if(0!==b.length){c="xml=1";k=[];for(g=0;g<b.length;g++){l=0<g?g:"";c+="&username"+l+"=dummy";c+="&password"+l+"="+encodeURIComponent(lpenc_acct(a,g_sites[b[g]],g_shares));c+="&id"+l+"="+encodeURIComponent(b[g]);try{lp_in_array(g_sites[b[g]].tld,k)||(k[k.length]=g_sites[b[g]].tld)}catch(n){}}try{for(g in g_sites)if(g_sites[g].genpw&&lp_in_array(g_sites[g].tld,k)&&lpmdec_acct(g_sites[g].password,!0,g_sites[g],g_shares)==a){c+="&delgenpwaid="+encodeURIComponent(g);
break}}catch(n){}0!=h&&(c+="&sharedfolderid="+en(h));"undefined"!=typeof d&&d&&(c+="&autochange=1");a={aid:0};a.postdata=c;a.url=base_url+"change_pw.php";a.handler=e;a.param={aid:a.aid,postdata:a.postdata,url:a.url,handler:a.handler};a.successCallback=e;$.ajax({type:"POST",url:a.url,data:a.postdata,dataType:"text",success:function(a){a=$(jQuery.parseXML(a)).find("ok");if(a.length)for(var b="";a.attr("id"+b);){var d=g_sites[a.attr("id"+b)],c=crypto_atob(a.attr("newpassword"+b)),f=crypto_atob(a.attr("oldpassword"+
b));d.password=c;if(d.fields)for(var g=0;g<d.fields.length;++g){var h=d.fields[g];"password"!=h.type||h.value!=f&&lpmdec_acct(h.value,!0,d,g_shares)!=lpmdec_acct(f,!0,d,g_shares)||(h.value=c)}b=""===b?1:++b}e()},failure:f})}};
addeditformfill=function(a,b,d,e){var f;f="&method="+encodeURIComponent(getBG().get_method());for(var c in a)f+=(""==f?"":"&")+c+"="+en(a[c]);a=!1;"undefined"!=typeof b.group&&""!=b.group&&(a=issharedfolder(g_shares,b.group));f+=0==a?"":"&sharedfolderid="+en(a.id);f+=get_identity_param();f+="&token="+g_token;$.ajax({type:"POST",url:base_url+"formfill.php",data:f+"&src=website",dataType:"text",success:function(a){var e=$(jQuery.parseXML(a)).find("result");if(e.length){e.attr("msg");a=e.attr("ffid");
add_ident_ffid(a);var c=e.attr("cfids");e.attr("accts_version");for(var e=[],f=""==c?[]:c.split(","),h=0,c=1;"undefined"!=typeof b["customfield"+c+"cfid"];++c){var m={};m.cfid=0!=b["customfield"+c+"cfid"]?b["customfield"+c+"cfid"]:h<f.length?f[h++]:0;m.text=b["customfield"+c+"text"];m.value=b["customfield"+c+"value"];m.alttext=b["customfield"+c+"alttext"];""==m.text&&""==m.value&&""==m.alttext||e.push(m)}f=b.cmd;delete b.cmd;delete b.deleteext;for(c=1;"undefined"!=typeof b["customfield"+c+"cfid"];++c)delete b["customfield"+
c+"cfid"],delete b["customfield"+c+"text"],delete b["customfield"+c+"value"],delete b["customfield"+c+"alttext"];b.custom_fields=e;if("add"==f)b.ffid=a,g_formfills.push(b);else for(c=0;c<g_formfills.length;++c)if(a==g_formfills[c].ffid){g_formfills[c]=b;break}d&&d(b)}},failure:e});return!0};add_ident_aid=function(a){if(g_identity){for(var b=null,d=0;d<g_identities.length;d++)if(g_identities[d].iid===g_identity){b=g_identities[d];break}b&&(b.aids&&(b.aids+=","),b.aids+=a,b.aidarr=b.aids.split(","))}};
add_ident_ffid=function(a){if(g_identity){for(var b=null,d=0;d<g_identities.length;d++)if(g_identities[d].iid==g_identity){b=g_identities[d];break}b&&(b.ffids&&(b.ffids+=","),b.ffids+=a,b.ffidarr=b.ffids.split(","))}};db_prepend=function(a){return a};localStorage_setItem=function(a,b){try{return localStorage.setItem(a,b),!0}catch(d){return!1}};localStorage_getItem=function(a){try{return localStorage.getItem(a)}catch(b){return null}};openURL=function(a){window.open(a)};canLaunchApplication=function(){return!1};
singlefactor_reprompt=function(a,b,d){a()};isOffline=function(){return!1};get_method=function(){return"web"};lpReportError=function(){errorCount=0;return function(a){!0===g_prompts.improve&&(++errorCount,100<errorCount||$.ajax({url:base_url+"error.php",type:"POST",data:{msg:"error: website("+lpversion+") errors("+errorCount+"): "+a}}))}}();loglogin=function(){};function refreshGroupNames(){}sendLpImprove=function(){};VaultToggle={toggleVault3_0:function(){}};
