var __extends=this&&this.__extends||function(a,f){function d(){this.constructor=a}for(var g in f)f.hasOwnProperty(g)&&(a[g]=f[g]);a.prototype=null===f?Object.create(f):(d.prototype=f.prototype,new d)},LastPass;(function(a){a=a.Web||(a.Web={});a=a.Automation||(a.Automation={});a=a.Environments||(a.Environments={});a[a.chrome=0]="chrome";a[a.firefox=1]="firefox";a[a.safari=2]="safari";a[a.ios=3]="ios";a[a.android=4]="android";a[a.mock=5]="mock"})(LastPass||(LastPass={}));
(function(a){a=a.Web||(a.Web={});a.Automation||(a.Automation={})})(LastPass||(LastPass={}));(function(a){a=a.Web||(a.Web={});a=a.Automation||(a.Automation={});a.Android||(a.Android={})})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){(function(d){var c=function(){function b(b){this.proxy=b}b.prototype.reportDone=function(){this.proxy.reportDone()};b.prototype.userInformationNeeded=function(){this.proxy.userInformationNeeded()};b.prototype.reportError=function(b){b="string"===typeof b?b:JSON.stringify({name:b.name,message:b.message});this.proxy.reportError(b)};b.prototype.reportLog=function(b){this.proxy.reportLog(JSON.stringify(b))};b.prototype.isMobile=function(){return!0};b.prototype.getEnvironment=
function(){return a.Environments.android};return b}();d.AndroidHostEnvironment=c})(a.Android||(a.Android={}))})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){(function(a){(function(b){b[b.Pending=0]="Pending";b[b.Resolved=1]="Resolved";b[b.Failed=2]="Failed"})(a.PromiseState||(a.PromiseState={}));var c=a.PromiseState,b=function(){function b(b){this.hostEnvironment=b;this.state=c.Pending;this.error=this.data=null;this.okCallbacks=[];this.errorCallbacks=[]}b.prototype.then=function(b,a){void 0===a&&(a=null);if(this.state===c.Resolved)try{b(this.data)}catch(k){this.hostEnvironment.reportError(k)}else this.state===c.Failed?
a(this.error):(this.okCallbacks.push(b),a&&this.errorCallbacks.push(a))};return b}();a.Promise=b;var e=function(){function a(a){this.hostEnvironment=a;this.promise=new b(this.hostEnvironment)}a.prototype.resolve=function(b){var a=this;this.promise.state=c.Resolved;this.promise.data=b;this.promise.okCallbacks.forEach(function(e){try{e(b)}catch(l){a.hostEnvironment.reportError(l)}})};a.prototype.reject=function(b){this.promise.state=c.Failed;this.promise.error=b;this.hostEnvironment.reportError(b);
this.promise.errorCallbacks.forEach(function(a){a(b)})};return a}();a.Deferred=e})(a.Promise||(a.Promise={}))})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){var d=function(){function a(){}a.submitForm=function(b){b.submit()};Object.defineProperty(a.prototype,"location",{get:function(){return window.location.href},enumerable:!0,configurable:!0});a.prototype.findElement=function(b){var a=[];b instanceof Array?a=b:"string"===typeof b&&a.push(b);for(b=0;b<a.length;b++){var c=document.querySelector(a[b]);if(c)return c}return null};a.prototype.findAllElements=function(b){var a=[];b instanceof Array?a=b:"string"===typeof b&&
a.push(b);for(b=0;b<a.length;b++){var c=document.querySelectorAll(a[b]);if(c)return c}return null};a.prototype.elementExists=function(b){return null!==this.findElement(b)};a.prototype.clickButton=function(b){this.triggerEvents(["mousedown","mouseup"],b);b.click()};a.prototype.mouseClickButton=function(b){this.triggerEvents(["mousedown","mouseup"],b)};a.prototype.checkCheckBox=function(b){b.checked=!0};a.prototype.checkRadioButton=function(b){b.checked=!0};a.prototype.setValue=function(b,a){this.triggerEvents(["focus",
"keydown","keydown"],b);b.value=a;this.triggerEvents(["keyup","keyup","input","blur","change"],b)};a.prototype.triggerEvents=function(b,a){for(var e=0,c=b.length;e<c;e++){var d=document.createEvent("HTMLEvents");d.initEvent(b[e],!0,!0);a.dispatchEvent(d)}};return a}();a.Document=d})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){var d=function(){function c(a,e){this.document=a;this.hostEnvironment=e}c.prototype.clearTimeout=function(){clearInterval(this.intervalHandle)};c.prototype.waitForNavigation=function(b){var e=this;void 0===b&&(b=1E4);clearInterval(this.intervalHandle);this.intervalHandle=setInterval(function(){clearInterval(e.intervalHandle);e.hostEnvironment.reportError(new a.NavigationTimeoutError)},b)};c.prototype.waitForSelector=function(b,e){var c=this;void 0===e&&(e=1E4);
var d=new a.Promise.Deferred(this.hostEnvironment),f=0;clearInterval(this.intervalHandle);this.intervalHandle=window.setInterval(function(){c.document.elementExists(b)&&(window.clearInterval(c.intervalHandle),d.resolve(c.document.findElement(b)));if(f>=e){window.clearInterval(c.intervalHandle);var g=new a.SelectorNotFoundError(b);d.reject(g);throw g;}f+=500},500);return d.promise};c.prototype.waitForSelectorToDisappear=function(b,e){var c=this;void 0===e&&(e=1E4);var d=new a.Promise.Deferred(this.hostEnvironment),
f=0;clearInterval(this.intervalHandle);this.intervalHandle=window.setInterval(function(){c.document.elementExists(b)||(window.clearInterval(c.intervalHandle),d.resolve());if(f>=e){window.clearInterval(c.intervalHandle);var g=new a.SelectorFoundError(b);d.reject(g);throw g;}f+=500},500);return d.promise};c.prototype.clickButton=function(b){var e=this.document.findElement(b);if(null===e)throw new a.SelectorNotFoundError(b);this.document.clickButton(e)};c.prototype.mouseClickButton=function(b){var e=
this.document.findElement(b);if(null===e)throw new a.SelectorNotFoundError(b);this.document.mouseClickButton(e)};c.prototype.checkRadioButton=function(b){var e=this.document.findElement(b);if(null===e)throw new a.SelectorNotFoundError(b);this.document.clickButton(e)};c.prototype.setValue=function(b,e){var c=this.document.findElement(b);if(null===c)throw new a.SelectorNotFoundError(b);this.document.setValue(c,e)};return c}();a.Helpers=d})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||
(LastPass={}));(function(a){a=a.Web||(a.Web={});a.Automation||(a.Automation={})})(LastPass||(LastPass={}));(function(a){(function(a){(function(a){var d=function(a){function b(b){a.call(this,"Selector not found: "+b);this.name="Selector not found Error";this.message="Selector not found: "+b;this.stack=Error().stack}__extends(b,a);return b}(Error);a.SelectorNotFoundError=d})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){var d=function(){function c(){}c.prototype.reportDone=function(){console.log("Done!")};c.prototype.userInformationNeeded=function(){console.log("User information needed!")};c.prototype.reportError=function(a){console.log("Error: "+a.message)};c.prototype.reportLog=function(a){console.log("Log: "+a)};c.prototype.isMobile=function(){return!1};c.prototype.getEnvironment=function(){return a.Environments.mock};return c}();a.MockHostEnvironment=d})(a.Automation||(a.Automation=
{}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));(function(a){(function(a){(function(a){var d=function(a){function b(b){a.call(this,"Selector still found: "+b);this.name="Selector found Error";this.message="Selector found: "+b;this.stack=Error().stack}__extends(b,a);return b}(Error);a.SelectorFoundError=d})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){var d=function(){function a(a){this.host=a}a.prototype.reportDone=function(){this.clearTimeoutFunction();this.host.reportDone()};a.prototype.userInformationNeeded=function(){this.clearTimeoutFunction();this.host.userInformationNeeded()};a.prototype.reportError=function(a){this.clearTimeoutFunction();this.host.reportError(a)};a.prototype.reportLog=function(a){this.host.reportLog(a)};a.prototype.setClearTimeoutFunction=function(a){this.clearTimeoutFunction=a};
a.prototype.isMobile=function(){return this.host.isMobile()};a.prototype.getEnvironment=function(){return this.host.getEnvironment()};return a}(),c=function(){function b(b){var c=this;this.document=new a.Document;this.host=this.helpers=null;this.host=b=new d(b);this.helpers=new a.Helpers(this.document,this.host);b.setClearTimeoutFunction(function(){return c.helpers.clearTimeout()})}b.prototype.run=function(a){try{this.helpers.waitForNavigation(),a()}catch(h){this.host.reportError(h)}};return b}();
a.Context=c})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){(function(d){var c=function(){function b(){}b.prototype.reportDone=function(){window.location.href=b.redirectBase+"done"};b.prototype.userInformationNeeded=function(){window.location.href=b.redirectBase+"user"};b.prototype.reportError=function(a){window.location.href=b.redirectBase+"error/error?name="+a.name+"&message="+a.message};b.prototype.reportLog=function(a){window.location.href=b.redirectBase+"log/log?data="+JSON.stringify(a)};b.prototype.isMobile=function(){return!0};
b.prototype.getEnvironment=function(){return a.Environments.ios};b.redirectBase="lpomscallback://";return b}();d.IOSHostEnvironment=c})(a.IOS||(a.IOS={}))})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
(function(a){(function(a){(function(a){var d=function(a){function b(){a.call(this,"Navigation timed out.");this.name="Navigation time out Error";this.message="Navigation timed out.";this.stack=Error().stack}__extends(b,a);return b}(Error);a.NavigationTimeoutError=d})(a.Automation||(a.Automation={}))})(a.Web||(a.Web={}))})(LastPass||(LastPass={}));
