var ActionEvents=function(){this.actions={}};
(function(){ActionEvents.prototype.subscribeToAction=function(b,c){b&&c&&(this.actions[b]?this.actions[b].push(c):this.actions[b]=[c])};ActionEvents.prototype.unSubscribeActionFn=function(b,c){if(b&&this.actions[b]){var d=this.actions[b].indexOf(c);0<=d&&delete this.actions[b][d]}};ActionEvents.prototype.unSubscribeAllAction=function(b){b&&this.actions[b]&&delete this.actions[b]};ActionEvents.prototype.triggerAction=function(b){if(b&&this.actions[b])for(var c=0;this.actions&&c<this.actions[b].length;c++)if(this.actions[b][c]&&
"function"==typeof this.actions[b][c])this.actions[b][c](arguments)}})();var IntroTourFlow=function(b){IntroTourFlow.prototype.setup(b)};
(function(b,c,d,e){IntroTourFlow.prototype.setup=function(a){if(!a||!a.tour||!a.tour.steps||0==a.tour.steps.length)throw Error("Steps Array needs to have at least one step");this.steps=a.tour.steps;this.exitStep=a.tour.exitStep;this.welcomeStep=a.tour.welcomeStep;this.laterStep=a.tour.laterStep;this.isLater=a.isLater;this.lastIndexComplete=this.currentStepIndex=-1;this.currentStep=null;this.actionEvents=new c;this.pingManager=new d({steps:this.steps});this.invisibleShade=new e({shadeClass:"invisible-shade"});
this.darkShade=new e({shadeClass:"dark-shade"})};IntroTourFlow.prototype.getFirstStep=function(){return 0<this.steps.length?(this.currentStepIndex=0,this.steps[this.currentStepIndex]):null};IntroTourFlow.prototype.getLastStep=function(){return 0<this.steps.length?this.steps[this.steps.length-1]:null};IntroTourFlow.prototype.getNextStep=function(){return this.hasNextStep()?this.steps[++this.currentStepIndex]:null};IntroTourFlow.prototype.getPreviousStep=function(){return this.hasPreviousStep()?this.steps[--this.currentStepIndex]:
null};IntroTourFlow.prototype.getExitStep=function(){return this.exitStep};IntroTourFlow.prototype.hasNextStep=function(){return this.currentStepIndex+1<this.steps.length};IntroTourFlow.prototype.hasPreviousStep=function(){return 0<=this.currentStepIndex-1};IntroTourFlow.prototype.setCurrentStep=function(a){this.currentStep=a;for(var b=0;b<this.steps.length;b++)if(this.steps[b]===a)return this.currentStepIndex=b;return this.currentStepIndex=-1};IntroTourFlow.prototype.goToStep=function(a){if(a){b.tourDialogBase.open({options:a,
flow:this});this.setCurrentStep(a);-1!=this.currentStepIndex&&(this.lastIndexComplete=this.currentStepIndex,this.pingManager.showAllFuture(this.currentStepIndex));a.openAction&&"function"==typeof a.openAction&&a.openAction();var c=this;a.autoClose&&0<a.autoClose&&(c.isCurrentStepClosed=!1,setTimeout(function(){c.isCurrentStepClosed||(c.closeCurrentStep(),c.executeAction("close"))},a.autoClose))}};IntroTourFlow.prototype.closeCurrentStep=function(){this.isCurrentStepClosed=!0;b.tourDialogBase.close(!0);
this.pingManager.hideAll();this.currentStep&&this.currentStep.closeAction&&"function"==typeof this.currentStep.closeAction&&this.currentStep.closeAction()};IntroTourFlow.prototype.startFlow=function(a){this.isLater?this.goToStep(this.laterStep):a?this.executeAction("start",a):(this.goToStep(this.welcomeStep),bg.sendLpImprove("vaulttour",{version:"41"}));Topics.get(Topics.ESCAPE).subscribe(this.getEscapeHandler())};IntroTourFlow.prototype.getEscapeHandler=function(){var a=this;a.escapeHandler||(a.escapeHandler=
function(b){a.closeCurrentStep();a.executeAction(0<=a.lastIndexComplete?"exit":"close")});return a.escapeHandler};IntroTourFlow.prototype.executeAction=function(a,b){switch(a){case "start":this.goToStep(this.getFirstStep());this.invisibleShade.show();this.darkShade.show();bg.sendLpImprove("vaulttour::start",{version:"41",source:b?"help":"welcome"});break;case "next":this.goToStep(this.getNextStep());break;case "previous":this.goToStep(this.getPreviousStep());break;case "exit":this.goToStep(this.getExitStep());
this.darkShade.hide();break;case "later":bg.sendLpImprove("vaulttour::choice",{choice:"later"});break;case "never":bg.sendLpImprove("vaulttour::choice",{choice:"never"});break;case "close":this.invisibleShade.hide(),this.darkShade.hide(),Topics.get(Topics.ESCAPE).unsubscribe(this.escapeHandler),0<=this.lastIndexComplete&&bg.sendLpImprove("vaulttour::exit",{version:"41",page:this.lastIndexComplete+1})}this.actionEvents&&this.actionEvents.triggerAction(a)};IntroTourFlow.prototype.cleanup=function(){this.invisibleShade&&
(this.invisibleShade.cleanup(),delete this.invisibleShade);this.darkShade&&(this.darkShade.cleanup(),delete this.darkShade);this.pingManager&&(this.pingManager.cleanup(),delete this.pingManager);this.currentStep=null;delete this.steps;delete this.exitStep;delete this.welcomeStep;delete this.laterStep};IntroTourFlow.prototype.subscribeToAction=function(a,b){this.actionEvents.subscribeToAction(a,b)};IntroTourFlow.prototype.unSubscribeAction=function(a){this.actionEvents.unSubscribeAllAction(a)}})(dialogs,
ActionEvents,lpPingManager,IntroTourShade);
