var IntroTourDialog=function(c){Dialog.call(this,c,{closeButtonEnabled:!1,maximizeButtonEnabled:!1,dynamicHeight:!0,hideHeader:!0,hideButtons:!0,confirmOnClose:!1,buttonsInsideContent:!0});IntroTourDialog.prototype._arrow=null;IntroTourDialog.prototype._options=null};IntroTourDialog.prototype=Object.create(Dialog.prototype);IntroTourDialog.prototype.constructor=IntroTourDialog;
(function(c,l){function h(a,b,d,e,c){var g=0;switch(a){case "top":case "left":g=b?d:d+e;break;case "right":case "bottom":g=b?d+e-c:d-c}return g}function k(a,b,d,e,c){switch(a){case "top":case "left":a=b;break;case "right":case "bottom":a=b+d-c;break;default:a=e-Math.round(c/2)}return a}IntroTourDialog.prototype.createButton=function(a,b,d,e){if(a&&b){var f=b.style||"",g=b.sizeStyle||"col-6";b=c("<div></div>").addClass(g).append(c("<button></button>").text(b.text).data("index",d).addClass("btn-base radius-sm "+
f).off().on("click",e));a.append(b)}};IntroTourDialog.prototype.setup=function(a,b){if(b&&b.options&&b.flow){var d=this;d._options=c.extend({title:Strings.translateString("Tour Title here")},b.options);var e=d.$element.find(".buttons").empty();d.$element.removeClass().addClass("dialog responsive intro-tour-dialog");d._options["class"]&&d.$element.addClass(d._options["class"]);for(var f=0;f<d._options.buttons.length;f++)this.createButton(e,d._options.buttons[f],f,function(a){a.preventDefault();b.flow.closeCurrentStep();
a=c(a.target).data("index");c.isNumeric(a)&&0<=a&&a<d._options.buttons.length&&(a=d._options.buttons[a],a.action&&b.flow.executeAction(a.action))});a.find("#btnClose").off().on("click",function(a){a.preventDefault();b.flow.closeCurrentStep();d._options.exitAction&&b.flow.executeAction(d._options.exitAction)});this.setText(this._options.title,this.$element.find("#mainTitle"));e="function"==typeof this._options.contentText1?this._options.contentText1():this._options.contentText1;this.setText(e,this.$element.find("#contentText1"));
e="function"==typeof this._options.contentText2?this._options.contentText2():this._options.contentText2;this.setText(e,this.$element.find("#contentText2"));Dialog.prototype.setup.apply(this,arguments);this.setSize(this._options.position);this.setPosition(this._options.position);this._options.position&&this._options.position.arrowPosition?(this._arrow=this._arrow||new l({$parentEl:this.$element,arrowClass:"arrow-box a-white"}),this._arrow.show(this._options.position.orientation,this._options.position.arrowPosition)):
this._arrow&&this._arrow.hide();(this.$overlayDialogEl=c("#dialogOverlay"))&&0<this.$overlayDialogEl.length&&this.$overlayDialogEl.detach();c("body").removeClass("dialogState");this.subscribeToWindowResize()}};IntroTourDialog.prototype.setText=function(a,b){a&&b?b.text(a).show():b.hide()};IntroTourDialog.prototype.setPosition=function(a){a.dialogPosition=null;a&&a.targetId&&(a.$targetEl=c(a.targetId),a.targetDimensions=this.getDimensions(a.$targetEl),a.dialogPosition=this.computeDialogPosition(this.$element,
a));a.dialogPosition&&this.$element.offset(a.dialogPosition)};IntroTourDialog.prototype.setSize=function(a){if(a){a.$targetEl=c(a.targetId);var b=this.getDimensions(a.$targetEl);if(a.fillWidth){var d=c(a.fillWidth);d&&0<d.length?this.$element.width(d.width()):this.$element.width(b.width)}else this.$element.css("width","");a.fillHeight?(d=c(a.fillHeight))&&0<d.length?this.$element.height(d.height()):this.$element.height(b.height):this.$element.css("height","")}};IntroTourDialog.prototype.subscribeToWindowResize=
function(){var a=this;a.positionAndResizeHandler=function(b){a.setSize(a._options.position);a.setPosition(a._options.position)};window&&window.addEventListener("resize",a.positionAndResizeHandler);Topics.get(Topics.VAULT_LEFT_MENU_TOGGLE).subscribe(a.positionAndResizeHandler);Topics.get(Topics.EMPTY_VAULT_STATE_CHANGE).subscribe(a.positionAndResizeHandler)};IntroTourDialog.prototype.unSubscribeToWindowResize=function(){window&&(window.removeEventListener&&window.removeEventListener("resize",this.positionAndResizeHandler),
this.positionAndResizeHandler=null);Topics.get(Topics.VAULT_LEFT_MENU_TOGGLE).unsubscribe(this.positionAndResizeHandler);Topics.get(Topics.EMPTY_VAULT_STATE_CHANGE).unsubscribe(this.positionAndResizeHandler)};IntroTourDialog.prototype.computeDialogPosition=function(a,b){if(a&&0<a.length&&b&&0<b.$targetEl.length){var d=b.arrowPosition?15:0;b.dialogDimensions=this.getDimensions(a);var c={top:0,left:0},f=b.align||"center";switch(b.orientation){case "top":c.left=k(f,b.targetDimensions.left,b.targetDimensions.width,
b.targetDimensions.center.left,b.dialogDimensions.width);c.top=h(b.orientation,b.inside,b.targetDimensions.top,b.targetDimensions.height,b.dialogDimensions.height)+d;break;case "bottom":c.left=k(f,b.targetDimensions.left,b.targetDimensions.width,b.targetDimensions.center.left,b.dialogDimensions.width);c.top=h(b.orientation,b.inside,b.targetDimensions.top,b.targetDimensions.height,b.dialogDimensions.height)-d;break;case "left":c.top=k(f,b.targetDimensions.top,b.targetDimensions.height,b.targetDimensions.center.top,
b.dialogDimensions.height);c.left=h(b.orientation,b.inside,b.targetDimensions.left,b.targetDimensions.width,b.dialogDimensions.width)+d;break;case "right":c.top=k(f,b.targetDimensions.top,b.targetDimensions.height,b.targetDimensions.center.top,b.dialogDimensions.height),c.left=h(b.orientation,b.inside,b.targetDimensions.left,b.targetDimensions.width,b.dialogDimensions.width)-d}b.offset&&(c.top+=b.offset.top,c.left+=b.offset.left);return c}return null};IntroTourDialog.prototype.getDimensions=function(a){return a&&
0<a.length?(a=c.extend({height:a.height(),width:a.width()},a.offset()),a.center={top:Math.round(a.top+a.height/2),left:Math.round(a.left+a.width/2)},a):null};IntroTourDialog.prototype.show=function(){Dialog.prototype.show.apply(this,arguments);c("body").removeClass("dialogState")};IntroTourDialog.prototype.hide=function(){Dialog.prototype.hide.apply(this,arguments);c("body").addClass("dialogState")};IntroTourDialog.prototype.close=function(a){a&&(Dialog.prototype.close.apply(this,arguments),c("body").removeClass("dialogState"),
this.$overlayDialogEl&&c("body").append(this.$overlayDialogEl),this.unSubscribeToWindowResize())};IntroTourDialog.prototype.showBlurOverlay=function(){c("body").addClass("dialogState")};IntroTourDialog.prototype.hideBlurOverlay=function(){c("body").removeClass("dialogState")};IntroTourDialog.prototype.closeOnSuccess=function(){};IntroTourDialog.prototype.getZIndex=function(){var a=this.$element.css("z-index");if("auto"===a)return 0;a=parseInt(a);return 8>a?8:a}})(jQuery,lpArrow);
